# **Feature Generation Notebook**
The purpose of this notebook is to generate and save the features for modeling

## **1.0: Package and Data Load**

In [171]:
import pandas as pd
import numpy as np
import pickle

In [2]:
tw1 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw1_processed.csv')
tw2 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw2_processed.csv')
tw3 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw3_processed.csv')
tw4 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw4_processed.csv')
tw5 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw5_processed.csv')
tw6 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw6_processed.csv')
tw7 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw7_processed.csv')
tw8 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw8_processed.csv')
tw9 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw9_processed.csv')

In [6]:
games = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/games.csv')
plays = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/plays.csv')
players = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/players.csv')
tackles = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/tackles.csv')

In [8]:
#Function to create 'game_play_Id' column in DF
def game_play_Id(df):
    df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')

    return df

In [9]:
plays = game_play_Id(plays)
tackles = game_play_Id(tackles)

In [20]:
plays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12486 entries, 0 to 12485
Data columns (total 36 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   gameId                            12486 non-null  int64
 1   playId                            12486 non-null  int64
 2   ballCarrierId                     12486 non-null  int64
 3   ballCarrierDisplayName            12486 non-null  object
 4   playDescription                   12486 non-null  object
 5   quarter                           12486 non-null  int64
 6   down                              12486 non-null  int64
 7   yardsToGo                         12486 non-null  int64
 8   possessionTeam                    12486 non-null  object
 9   defensiveTeam                     12486 non-null  object
 10  yardlineSide                      12319 non-null  object
 11  yardlineNumber                    12486 non-null  int64
 12  gameClock                         12486 non-null  object
 13  preSnapHomeScore                  12486 non-null  int64
 14  preSnapVisitorScore               12486 non-null  int64
 15  passResult                        6105 non-null   object
 16  passLength                        5634 non-null   float64
 17  penaltyYards                      615 non-null    float64
 18  prePenaltyPlayResult              12486 non-null  int64
 19  playResult                        12486 non-null  int64
 20  playNullifiedByPenalty            12486 non-null  object
 21  absoluteYardlineNumber            12486 non-null  int64
 22  offenseFormation                  12482 non-null  object
 23  defendersInTheBox                 12481 non-null  float64
 24  passProbability                   12149 non-null  float64
 25  preSnapHomeTeamWinProbability     12486 non-null  float64
 26  preSnapVisitorTeamWinProbability  12486 non-null  float64
 27  homeTeamWinProbabilityAdded       12486 non-null  float64
 28  visitorTeamWinProbilityAdded      12486 non-null  float64
 29  expectedPoints                    12486 non-null  float64
 30  expectedPointsAdded               12485 non-null  float64
 31  foulName1                         592 non-null    object
 32  foulName2                         25 non-null     object
 33  foulNFLId1                        592 non-null    float64
 34  foulNFLId2                        25 non-null     float64
 35  game_play_Id                      12486 non-null  object
dtypes: float64(12), int64(12), object(12)
memory usage: 3.4+ MB

In [7]:
pd.set_option('display.max_columns', None)
tw1.head()

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
0,2022090800,56,42489.0,Stefon Diggs,1,2022-09-08 20:24:05.200000,14.0,BUF,left,80.60,38.29,6.23,0.90,0.62,140.05,189.38,NaN,2022090800_56,LA,42489,80.60,38.29,6.23,0.90,0.62,140.05,189.38,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.451889,0.451889,191,191,171.90,171.90
1,2022090800,56,42489.0,Stefon Diggs,2,2022-09-08 20:24:05.299999,14.0,BUF,left,80.48,37.68,6.24,1.27,0.62,134.22,191.08,pass_arrived,2022090800_56,LA,42489,80.48,37.68,6.24,1.27,0.62,134.22,191.08,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.368222,0.368222,191,191,242.57,242.57
2,2022090800,56,42489.0,Stefon Diggs,3,2022-09-08 20:24:05.400000,14.0,BUF,left,80.34,37.09,5.98,2.48,0.60,127.16,194.40,NaN,2022090800_56,LA,42489,80.34,37.09,5.98,2.48,0.60,127.16,194.40,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.252889,0.252889,191,191,473.68,473.68
3,2022090800,56,42489.0,Stefon Diggs,4,2022-09-08 20:24:05.500000,14.0,BUF,left,80.19,36.53,5.67,3.37,0.58,120.72,196.97,NaN,2022090800_56,LA,42489,80.19,36.53,5.67,3.37,0.58,120.72,196.97,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.152778,0.152778,191,191,643.67,643.67
4,2022090800,56,42489.0,Stefon Diggs,5,2022-09-08 20:24:05.599999,14.0,BUF,left,80.01,36.00,5.43,3.65,0.56,118.07,199.54,NaN,2022090800_56,LA,42489,80.01,36.00,5.43,3.65,0.56,118.07,199.54,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.094778,0.094778,191,191,697.15,697.15

## **2.0: Feature Generation**

### **2.1: Figuring out how many non-assist tackling events**

In [11]:
tackles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            17426 non-null  int64
 1   playId            17426 non-null  int64
 2   nflId             17426 non-null  int64
 3   tackle            17426 non-null  int64
 4   assist            17426 non-null  int64
 5   forcedFumble      17426 non-null  int64
 6   pff_missedTackle  17426 non-null  int64
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB

In [43]:
tackles_1v1 = tackles[(tackles['tackle'] == 1) | (tackles['pff_missedTackle'] == 1)]

In [44]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11974 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11974 non-null  int64
 1   playId            11974 non-null  int64
 2   nflId             11974 non-null  int64
 3   tackle            11974 non-null  int64
 4   assist            11974 non-null  int64
 5   forcedFumble      11974 non-null  int64
 6   pff_missedTackle  11974 non-null  int64
 7   game_play_Id      11974 non-null  object
dtypes: int64(7), object(1)
memory usage: 841.9+ KB

In [45]:
tackles_1v1.tackle.value_counts()

tackle
1    9919
0    2055
Name: count, dtype: int64

In [46]:
tackles_1v1.pff_missedTackle.value_counts()

pff_missedTackle
0    9884
1    2090
Name: count, dtype: int64

In [17]:
tackles_weird = tackles[(tackles['tackle'] == 1) & (tackles['pff_missedTackle'] == 1)]

In [28]:
tackles_weird.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 219 to 9620
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            35 non-null     int64
 1   playId            35 non-null     int64
 2   nflId             35 non-null     int64
 3   tackle            35 non-null     int64
 4   assist            35 non-null     int64
 5   forcedFumble      35 non-null     int64
 6   pff_missedTackle  35 non-null     int64
 7   game_play_Id      35 non-null     object
dtypes: int64(7), object(1)
memory usage: 2.5+ KB

### **2.2: Creating Event Type Label**

In [47]:
# Function to determine event_type
def determine_event_type(row):
    if row['tackle'] == 1 and row['pff_missedTackle'] == 0:
        return 1
    elif row['tackle'] == 0 and row['pff_missedTackle'] == 1:
        return 2
    else:
        return None

In [48]:
# Apply the function to each row
tackles_1v1['event_type'] = tackles_1v1.apply(determine_event_type, axis=1)

# Find indices where both 'tackle' and 'pff_missedTackle' are 1
both_one_indices = tackles_1v1[(tackles_1v1['tackle'] == 1) & (tackles_1v1['pff_missedTackle'] == 1)].index

# Create duplicates of these rows
duplicates = tackles_1v1.loc[both_one_indices].copy()

# Modify the original rows
tackles_1v1.loc[both_one_indices, 'tackle'] = 0
tackles_1v1.loc[both_one_indices, 'event_type'] = 2

# Modify the duplicates
duplicates['pff_missedTackle'] = 0
duplicates['event_type'] = 1

# Concatenate the original DataFrame with the duplicates
tackles_1v1 = pd.concat([tackles_1v1, duplicates])

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/2649901282.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tackles_1v1['event_type'] = tackles_1v1.apply(determine_event_type, axis=1)

In [49]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            12009 non-null  int64
 1   playId            12009 non-null  int64
 2   nflId             12009 non-null  int64
 3   tackle            12009 non-null  int64
 4   assist            12009 non-null  int64
 5   forcedFumble      12009 non-null  int64
 6   pff_missedTackle  12009 non-null  int64
 7   game_play_Id      12009 non-null  object
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB

In [130]:
tackles_1v1.event_type.value_counts()

event_type
1.0    9919
2.0    2090
Name: count, dtype: int64

In [129]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            12009 non-null  int64
 1   playId            12009 non-null  int64
 2   nflId             12009 non-null  int64
 3   tackle            12009 non-null  int64
 4   assist            12009 non-null  int64
 5   forcedFumble      12009 non-null  int64
 6   pff_missedTackle  12009 non-null  int64
 7   game_play_Id      12009 non-null  object
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB

### **2.3: Combining all tracking data into one df**

In [142]:
tw1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154194 entries, 0 to 154193
Data columns (total 46 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   gameId            154194 non-null  int64
 1   playId            154194 non-null  int64
 2   nflId             154194 non-null  float64
 3   displayName       154194 non-null  object
 4   frameId           154194 non-null  int64
 5   time              154194 non-null  object
 6   jerseyNumber      154194 non-null  float64
 7   club              154194 non-null  object
 8   playDirection     154194 non-null  object
 9   x                 154194 non-null  float64
 10  y                 154194 non-null  float64
 11  s                 154194 non-null  float64
 12  a                 154194 non-null  float64
 13  dis               154194 non-null  float64
 14  o                 154194 non-null  float64
 15  dir               154194 non-null  float64
 16  event             13684 non-null   object
 17  game_play_Id      154194 non-null  object
 18  defensiveTeam     154194 non-null  object
 19  ballCarrierId     154194 non-null  int64
 20  bcx               154194 non-null  float64
 21  bcy               154194 non-null  float64
 22  bc_s              154194 non-null  float64
 23  bc_a              154194 non-null  float64
 24  bc_dis            154194 non-null  float64
 25  bc_o              154194 non-null  float64
 26  bc_dir            154194 non-null  float64
 27  distance_from_bc  154194 non-null  float64
 28  tackler_one       120749 non-null  float64
 29  tackler_two       104 non-null     float64
 30  assister_one      60503 non-null   float64
 31  assister_two      31428 non-null   float64
 32  missed_tackler_1  41990 non-null   float64
 33  missed_tackler_2  10793 non-null   float64
 34  missed_tackler_3  490 non-null     float64
 35  missed_tackler_4  0 non-null       float64
 36  missed_tackler_5  0 non-null       float64
 37  missed_tackler_6  0 non-null       float64
 38  new_event         256 non-null     object
 39  cosine            145216 non-null  float64
 40  do_align          154194 non-null  float64
 41  bc_do_align       154194 non-null  float64
 42  weight            154194 non-null  int64
 43  bc_weight         154194 non-null  int64
 44  force             154194 non-null  float64
 45  bc_force          154194 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 54.1+ MB

In [132]:
tracking_clean = pd.concat([tw1, tw2, tw3, tw4, tw5, tw6, tw7, tw8, tw9], ignore_index=True)

In [154]:
tracking_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334038 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1334038 non-null  int64
 1   playId            1334038 non-null  int64
 2   nflId             1334038 non-null  float64
 3   displayName       1334038 non-null  object
 4   frameId           1334038 non-null  int64
 5   time              1334038 non-null  object
 6   jerseyNumber      1334038 non-null  float64
 7   club              1334038 non-null  object
 8   playDirection     1334038 non-null  object
 9   x                 1334038 non-null  float64
 10  y                 1334038 non-null  float64
 11  s                 1334038 non-null  float64
 12  a                 1334038 non-null  float64
 13  dis               1334038 non-null  float64
 14  o                 1334038 non-null  float64
 15  dir               1334038 non-null  float64
 16  event             115891 non-null   object
 17  game_play_Id      1334038 non-null  object
 18  defensiveTeam     1334038 non-null  object
 19  ballCarrierId     1334038 non-null  int64
 20  bcx               1334038 non-null  float64
 21  bcy               1334038 non-null  float64
 22  bc_s              1334038 non-null  float64
 23  bc_a              1334038 non-null  float64
 24  bc_dis            1334038 non-null  float64
 25  bc_o              1334038 non-null  float64
 26  bc_dir            1334038 non-null  float64
 27  distance_from_bc  1334038 non-null  float64
 28  tackler_one       981539 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565335 non-null   float64
 31  assister_two      323674 non-null   float64
 32  missed_tackler_1  342879 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2090 non-null     object
 39  cosine            1255662 non-null  float64
 40  do_align          1334038 non-null  float64
 41  bc_do_align       1334038 non-null  float64
 42  weight            1334038 non-null  int64
 43  bc_weight         1334038 non-null  int64
 44  force             1334038 non-null  float64
 45  bc_force          1334038 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 468.2+ MB

In [155]:
###Saving Tracking Clean (Still has all observations)
tracking_clean.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean.csv', index=False)

### **2.4: Deleting Observations without a second of data beforehand**

In [615]:
def check_indices(df):
    # Get the indices of the rows where 'event' is 'tackle' and 'nflId' is not equal to 'ballCarrierId'
    tackle_indices = df[(df['event'] == 'first_contact') & (df['nflId'] != df['ballCarrierId'])].index

    # Number of frames before 'tackle' event
    X = 10

    # Initialize count
    count = 0

    # List to store the indices where 'game_play_Id' and 'nflId' are different
    different_indices = []

    for idx in tackle_indices:
        # Check if the index X indices before exists in the DataFrame
        if idx - X in df.index:
            # Check if 'game_play_Id' and 'nflId' are the same
            if df.loc[idx, 'game_play_Id'] != df.loc[idx - X, 'game_play_Id'] or df.loc[idx, 'nflId'] != df.loc[idx - X, 'nflId']:
                count += 1
                different_indices.append(idx)

    # Print the indices where 'game_play_Id' and 'nflId' are different
    print('Indices where game_play_Id and nflId are different:', different_indices)

    # Print the count
    print('Count:', count)

    return different_indices

In [616]:
check_indices(tracking_clean_1)

Indices where game_play_Id and nflId are different: [640, 1148, 1415, 2079, 2436, 4734, 4750, 4769, 4827, 5544, 5589, 5849, 6615, 7087, 7161, 7220, 7965, 8001, 8178, 8962, 10858, 12197, 12633, 12899, 12928, 13454, 14123, 14156, 14211, 15390, 16450, 17262, 17544, 17639, 18599, 18940, 19260, 19705, 19760, 20367, 20934, 29255, 29272, 32223, 36300, 36321, 40298, 41001, 41036, 42226, 43173, 43560, 43772, 45697, 45737, 46430, 47264, 47694, 47752, 48228, 49097, 49744, 49796, 50649, 51387, 51419, 52013, 52728, 52745, 54042, 54236, 54282, 54949, 55358, 56141, 57294, 58851, 59262, 59294, 61681, 63079, 63099, 63228, 63446, 63507, 65122, 65326, 65518, 67737, 68939, 69657, 70668, 71030, 71112, 71154, 71637, 72548, 72608, 74012, 74085, 74756, 75285, 77204, 77253, 77302, 77350, 77406, 77948, 78011, 78231, 79459, 79478, 79512, 80890, 81175, 81496, 82618, 84565, 84591, 84643, 87198, 87215, 87247, 87318, 87717, 87805, 88471, 88793, 88815, 88870, 89440, 90300, 90352, 91546, 91580, 91926, 94997, 96668, 97928, 98195, 98258, 99078, 99112, 100508, 101334, 101438, 101490, 101750, 102037, 102881, 103569, 103609, 104616, 106600, 106642, 106785, 107472, 111490, 111564, 111636, 112151, 112824, 112951, 112984, 113017, 113120, 113196, 113257, 113308, 113962, 114040, 114079, 115182, 115217, 117643, 117657, 118987, 119386, 119888, 121457, 122347, 122757, 122793, 123926, 125616, 129030, 129079, 129355, 130140, 130221, 130660, 131037, 131289, 132161, 132181, 134094, 136683, 137173, 138677, 138712, 139961, 140201, 141810, 141867, 141886, 141930, 141954, 142470, 142508, 144413, 145364, 145789, 146226, 148804, 148850, 148899, 148933, 149332, 149345, 150021, 150731, 150834, 150859, 151143, 151206, 151238, 151729, 152538, 152747, 152988, 153056, 153097, 154807, 155661, 156132, 156766, 156791, 156847, 156903, 157138, 157160, 158449, 158496, 160507, 161210, 163936, 164971, 164994, 165231, 166791, 166901, 166986, 167909, 169724, 170048, 173131, 175212, 175460, 176137, 181912, 182637, 185387, 187087, 188250, 188454, 189562, 190779, 191042, 191215, 191257, 192220, 192366, 192987, 193015, 193737, 193934, 194596, 195842, 196706, 196739, 198601, 198625, 201700, 201868, 202239, 202322, 207838, 207874, 209254, 209341, 209715, 210052, 210091, 211571, 212127, 212362, 212896, 213966, 216164, 216261, 217042, 217473, 217549, 217749, 219258, 219295, 219554, 219579, 219848, 220246, 220411, 220640, 221331, 221675, 221766, 221844, 222067, 222744, 225884, 226795, 227625, 227695, 228324, 228356, 229672, 229690, 230315, 230344, 230515, 230535, 232706, 233038, 234229, 234253, 238105, 238212, 238263, 240677, 242825, 242881, 242993, 243863, 245446, 246083, 247029, 248127, 250251, 250275, 253400, 253454, 255989, 258784, 259887, 259969, 260796, 261105, 261864, 262925, 263852, 264885, 266188, 266316, 270420, 271420, 271619, 271757, 271884, 272626, 273011, 274661, 276029, 276971, 277027, 277589, 278343, 279087, 284220, 285344, 287251, 287323, 287378, 287561, 287581, 287642, 288174, 292107, 293342, 293374, 293510, 293719, 293877, 293977, 294465, 294839, 295167, 295751, 295801, 296854, 297203, 298428, 298713, 299261, 299309, 299857, 299907, 300988, 301103, 301542, 301570, 301858, 302724, 303009, 303987, 304410, 304465, 305202, 306634, 306754, 306814, 307628, 312512, 316015, 316169, 318932, 319175, 323137, 323210, 324656, 325705, 331563, 332093, 335309, 335818, 336181, 336221, 336613, 337043, 337133, 337173, 337193, 337692, 337858, 338600, 338620, 338643, 339843, 340674, 340709, 341615, 342428, 342766, 343103, 343304, 343337, 343876, 344071, 344378, 344534, 344564, 344699, 345903, 346341, 346740, 348258, 348586, 348628, 349612, 350579, 351368, 351642, 351680, 352915, 353103, 353139, 354579, 354904, 356507, 356778, 356977, 357311, 357342, 357359, 357753, 358522, 358894, 359764, 359992, 363369, 364346, 365419, 365893, 366175, 368226, 371143, 372862, 372950, 373914, 374565, 375500, 375652, 375696, 375944, 375974, 376793, 377188, 377233, 377673, 377727, 377917, 378611, 379517, 382014, 383164, 383373, 384195, 384217, 386188, 386227, 388248, 389138, 391600, 392673, 392718, 394078, 394548, 394615, 394639, 395104, 395138, 396591, 396906, 396942, 396960, 397349, 397550, 398649, 398701, 399159, 400992, 401014, 402346, 403208, 404299, 404599, 405195, 406137, 406503, 406549, 408090, 408281, 410935, 410965, 411327, 412888, 413196, 414629, 414646, 415423, 418023, 419401, 420298, 420496, 420701, 421363, 421592, 421623, 421680, 423334, 424105, 424127, 424737, 424773, 425151, 425262, 425304, 425978, 426591, 426606, 426958, 427027, 430253, 431254, 433309, 433340, 434554, 434943, 435127, 435231, 436471, 436809, 436837, 437956, 437975, 438464, 438656, 438848, 438990, 439690, 440861, 441901, 441942, 442012, 442042, 443819, 444423, 444452, 446541, 447126, 448189, 450245, 451076, 451476, 451987, 452913, 453295, 453862, 455384, 455399, 461365, 462525, 463952, 464468, 466812, 466828, 467946, 469082, 469283, 470613, 471272, 471290, 471712, 471879, 472613, 473614, 474578, 475681, 475719, 476816, 477899, 482970, 484133, 487421, 487451, 488707, 488910, 488962, 494715, 495421, 495462, 496885, 497853, 497910, 498210, 498586, 498800, 498952, 499187, 499388, 508254, 508289, 510319, 510485, 512199, 512861, 513203, 514196, 514227, 515810, 515915, 516048, 516234, 516369, 516994, 518285, 520186, 520346, 522624, 522661, 523293, 523335, 523465, 525812, 526172, 527064, 528586, 530236, 530264, 531655, 531687, 535349, 535372, 535787, 535826, 535904, 537020, 538160, 539675, 541053, 541963, 544569, 550532, 551227, 551254, 553684, 561118, 570252, 570638, 572620, 574214, 576991, 577337, 578014, 578900, 583096, 584459, 585816, 587676, 587693, 588395, 590040, 590556, 590786, 592192, 592458, 593827, 593919, 593958, 594182, 594740, 595583, 595636, 596311, 597653, 597701, 598909, 599062, 600139, 600157, 600373, 601145, 601648, 602570, 602606, 602890, 602970, 603151, 605871, 606142, 606220, 613014, 613062, 615342, 615369, 615942, 616700, 618646, 620960, 621115, 621791, 622200, 622303, 623874, 623919, 624691, 625302, 626072, 626094, 626672, 628029, 628485, 629438, 629510, 630070, 630221, 630751, 630827, 630865, 631782, 633058, 634114, 640750, 644013, 644061, 645849, 645872, 647265, 648263, 651617, 654381, 654691, 654736, 657595, 658641, 658701, 658900, 658946, 658973, 660238, 660484, 660526, 660548, 660642, 662692, 664321, 664444, 664480, 664552, 665165, 665782, 667089, 667131, 672899, 676305, 679017, 680315, 681672, 686063, 686318, 689423, 691115, 695631, 696101, 697675, 697723, 697748, 697803, 697909, 698693, 699064, 703301, 703916, 704811, 704856, 706173, 707536, 707909, 711006, 711058, 711110, 711214, 714466, 714767, 714809, 715586, 718982, 719132, 719207, 719879, 719989, 720213, 720247, 722405, 722484, 722642, 724813, 724845, 726279, 726886, 728347, 728383, 728926, 730191, 730254, 730764, 730931, 731401, 734337, 734381, 737079, 737377, 737400, 741491, 741596, 741616, 742779, 743102, 744177, 745132, 745161, 745712, 746818, 747855, 749469, 750160, 750696, 751333, 751745, 752358, 752391, 753032, 754718, 757032, 758343, 760435, 760930, 761288, 761334, 761678, 762203, 762987, 764393, 765722, 766489, 769284, 769358, 772535, 774350, 774367, 778612, 778691, 779302, 779492, 784041, 784101, 784269, 784303, 784812, 785039, 785243, 785306, 785533, 786764, 787460, 788829, 789194, 790285, 790974, 792002, 794497, 795471, 796848, 796922, 797086, 797738, 797785, 798184, 799663, 800397, 800985, 801067, 801802, 802707, 802745, 803015, 803238, 805354, 805393, 805463, 805637, 806565, 808086, 808987, 809189, 809284, 809315, 810692, 810735, 810778, 810864, 812469, 812531, 812737, 812783, 814888, 814948, 816954, 817215, 817827, 818506, 820234, 821087, 821446, 822117, 824125, 824150, 826984, 827495, 827526, 827986, 828896, 829790, 830948, 831762, 832178, 835402, 835799, 836986, 837016, 840353, 843062, 843526, 844023, 845480, 845609, 845872, 846274, 846309, 846453, 846852, 846875, 847134, 847606, 848669, 849288, 849305, 851511, 851827, 851897, 853709, 855786, 856044, 856058, 856372, 856385, 857029, 857579, 857863, 859517, 859539, 859581, 861718, 866583, 871428, 871859, 873636, 873701, 875002, 875339, 875384, 877638, 878275, 878429, 878471, 880572, 880634, 880773, 881785, 884455, 887767, 888256, 889527, 894455, 894489, 895567, 895735, 895755, 896685, 897334, 898122, 898508, 898793, 898819, 900003, 901518, 901859, 905722, 905760, 906290, 908960, 909040, 915106, 917143, 920737, 920783, 923233, 925719, 925803, 925933, 926334, 926376, 931060, 931521, 932143, 932408, 932450, 932860, 935150, 935184, 935973, 936415, 936445, 938051, 938411, 938479, 940182, 940837, 941363, 941387, 941519, 941564, 942438, 942600, 943010, 943366, 944275, 944435, 945242, 945278, 945316, 946969, 946997, 947460, 947512, 948118, 948161, 948185, 948303, 949150, 950324, 951361, 954084, 954545, 956374, 958146, 959467, 959569, 959620, 959702, 960166, 960206, 960932, 961679, 962779, 962837, 963074, 963507, 966076, 967056, 967085, 967247, 967499, 968980, 970266, 974645, 974705, 975328, 976224, 977130, 979810, 979837, 979990, 980033, 980414, 980665, 981463, 981915, 982108, 982150, 985222, 986050, 986098, 986243, 986275, 986290, 986322, 986384, 987667, 987701, 988968, 989313, 989800, 989835, 990132, 990662, 990755, 991631, 998053, 998326, 999886, 1001378, 1002001, 1003530, 1003683, 1003955, 1003975, 1004890, 1004937, 1005514, 1005619, 1007104, 1008242, 1008499, 1009870, 1010018, 1010052, 1012455, 1013572, 1014473, 1017227, 1017420, 1018073, 1018127, 1018504, 1018542, 1018580, 1023318, 1023373, 1023847, 1023871, 1024903, 1024928, 1025914, 1025955, 1026040, 1026071, 1026318, 1027894, 1028561, 1028595, 1029293, 1029317, 1029365, 1029392, 1029574, 1030753, 1031173, 1031211, 1032004, 1032343, 1032387, 1033209, 1034289, 1034699, 1036408, 1037737, 1040602, 1042689, 1042789, 1043909, 1044071, 1049499, 1050426, 1050624, 1050885, 1054226, 1054246, 1055126, 1055205, 1055946, 1056277, 1056465, 1063671, 1068898, 1069348, 1069388, 1071899, 1071937, 1072833, 1073744, 1076083, 1076487, 1076531, 1077999, 1078202, 1080789, 1081512, 1086503, 1086767, 1086943, 1087136, 1088771, 1089651, 1089847, 1090543, 1090750, 1091177, 1093949, 1094157, 1094187, 1094247, 1095936, 1095971, 1096005, 1096301, 1096702, 1096769, 1096836, 1096970, 1101166, 1103429, 1103997, 1106531, 1107445, 1108072, 1110595, 1111639, 1112262, 1114523, 1114548, 1114595, 1114637, 1114692, 1114725, 1114987, 1115552, 1115805, 1117042, 1117892, 1117928, 1118490, 1118553, 1119167, 1120269, 1120335, 1120780, 1121055, 1122186, 1122299, 1122375, 1122810, 1122872, 1122934, 1123193, 1123228, 1124550, 1124598, 1125259, 1125892, 1126318, 1126373, 1126483, 1128467, 1128971, 1130118, 1130392, 1131553, 1131711, 1131790, 1132114, 1132171, 1133214, 1133891, 1136502, 1136567, 1136632, 1137767, 1138657, 1139151, 1140759, 1143379, 1143528, 1144906, 1145170, 1151210, 1151260, 1152726, 1154934, 1155309, 1157310, 1159211, 1159831, 1161025, 1161161, 1161213, 1162170, 1162276, 1163988, 1165440, 1165742, 1165908, 1168308, 1168448, 1172631, 1174355, 1174983, 1175737, 1177423, 1180194, 1180486, 1181401, 1181494, 1181531, 1181836, 1181881, 1182539, 1182582, 1182802, 1182834, 1183083, 1183802, 1183827, 1183851, 1184881, 1184914, 1185714, 1188671, 1188701, 1189838, 1189883, 1190057, 1192470, 1192756, 1197658, 1197691, 1199113, 1199344, 1199440, 1200632, 1201196, 1201232, 1201806, 1203280, 1203764, 1205912, 1207466, 1211063, 1211301, 1211521, 1212257, 1212273, 1212411, 1212511, 1212553, 1213414, 1214721, 1216795, 1217413, 1217471, 1219162, 1220550, 1222384, 1223098, 1223139, 1224039, 1225325, 1225736, 1225922, 1227619, 1227675, 1227973, 1228020, 1228393, 1228482, 1229933, 1230702, 1233326, 1234443, 1234501, 1235161, 1235196, 1235476, 1236050, 1236425, 1237266, 1237778, 1238305, 1238617, 1238679, 1240387, 1240574, 1241046, 1241401, 1241443, 1242367, 1242447, 1242514, 1242921, 1243438, 1245344, 1248739, 1250648, 1250831, 1251185, 1253580, 1255124, 1260947, 1261459, 1262011, 1262053, 1263982, 1264044, 1265014, 1269671, 1270130, 1270150, 1270598, 1270634, 1270916, 1271028, 1271272, 1271599, 1272075, 1272130, 1273248, 1274217, 1274271, 1274991, 1275474, 1276298, 1277640, 1277704, 1278304, 1278321, 1278832, 1280880, 1281011, 1281619, 1282501, 1282551, 1283120, 1284003, 1284892, 1284909, 1285400, 1286551, 1289418, 1289440, 1289894, 1291131, 1291507, 1292249, 1293622, 1295966, 1296505, 1296534, 1297192, 1298063, 1298313, 1298333, 1299302, 1300196, 1300236, 1300281, 1300371, 1301624, 1303074, 1303109, 1303201, 1304459, 1304608, 1304652, 1306078, 1306483, 1306505, 1307182, 1308131, 1309281, 1309572, 1309636, 1311151, 1311725, 1312532, 1316456, 1316682]
Count: 1544

[640,
 1148,
 1415,
 2079,
 2436,
 4734,
 4750,
 4769,
 4827,
 5544,
 5589,
 5849,
 6615,
 7087,
 7161,
 7220,
 7965,
 8001,
 8178,
 8962,
 10858,
 12197,
 12633,
 12899,
 12928,
 13454,
 14123,
 14156,
 14211,
 15390,
 16450,
 17262,
 17544,
 17639,
 18599,
 18940,
 19260,
 19705,
 19760,
 20367,
 20934,
 29255,
 29272,
 32223,
 36300,
 36321,
 40298,
 41001,
 41036,
 42226,
 43173,
 43560,
 43772,
 45697,
 45737,
 46430,
 47264,
 47694,
 47752,
 48228,
 49097,
 49744,
 49796,
 50649,
 51387,
 51419,
 52013,
 52728,
 52745,
 54042,
 54236,
 54282,
 54949,
 55358,
 56141,
 57294,
 58851,
 59262,
 59294,
 61681,
 63079,
 63099,
 63228,
 63446,
 63507,
 65122,
 65326,
 65518,
 67737,
 68939,
 69657,
 70668,
 71030,
 71112,
 71154,
 71637,
 72548,
 72608,
 74012,
 74085,
 74756,
 75285,
 77204,
 77253,
 77302,
 77350,
 77406,
 77948,
 78011,
 78231,
 79459,
 79478,
 79512,
 80890,
 81175,
 81496,
 82618,
 84565,
 84591,
 84643,
 87198,
 87215,
 87247,
 87318,
 87717,
 87805,
 88471,
 88793,
 88815,
 88870,
 89440,
 90300,
 90352,
 91546,
 91580,
 91926,
 94997,
 96668,
 97928,
 98195,
 98258,
 99078,
 99112,
 100508,
 101334,
 101438,
 101490,
 101750,
 102037,
 102881,
 103569,
 103609,
 104616,
 106600,
 106642,
 106785,
 107472,
 111490,
 111564,
 111636,
 112151,
 112824,
 112951,
 112984,
 113017,
 113120,
 113196,
 113257,
 113308,
 113962,
 114040,
 114079,
 115182,
 115217,
 117643,
 117657,
 118987,
 119386,
 119888,
 121457,
 122347,
 122757,
 122793,
 123926,
 125616,
 129030,
 129079,
 129355,
 130140,
 130221,
 130660,
 131037,
 131289,
 132161,
 132181,
 134094,
 136683,
 137173,
 138677,
 138712,
 139961,
 140201,
 141810,
 141867,
 141886,
 141930,
 141954,
 142470,
 142508,
 144413,
 145364,
 145789,
 146226,
 148804,
 148850,
 148899,
 148933,
 149332,
 149345,
 150021,
 150731,
 150834,
 150859,
 151143,
 151206,
 151238,
 151729,
 152538,
 152747,
 152988,
 153056,
 153097,
 154807,
 155661,
 156132,
 156766,
 156791,
 156847,
 156903,
 157138,
 157160,
 158449,
 158496,
 160507,
 161210,
 163936,
 164971,
 164994,
 165231,
 166791,
 166901,
 166986,
 167909,
 169724,
 170048,
 173131,
 175212,
 175460,
 176137,
 181912,
 182637,
 185387,
 187087,
 188250,
 188454,
 189562,
 190779,
 191042,
 191215,
 191257,
 192220,
 192366,
 192987,
 193015,
 193737,
 193934,
 194596,
 195842,
 196706,
 196739,
 198601,
 198625,
 201700,
 201868,
 202239,
 202322,
 207838,
 207874,
 209254,
 209341,
 209715,
 210052,
 210091,
 211571,
 212127,
 212362,
 212896,
 213966,
 216164,
 216261,
 217042,
 217473,
 217549,
 217749,
 219258,
 219295,
 219554,
 219579,
 219848,
 220246,
 220411,
 220640,
 221331,
 221675,
 221766,
 221844,
 222067,
 222744,
 225884,
 226795,
 227625,
 227695,
 228324,
 228356,
 229672,
 229690,
 230315,
 230344,
 230515,
 230535,
 232706,
 233038,
 234229,
 234253,
 238105,
 238212,
 238263,
 240677,
 242825,
 242881,
 242993,
 243863,
 245446,
 246083,
 247029,
 248127,
 250251,
 250275,
 253400,
 253454,
 255989,
 258784,
 259887,
 259969,
 260796,
 261105,
 261864,
 262925,
 263852,
 264885,
 266188,
 266316,
 270420,
 271420,
 271619,
 271757,
 271884,
 272626,
 273011,
 274661,
 276029,
 276971,
 277027,
 277589,
 278343,
 279087,
 284220,
 285344,
 287251,
 287323,
 287378,
 287561,
 287581,
 287642,
 288174,
 292107,
 293342,
 293374,
 293510,
 293719,
 293877,
 293977,
 294465,
 294839,
 295167,
 295751,
 295801,
 296854,
 297203,
 298428,
 298713,
 299261,
 299309,
 299857,
 299907,
 300988,
 301103,
 301542,
 301570,
 301858,
 302724,
 303009,
 303987,
 304410,
 304465,
 305202,
 306634,
 306754,
 306814,
 307628,
 312512,
 316015,
 316169,
 318932,
 319175,
 323137,
 323210,
 324656,
 325705,
 331563,
 332093,
 335309,
 335818,
 336181,
 336221,
 336613,
 337043,
 337133,
 337173,
 337193,
 337692,
 337858,
 338600,
 338620,
 338643,
 339843,
 340674,
 340709,
 341615,
 342428,
 342766,
 343103,
 343304,
 343337,
 343876,
 344071,
 344378,
 344534,
 344564,
 344699,
 345903,
 346341,
 346740,
 348258,
 348586,
 348628,
 349612,
 350579,
 351368,
 351642,
 351680,
 352915,
 353103,
 353139,
 354579,
 354904,
 356507,
 356778,
 356977,
 357311,
 357342,
 357359,
 357753,
 358522,
 358894,
 359764,
 359992,
 363369,
 364346,
 365419,
 365893,
 366175,
 368226,
 371143,
 372862,
 372950,
 373914,
 374565,
 375500,
 375652,
 375696,
 375944,
 375974,
 376793,
 377188,
 377233,
 377673,
 377727,
 377917,
 378611,
 379517,
 382014,
 383164,
 383373,
 384195,
 384217,
 386188,
 386227,
 388248,
 389138,
 391600,
 392673,
 392718,
 394078,
 394548,
 394615,
 394639,
 395104,
 395138,
 396591,
 396906,
 396942,
 396960,
 397349,
 397550,
 398649,
 398701,
 399159,
 400992,
 401014,
 402346,
 403208,
 404299,
 404599,
 405195,
 406137,
 406503,
 406549,
 408090,
 408281,
 410935,
 410965,
 411327,
 412888,
 413196,
 414629,
 414646,
 415423,
 418023,
 419401,
 420298,
 420496,
 420701,
 421363,
 421592,
 421623,
 421680,
 423334,
 424105,
 424127,
 424737,
 424773,
 425151,
 425262,
 425304,
 425978,
 426591,
 426606,
 426958,
 427027,
 430253,
 431254,
 433309,
 433340,
 434554,
 434943,
 435127,
 435231,
 436471,
 436809,
 436837,
 437956,
 437975,
 438464,
 438656,
 438848,
 438990,
 439690,
 440861,
 441901,
 441942,
 442012,
 442042,
 443819,
 444423,
 444452,
 446541,
 447126,
 448189,
 450245,
 451076,
 451476,
 451987,
 452913,
 453295,
 453862,
 455384,
 455399,
 461365,
 462525,
 463952,
 464468,
 466812,
 466828,
 467946,
 469082,
 469283,
 470613,
 471272,
 471290,
 471712,
 471879,
 472613,
 473614,
 474578,
 475681,
 475719,
 476816,
 477899,
 482970,
 484133,
 487421,
 487451,
 488707,
 488910,
 488962,
 494715,
 495421,
 495462,
 496885,
 497853,
 497910,
 498210,
 498586,
 498800,
 498952,
 499187,
 499388,
 508254,
 508289,
 510319,
 510485,
 512199,
 512861,
 513203,
 514196,
 514227,
 515810,
 515915,
 516048,
 516234,
 516369,
 516994,
 518285,
 520186,
 520346,
 522624,
 522661,
 523293,
 523335,
 523465,
 525812,
 526172,
 527064,
 528586,
 530236,
 530264,
 531655,
 531687,
 535349,
 535372,
 535787,
 535826,
 535904,
 537020,
 538160,
 539675,
 541053,
 541963,
 544569,
 550532,
 551227,
 551254,
 553684,
 561118,
 570252,
 570638,
 572620,
 574214,
 576991,
 577337,
 578014,
 578900,
 583096,
 584459,
 585816,
 587676,
 587693,
 588395,
 590040,
 590556,
 590786,
 592192,
 592458,
 593827,
 593919,
 593958,
 594182,
 594740,
 595583,
 595636,
 596311,
 597653,
 597701,
 598909,
 599062,
 600139,
 600157,
 600373,
 601145,
 601648,
 602570,
 602606,
 602890,
 602970,
 603151,
 605871,
 606142,
 606220,
 613014,
 613062,
 615342,
 615369,
 615942,
 616700,
 618646,
 620960,
 621115,
 621791,
 622200,
 622303,
 623874,
 623919,
 624691,
 625302,
 626072,
 626094,
 626672,
 628029,
 628485,
 629438,
 629510,
 630070,
 630221,
 630751,
 630827,
 630865,
 631782,
 633058,
 634114,
 640750,
 644013,
 644061,
 645849,
 645872,
 647265,
 648263,
 651617,
 654381,
 654691,
 654736,
 657595,
 658641,
 658701,
 658900,
 658946,
 658973,
 660238,
 660484,
 660526,
 660548,
 660642,
 662692,
 664321,
 664444,
 664480,
 664552,
 665165,
 665782,
 667089,
 667131,
 672899,
 676305,
 679017,
 680315,
 681672,
 686063,
 686318,
 689423,
 691115,
 695631,
 696101,
 697675,
 697723,
 697748,
 697803,
 697909,
 698693,
 699064,
 703301,
 703916,
 704811,
 704856,
 706173,
 707536,
 707909,
 711006,
 711058,
 711110,
 711214,
 714466,
 714767,
 714809,
 715586,
 718982,
 719132,
 719207,
 719879,
 719989,
 720213,
 720247,
 722405,
 722484,
 722642,
 724813,
 724845,
 726279,
 726886,
 728347,
 728383,
 728926,
 730191,
 730254,
 730764,
 730931,
 731401,
 734337,
 734381,
 737079,
 737377,
 737400,
 741491,
 741596,
 741616,
 742779,
 743102,
 744177,
 745132,
 745161,
 745712,
 746818,
 747855,
 749469,
 750160,
 750696,
 751333,
 751745,
 752358,
 752391,
 753032,
 754718,
 757032,
 758343,
 760435,
 760930,
 761288,
 761334,
 761678,
 762203,
 762987,
 764393,
 765722,
 766489,
 769284,
 769358,
 772535,
 774350,
 774367,
 778612,
 778691,
 779302,
 779492,
 784041,
 784101,
 784269,
 784303,
 784812,
 785039,
 785243,
 785306,
 785533,
 786764,
 787460,
 788829,
 789194,
 790285,
 790974,
 792002,
 794497,
 795471,
 796848,
 796922,
 797086,
 797738,
 797785,
 798184,
 799663,
 800397,
 800985,
 801067,
 801802,
 802707,
 802745,
 803015,
 803238,
 805354,
 805393,
 805463,
 805637,
 806565,
 808086,
 808987,
 809189,
 809284,
 809315,
 810692,
 810735,
 810778,
 810864,
 812469,
 812531,
 812737,
 812783,
 814888,
 814948,
 816954,
 817215,
 817827,
 818506,
 820234,
 821087,
 821446,
 822117,
 824125,
 824150,
 826984,
 827495,
 827526,
 827986,
 828896,
 829790,
 830948,
 831762,
 832178,
 835402,
 835799,
 836986,
 837016,
 840353,
 843062,
 843526,
 844023,
 845480,
 845609,
 845872,
 846274,
 846309,
 846453,
 846852,
 846875,
 ...]

In [161]:
missing_indices_07 = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [14063, 14074, 17612, 17623, 20579, 20590, 51887, 51898, 91263, 91274, 91562, 91573, 106329, 106340, 119489, 119500, 136398, 136409, 144658, 144669, 144878, 144889, 154658, 154669, 191539, 191550, 230405, 230416, 243028, 243039, 255160, 255171, 276491, 276502, 290376, 290387, 348106, 348117, 385470, 385481, 401427, 401438, 424743, 424754, 432652, 432663, 450031, 450042, 459968, 459979, 479700, 479711, 486440, 486451, 521657, 521668, 524722, 524733, 564815, 564826, 581886, 581897, 599640, 599651, 604195, 604206, 604781, 604792, 644283, 644294, 654830, 654841, 657479, 657490, 666904, 666915, 695217, 695228, 718709, 718720, 723525, 723536, 737745, 737756, 767105, 767116, 786301, 786312, 820288, 820299, 867588, 867599, 924264, 924275, 946608, 946619, 953235, 953246, 1002689, 1002700, 1002711, 1002722, 1036794, 1036805, 1148633, 1148644, 1191458, 1191469, 1196551, 1196562, 1314707, 1314718, 1316210, 1316221, 1318480, 1318491, 1319282, 1319293]
Count: 118

In [177]:
missing_indices_1 = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [1315, 1327, 2656, 2670, 14063, 14074, 17612, 17623, 17635, 17647, 18586, 18600, 20579, 20590, 21210, 21223, 28372, 28385, 33582, 38659, 38673, 39329, 39343, 43404, 43416, 46962, 46975, 47234, 47246, 50191, 50205, 51887, 51898, 54749, 54761, 55128, 55141, 60335, 60347, 66088, 66101, 76756, 76769, 76851, 76863, 77770, 77782, 83988, 84001, 90209, 90222, 91263, 91274, 91562, 91573, 92539, 92553, 96571, 96583, 96964, 96977, 98068, 98082, 98508, 98522, 106329, 106340, 106353, 106366, 108474, 108487, 108500, 119489, 119500, 121755, 121769, 122518, 122532, 127548, 127562, 136398, 136409, 138069, 138083, 139897, 139911, 140810, 140822, 142333, 142347, 144658, 144669, 144878, 144889, 154658, 154669, 154779, 154791, 156073, 156087, 156694, 156707, 159833, 159845, 163121, 163133, 170023, 170036, 175554, 175568, 179355, 179369, 180149, 180161, 189038, 189052, 191539, 191550, 196635, 196648, 199053, 199067, 203011, 203023, 204547, 204559, 204704, 204717, 204877, 204889, 204902, 204915, 205420, 205432, 205911, 205923, 209055, 209068, 209080, 209092, 212911, 212925, 215112, 215126, 220822, 220834, 226877, 226890, 229712, 229725, 230405, 230416, 237220, 237233, 237767, 237779, 243028, 243039, 254044, 254056, 254070, 254084, 255160, 255171, 263701, 263715, 263729, 263743, 271012, 271026, 276491, 276502, 280246, 280260, 281089, 281101, 287764, 287776, 288875, 288889, 290376, 290387, 290461, 290473, 291306, 291319, 291593, 291607, 305947, 305959, 310754, 310768, 311916, 311928, 311940, 317394, 317407, 324536, 324550, 327023, 327035, 327048, 327061, 340560, 340574, 342933, 342947, 348106, 348117, 348708, 348722, 349342, 349355, 352754, 352768, 354068, 354080, 355570, 355583, 357785, 357799, 374187, 374201, 378109, 378121, 378133, 378145, 381446, 381460, 382244, 382258, 382270, 382282, 383183, 383197, 383780, 383794, 385470, 385481, 387254, 387268, 391622, 391634, 395088, 395101, 395965, 395979, 399315, 399327, 401427, 401438, 402235, 402249, 402439, 402451, 403054, 403068, 404249, 404261, 408577, 408591, 409885, 409897, 412653, 412666, 412679, 412692, 424743, 424754, 425800, 425814, 426776, 426789, 428927, 428939, 429972, 429986, 432652, 432663, 440877, 440889, 450031, 450042, 450638, 450652, 456166, 456179, 459968, 459979, 474134, 474146, 479700, 479711, 482306, 482318, 486440, 486451, 488044, 488058, 494012, 494024, 496772, 496786, 500726, 500740, 502265, 502279, 509367, 509379, 516618, 516632, 519537, 519549, 519677, 519691, 521657, 521668, 524722, 524733, 525815, 525827, 527291, 527304, 527317, 527330, 533067, 533080, 540127, 540139, 540715, 540729, 541290, 541304, 542057, 542070, 542897, 542911, 545637, 545651, 556720, 556733, 564815, 564826, 565278, 565292, 567187, 567201, 581886, 581897, 587095, 587108, 588325, 588339, 594344, 594356, 598286, 598298, 599640, 599651, 604195, 604206, 604781, 604792, 607063, 607075, 611526, 611540, 615426, 615440, 619779, 619793, 621746, 621760, 626487, 626499, 643272, 643284, 644283, 644294, 645840, 645854, 646660, 646673, 648980, 648992, 649005, 649018, 654830, 654841, 657479, 657490, 660189, 660201, 662618, 662631, 663887, 663901, 664357, 664369, 666904, 666915, 670730, 670744, 671189, 671201, 685048, 685061, 694630, 694644, 695217, 695228, 707378, 707391, 708946, 708960, 717155, 717167, 718709, 718720, 723525, 723536, 723826, 723840, 723854, 725369, 725381, 725437, 725451, 727010, 727024, 732433, 732446, 734040, 734054, 737745, 737756, 747761, 747774, 748036, 748050, 767105, 767116, 769495, 769508, 769592, 769604, 770979, 770991, 786301, 786312, 790736, 790748, 794283, 794296, 798682, 798694, 799979, 799991, 805190, 805204, 808469, 808482, 811436, 811449, 818076, 818090, 820288, 820299, 837817, 837829, 839641, 839654, 843371, 843384, 845241, 845254, 845884, 845896, 850028, 850040, 853166, 853179, 855591, 855604, 857218, 857232, 859855, 859869, 867588, 867599, 876526, 876538, 881585, 881598, 887831, 887844, 896642, 896654, 896668, 896682, 898650, 898662, 898981, 898993, 902010, 902022, 902730, 902743, 908078, 908091, 911349, 911363, 911659, 911673, 916714, 916727, 919052, 919065, 923262, 923276, 924264, 924275, 926837, 926850, 927966, 927979, 934678, 934691, 941413, 941427, 941441, 941455, 944680, 944692, 946608, 946619, 953235, 953246, 953258, 953270, 967010, 967023, 979579, 979592, 1000963, 1000977, 1001942, 1001955, 1002689, 1002700, 1002711, 1002722, 1019697, 1019710, 1028282, 1028294, 1028542, 1028554, 1032356, 1032370, 1033242, 1033256, 1036794, 1036805, 1038001, 1038013, 1041485, 1041498, 1042466, 1042478, 1048860, 1048873, 1048886, 1062086, 1062099, 1063982, 1063995, 1069082, 1069096, 1070423, 1070435, 1091920, 1091934, 1092408, 1092422, 1101704, 1101716, 1116754, 1116768, 1118312, 1118325, 1121181, 1121195, 1123553, 1123566, 1130379, 1130393, 1131365, 1131379, 1134004, 1134016, 1136232, 1136245, 1136481, 1136495, 1141945, 1141957, 1144710, 1144722, 1148633, 1148644, 1159488, 1159502, 1161622, 1161635, 1162973, 1162985, 1168027, 1168041, 1171774, 1171786, 1191458, 1191469, 1196231, 1196243, 1196551, 1196562, 1200460, 1200474, 1200654, 1200668, 1206773, 1206785, 1207218, 1207230, 1211346, 1211358, 1215615, 1215629, 1240393, 1240407, 1245245, 1245259, 1248510, 1248524, 1248538, 1255160, 1255172, 1256218, 1256231, 1264990, 1265002, 1265014, 1266259, 1266273, 1270652, 1270664, 1272695, 1272708, 1273518, 1273530, 1281301, 1281315, 1297666, 1297680, 1297694, 1301459, 1301471, 1308760, 1308774, 1308993, 1309006, 1314707, 1314718, 1316210, 1316221, 1318480, 1318491, 1319282, 1319293, 1322330, 1322344, 1323878, 1323891, 1324044, 1324057, 1328638, 1328650, 1329968, 1329982]
Count: 690

In [384]:
missing_indices_fumble_1 = check_indices(tracking_clean_1)

Indices where game_play_Id and nflId are different: [79541, 123526, 444032, 969176]
Count: 4

In [239]:
missing_indices_1_no_bc = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [1327, 2670, 14063, 17623, 17647, 18600, 20590, 21223, 28372, 38659, 39343, 43404, 46962, 47246, 50191, 51887, 54749, 55141, 60335, 66088, 76756, 76851, 77770, 84001, 90209, 91274, 91562, 92539, 96571, 96964, 98082, 98508, 106340, 106353, 108487, 108500, 119500, 121769, 122532, 127548, 136398, 138083, 139897, 140822, 142347, 144669, 144889, 154669, 154791, 156087, 156707, 159845, 163133, 170023, 175568, 179355, 180161, 189038, 191550, 196635, 199053, 203023, 204559, 204717, 204877, 204902, 205420, 205911, 209055, 209080, 212925, 215126, 220822, 226877, 229712, 230405, 237220, 237779, 243039, 254044, 254070, 255160, 263715, 263743, 271012, 276491, 280260, 281101, 287776, 288889, 290387, 290461, 291319, 291593, 305947, 310768, 311916, 311928, 317394, 324550, 327023, 327061, 340574, 342947, 348106, 348722, 349355, 352754, 354068, 355583, 357799, 374201, 378109, 378133, 381446, 382244, 382270, 383183, 383780, 385470, 387254, 391634, 395101, 395979, 399315, 401438, 402235, 402451, 403068, 404261, 408591, 409885, 412653, 412692, 424743, 425800, 426776, 428939, 429986, 432663, 440889, 450031, 450638, 456166, 459968, 474134, 479700, 482318, 486440, 488044, 494024, 496786, 500726, 502279, 509367, 516632, 519537, 519677, 521657, 524733, 525827, 527291, 527330, 533067, 540139, 540715, 541290, 542057, 542911, 545637, 556733, 564815, 565278, 567187, 581886, 587108, 588339, 594356, 598298, 599640, 604206, 604792, 607075, 611540, 615426, 619793, 621760, 626499, 643284, 644294, 645854, 646660, 648992, 649005, 654830, 657490, 660201, 662631, 663887, 664357, 666915, 670730, 671201, 685048, 694644, 695217, 707391, 708946, 717167, 718709, 723525, 723826, 723840, 725369, 725451, 727010, 732433, 734054, 737745, 747761, 748050, 767116, 769508, 769592, 770991, 786312, 790736, 794283, 798694, 799991, 805190, 808469, 811449, 818076, 820288, 837829, 839641, 843371, 845254, 845896, 850028, 853166, 855591, 857218, 859855, 867588, 876538, 881585, 887831, 896642, 896668, 898650, 898981, 902010, 902730, 908078, 911349, 911659, 916714, 919065, 923276, 924275, 926850, 927979, 934691, 941413, 941455, 944680, 946608, 953246, 953258, 967023, 979592, 1000963, 1001955, 1002700, 1002711, 1019710, 1028282, 1028554, 1032370, 1033256, 1036805, 1038013, 1041485, 1042466, 1048860, 1048873, 1062086, 1063995, 1069082, 1070423, 1091934, 1092422, 1101704, 1116754, 1118325, 1121195, 1123566, 1130393, 1131365, 1134016, 1136245, 1136495, 1141945, 1144710, 1148633, 1159502, 1161622, 1162973, 1168041, 1171786, 1191458, 1196243, 1196562, 1200474, 1200654, 1206785, 1207218, 1211346, 1215629, 1240407, 1245259, 1248510, 1248524, 1255172, 1256231, 1264990, 1265014, 1266273, 1270652, 1272695, 1273530, 1281301, 1297666, 1297694, 1301471, 1308774, 1309006, 1314707, 1316221, 1318491, 1319282, 1322330, 1323891, 1324057, 1328638, 1329968]
Count: 348

**Checking if any indices are in 'missing_indices_07' but are not in 'missing_indices_1'**

In [184]:
# Convert the lists to sets
set_07 = set(missing_indices_07)
set_1 = set(missing_indices_1)

# Find the elements that are in set_07 but not in set_1
difference = set_07.difference(set_1)

# Print the number of such elements
print(len(difference))

0

In [172]:
# Define the path to the folder where you want to save the file
folder_path = '/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/'

In [173]:
###Save list of Tackle Indices for 7 frames before
with open(folder_path + 'missed_indices_07.pkl', 'wb') as f:
    pickle.dump(missing_indices_07, f)

In [178]:
###Save list of Tackle Indices for 10 frames before
with open(folder_path + 'missing_indices_1.pkl', 'wb') as f:
    pickle.dump(missing_indices_1, f)

In [240]:
###Function to check number of indicies that they there is data for missed tackles
def check_indices_mt(df):
    # Get the indices of the rows where 'event' is 'tackle'
    missed_tackle_indices = df[(df['new_event'] == 'missed tackle') & (df['nflId'] != df['ballCarrierId'])].index

    # Number of frames before 'tackle' event
    X = 10

    # Initialize count
    count = 0

    # List to store the indices where 'game_play_Id' and 'nflId' are different
    different_indices = []

    for idx in missed_tackle_indices:
        # Check if the index X indices before exists in the DataFrame
        if idx - X in df.index:
            # Check if 'game_play_Id' and 'nflId' are the same
            if df.loc[idx, 'game_play_Id'] != df.loc[idx - X, 'game_play_Id'] or df.loc[idx, 'nflId'] != df.loc[idx - X, 'nflId']:
                count += 1
                different_indices.append(idx)

    # Print the indices where 'game_play_Id' and 'nflId' are different
    print('Indices where game_play_Id and nflId are different:', different_indices)

    # Print the count
    print('Count:', count)

    return different_indices

In [163]:
missing_indices_mt_07 = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 34725, 51731, 52779, 55640, 57411, 58035, 68848, 86381, 107019, 110595, 120597, 120631, 136338, 147996, 156674, 158520, 178125, 212823, 214636, 311921, 332121, 351489, 368915, 372788, 382782, 409111, 432892, 452750, 464894, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 574471, 581048, 610460, 630315, 654434, 670021, 673241, 676171, 692371, 699997, 771085, 780654, 788532, 794968, 795241, 796630, 807953, 815705, 819585, 840445, 841241, 842578, 845521, 854124, 877829, 884016, 886686, 899833, 901033, 907655, 921162, 924949, 933033, 959407, 987203, 994045, 1047478, 1053698, 1060203, 1091799, 1124084, 1128294, 1136398, 1140202, 1150719, 1165152, 1177443, 1181479, 1194337, 1214065, 1214145, 1215864, 1218259, 1236455, 1239235, 1266063, 1272172, 1296186, 1307083]
Count: 100

In [180]:
missing_indices_mt_1 = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 19937, 34725, 44263, 48795, 51731, 52145, 52779, 55640, 57411, 58035, 59739, 64431, 68848, 73619, 78497, 83491, 86381, 88656, 99800, 107019, 110595, 117045, 120597, 120631, 136338, 147996, 148433, 155369, 156674, 158520, 177788, 178125, 192331, 193642, 212823, 214636, 216202, 225155, 226134, 244252, 263660, 298871, 301237, 306877, 311921, 317547, 323191, 327498, 332121, 341552, 350970, 351489, 356544, 368915, 372788, 380308, 380580, 382385, 382782, 398124, 409111, 427521, 432892, 436573, 444996, 452750, 464894, 466031, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 557963, 574471, 581048, 592086, 596080, 610460, 623984, 630315, 636633, 654434, 668747, 670021, 673241, 676171, 692371, 699997, 706701, 712253, 713260, 723993, 729310, 730937, 731747, 752331, 764733, 771085, 771476, 780654, 788532, 794968, 795080, 795241, 796630, 796807, 807953, 809992, 812423, 815705, 819585, 819869, 823013, 825463, 840445, 841241, 842578, 843034, 845521, 847855, 854124, 877829, 884016, 886686, 887370, 899261, 899833, 901033, 906224, 907655, 910631, 911311, 921162, 924949, 926079, 933033, 944461, 959407, 987203, 994045, 994666, 1002894, 1020531, 1047478, 1053698, 1057306, 1060203, 1069427, 1077155, 1085274, 1091799, 1102411, 1107945, 1124084, 1124511, 1128294, 1132489, 1136398, 1140202, 1150719, 1152050, 1164741, 1165152, 1177443, 1181479, 1194337, 1195152, 1204679, 1209794, 1214065, 1214145, 1215864, 1216842, 1218259, 1229866, 1236455, 1239235, 1240551, 1266063, 1269088, 1272172, 1274447, 1277804, 1296186, 1302468, 1307083, 1313187]
Count: 195

In [241]:
missing_indices_mt_1_no_bc = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 19937, 34725, 44263, 48795, 51731, 52145, 52779, 55640, 57411, 58035, 59739, 64431, 68848, 73619, 78497, 83491, 86381, 88656, 99800, 107019, 110595, 117045, 120597, 120631, 136338, 147996, 148433, 155369, 156674, 158520, 177788, 178125, 192331, 193642, 212823, 214636, 216202, 225155, 226134, 244252, 263660, 298871, 301237, 306877, 311921, 317547, 323191, 327498, 332121, 341552, 350970, 351489, 356544, 368915, 372788, 380308, 380580, 382385, 382782, 398124, 409111, 427521, 432892, 436573, 444996, 452750, 464894, 466031, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 557963, 574471, 581048, 592086, 596080, 610460, 623984, 630315, 636633, 654434, 668747, 670021, 673241, 676171, 692371, 699997, 706701, 712253, 713260, 723993, 729310, 730937, 731747, 752331, 764733, 771085, 771476, 780654, 788532, 794968, 795080, 795241, 796630, 796807, 807953, 809992, 812423, 815705, 819585, 819869, 823013, 825463, 840445, 841241, 842578, 843034, 845521, 847855, 854124, 877829, 884016, 886686, 887370, 899261, 899833, 901033, 906224, 907655, 910631, 911311, 921162, 924949, 926079, 933033, 944461, 959407, 987203, 994045, 994666, 1002894, 1020531, 1047478, 1053698, 1057306, 1060203, 1069427, 1077155, 1085274, 1091799, 1102411, 1107945, 1124084, 1124511, 1128294, 1132489, 1136398, 1140202, 1150719, 1152050, 1164741, 1165152, 1177443, 1181479, 1194337, 1195152, 1204679, 1209794, 1214065, 1214145, 1215864, 1216842, 1218259, 1229866, 1236455, 1239235, 1240551, 1266063, 1269088, 1272172, 1274447, 1277804, 1296186, 1302468, 1307083, 1313187]
Count: 195

In [174]:
###Save list of Missed Tackle Indices for 7 frames before
with open(folder_path + 'missed_indices_mt_07.pkl', 'wb') as f:
    pickle.dump(missing_indices_mt_07, f)

In [181]:
###Save list of Missed Tackle Indices for 10 frames before
with open(folder_path + 'missed_indices_mt_1.pkl', 'wb') as f:
    pickle.dump(missing_indices_mt_1, f)

In [165]:
'''OLD VERSION
###Function to delete rows where there is no data at least 7 frames before the tackle
def drop_dataless_rows(df, indices):
    count = 0
    for index in indices:
        game_play_id = df.loc[index, 'game_play_Id']
        nfl_id = df.loc[index, 'nflId']
        matching_rows = df[(df['game_play_Id'] == game_play_id) & (df['nflId'] == nfl_id)]
        count += len(matching_rows)
        df = df.drop(matching_rows.index)
    print(f'Total matching rows: {count}')
    return df
'''

In [204]:
###Function to delete rows where there is no data at least 10 frames before the tackle
def drop_dataless_rows(df, indices):
    count = 0
    for index in indices:
        if index in df.index:
            game_play_id = df.loc[index, 'game_play_Id']
            nfl_id = df.loc[index, 'nflId']
            matching_rows = df[(df['game_play_Id'] == game_play_id) & (df['nflId'] == nfl_id)]
            count += len(matching_rows)
            df = df.drop(matching_rows.index)
        else:
            print(f'Index {index} not in DataFrame')
    print(f'Total matching rows: {count}')
    return df

In [203]:
missing_indices_1

[1315,
 1327,
 2656,
 2670,
 14063,
 14074,
 17612,
 17623,
 17635,
 17647,
 18586,
 18600,
 20579,
 20590,
 21210,
 21223,
 28372,
 28385,
 33582,
 38659,
 38673,
 39329,
 39343,
 43404,
 43416,
 46962,
 46975,
 47234,
 47246,
 50191,
 50205,
 51887,
 51898,
 54749,
 54761,
 55128,
 55141,
 60335,
 60347,
 66088,
 66101,
 76756,
 76769,
 76851,
 76863,
 77770,
 77782,
 83988,
 84001,
 90209,
 90222,
 91263,
 91274,
 91562,
 91573,
 92539,
 92553,
 96571,
 96583,
 96964,
 96977,
 98068,
 98082,
 98508,
 98522,
 106329,
 106340,
 106353,
 106366,
 108474,
 108487,
 108500,
 119489,
 119500,
 121755,
 121769,
 122518,
 122532,
 127548,
 127562,
 136398,
 136409,
 138069,
 138083,
 139897,
 139911,
 140810,
 140822,
 142333,
 142347,
 144658,
 144669,
 144878,
 144889,
 154658,
 154669,
 154779,
 154791,
 156073,
 156087,
 156694,
 156707,
 159833,
 159845,
 163121,
 163133,
 170023,
 170036,
 175554,
 175568,
 179355,
 179369,
 180149,
 180161,
 189038,
 189052,
 191539,
 191550,
 196635,
 196648,
 199053,
 199067,
 203011,
 203023,
 204547,
 204559,
 204704,
 204717,
 204877,
 204889,
 204902,
 204915,
 205420,
 205432,
 205911,
 205923,
 209055,
 209068,
 209080,
 209092,
 212911,
 212925,
 215112,
 215126,
 220822,
 220834,
 226877,
 226890,
 229712,
 229725,
 230405,
 230416,
 237220,
 237233,
 237767,
 237779,
 243028,
 243039,
 254044,
 254056,
 254070,
 254084,
 255160,
 255171,
 263701,
 263715,
 263729,
 263743,
 271012,
 271026,
 276491,
 276502,
 280246,
 280260,
 281089,
 281101,
 287764,
 287776,
 288875,
 288889,
 290376,
 290387,
 290461,
 290473,
 291306,
 291319,
 291593,
 291607,
 305947,
 305959,
 310754,
 310768,
 311916,
 311928,
 311940,
 317394,
 317407,
 324536,
 324550,
 327023,
 327035,
 327048,
 327061,
 340560,
 340574,
 342933,
 342947,
 348106,
 348117,
 348708,
 348722,
 349342,
 349355,
 352754,
 352768,
 354068,
 354080,
 355570,
 355583,
 357785,
 357799,
 374187,
 374201,
 378109,
 378121,
 378133,
 378145,
 381446,
 381460,
 382244,
 382258,
 382270,
 382282,
 383183,
 383197,
 383780,
 383794,
 385470,
 385481,
 387254,
 387268,
 391622,
 391634,
 395088,
 395101,
 395965,
 395979,
 399315,
 399327,
 401427,
 401438,
 402235,
 402249,
 402439,
 402451,
 403054,
 403068,
 404249,
 404261,
 408577,
 408591,
 409885,
 409897,
 412653,
 412666,
 412679,
 412692,
 424743,
 424754,
 425800,
 425814,
 426776,
 426789,
 428927,
 428939,
 429972,
 429986,
 432652,
 432663,
 440877,
 440889,
 450031,
 450042,
 450638,
 450652,
 456166,
 456179,
 459968,
 459979,
 474134,
 474146,
 479700,
 479711,
 482306,
 482318,
 486440,
 486451,
 488044,
 488058,
 494012,
 494024,
 496772,
 496786,
 500726,
 500740,
 502265,
 502279,
 509367,
 509379,
 516618,
 516632,
 519537,
 519549,
 519677,
 519691,
 521657,
 521668,
 524722,
 524733,
 525815,
 525827,
 527291,
 527304,
 527317,
 527330,
 533067,
 533080,
 540127,
 540139,
 540715,
 540729,
 541290,
 541304,
 542057,
 542070,
 542897,
 542911,
 545637,
 545651,
 556720,
 556733,
 564815,
 564826,
 565278,
 565292,
 567187,
 567201,
 581886,
 581897,
 587095,
 587108,
 588325,
 588339,
 594344,
 594356,
 598286,
 598298,
 599640,
 599651,
 604195,
 604206,
 604781,
 604792,
 607063,
 607075,
 611526,
 611540,
 615426,
 615440,
 619779,
 619793,
 621746,
 621760,
 626487,
 626499,
 643272,
 643284,
 644283,
 644294,
 645840,
 645854,
 646660,
 646673,
 648980,
 648992,
 649005,
 649018,
 654830,
 654841,
 657479,
 657490,
 660189,
 660201,
 662618,
 662631,
 663887,
 663901,
 664357,
 664369,
 666904,
 666915,
 670730,
 670744,
 671189,
 671201,
 685048,
 685061,
 694630,
 694644,
 695217,
 695228,
 707378,
 707391,
 708946,
 708960,
 717155,
 717167,
 718709,
 718720,
 723525,
 723536,
 723826,
 723840,
 723854,
 725369,
 725381,
 725437,
 725451,
 727010,
 727024,
 732433,
 732446,
 734040,
 734054,
 737745,
 737756,
 747761,
 747774,
 748036,
 748050,
 767105,
 767116,
 769495,
 769508,
 769592,
 769604,
 770979,
 770991,
 786301,
 786312,
 790736,
 790748,
 794283,
 794296,
 798682,
 798694,
 799979,
 799991,
 805190,
 805204,
 808469,
 808482,
 811436,
 811449,
 818076,
 818090,
 820288,
 820299,
 837817,
 837829,
 839641,
 839654,
 843371,
 843384,
 845241,
 845254,
 845884,
 845896,
 850028,
 850040,
 853166,
 853179,
 855591,
 855604,
 857218,
 857232,
 859855,
 859869,
 867588,
 867599,
 876526,
 876538,
 881585,
 881598,
 887831,
 887844,
 896642,
 896654,
 896668,
 896682,
 898650,
 898662,
 898981,
 898993,
 902010,
 902022,
 902730,
 902743,
 908078,
 908091,
 911349,
 911363,
 911659,
 911673,
 916714,
 916727,
 919052,
 919065,
 923262,
 923276,
 924264,
 924275,
 926837,
 926850,
 927966,
 927979,
 934678,
 934691,
 941413,
 941427,
 941441,
 941455,
 944680,
 944692,
 946608,
 946619,
 953235,
 953246,
 953258,
 953270,
 967010,
 967023,
 979579,
 979592,
 1000963,
 1000977,
 1001942,
 1001955,
 1002689,
 1002700,
 1002711,
 1002722,
 1019697,
 1019710,
 1028282,
 1028294,
 1028542,
 1028554,
 1032356,
 1032370,
 1033242,
 1033256,
 1036794,
 1036805,
 1038001,
 1038013,
 1041485,
 1041498,
 1042466,
 1042478,
 1048860,
 1048873,
 1048886,
 1062086,
 1062099,
 1063982,
 1063995,
 1069082,
 1069096,
 1070423,
 1070435,
 1091920,
 1091934,
 1092408,
 1092422,
 1101704,
 1101716,
 1116754,
 1116768,
 1118312,
 1118325,
 1121181,
 1121195,
 1123553,
 1123566,
 1130379,
 1130393,
 1131365,
 1131379,
 1134004,
 1134016,
 1136232,
 1136245,
 1136481,
 1136495,
 1141945,
 1141957,
 1144710,
 1144722,
 1148633,
 1148644,
 1159488,
 1159502,
 1161622,
 1161635,
 1162973,
 1162985,
 1168027,
 1168041,
 1171774,
 1171786,
 1191458,
 1191469,
 1196231,
 1196243,
 1196551,
 1196562,
 1200460,
 1200474,
 1200654,
 1200668,
 1206773,
 1206785,
 1207218,
 1207230,
 1211346,
 1211358,
 1215615,
 1215629,
 1240393,
 1240407,
 1245245,
 1245259,
 1248510,
 1248524,
 1248538,
 1255160,
 1255172,
 1256218,
 1256231,
 1264990,
 1265002,
 1265014,
 1266259,
 1266273,
 1270652,
 1270664,
 1272695,
 1272708,
 1273518,
 1273530,
 1281301,
 1281315,
 1297666,
 1297680,
 1297694,
 1301459,
 1301471,
 1308760,
 1308774,
 1308993,
 1309006,
 1314707,
 1314718,
 1316210,
 1316221,
 1318480,
 1318491,
 1319282,
 1319293,
 1322330,
 1322344,
 1323878,
 1323891,
 1324044,
 1324057,
 1328638,
 1328650,
 1329968,
 1329982]

In [166]:
tracking_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334038 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1334038 non-null  int64
 1   playId            1334038 non-null  int64
 2   nflId             1334038 non-null  float64
 3   displayName       1334038 non-null  object
 4   frameId           1334038 non-null  int64
 5   time              1334038 non-null  object
 6   jerseyNumber      1334038 non-null  float64
 7   club              1334038 non-null  object
 8   playDirection     1334038 non-null  object
 9   x                 1334038 non-null  float64
 10  y                 1334038 non-null  float64
 11  s                 1334038 non-null  float64
 12  a                 1334038 non-null  float64
 13  dis               1334038 non-null  float64
 14  o                 1334038 non-null  float64
 15  dir               1334038 non-null  float64
 16  event             115891 non-null   object
 17  game_play_Id      1334038 non-null  object
 18  defensiveTeam     1334038 non-null  object
 19  ballCarrierId     1334038 non-null  int64
 20  bcx               1334038 non-null  float64
 21  bcy               1334038 non-null  float64
 22  bc_s              1334038 non-null  float64
 23  bc_a              1334038 non-null  float64
 24  bc_dis            1334038 non-null  float64
 25  bc_o              1334038 non-null  float64
 26  bc_dir            1334038 non-null  float64
 27  distance_from_bc  1334038 non-null  float64
 28  tackler_one       981539 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565335 non-null   float64
 31  assister_two      323674 non-null   float64
 32  missed_tackler_1  342879 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2090 non-null     object
 39  cosine            1255662 non-null  float64
 40  do_align          1334038 non-null  float64
 41  bc_do_align       1334038 non-null  float64
 42  weight            1334038 non-null  int64
 43  bc_weight         1334038 non-null  int64
 44  force             1334038 non-null  float64
 45  bc_force          1334038 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 468.2+ MB

In [167]:
###Running for Tackles Indices
tracking_clean_07 = drop_dataless_rows(tracking_clean, missing_indices_07)

Total matching rows: 1298

In [168]:
tracking_clean_07.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1332740 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1332740 non-null  int64
 1   playId            1332740 non-null  int64
 2   nflId             1332740 non-null  float64
 3   displayName       1332740 non-null  object
 4   frameId           1332740 non-null  int64
 5   time              1332740 non-null  object
 6   jerseyNumber      1332740 non-null  float64
 7   club              1332740 non-null  object
 8   playDirection     1332740 non-null  object
 9   x                 1332740 non-null  float64
 10  y                 1332740 non-null  float64
 11  s                 1332740 non-null  float64
 12  a                 1332740 non-null  float64
 13  dis               1332740 non-null  float64
 14  o                 1332740 non-null  float64
 15  dir               1332740 non-null  float64
 16  event             115551 non-null   object
 17  game_play_Id      1332740 non-null  object
 18  defensiveTeam     1332740 non-null  object
 19  ballCarrierId     1332740 non-null  int64
 20  bcx               1332740 non-null  float64
 21  bcy               1332740 non-null  float64
 22  bc_s              1332740 non-null  float64
 23  bc_a              1332740 non-null  float64
 24  bc_dis            1332740 non-null  float64
 25  bc_o              1332740 non-null  float64
 26  bc_dir            1332740 non-null  float64
 27  distance_from_bc  1332740 non-null  float64
 28  tackler_one       980241 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565335 non-null   float64
 31  assister_two      323674 non-null   float64
 32  missed_tackler_1  342879 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2090 non-null     object
 39  cosine            1254364 non-null  float64
 40  do_align          1332740 non-null  float64
 41  bc_do_align       1332740 non-null  float64
 42  weight            1332740 non-null  int64
 43  bc_weight         1332740 non-null  int64
 44  force             1332740 non-null  float64
 45  bc_force          1332740 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 477.9+ MB

In [169]:
###Running for Missed Tackle Indices
tracking_clean_07 = drop_dataless_rows(tracking_clean_07, missing_indices_mt_07)

Total matching rows: 3609

In [170]:
tracking_clean_07.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1329131 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1329131 non-null  int64
 1   playId            1329131 non-null  int64
 2   nflId             1329131 non-null  float64
 3   displayName       1329131 non-null  object
 4   frameId           1329131 non-null  int64
 5   time              1329131 non-null  object
 6   jerseyNumber      1329131 non-null  float64
 7   club              1329131 non-null  object
 8   playDirection     1329131 non-null  object
 9   x                 1329131 non-null  float64
 10  y                 1329131 non-null  float64
 11  s                 1329131 non-null  float64
 12  a                 1329131 non-null  float64
 13  dis               1329131 non-null  float64
 14  o                 1329131 non-null  float64
 15  dir               1329131 non-null  float64
 16  event             115238 non-null   object
 17  game_play_Id      1329131 non-null  object
 18  defensiveTeam     1329131 non-null  object
 19  ballCarrierId     1329131 non-null  int64
 20  bcx               1329131 non-null  float64
 21  bcy               1329131 non-null  float64
 22  bc_s              1329131 non-null  float64
 23  bc_a              1329131 non-null  float64
 24  bc_dis            1329131 non-null  float64
 25  bc_o              1329131 non-null  float64
 26  bc_dir            1329131 non-null  float64
 27  distance_from_bc  1329131 non-null  float64
 28  tackler_one       976963 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564973 non-null   float64
 31  assister_two      323448 non-null   float64
 32  missed_tackler_1  339270 non-null   float64
 33  missed_tackler_2  76926 non-null    float64
 34  missed_tackler_3  14781 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1990 non-null     object
 39  cosine            1250757 non-null  float64
 40  do_align          1329131 non-null  float64
 41  bc_do_align       1329131 non-null  float64
 42  weight            1329131 non-null  int64
 43  bc_weight         1329131 non-null  int64
 44  force             1329131 non-null  float64
 45  bc_force          1329131 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 476.6+ MB

In [182]:
tracking_clean_07.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_07.csv', index=False)

**Generating tracking_clean for observations that have at least 10 frames of data available before them**

In [189]:
# Convert the lists to sets
set_1 = set(missing_indices_1)
set_mt_1 = set(missing_indices_mt_1)

# Find the common elements
common_indices = set_1.intersection(set_mt_1)

# Convert the set back to a list, if needed
common_indices_list = list(common_indices)

print(common_indices_list)

[]

In [205]:
###Applying for Tackle Indices
tracking_clean_1 = drop_dataless_rows(tracking_clean, missing_indices_1)

Total matching rows: 8768

In [206]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1325270 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1325270 non-null  int64
 1   playId            1325270 non-null  int64
 2   nflId             1325270 non-null  float64
 3   displayName       1325270 non-null  object
 4   frameId           1325270 non-null  int64
 5   time              1325270 non-null  object
 6   jerseyNumber      1325270 non-null  float64
 7   club              1325270 non-null  object
 8   playDirection     1325270 non-null  object
 9   x                 1325270 non-null  float64
 10  y                 1325270 non-null  float64
 11  s                 1325270 non-null  float64
 12  a                 1325270 non-null  float64
 13  dis               1325270 non-null  float64
 14  o                 1325270 non-null  float64
 15  dir               1325270 non-null  float64
 16  event             113796 non-null   object
 17  game_play_Id      1325270 non-null  object
 18  defensiveTeam     1325270 non-null  object
 19  ballCarrierId     1325270 non-null  int64
 20  bcx               1325270 non-null  float64
 21  bcy               1325270 non-null  float64
 22  bc_s              1325270 non-null  float64
 23  bc_a              1325270 non-null  float64
 24  bc_dis            1325270 non-null  float64
 25  bc_o              1325270 non-null  float64
 26  bc_dir            1325270 non-null  float64
 27  distance_from_bc  1325270 non-null  float64
 28  tackler_one       972908 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565212 non-null   float64
 31  assister_two      323551 non-null   float64
 32  missed_tackler_1  342726 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2086 non-null     object
 39  cosine            1246894 non-null  float64
 40  do_align          1325270 non-null  float64
 41  bc_do_align       1325270 non-null  float64
 42  weight            1325270 non-null  int64
 43  bc_weight         1325270 non-null  int64
 44  force             1325270 non-null  float64
 45  bc_force          1325270 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 475.2+ MB

In [202]:
index_to_check = 311916
if index_to_check in missing_indices_1:
    print(f"Index {index_to_check} is in 'missing_indices_1'")
else:
    print(f"Index {index_to_check} is not in 'missing_indices_1'")

Index 311916 is in 'missing_indices_1'

In [207]:
###Applying for Missed Tackle Indices
tracking_clean_1 = drop_dataless_rows(tracking_clean_1, missing_indices_mt_1)

Index 311921 not in DataFrame
Total matching rows: 7394

In [208]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1317876 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317876 non-null  int64
 1   playId            1317876 non-null  int64
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object
 4   frameId           1317876 non-null  int64
 5   time              1317876 non-null  object
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object
 8   playDirection     1317876 non-null  object
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  event             113127 non-null   object
 17  game_play_Id      1317876 non-null  object
 18  defensiveTeam     1317876 non-null  object
 19  ballCarrierId     1317876 non-null  int64
 20  bcx               1317876 non-null  float64
 21  bcy               1317876 non-null  float64
 22  bc_s              1317876 non-null  float64
 23  bc_a              1317876 non-null  float64
 24  bc_dis            1317876 non-null  float64
 25  bc_o              1317876 non-null  float64
 26  bc_dir            1317876 non-null  float64
 27  distance_from_bc  1317876 non-null  float64
 28  tackler_one       966361 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239506 non-null  float64
 40  do_align          1317876 non-null  float64
 41  bc_do_align       1317876 non-null  float64
 42  weight            1317876 non-null  int64
 43  bc_weight         1317876 non-null  int64
 44  force             1317876 non-null  float64
 45  bc_force          1317876 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 472.6+ MB

In [209]:
tracking_clean_1.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv', index=False)

In [215]:
tracking_clean_1 = tracking_clean_1.reset_index(drop=True)

### **2.5: Deleting Observations from Tackles_1v1 which did not have a full second of data before hand**

In [232]:
def drop_matching_rows(df1, df2, indices):
    for i in indices:
        if i in df2.index:
            game_play_Id = df2.loc[i, 'game_play_Id']
            nflId = df2.loc[i, 'nflId']
            df1 = df1.drop(df1[(df1['game_play_Id'] == game_play_Id) & (df1['nflId'] == nflId)].index)
    return df1

In [246]:
tackles_1v1_1 = drop_matching_rows(tackles_1v1, tracking_clean, missing_indices_1)

In [247]:
tackles_1v1_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11667 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11667 non-null  int64
 1   playId            11667 non-null  int64
 2   nflId             11667 non-null  int64
 3   tackle            11667 non-null  int64
 4   assist            11667 non-null  int64
 5   forcedFumble      11667 non-null  int64
 6   pff_missedTackle  11667 non-null  int64
 7   game_play_Id      11667 non-null  object
 8   event_type        11667 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 911.5+ KB

In [248]:
tackles_1v1_1 = drop_matching_rows(tackles_1v1_1, tracking_clean, missing_indices_mt_1)

In [249]:
tackles_1v1_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11472 non-null  int64
 1   playId            11472 non-null  int64
 2   nflId             11472 non-null  int64
 3   tackle            11472 non-null  int64
 4   assist            11472 non-null  int64
 5   forcedFumble      11472 non-null  int64
 6   pff_missedTackle  11472 non-null  int64
 7   game_play_Id      11472 non-null  object
 8   event_type        11472 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 896.2+ KB

In [250]:
tackles_1v1_1.head(10)

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0
5,2022090800,1286,44976,1,0,0,0,2022090800_1286,1.0
6,2022090800,1736,44976,1,0,0,0,2022090800_1736,1.0
7,2022090800,2860,46085,1,0,0,0,2022090800_2860,1.0
8,2022090800,3092,46190,1,0,0,0,2022090800_3092,1.0
9,2022090800,3145,52647,1,0,0,0,2022090800_3145,1.0

### **2.6: Generating Average Magnitude**

In [251]:
def compute_speed_features_original(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['s_avg_05'] = None
    df1['s_avg_1'] = None
    df1['bc_s_avg_05'] = None
    df1['bc_s_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 3:
            condition = (df2['event'] == 'fumble') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1 nor 2

        matching_indexes = df2.index[condition]

        for i in matching_indexes:
            # Ensure index range does not go below 0
            start_index_05 = max(i - 5, 0)
            start_index_1 = max(i - 10, 0)

            # Calculate averages and assign to df1
            df1.at[index, 's_avg_05'] = df2.loc[start_index_05:i, 's'].mean()
            df1.at[index, 's_avg_1'] = df2.loc[start_index_1:start_index_05, 's'].mean()
            df1.at[index, 'bc_s_avg_05'] = df2.loc[start_index_05:i, 'bc_s'].mean()
            df1.at[index, 'bc_s_avg_1'] = df2.loc[start_index_1:start_index_05, 'bc_s'].mean()

    return df1

# Example usage:
# updated_df1 = compute_averages_modified(df1, df2)

In [252]:
tackles_1v1_1_test = compute_speed_features(tackles_1v1_1, tracking_clean_1)

In [261]:
tackles_1v1_1_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11472 non-null  int64
 1   playId            11472 non-null  int64
 2   nflId             11472 non-null  int64
 3   tackle            11472 non-null  int64
 4   assist            11472 non-null  int64
 5   forcedFumble      11472 non-null  int64
 6   pff_missedTackle  11472 non-null  int64
 7   game_play_Id      11472 non-null  object
 8   event_type        11472 non-null  float64
 9   s_avg_05          9678 non-null   object
 10  s_avg_1           9678 non-null   object
 11  bc_s_avg_05       9678 non-null   object
 12  bc_s_avg_1        9678 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.5+ MB

In [262]:
tracking_clean.event.value_counts()

event
first_contact                26142
tackle                       24948
ball_snap                    16053
handoff                      15071
pass_outcome_caught          12708
pass_arrived                 11123
out_of_bounds                 3924
run                           2140
man_in_motion                 1054
play_action                    652
touchdown                      545
shift                          359
qb_slide                       291
fumble                         244
pass_forward                   206
snap_direct                    127
lateral                         63
line_set                        56
pass_shovel                     38
autoevent_passforward           36
autoevent_passinterrupted       29
qb_sack                         21
autoevent_ballsnap              15
fumble_defense_recovered        14
penalty_flag                    12
fumble_offense_recovered         8
safety                           7
run_pass_option                  2
penalty_accepted                 2
pass_outcome_touchdown           1
Name: count, dtype: int64

**Exploration to find out why averages are not identified for all observations**

In [268]:
play_1 = tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022090800_101') & (tracking_clean_1['nflId'] == 42816)]

In [275]:
play_1[39:44]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
143,2022090800,101,42816.0,Troy Hill,40,2022-09-08 20:25:12.099999,2.0,LA,left,69.51,40.99,4.43,3.74,0.44,165.31,190.65,NaN,2022090800_101,LA,47857,69.36,40.67,6.17,4.90,0.62,292.32,270.68,0.353412,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.173133,0.718444,0.759556,184,203,688.16,994.70
144,2022090800,101,42816.0,Troy Hill,41,2022-09-08 20:25:12.200000,2.0,LA,left,69.41,40.58,4.20,3.50,0.42,160.90,195.40,NaN,2022090800_101,LA,47857,68.76,40.63,5.97,4.68,0.60,293.95,265.31,0.651920,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.343496,0.616667,0.681778,184,203,644.00,950.04
145,2022090800,101,42816.0,Troy Hill,42,2022-09-08 20:25:12.299999,2.0,LA,left,69.31,40.24,3.55,4.01,0.36,189.49,198.63,NaN,2022090800_101,LA,47857,68.18,40.54,5.75,4.38,0.58,294.97,260.48,1.169145,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.471782,0.898444,0.616778,184,203,737.84,889.14
146,2022090800,101,42816.0,Troy Hill,43,2022-09-08 20:25:12.400000,2.0,LA,left,69.22,39.94,3.00,4.41,0.31,196.68,199.90,NaN,2022090800_101,LA,47857,67.65,40.43,5.47,4.04,0.54,296.60,256.58,1.644688,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.549315,0.964222,0.555333,184,203,811.44,820.12
147,2022090800,101,42816.0,Troy Hill,44,2022-09-08 20:25:12.500000,2.0,LA,left,69.14,39.69,2.42,4.77,0.26,203.84,200.76,NaN,2022090800_101,LA,47857,67.16,40.30,5.11,4.12,0.51,239.44,253.43,2.071835,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.606405,0.965778,0.844556,184,203,877.68,836.36

In [276]:
play_1['s'][39:44].mean()

3.5200000000000005

In [254]:
tackles_1v1_1_test.head(50)

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0,3.233333,4.348333,5.535,6.72
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0,2.083333,1.8,0.276667,0.341667
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0,2.328333,2.258333,3.06,2.4
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0,4.12,5.241667,4.271667,5.561667
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0,0.745,1.78,1.446667,2.041667
5,2022090800,1286,44976,1,0,0,0,2022090800_1286,1.0,None,None,None,None
6,2022090800,1736,44976,1,0,0,0,2022090800_1736,1.0,4.665,4.676667,4.283333,4.656667
7,2022090800,2860,46085,1,0,0,0,2022090800_2860,1.0,2.381667,3.155,3.231667,2.735
8,2022090800,3092,46190,1,0,0,0,2022090800_3092,1.0,None,None,None,None
9,2022090800,3145,52647,1,0,0,0,2022090800_3145,1.0,2.445,1.703333,2.546667,1.438333
10,2022090800,3362,46190,1,0,0,0,2022090800_3362,1.0,4.471667,4.191667,2.981667,4.37
11,2022090800,3383,54488,1,0,0,0,2022090800_3383,1.0,2.126667,1.716667,2.195,1.501667
12,2022091100,1260,44851,1,0,0,0,2022091100_1260,1.0,2.95,1.766667,2.278333,2.855
13,2022091100,1672,40017,1,0,0,0,2022091100_1672,1.0,0.971667,0.991667,2.82,3.028333
14,2022091100,2114,53469,1,0,0,0,2022091100_2114,1.0,1.198333,2.685,5.098333,5.17
15,2022091100,2353,38607,1,0,0,0,2022091100_2353,1.0,2.716667,4.586667,3.188333,5.398333
16,2022091100,2512,53611,1,0,0,0,2022091100_2512,1.0,3.436667,5.131667,4.616667,5.678333
17,2022091100,2640,44862,1,0,0,0,2022091100_2640,1.0,5.78,6.151667,5.931667,6.325
18,2022091100,2878,53489,1,0,0,0,2022091100_2878,1.0,0.503333,0.998333,2.945,3.931667
19,2022091100,2899,37097,1,0,0,0,2022091100_2899,1.0,1.425,2.205,0.813333,1.881667
20,2022091100,3578,52542,1,0,0,0,2022091100_3578,1.0,2.39,4.555,3.393333,4.656667
21,2022091100,3647,53469,1,0,0,0,2022091100_3647,1.0,3.873333,6.043333,4.896667,5.036667
22,2022091100,3778,53489,1,0,0,0,2022091100_3778,1.0,3.341667,2.915,5.008333,6.561667
23,2022091101,1691,53481,1,0,0,0,2022091101_1691,1.0,None,None,None,None
24,2022091101,1744,44903,1,0,0,0,2022091101_1744,1.0,7.116667,8.798333,7.426667,8.34
25,2022091101,1785,52452,1,0,0,0,2022091101_1785,1.0,2.965,5.166667,3.836667,4.57
26,2022091101,2051,46527,1,0,0,0,2022091101_2051,1.0,0.276667,0.616667,0.028333,0.098333
27,2022091101,3221,47799,1,0,0,0,2022091101_3221,1.0,4.305,5.533333,3.486667,4.776667
28,2022091102,86,44938,1,0,0,0,2022091102_86,1.0,1.888333,3.456667,1.406667,2.903333
29,2022091102,531,52571,1,0,0,0,2022091102_531,1.0,2.951667,3.93,3.596667,3.798333
30,2022091102,756,53609,1,0,0,0,2022091102_756,1.0,4.213333,6.506667,4.518333,5.47
31,2022091102,1493,54504,1,0,0,0,2022091102_1493,1.0,2.043333,1.76,0.991667,3.22
32,2022091102,2065,54504,1,0,0,0,2022091102_2065,1.0,1.92,4.413333,1.988333,4.521667
33,2022091102,2352,46290,1,0,0,0,2022091102_2352,1.0,0.12,0.748333,0.323333,0.406667
34,2022091102,2759,54504,1,0,0,0,2022091102_2759,1.0,3.711667,5.151667,3.516667,4.25
35,2022091102,3783,52571,1,0,0,0,2022091102_3783,1.0,0.226667,0.708333,1.355,2.585
36,2022091102,4102,54639,1,0,0,0,2022091102_4102,1.0,None,None,None,None
37,2022091103,520,46146,1,0,0,0,2022091103_520,1.0,1.515,1.053333,1.703333,1.118333
38,2022091103,1037,44842,1,0,0,0,2022091103_1037,1.0,2.888333,4.241667,1.036667,2.526667
39,2022091103,1315,46080,1,0,0,0,2022091103_1315,1.0,2.01,1.515,1.975,3.288333
40,2022091103,1405,46080,1,0,0,0,2022091103_1405,1.0,None,None,None,None
41,2022091103,1672,46080,1,0,0,0,2022091103_1672,1.0,None,None,None,None
42,2022091103,2058,43641,1,0,0,0,2022091103_2058,1.0,1.033333,2.64,1.215,0.985
43,2022091103,2172,46097,1,0,0,0,2022091103_2172,1.0,None,None,None,None
44,2022091103,2222,44842,1,0,0,0,2022091103_2222,1.0,2.876667,4.256667,3.306667,5.405
45,2022091103,2291,46698,1,0,0,0,2022091103_2291,1.0,1.42,1.351667,2.566667,2.785
47,2022091103,3147,44872,1,0,0,0,2022091103_3147,1.0,4.353333,4.203333,2.95,3.05
48,2022091103,3251,43325,1,0,0,0,2022091103_3251,1.0,6.666667,7.965,5.623333,7.798333
49,2022091103,4175,43641,1,0,0,0,2022091103_4175,1.0,3.42,5.445,2.835,3.85
50,2022091103,4686,43641,1,0,0,0,2022091103_4686,1.0,2.055,2.986667,2.67,2.068333

In [286]:
def count_and_delete_out_of_bounds(tackles_1v1_1_test, tracking_clean_1):
    # Filter rows where 's_avg_05', 's_avg_1', 'bc_s_avg_05', and 'bc_s_avg_1' are None
    filtered_tackles = tackles_1v1_1_test[tackles_1v1_1_test[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

    count = 0
    # Iterate over the filtered rows
    for index, row in filtered_tackles.iterrows():
        # Find matching rows in tracking_clean_1
        matching_rows = tracking_clean_1[(tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                                         (tracking_clean_1['nflId'] == row['nflId'])]
        # Count how many times 'event' is 'out_of_bounds'
        count += (matching_rows['event'] == 'out_of_bounds').sum()
        
        # Drop the row from tackles_1v1_1_test if it contributes to the count
        if (matching_rows['event'] == 'out_of_bounds').sum() > 0:
            tackles_1v1_1_test = tackles_1v1_1_test.drop(index)
    
    return tackles_1v1_1_test

In [287]:
tackles_1v1_1_test_drop = count_and_delete_out_of_bounds(tackles_1v1_1_test, tracking_clean_1)

In [285]:
tackles_1v1_1_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11472 non-null  int64
 1   playId            11472 non-null  int64
 2   nflId             11472 non-null  int64
 3   tackle            11472 non-null  int64
 4   assist            11472 non-null  int64
 5   forcedFumble      11472 non-null  int64
 6   pff_missedTackle  11472 non-null  int64
 7   game_play_Id      11472 non-null  object
 8   event_type        11472 non-null  float64
 9   s_avg_05          9678 non-null   object
 10  s_avg_1           9678 non-null   object
 11  bc_s_avg_05       9678 non-null   object
 12  bc_s_avg_1        9678 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.5+ MB

In [288]:
tackles_1v1_1_test_drop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9875 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9875 non-null   int64
 1   playId            9875 non-null   int64
 2   nflId             9875 non-null   int64
 3   tackle            9875 non-null   int64
 4   assist            9875 non-null   int64
 5   forcedFumble      9875 non-null   int64
 6   pff_missedTackle  9875 non-null   int64
 7   game_play_Id      9875 non-null   object
 8   event_type        9875 non-null   float64
 9   s_avg_05          9678 non-null   object
 10  s_avg_1           9678 non-null   object
 11  bc_s_avg_05       9678 non-null   object
 12  bc_s_avg_1        9678 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.1+ MB

**Seeing why remaining 197 are missing**

In [316]:
tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022092513_2900') & (tracking_clean_1['nflId'] == 46757)]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
443112,2022092513,2900,46757.0,Charvarius Ward,1,2022-09-25 22:41:58.400000,7.0,SF,right,17.73,16.53,0.18,0.11,0.03,302.30,303.46,NaN,2022092513_2900,SF,42358,8.52,24.00,0.00,0.00,0.00,87.58,69.05,11.858541,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.987111,0.794111,195,215,21.45,0.00
443113,2022092513,2900,46757.0,Charvarius Ward,2,2022-09-25 22:41:58.500000,7.0,SF,right,17.70,16.58,0.22,0.14,0.06,303.39,311.04,NaN,2022092513_2900,SF,42358,8.52,24.00,0.00,0.00,0.00,87.58,67.69,11.803762,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915000,0.779000,195,215,27.30,0.00
443114,2022092513,2900,46757.0,Charvarius Ward,3,2022-09-25 22:41:58.599999,7.0,SF,right,17.67,16.60,0.22,0.16,0.04,303.39,312.21,NaN,2022092513_2900,SF,42358,8.52,24.00,0.00,0.00,0.00,88.28,71.30,11.767859,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.902000,0.811333,195,215,31.20,0.00
443115,2022092513,2900,46757.0,Charvarius Ward,4,2022-09-25 22:41:58.700000,7.0,SF,right,17.66,16.63,0.21,0.16,0.03,302.47,314.67,NaN,2022092513_2900,SF,42358,8.53,24.00,0.00,0.00,0.00,88.28,72.93,11.733448,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.864444,0.829444,195,215,31.20,0.00
443116,2022092513,2900,46757.0,Charvarius Ward,5,2022-09-25 22:41:58.799999,7.0,SF,right,17.65,16.64,0.19,0.15,0.01,302.47,315.51,NaN,2022092513_2900,SF,42358,8.53,24.00,0.00,0.00,0.00,87.65,74.16,11.719386,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.855111,0.850111,195,215,29.25,0.00
443117,2022092513,2900,46757.0,Charvarius Ward,6,2022-09-25 22:41:58.900000,7.0,SF,right,17.64,16.65,0.17,0.15,0.01,300.85,316.52,ball_snap,2022092513_2900,SF,42358,8.53,24.00,0.01,0.17,0.00,86.84,114.13,11.705324,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.924613,0.825889,0.696778,195,215,29.25,36.55
443118,2022092513,2900,46757.0,Charvarius Ward,7,2022-09-25 22:41:59.000000,7.0,SF,right,17.62,16.68,0.17,0.15,0.03,300.85,317.10,NaN,2022092513_2900,SF,42358,8.53,23.99,0.06,0.48,0.00,85.11,125.55,11.664656,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.979750,0.819444,0.550667,195,215,29.25,103.20
443119,2022092513,2900,46757.0,Charvarius Ward,8,2022-09-25 22:41:59.099999,7.0,SF,right,17.60,16.70,0.17,0.15,0.04,300.85,317.91,NaN,2022092513_2900,SF,42358,8.55,23.98,0.20,1.13,0.02,84.52,126.75,11.614685,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.981091,0.810444,0.530778,195,215,29.25,242.95
443120,2022092513,2900,46757.0,Charvarius Ward,9,2022-09-25 22:41:59.200000,7.0,SF,right,17.58,16.74,0.16,0.16,0.04,299.96,319.71,NaN,2022092513_2900,SF,42358,8.58,23.96,0.41,1.49,0.04,84.52,126.87,11.538128,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.974994,0.780556,0.529444,195,215,31.20,320.35
443121,2022092513,2900,46757.0,Charvarius Ward,10,2022-09-25 22:41:59.299999,7.0,SF,right,17.56,16.79,0.19,0.39,0.05,300.70,323.81,NaN,2022092513_2900,SF,42358,8.65,23.91,0.80,2.18,0.09,84.52,126.34,11.405372,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.953874,0.743222,0.535333,195,215,76.05,468.70
443122,2022092513,2900,46757.0,Charvarius Ward,11,2022-09-25 22:41:59.400000,7.0,SF,right,17.53,16.83,0.34,1.42,0.05,300.70,328.08,NaN,2022092513_2900,SF,42358,8.75,23.85,1.20,2.64,0.12,81.59,123.44,11.241388,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.908945,0.695778,0.535000,195,215,276.90,567.60
443123,2022092513,2900,46757.0,Charvarius Ward,12,2022-09-25 22:41:59.500000,7.0,SF,right,17.50,16.87,0.58,2.19,0.05,301.37,328.43,NaN,2022092513_2900,SF,42358,8.89,23.77,1.62,2.98,0.16,78.89,121.47,11.033680,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.891323,0.699333,0.526889,195,215,427.05,640.70
443124,2022092513,2900,46757.0,Charvarius Ward,13,2022-09-25 22:41:59.599999,7.0,SF,right,17.46,16.94,0.90,2.62,0.08,302.68,329.47,NaN,2022092513_2900,SF,42358,9.09,23.68,2.12,3.37,0.22,79.88,116.44,10.746371,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.838385,0.702333,0.593778,195,215,510.90,724.55
443125,2022092513,2900,46757.0,Charvarius Ward,14,2022-09-25 22:41:59.700000,7.0,SF,right,17.40,17.05,1.31,2.98,0.12,302.68,329.97,NaN,2022092513_2900,SF,42358,9.31,23.58,2.55,3.36,0.25,79.88,113.92,10.396586,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.808504,0.696778,0.621778,195,215,581.10,722.40
443126,2022092513,2900,46757.0,Charvarius Ward,15,2022-09-25 22:41:59.799999,7.0,SF,right,17.32,17.19,1.74,3.25,0.17,302.68,331.57,NaN,2022092513_2900,SF,42358,9.59,23.49,3.00,3.51,0.29,77.43,110.21,9.972106,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.750573,0.679000,0.635778,195,215,633.75,754.65
443127,2022092513,2900,46757.0,Charvarius Ward,16,2022-09-25 22:41:59.900000,7.0,SF,right,17.24,17.37,2.09,3.09,0.19,302.68,332.77,NaN,2022092513_2900,SF,42358,9.89,23.39,3.37,3.22,0.32,77.43,107.16,9.500679,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.699539,0.665667,0.669667,195,215,602.55,692.30
443128,2022092513,2900,46757.0,Charvarius Ward,17,2022-09-25 22:42:00.000000,7.0,SF,right,17.13,17.57,2.43,2.75,0.23,304.06,333.89,NaN,2022092513_2900,SF,42358,10.24,23.30,3.67,2.89,0.36,78.93,103.32,8.961306,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.635135,0.668556,0.729000,195,215,536.25,621.35
443129,2022092513,2900,46757.0,Charvarius Ward,18,2022-09-25 22:42:00.099999,7.0,SF,right,17.02,17.81,2.76,2.55,0.27,304.06,334.76,NaN,2022092513_2900,SF,42358,10.61,23.24,3.90,2.52,0.38,79.82,99.86,8.400774,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.575005,0.658889,0.777333,195,215,497.25,541.80
443130,2022092513,2900,46757.0,Charvarius Ward,19,2022-09-25 22:42:00.200000,7.0,SF,right,16.90,18.08,3.02,2.25,0.29,303.44,336.11,handoff,2022092513_2900,SF,42358,11.01,23.18,4.07,2.15,0.40,81.08,97.00,7.791155,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.513391,0.637000,0.823111,195,215,438.75,462.25
443131,2022092513,2900,46757.0,Charvarius Ward,20,2022-09-25 22:42:00.299999,7.0,SF,right,16.77,18.36,3.20,1.71,0.31,304.55,336.51,NaN,2022092513_2900,SF,42358,11.41,23.14,4.16,1.75,0.41,83.79,94.33,7.181783,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.466695,0.644889,0.882889,195,215,333.45,376.25
443132,2022092513,2900,46757.0,Charvarius Ward,21,2022-09-25 22:42:00.400000,7.0,SF,right,16.64,18.66,3.34,1.20,0.33,307.11,336.99,NaN,2022092513_2900,SF,42358,11.82,23.13,4.14,1.60,0.41,87.81,91.30,6.573682,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.411673,0.668000,0.961222,195,215,234.00,344.00
443133,2022092513,2900,46757.0,Charvarius Ward,22,2022-09-25 22:42:00.500000,7.0,SF,right,16.51,18.98,3.47,0.97,0.34,310.00,338.41,NaN,2022092513_2900,SF,42358,12.24,23.13,4.12,1.52,0.41,90.52,88.95,5.954444,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.350861,0.684333,0.982556,195,215,189.15,326.80
443134,2022092513,2900,46757.0,Charvarius Ward,23,2022-09-25 22:42:00.599999,7.0,SF,right,16.39,19.31,3.61,0.92,0.35,311.95,339.81,NaN,2022092513_2900,SF,42358,12.64,23.15,4.08,1.73,0.41,91.54,85.57,5.367318,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.271608,0.690444,0.933667,195,215,179.40,371.95
443135,2022092513,2900,46757.0,Charvarius Ward,24,2022-09-25 22:42:00.700000,7.0,SF,right,16.27,19.65,3.70,0.94,0.37,314.76,341.79,NaN,2022092513_2900,SF,42358,13.04,23.21,3.97,2.09,0.40,89.87,81.36,4.806922,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.166252,0.699667,0.905444,195,215,183.30,449.35
443136,2022092513,2900,46757.0,Charvarius Ward,25,2022-09-25 22:42:00.799999,7.0,SF,right,16.16,20.01,3.82,1.38,0.38,319.29,345.21,NaN,2022092513_2900,SF,42358,13.43,23.28,3.89,2.15,0.39,89.87,77.84,4.259789,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.045886,0.712000,0.866333,195,215,269.10,462.25
443137,2022092513,2900,46757.0,Charvarius Ward,26,2022-09-25 22:42:00.900000,7.0,SF,right,16.07,20.39,3.89,1.44,0.39,322.13,347.88,NaN,2022092513_2900,SF,42358,13.80,23.38,3.82,2.20,0.39,88.66,74.19,3.754064,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.064358,0.713889,0.839222,195,215,280.80,473.00
443138,2022092513,2900,46757.0,Charvarius Ward,27,2022-09-25 22:42:01.000000,7.0,SF,right,16.00,20.78,4.08,1.71,0.40,326.14,350.95,NaN,2022092513_2900,SF,42358,14.16,23.49,3.68,2.19,0.37,86.99,70.84,3.275622,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.175539,0.724333,0.820556,195,215,333.45,470.85
443139,2022092513,2900,46757.0,Charvarius Ward,28,2022-09-25 22:42:01.099999,7.0,SF,right,15.95,21.20,4.26,1.86,0.42,330.40,354.38,NaN,2022092513_2900,SF,42358,14.48,23.62,3.40,2.64,0.34,85.86,66.79,2.831484,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.302204,0.733556,0.788111,195,215,362.70,567.60
443140,2022092513,2900,46757.0,Charvarius Ward,29,2022-09-25 22:42:01.200000,7.0,SF,right,15.92,21.64,4.39,1.68,0.44,333.80,356.78,NaN,2022092513_2900,SF,42358,14.76,23.77,3.13,3.11,0.32,89.08,60.69,2.425387,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.439782,0.744667,0.684556,195,215,327.60,668.65
443141,2022092513,2900,46757.0,Charvarius Ward,30,2022-09-25 22:42:01.299999,7.0,SF,right,15.91,22.09,4.49,1.65,0.45,335.36,359.78,NaN,2022092513_2900,SF,42358,15.02,23.93,2.91,3.14,0.30,86.91,55.25,2.043942,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.566838,0.728667,0.648222,195,215,321.75,675.10
443142,2022092513,2900,46757.0,Charvarius Ward,31,2022-09-25 22:42:01.400000,7.0,SF,right,15.93,22.55,4.61,1.64,0.46,336.09,2.79,NaN,2022092513_2900,SF,42358,15.24,24.11,2.74,3.24,0.28,90.05,47.70,1.705784,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.708217,0.703333,0.529444,195,215,319.80,696.60
443143,2022092513,2900,46757.0,Charvarius Ward,32,2022-09-25 22:42:01.500000,7.0,SF,right,15.97,23.01,4.63,1.64,0.46,336.09,5.53,NaN,2022092513_2900,SF,42358,15.42,24.32,2.67,3.31,0.27,90.05,38.24,1.420774,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.841416,0.672889,0.424333,195,215,319.80,711.65
443144,2022092513,2900,46757.0,Charvarius Ward,33,2022-09-25 22:42:01.599999,7.0,SF,right,16.02,23.45,4.48,1.63,0.44,334.12,7.39,NaN,2022092513_2900,SF,42358,15.55,24.54,2.59,3.36,0.26,85.30,28.65,1.187013,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.931945,0.630333,0.370556,195,215,317.85,722.40
443145,2022092513,2900,46757.0,Charvarius Ward,34,2022-09-25 22:42:01.700000,7.0,SF,right,16.09,23.89,4.41,1.59,0.44,338.68,9.21,NaN,2022092513_2900,SF,42358,15.66,24.77,2.58,2.96,0.26,83.29,21.78,0.979439,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.976031,0.660778,0.316556,195,215,310.05,636.40
443146,2022092513,2900,46757.0,Charvarius Ward,35,2022-09-25 22:42:01.799999,7.0,SF,right,16.12,24.26,4.02,1.90,0.37,335.89,8.89,first_contact,2022092513_2900,SF,42358,15.73,25.01,2.50,2.89,0.25,65.33,13.00,0.845340,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997428,0.633333,0.418556,195,215,370.50,621.35
443147,2022092513,2900,46757.0,Charvarius Ward,36,2022-09-25 22:42:01.900000,7.0,SF,right,16.19,24.65,3.83,2.07,0.39,335.89,9.89,NaN,2022092513_2900,SF,42358,15.77,25.25,2.45,2.53,0.24,54.16,7.03,0.732393,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.998754,0.622222,0.476333,195,215,403.65,543.95
443148,2022092513,2900,46757.0,Charvarius Ward,37,2022-09-25 22:42:02.000000,7.0,SF,right,16.18,24.95,3.31,2.74,0.30,333.50,6.78,NaN,2022092513_2900,SF,42358,15.79,25.49,2.44,2.19,0.24,47.89,1.55,0.666108,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.995837,0.630222,0.485111,195,215,534.30,470.85
443149,2022092513,2900,46757.0,Charvarius Ward,38,2022-09-25 22:42:02.099999,7.0,SF,right,16.17,25.23,2.88,3.37,0.28,333.50,2.37,NaN,2022092513_2900,SF,42358,15.80,25.70,2.20,1.90,0.20,40.34,358.24,0.598164,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997403,0.679222,0.532222,195,215,657.15,408.50
443150,2022092513,2900,46757.0,Charvarius Ward,39,2022-09-25 22:42:02.200000,7.0,SF,right,16.15,25.45,2.29,4.23,0.22,350.11,357.72,NaN,2022092513_2900,SF,42358,15.77,25.90,2.07,1.94,0.21,31.75,351.42,0.588982,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.993961,0.915444,0.551889,195,215,824.85,417.10
443151,2022092513,2900,46757.0,Charvarius Ward,40,2022-09-25 22:42:02.299999,7.0,SF,right,16.13,25.64,1.83,3.96,0.20,350.11,351.62,NaN,2022092513_2900,SF,42358,15.73,26.09,1.89,1.98,0.19,26.83,346.35,0.602080,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.995773,0.983222,0.550222,195,215,772.20,425.70
443152,2022092513,2900,46757.0,Charvarius Ward,41,2022-09-25 22:42:02.400000,7.0,SF,right,16.10,25.80,1.44,3.84,0.16,347.77,344.97,NaN,2022092513_2900,SF,42358,15.70,26.23,1.62,2.08,0.15,26.10,342.80,0.587282,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999283,0.968889,0.518889,195,215,748.80,447.20
443153,2022092513,2900,46757.0,Charvarius Ward,42,2022-09-25 22:42:02.500000,7.0,SF,right,16.06,25.92,1.05,3.80,0.12,342.64,333.72,NaN,2022092513_2900,SF,42358,15.66,26.36,1.34,2.30,0.13,16.62,336.97,0.594643,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.998392,0.900889,0.559444,195,215,741.00,494.50
443154,2022092513,2900,46757.0,Charvarius Ward,43,2022-09-25 22:42:02.599999,7.0,SF,right,16.01,26.00,0.83,3.37,0.09,338.94,318.43,NaN,2022092513_2900,SF,42358,15.59,26.47,1.14,2.80,0.13,11.12,327.73,0.630317,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.986856,0.772111,0.517889,195,215,657.15,602.00
443155,2022092513,2900,46757.0,Charvarius Ward,44,2022-09-25 22:42:02.700000,7.0,SF,right,15.95,26.05,0.71,2.58,0.08,337.72,305.08,NaN,2022092513_2900,SF,42358,15.53,26.56,0.88,2.89,0.10,1.99,318.26,0.660681,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.973659,0.637333,0.514111,195,215,503.10,621.35
443156,2022092513,2900,46757.0,Charvarius Ward,45,2022-09-25 22:42:02.799999,7.0,SF,right,15.89,26.08,0.64,2.10,0.07,335.48,286.14,NaN,2022092513_2900,SF,42358,15.47,26.60,0.75,2.78,0.08,351.47,293.85,0.668431,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.990960,0.451778,0.359778,195,215,409.50,597.70
443157,2022092513,2900,46757.0,Charvarius Ward,46,2022-09-25 22:42:02.900000,7.0,SF,right,15.84,26.10,0.52,1.50,0.05,323.27,278.63,NaN,2022092513_2900,SF,42358,15.40,26.62,0.79,2.26,0.07,331.08,277.62,0.681175,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999845,0.504000,0.406000,195,215,292.50,485.90
443158,2022092513,2900,46757.0,Charvarius Ward,47,2022-09-25 22:42:03.000000,7.0,SF,right,15.79,26.11,0.51,1.05,0.05,314.38,271.54,NaN,2022092513_2900,SF,42358,15.32,26.62,0.76,1.48,0.08,320.23,270.79,0.693542,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999914,0.524000,0.450667,195,215,204.75,318.20
443159,2022092513,2900,46757.0,Charvarius Ward,48,2022-09-25 22:42:03.099999,7.0,SF,right,15.73,26.11,0.52,0.76,0.06,307.05,263.94,NaN,2022092513_2900,SF,42358,15.24,26.61,0.79,1.08,0.08,314.92,261.39,0.700071,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999010,0.521000,0.405222,195,215,148.20,232.20
443160,2022092513,2900,46757.0,Charvarius Ward,49,2022-09-25 22:42:03.200000,7.0,SF,right,15.71,26.11,0.33,0.85,0.03,272.65,260.76,NaN,2022092513_2900,SF,42358,15.18,26.60,0.50,0.81,0.06,307.63,266.98,0.721803,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.994113,0.867889,0.548333,195,215,165.75,174.15
443161,2022092513,2900,46757.0,Charvarius Ward,50,2022-09-25 22:42:03.299999,7.0,SF,right,15.70,26.12,0.16,0.97,0.01,191.38,270.46,fumble,2022092513_2900,SF,42358,15.13,26.60,0.38,0.95,0.04,303.17,273.55,0.745185,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.998546,0.121333,0.670889,195,215,189.15,204.25
443162,2022092513,2900,46757.0,Charvarius Ward,51,2022-09-25 22:42:03.400000,7.0,SF,right,15.67,26.12,0.21,0.58,0.03,187.08,273.43,NaN,2022092513_2900,SF,42358,15.11,26.64,0.39,1.21,0.04,292.89,320.51,0.764199,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.680977,0.040556,0.693111,195,215,113.10,260.15
443163,2022092513,2900,46757.0,Charvarius Ward,52,2022-09-25 22:42:03.500000,7.0,SF,right,15.62,26.12,0.37,0.21,0.04,185.99,271.30,NaN,2022092513_2900,SF,42358,15.07,26.66,0.44,0.84,0.05,280.54,316.28,0.770779,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.707354,0.052111,0.602889,195,215,40.95,180.60
443164,2022092513,2900,46757.0,Charvarius Ward,53,2022-09-25 22:42:03.599999,7.0,SF,right,15.58,26.13,0.56,0.81,0.05,199.96,279.14,NaN,2022092513_2900,SF,42358,15.01,26.69,0.54,0.41,0.06,280.54,304.21,0.799062,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.905791,0.120222,0.737000,195,215,157.95,88.15
443165,2022092513,2900,46757.0,Charvarius Ward,54,2022-09-25 22:42:03.700000,7.0,SF,right,15.50,26.13,0.81,1.53,0.07,269.84,273.20,NaN,2022092513_2900,SF,42358,14.96,26.72,0.57,0.47,0.05,275.59,306.89,0.799812,46757.0,NaN,48123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.832051,0.962667,0.652222,195,215,298.35,101.05

In [305]:
missing_197_events = tackles_1v1_1_test_drop[tackles_1v1_1_test_drop[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

In [321]:
missing_197_events.forcedFumble.value_counts()

forcedFumble
0    134
1     63
Name: count, dtype: int64

**Dropping observations with missing generated speed features where tackler did not force fumble**

In [322]:
# Create a mask for rows where all specified columns are null
null_mask = tackles_1v1_1_test_drop[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)

# Create a mask for rows where 'tackle' is 1 and 'forcedFumble' is not 1
tackle_mask = (tackles_1v1_1_test_drop['tackle'] == 1) & (tackles_1v1_1_test_drop['forcedFumble'] != 1)

# Combine the masks and drop the rows
tackles_1v1_1_fumbles = tackles_1v1_1_test_drop.drop(tackles_1v1_1_test_drop[null_mask & tackle_mask].index)

In [330]:
tackles_1v1_1_fumbles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9741 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9741 non-null   int64
 1   playId            9741 non-null   int64
 2   nflId             9741 non-null   int64
 3   tackle            9741 non-null   int64
 4   assist            9741 non-null   int64
 5   forcedFumble      9741 non-null   int64
 6   pff_missedTackle  9741 non-null   int64
 7   game_play_Id      9741 non-null   object
 8   event_type        9741 non-null   float64
 9   s_avg_05          9678 non-null   object
 10  s_avg_1           9678 non-null   object
 11  bc_s_avg_05       9678 non-null   object
 12  bc_s_avg_1        9678 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB

In [333]:
all_71_fumbles = tackles_1v1_1_fumbles[tackles_1v1_1_fumbles.forcedFumble == 1]

In [360]:
long_play = tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022100904_3777') & (tracking_clean_1['nflId'] == 52497)]

In [361]:
long_play[:60]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
667593,2022100904,3777,52497.0,Cameron Dantzler,1,2022-10-09 15:50:01.400000,3.0,MIN,left,51.24,8.93,2.58,4.20,0.23,87.59,115.74,NaN,2022100904_3777,MIN,53586,54.10,9.42,2.20,3.31,0.21,55.27,169.95,2.901672,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.584816,0.687222,-0.274222,185,179,777.00,592.49
667594,2022100904,3777,52497.0,Cameron Dantzler,2,2022-10-09 15:50:01.500000,3.0,MIN,left,51.49,8.80,3.00,3.76,0.28,92.18,119.39,pass_arrived,2022100904_3777,MIN,53586,54.15,9.18,2.59,3.12,0.25,66.81,165.62,2.687006,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.691765,0.697667,-0.097889,185,179,695.60,558.48
667595,2022100904,3777,52497.0,Cameron Dantzler,3,2022-10-09 15:50:01.599999,3.0,MIN,left,51.77,8.62,3.42,3.42,0.33,95.45,123.96,NaN,2022100904_3777,MIN,53586,54.22,8.91,2.94,2.77,0.28,75.92,163.88,2.467104,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.766941,0.683222,0.022667,185,179,632.70,495.83
667596,2022100904,3777,52497.0,Cameron Dantzler,4,2022-10-09 15:50:01.700000,3.0,MIN,left,52.06,8.41,3.78,3.06,0.36,101.28,127.66,NaN,2022100904_3777,MIN,53586,54.31,8.59,3.33,2.55,0.32,88.22,163.99,2.257189,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.805618,0.706889,0.158111,185,179,566.10,456.45
667597,2022100904,3777,52497.0,Cameron Dantzler,5,2022-10-09 15:50:01.799999,3.0,MIN,left,52.36,8.15,4.07,2.75,0.39,105.70,130.77,NaN,2022100904_3777,MIN,53586,54.40,8.25,3.62,2.20,0.35,104.39,164.74,2.042450,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.829330,0.721444,0.329444,185,179,508.75,393.80
667598,2022100904,3777,52497.0,Cameron Dantzler,6,2022-10-09 15:50:01.900000,3.0,MIN,left,52.68,7.87,4.32,2.33,0.42,108.56,133.09,pass_outcome_caught,2022100904_3777,MIN,53586,54.49,7.89,3.82,1.66,0.37,119.45,165.07,1.810110,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.848233,0.727444,0.493111,185,179,431.05,297.14
667599,2022100904,3777,52497.0,Cameron Dantzler,7,2022-10-09 15:50:02.000000,3.0,MIN,left,52.98,7.53,4.60,2.60,0.46,113.13,138.87,NaN,2022100904_3777,MIN,53586,54.59,7.51,3.98,1.25,0.39,128.26,165.98,1.610124,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.890133,0.714000,0.580889,185,179,481.00,223.75
667600,2022100904,3777,52497.0,Cameron Dantzler,8,2022-10-09 15:50:02.099999,3.0,MIN,left,53.25,7.14,4.80,2.97,0.47,116.06,144.62,NaN,2022100904_3777,MIN,53586,54.68,7.14,3.91,0.51,0.38,140.40,166.86,1.430000,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.925607,0.682667,0.706000,185,179,549.45,91.29
667601,2022100904,3777,52497.0,Cameron Dantzler,9,2022-10-09 15:50:02.200000,3.0,MIN,left,53.51,6.72,4.99,3.16,0.49,118.82,149.51,NaN,2022100904_3777,MIN,53586,54.74,6.78,3.78,0.93,0.37,151.68,169.32,1.231463,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.940822,0.659000,0.804000,185,179,584.60,166.47
667602,2022100904,3777,52497.0,Cameron Dantzler,10,2022-10-09 15:50:02.299999,3.0,MIN,left,53.74,6.27,5.11,3.20,0.51,125.21,154.26,NaN,2022100904_3777,MIN,53586,54.80,6.42,3.65,1.35,0.36,154.01,171.12,1.070561,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.957016,0.677222,0.809889,185,179,592.00,241.65
667603,2022100904,3777,52497.0,Cameron Dantzler,11,2022-10-09 15:50:02.400000,3.0,MIN,left,53.93,5.79,5.17,3.34,0.52,136.16,159.50,first_contact,2022100904_3777,MIN,53586,54.82,6.09,3.28,2.42,0.32,164.65,175.94,0.939202,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.959117,0.740667,0.874556,185,179,617.90,433.18
667604,2022100904,3777,52497.0,Cameron Dantzler,12,2022-10-09 15:50:02.500000,3.0,MIN,left,54.10,5.31,5.09,3.26,0.51,148.06,163.10,NaN,2022100904_3777,MIN,53586,54.82,5.79,2.98,3.22,0.31,181.58,181.53,0.865332,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.948711,0.832889,0.999444,185,179,603.10,576.38
667605,2022100904,3777,52497.0,Cameron Dantzler,13,2022-10-09 15:50:02.599999,3.0,MIN,left,54.23,4.83,4.94,3.09,0.50,157.46,166.54,NaN,2022100904_3777,MIN,53586,54.78,5.51,2.68,4.14,0.28,197.65,190.72,0.874586,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.912263,0.899111,0.923000,185,179,571.65,741.06
667606,2022100904,3777,52497.0,Cameron Dantzler,14,2022-10-09 15:50:02.700000,3.0,MIN,left,54.33,4.36,4.65,3.21,0.48,153.24,169.75,NaN,2022100904_3777,MIN,53586,54.70,5.26,2.51,4.15,0.26,202.93,201.01,0.973088,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.854821,0.816556,0.978667,185,179,593.85,742.85
667607,2022100904,3777,52497.0,Cameron Dantzler,15,2022-10-09 15:50:02.799999,3.0,MIN,left,54.40,3.92,4.35,3.51,0.45,152.58,173.03,NaN,2022100904_3777,MIN,53586,54.58,5.03,2.54,3.96,0.26,217.39,211.74,1.124500,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.780321,0.772778,0.937222,185,179,649.35,708.84
667608,2022100904,3777,52497.0,Cameron Dantzler,16,2022-10-09 15:50:02.900000,3.0,MIN,left,54.43,3.52,3.82,4.41,0.40,158.14,177.35,NaN,2022100904_3777,MIN,53586,54.43,4.82,2.68,3.91,0.26,229.12,221.10,1.300000,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.722364,0.786556,0.910889,185,179,815.85,699.89
667609,2022100904,3777,52497.0,Cameron Dantzler,17,2022-10-09 15:50:03.000000,3.0,MIN,left,54.43,3.18,3.26,4.95,0.34,187.58,182.05,NaN,2022100904_3777,MIN,53586,54.23,4.62,2.89,3.49,0.28,236.48,228.05,1.453823,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.694658,0.938556,0.906333,185,179,915.75,624.71
667610,2022100904,3777,52497.0,Cameron Dantzler,18,2022-10-09 15:50:03.099999,3.0,MIN,left,54.38,2.91,2.59,5.81,0.27,198.04,192.46,NaN,2022100904_3777,MIN,53586,54.00,4.43,3.07,2.79,0.30,240.51,232.63,1.566780,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.764134,0.938000,0.912444,185,179,1074.85,499.41
667611,2022100904,3777,52497.0,Cameron Dantzler,19,2022-10-09 15:50:03.200000,3.0,MIN,left,54.30,2.69,2.20,5.63,0.24,205.74,203.58,NaN,2022100904_3777,MIN,53586,53.75,4.25,3.20,2.09,0.31,242.16,235.72,1.654116,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.846751,0.976000,0.928444,185,179,1041.55,374.11
667612,2022100904,3777,52497.0,Cameron Dantzler,20,2022-10-09 15:50:03.299999,3.0,MIN,left,54.18,2.51,1.98,5.52,0.21,222.31,220.99,NaN,2022100904_3777,MIN,53586,53.48,4.08,3.28,1.62,0.32,245.50,239.06,1.718982,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.950678,0.985333,0.928444,185,179,1021.20,289.98
667613,2022100904,3777,52497.0,Cameron Dantzler,21,2022-10-09 15:50:03.400000,3.0,MIN,left,54.02,2.40,1.94,5.23,0.19,237.14,239.91,NaN,2022100904_3777,MIN,53586,53.19,3.93,3.24,1.44,0.32,255.27,243.41,1.740632,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.998135,0.969222,0.868222,185,179,967.55,257.76
667614,2022100904,3777,52497.0,Cameron Dantzler,22,2022-10-09 15:50:03.500000,3.0,MIN,left,53.83,2.32,2.20,4.99,0.21,246.20,256.09,NaN,2022100904_3777,MIN,53586,52.90,3.80,3.17,1.55,0.32,262.02,247.60,1.747942,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.989042,0.890111,0.839778,185,179,923.15,277.45
667615,2022100904,3777,52497.0,Cameron Dantzler,23,2022-10-09 15:50:03.599999,3.0,MIN,left,53.60,2.29,2.47,4.59,0.23,261.01,267.48,NaN,2022100904_3777,MIN,53586,52.61,3.69,3.10,1.54,0.31,264.53,250.20,1.714672,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.954865,0.928111,0.840778,185,179,849.15,275.66
667616,2022100904,3777,52497.0,Cameron Dantzler,24,2022-10-09 15:50:03.700000,3.0,MIN,left,53.33,2.30,2.84,4.30,0.26,274.36,276.17,NaN,2022100904_3777,MIN,53586,52.33,3.60,2.98,1.63,0.30,267.90,252.93,1.640122,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.918860,0.979889,0.833667,185,179,795.50,291.77
667617,2022100904,3777,52497.0,Cameron Dantzler,25,2022-10-09 15:50:03.799999,3.0,MIN,left,53.03,2.35,3.17,3.64,0.30,276.70,281.00,NaN,2022100904_3777,MIN,53586,52.05,3.52,2.85,1.67,0.29,271.82,255.62,1.526204,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.903485,0.952222,0.820000,185,179,673.40,298.93
667618,2022100904,3777,52497.0,Cameron Dantzler,26,2022-10-09 15:50:03.900000,3.0,MIN,left,52.71,2.42,3.42,2.90,0.33,278.89,284.33,NaN,2022100904_3777,MIN,53586,51.78,3.44,2.78,1.33,0.29,272.99,255.38,1.380326,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.875042,0.939556,0.804333,185,179,536.50,238.07
667619,2022100904,3777,52497.0,Cameron Dantzler,27,2022-10-09 15:50:04.000000,3.0,MIN,left,52.37,2.50,3.58,1.83,0.35,284.90,283.88,NaN,2022100904_3777,MIN,53586,51.50,3.37,2.76,1.08,0.28,272.99,256.63,1.230366,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.889017,0.988667,0.818222,185,179,338.55,193.32
667620,2022100904,3777,52497.0,Cameron Dantzler,28,2022-10-09 15:50:04.099999,3.0,MIN,left,52.02,2.57,3.63,0.77,0.36,280.54,281.90,NaN,2022100904_3777,MIN,53586,51.23,3.30,2.73,0.83,0.28,270.81,256.94,1.075639,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.906603,0.984889,0.845889,185,179,142.45,148.57
667621,2022100904,3777,52497.0,Cameron Dantzler,29,2022-10-09 15:50:04.200000,3.0,MIN,left,51.68,2.63,3.54,0.28,0.35,280.54,280.51,NaN,2022100904_3777,MIN,53586,50.97,3.23,2.68,0.62,0.27,265.48,255.51,0.929570,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.906308,0.999667,0.889222,185,179,51.80,110.98
667622,2022100904,3777,52497.0,Cameron Dantzler,30,2022-10-09 15:50:04.299999,3.0,MIN,left,51.33,2.68,3.46,1.00,0.35,280.54,277.88,NaN,2022100904_3777,MIN,53586,50.70,3.16,2.72,0.49,0.28,259.98,254.22,0.792023,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.915943,0.970444,0.936000,185,179,185.00,87.71
667623,2022100904,3777,52497.0,Cameron Dantzler,31,2022-10-09 15:50:04.400000,3.0,MIN,left,51.00,2.71,3.25,1.93,0.33,273.25,274.65,NaN,2022100904_3777,MIN,53586,50.43,3.06,2.77,0.86,0.28,248.92,250.32,0.668880,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.911188,0.984444,0.984444,185,179,357.05,153.94
667624,2022100904,3777,52497.0,Cameron Dantzler,32,2022-10-09 15:50:04.500000,3.0,MIN,left,50.68,2.74,2.98,3.18,0.32,266.74,272.05,NaN,2022100904_3777,MIN,53586,50.19,2.94,2.75,1.57,0.27,238.60,243.72,0.529245,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.880229,0.941000,0.943111,185,179,588.30,281.03
667625,2022100904,3777,52497.0,Cameron Dantzler,33,2022-10-09 15:50:04.599999,3.0,MIN,left,50.40,2.74,2.52,3.70,0.28,265.35,268.55,NaN,2022100904_3777,MIN,53586,49.97,2.80,2.63,1.93,0.26,230.49,237.09,0.434166,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.853005,0.964444,0.926667,185,179,684.50,345.47
667626,2022100904,3777,52497.0,Cameron Dantzler,34,2022-10-09 15:50:04.700000,3.0,MIN,left,50.17,2.73,2.07,3.76,0.23,258.49,265.95,NaN,2022100904_3777,MIN,53586,49.76,2.65,2.55,2.02,0.25,208.38,231.75,0.417732,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,missed tackle,0.827081,0.917111,0.740333,185,179,695.60,361.58
667627,2022100904,3777,52497.0,Cameron Dantzler,35,2022-10-09 15:50:04.799999,3.0,MIN,left,49.99,2.71,1.64,3.76,0.18,252.94,260.10,NaN,2022100904_3777,MIN,53586,49.58,2.49,2.40,2.17,0.24,201.65,226.87,0.465296,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.836477,0.920444,0.719778,185,179,695.60,388.43
667628,2022100904,3777,52497.0,Cameron Dantzler,36,2022-10-09 15:50:04.900000,3.0,MIN,left,49.85,2.68,1.22,3.63,0.14,252.11,253.56,NaN,2022100904_3777,MIN,53586,49.42,2.33,2.24,2.16,0.22,170.79,222.56,0.554437,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.857167,0.983889,0.424778,185,179,671.55,386.64
667629,2022100904,3777,52497.0,Cameron Dantzler,37,2022-10-09 15:50:05.000000,3.0,MIN,left,49.77,2.63,0.85,3.53,0.10,250.65,237.37,fumble,2022100904_3777,MIN,53586,49.29,2.18,1.99,2.24,0.20,329.15,218.45,0.657951,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.945972,0.852444,-0.230000,185,179,653.05,400.96
667630,2022100904,3777,52497.0,Cameron Dantzler,38,2022-10-09 15:50:05.099999,3.0,MIN,left,49.71,2.58,0.65,3.21,0.07,242.66,212.68,NaN,2022100904_3777,MIN,53586,49.17,2.03,1.81,2.07,0.19,355.96,214.60,0.770779,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.999439,0.666889,-0.570667,185,179,593.85,370.53
667631,2022100904,3777,52497.0,Cameron Dantzler,39,2022-10-09 15:50:05.200000,3.0,MIN,left,49.70,2.52,0.61,2.96,0.06,234.07,179.11,NaN,2022100904_3777,MIN,53586,49.08,1.89,1.63,1.94,0.17,11.56,210.39,0.883912,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.854640,0.389333,-0.790778,185,179,547.60,347.26
667632,2022100904,3777,52497.0,Cameron Dantzler,40,2022-10-09 15:50:05.299999,3.0,MIN,left,49.72,2.45,0.77,2.71,0.07,226.50,153.11,NaN,2022100904_3777,MIN,53586,49.02,1.77,1.36,2.21,0.14,350.17,205.40,0.975910,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.611665,0.184556,-0.608556,185,179,501.35,395.59
667633,2022100904,3777,52497.0,Cameron Dantzler,41,2022-10-09 15:50:05.400000,3.0,MIN,left,49.78,2.38,1.06,2.67,0.10,222.08,138.25,NaN,2022100904_3777,MIN,53586,48.97,1.65,1.17,2.05,0.13,350.17,200.07,1.090413,52497.0,NaN,NaN,NaN,52497.0,NaN,NaN,NaN,NaN,NaN,NaN,0.472243,0.068556,-0.667778,185,179,493.95,366.95

In [359]:
all_71_fumbles[59:]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
7887,2022110608,1940,46711,1,0,1,0,2022110608_1940,1.0,None,None,None,None
8090,2022110300,3506,54540,1,0,1,0,2022110300_3506,1.0,5.051667,6.453333,5.248333,5.825
8123,2022110603,3713,52411,1,0,1,0,2022110603_3713,1.0,None,None,None,None
8374,2022110600,2183,41231,1,0,1,0,2022110600_2183,1.0,None,None,None,None
8689,2022103009,2259,53592,1,0,1,0,2022103009_2259,1.0,None,None,None,None
8913,2022100208,3298,54504,1,0,1,0,2022100208_3298,1.0,1.866667,1.473333,2.785,5.581667
9135,2022101600,690,54503,1,0,1,0,2022101600_690,1.0,None,None,None,None
9284,2022102303,193,47996,1,0,1,0,2022102303_193,1.0,None,None,None,None
9311,2022102305,3425,41483,1,0,1,0,2022102305_3425,1.0,None,None,None,None
9496,2022103012,762,54487,1,0,1,0,2022103012_762,1.0,None,None,None,None
9557,2022110603,3689,46958,1,0,1,0,2022110603_3689,1.0,None,None,None,None
4647,2022100904,3777,52497,1,0,1,0,2022100904_3777,1.0,2.97,3.363333,2.683333,2.796667

In [373]:
fumbles_63 = tackles_1v1_1_fumbles[tackles_1v1_1_fumbles[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

In [374]:
fumbles_63.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 81 to 9557
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            63 non-null     int64
 1   playId            63 non-null     int64
 2   nflId             63 non-null     int64
 3   tackle            63 non-null     int64
 4   assist            63 non-null     int64
 5   forcedFumble      63 non-null     int64
 6   pff_missedTackle  63 non-null     int64
 7   game_play_Id      63 non-null     object
 8   event_type        63 non-null     float64
 9   s_avg_05          0 non-null      object
 10  s_avg_1           0 non-null      object
 11  bc_s_avg_05       0 non-null      object
 12  bc_s_avg_1        0 non-null      object
dtypes: float64(1), int64(7), object(5)
memory usage: 6.9+ KB

In [372]:
tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022102300_3733') & (tracking_clean_1['nflId'] == 52627)]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
921449,2022102300,3733,52627.0,Geno Stone,1,2022-10-23 15:57:22.200000,26.0,BAL,left,72.27,45.84,4.25,3.52,0.41,194.61,233.59,NaN,2022102300_3733,BAL,52595,70.63,42.47,5.02,3.82,0.51,176.92,201.87,3.747866,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.850628,0.566889,0.722778,210,208,739.2,794.56
921450,2022102300,3733,52627.0,Geno Stone,2,2022-10-23 15:57:22.299999,26.0,BAL,left,71.93,45.57,4.52,3.10,0.44,194.61,230.39,NaN,2022102300_3733,BAL,52595,70.46,42.01,4.77,3.68,0.49,181.98,198.10,3.851558,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.845355,0.602444,0.820889,210,208,651.0,765.44
921451,2022102300,3733,52627.0,Geno Stone,3,2022-10-23 15:57:22.400000,26.0,BAL,left,71.59,45.25,4.77,3.03,0.47,197.14,225.39,NaN,2022102300_3733,BAL,52595,70.36,41.59,4.35,4.07,0.44,181.98,192.62,3.861153,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.840850,0.686111,0.881778,210,208,636.3,846.56
921452,2022102300,3733,52627.0,Geno Stone,4,2022-10-23 15:57:22.500000,26.0,BAL,left,71.26,44.89,4.94,2.92,0.49,196.22,220.80,NaN,2022102300_3733,BAL,52595,70.31,41.20,3.93,4.38,0.40,177.46,186.19,3.810328,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.823037,0.726889,0.903000,210,208,613.2,911.04
921453,2022102300,3733,52627.0,Geno Stone,5,2022-10-23 15:57:22.599999,26.0,BAL,left,70.96,44.49,5.13,3.12,0.51,194.79,215.65,pass_arrived,2022102300_3733,BAL,52595,70.28,40.82,3.63,4.15,0.37,180.91,181.41,3.732466,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.826688,0.768222,0.994444,210,208,655.2,863.20
921454,2022102300,3733,52627.0,Geno Stone,6,2022-10-23 15:57:22.700000,26.0,BAL,left,70.67,44.05,5.26,2.87,0.52,198.12,212.14,pass_outcome_caught,2022102300_3733,BAL,52595,70.27,40.47,3.37,3.53,0.35,185.40,178.75,3.602277,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.834944,0.844222,0.926111,210,208,602.7,734.24
921455,2022102300,3733,52627.0,Geno Stone,7,2022-10-23 15:57:22.799999,26.0,BAL,left,70.43,43.58,5.36,3.33,0.53,200.71,205.99,NaN,2022102300_3733,BAL,52595,70.28,40.16,3.08,3.04,0.32,188.94,176.90,3.423288,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.873857,0.941333,0.866222,210,208,699.3,632.32
921456,2022102300,3733,52627.0,Geno Stone,8,2022-10-23 15:57:22.900000,26.0,BAL,left,70.22,43.06,5.57,3.74,0.56,199.23,201.07,NaN,2022102300_3733,BAL,52595,70.26,39.85,2.99,1.95,0.31,196.31,181.96,3.210249,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.944892,0.979556,0.840556,210,208,785.4,405.60
921457,2022102300,3733,52627.0,Geno Stone,9,2022-10-23 15:57:23.000000,26.0,BAL,left,70.04,42.51,5.82,3.79,0.58,191.50,196.21,NaN,2022102300_3733,BAL,52595,70.24,39.55,2.93,1.90,0.30,200.32,186.34,2.966749,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.985199,0.947667,0.844667,210,208,795.9,395.20
921458,2022102300,3733,52627.0,Geno Stone,10,2022-10-23 15:57:23.099999,26.0,BAL,left,69.90,41.93,6.06,3.43,0.60,190.61,192.66,NaN,2022102300_3733,BAL,52595,70.19,39.26,2.98,2.23,0.30,207.31,192.43,2.685703,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999992,0.977222,0.834667,210,208,720.3,463.84
921459,2022102300,3733,52627.0,Geno Stone,11,2022-10-23 15:57:23.200000,26.0,BAL,left,69.77,41.32,6.25,2.77,0.62,188.81,190.50,NaN,2022102300_3733,BAL,52595,70.09,38.96,3.08,2.68,0.31,215.61,199.82,2.381596,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.986799,0.981222,0.824556,210,208,581.7,557.44
921460,2022102300,3733,52627.0,Geno Stone,12,2022-10-23 15:57:23.299999,26.0,BAL,left,69.66,40.70,6.37,2.01,0.63,186.99,189.17,NaN,2022102300_3733,BAL,52595,69.97,38.66,3.46,2.98,0.33,228.49,204.65,2.063419,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.963724,0.975778,0.735111,210,208,422.1,619.84
921461,2022102300,3733,52627.0,Geno Stone,13,2022-10-23 15:57:23.400000,26.0,BAL,left,69.54,40.06,6.47,0.81,0.65,187.93,189.63,NaN,2022102300_3733,BAL,52595,69.80,38.34,3.80,3.31,0.36,231.46,208.25,1.739540,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.947657,0.981111,0.742111,210,208,170.1,688.48
921462,2022102300,3733,52627.0,Geno Stone,14,2022-10-23 15:57:23.500000,26.0,BAL,left,69.42,39.42,6.51,0.10,0.65,189.78,190.37,NaN,2022102300_3733,BAL,52595,69.61,37.99,4.13,2.98,0.40,232.82,210.32,1.442567,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.939991,0.993444,0.750000,210,208,21.0,619.84
921463,2022102300,3733,52627.0,Geno Stone,15,2022-10-23 15:57:23.599999,26.0,BAL,left,69.30,38.78,6.53,0.58,0.65,191.22,190.96,NaN,2022102300_3733,BAL,52595,69.39,37.63,4.42,2.60,0.43,230.65,212.12,1.153516,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.932576,0.997111,0.794111,210,208,121.8,540.80
921464,2022102300,3733,52627.0,Geno Stone,16,2022-10-23 15:57:23.700000,26.0,BAL,left,69.16,38.14,6.48,1.26,0.65,197.48,192.75,NaN,2022102300_3733,BAL,52595,69.14,37.23,4.75,2.23,0.47,233.55,211.70,0.910220,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.945802,0.947444,0.757222,210,208,264.6,463.84
921465,2022102300,3733,52627.0,Geno Stone,17,2022-10-23 15:57:23.799999,26.0,BAL,left,68.99,37.53,6.36,1.88,0.64,204.73,195.27,NaN,2022102300_3733,BAL,52595,68.89,36.81,4.95,1.69,0.49,236.18,212.30,0.726911,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.956152,0.894889,0.734667,210,208,394.8,351.52
921466,2022102300,3733,52627.0,Geno Stone,18,2022-10-23 15:57:23.900000,26.0,BAL,left,68.80,36.92,6.23,2.30,0.63,213.12,197.56,fumble,2022102300_3733,BAL,52595,68.62,36.39,5.04,0.93,0.50,238.15,212.39,0.559732,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.966690,0.827111,0.713778,210,208,483.0,193.44
921467,2022102300,3733,52627.0,Geno Stone,19,2022-10-23 15:57:24.000000,26.0,BAL,left,68.61,36.34,6.04,2.53,0.61,218.54,199.51,NaN,2022102300_3733,BAL,52595,68.36,35.97,4.97,0.16,0.49,244.32,212.06,0.446542,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.976107,0.788556,0.641556,210,208,531.3,33.28
921468,2022102300,3733,52627.0,Geno Stone,20,2022-10-23 15:57:24.099999,26.0,BAL,left,68.40,35.82,5.62,3.30,0.56,226.81,202.14,NaN,2022102300_3733,BAL,52595,68.09,35.55,4.92,0.71,0.50,247.38,211.91,0.411096,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.985497,0.725889,0.605889,210,208,693.0,147.68
921469,2022102300,3733,52627.0,Geno Stone,21,2022-10-23 15:57:24.200000,26.0,BAL,left,68.19,35.34,5.17,3.99,0.53,236.43,204.65,NaN,2022102300_3733,BAL,52595,67.86,35.18,4.57,1.85,0.45,254.88,211.62,0.366742,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992610,0.646889,0.519333,210,208,837.9,384.80
921470,2022102300,3733,52627.0,Geno Stone,22,2022-10-23 15:57:24.299999,26.0,BAL,left,67.97,34.89,4.79,4.18,0.50,241.97,207.54,NaN,2022102300_3733,BAL,52595,67.65,34.84,4.09,2.82,0.40,244.87,211.91,0.323883,52627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997093,0.617444,0.633778,210,208,877.8,586.56

In [328]:
fumbles_63[:60]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
81,2022091106,3213,54936,1,0,1,0,2022091106_3213,1.0,None,None,None,None
208,2022091805,327,52518,1,0,1,0,2022091805_327,1.0,None,None,None,None
269,2022091103,2740,44872,1,0,1,0,2022091103_2740,1.0,None,None,None,None
439,2022091100,679,53489,1,0,1,0,2022091100_679,1.0,None,None,None,None
528,2022091110,1695,43326,1,0,1,0,2022091110_1695,1.0,None,None,None,None
731,2022091110,3842,52539,1,0,1,0,2022091110_3842,1.0,None,None,None,None
806,2022091801,3557,53481,1,0,1,0,2022091801_3557,1.0,None,None,None,None
912,2022091107,2680,46211,1,0,1,0,2022091107_2680,1.0,None,None,None,None
952,2022091111,2360,47843,1,0,1,0,2022091111_2360,1.0,None,None,None,None
1208,2022091200,2712,46117,1,0,1,0,2022091200_2712,1.0,None,None,None,None
1297,2022091102,268,52458,1,0,1,0,2022091102_268,1.0,None,None,None,None
1357,2022091107,2987,44999,1,0,1,0,2022091107_2987,1.0,None,None,None,None
1364,2022091109,2083,53592,1,0,1,0,2022091109_2083,1.0,None,None,None,None
1372,2022091110,1868,46657,1,0,1,0,2022091110_1868,1.0,None,None,None,None
1404,2022091108,3366,52469,1,0,1,0,2022091108_3366,1.0,None,None,None,None
1672,2022092513,2900,46757,1,0,1,0,2022092513_2900,1.0,None,None,None,None
1840,2022092505,3069,43700,1,0,1,0,2022092505_3069,1.0,None,None,None,None
1982,2022092200,1419,44903,1,0,1,0,2022092200_1419,1.0,None,None,None,None
2112,2022092513,3504,54637,1,0,1,0,2022092513_3504,1.0,None,None,None,None
2131,2022091807,3338,53537,1,0,1,0,2022091807_3338,1.0,None,None,None,None
2293,2022092512,1985,48241,1,0,1,0,2022092512_1985,1.0,None,None,None,None
2392,2022092501,684,44925,1,0,1,0,2022092501_684,1.0,None,None,None,None
2481,2022092510,3485,44848,1,0,1,0,2022092510_3485,1.0,None,None,None,None
2596,2022091811,4519,52416,1,0,1,0,2022091811_4519,1.0,None,None,None,None
2639,2022092500,586,46527,1,0,1,0,2022092500_586,1.0,None,None,None,None
2684,2022092505,3437,54479,1,0,1,0,2022092505_3437,1.0,None,None,None,None
2685,2022092505,3740,42361,1,0,1,0,2022092505_3740,1.0,None,None,None,None
3531,2022091200,1092,42393,1,0,1,0,2022091200_1092,1.0,None,None,None,None
3534,2022091200,2292,42543,1,0,1,0,2022091200_2292,1.0,None,None,None,None
3617,2022100202,881,53460,1,0,1,0,2022100202_881,1.0,None,None,None,None
3633,2022100204,4070,43478,1,0,1,0,2022100204_4070,1.0,None,None,None,None
3831,2022100201,676,52542,1,0,1,0,2022100201_676,1.0,None,None,None,None
3943,2022100600,1335,53438,1,0,1,0,2022100600_1335,1.0,None,None,None,None
4317,2022100207,3117,43388,1,0,1,0,2022100207_3117,1.0,None,None,None,None
5003,2022101609,2732,54574,1,0,1,0,2022101609_2732,1.0,None,None,None,None
5173,2022101604,2636,46307,1,0,1,0,2022101604_2636,1.0,None,None,None,None
5258,2022102300,3733,52627,1,0,1,0,2022102300_3733,1.0,None,None,None,None
5326,2022101000,1667,52546,1,0,1,0,2022101000_1667,1.0,None,None,None,None
5468,2022102300,3248,53481,1,0,1,0,2022102300_3248,1.0,None,None,None,None
5496,2022102304,1759,52444,1,0,1,0,2022102304_1759,1.0,None,None,None,None
5559,2022100910,467,42470,1,0,1,0,2022100910_467,1.0,None,None,None,None
5921,2022092513,3925,48447,1,0,1,0,2022092513_3925,1.0,None,None,None,None
5980,2022100205,1570,54574,1,0,1,0,2022100205_1570,1.0,None,None,None,None
6014,2022100209,617,53663,1,0,1,0,2022100209_617,1.0,None,None,None,None
6168,2022102303,1658,54562,1,0,1,0,2022102303_1658,1.0,None,None,None,None
6295,2022103002,2935,46088,1,0,1,0,2022103002_2935,1.0,None,None,None,None
6433,2022103001,2496,43441,1,0,1,0,2022103001_2496,1.0,None,None,None,None
6531,2022103011,1465,44830,1,0,1,0,2022103011_1465,1.0,None,None,None,None
7100,2022103003,395,54562,1,0,1,0,2022103003_395,1.0,None,None,None,None
7308,2022110605,2150,47872,1,0,1,0,2022110605_2150,1.0,None,None,None,None
7459,2022102309,182,52435,1,0,1,0,2022102309_182,1.0,None,None,None,None
7715,2022101603,1589,53462,1,0,1,0,2022101603_1589,1.0,None,None,None,None
7731,2022101604,3589,38559,1,0,1,0,2022101604_3589,1.0,None,None,None,None
7856,2022110605,3394,52619,1,0,1,0,2022110605_3394,1.0,None,None,None,None
7887,2022110608,1940,46711,1,0,1,0,2022110608_1940,1.0,None,None,None,None
8123,2022110603,3713,52411,1,0,1,0,2022110603_3713,1.0,None,None,None,None
8374,2022110600,2183,41231,1,0,1,0,2022110600_2183,1.0,None,None,None,None
8689,2022103009,2259,53592,1,0,1,0,2022103009_2259,1.0,None,None,None,None
9135,2022101600,690,54503,1,0,1,0,2022101600_690,1.0,None,None,None,None
9284,2022102303,193,47996,1,0,1,0,2022102303_193,1.0,None,None,None,None

**Manipulating observations that had fumbles recorded but also tackle or missed tackles**

In [364]:
tackles_1v1_1_fumbles = tackles_1v1_1_fumbles[tackles_1v1_1_fumbles['game_play_Id'] != '2022100904_3777']

In [369]:
tackles_1v1_1_fumbles.loc[tackles_1v1_1_fumbles['game_play_Id'] == '2022091109_1827', 'event_type'] = 3
tackles_1v1_1_fumbles[tackles_1v1_1_fumbles['game_play_Id'] == '2022091109_1827']

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
1140,2022091109,1827,47790,1,0,1,0,2022091109_1827,3.0,1.468333,1.576667,3.671667,4.611667

In [377]:
tackles_1v1_1_fumbles.event_type.value_counts()

event_type
1.0    7784
2.0    1891
3.0      64
Name: count, dtype: int64

In [376]:
tackles_1v1_1_fumbles.loc[tackles_1v1_1_fumbles[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1), 'event_type'] = 3
tackles_1v1_1_fumbles[tackles_1v1_1_fumbles[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
81,2022091106,3213,54936,1,0,1,0,2022091106_3213,3.0,None,None,None,None
208,2022091805,327,52518,1,0,1,0,2022091805_327,3.0,None,None,None,None
269,2022091103,2740,44872,1,0,1,0,2022091103_2740,3.0,None,None,None,None
439,2022091100,679,53489,1,0,1,0,2022091100_679,3.0,None,None,None,None
528,2022091110,1695,43326,1,0,1,0,2022091110_1695,3.0,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9135,2022101600,690,54503,1,0,1,0,2022101600_690,3.0,None,None,None,None
9284,2022102303,193,47996,1,0,1,0,2022102303_193,3.0,None,None,None,None
9311,2022102305,3425,41483,1,0,1,0,2022102305_3425,3.0,None,None,None,None
9496,2022103012,762,54487,1,0,1,0,2022103012_762,3.0,None,None,None,None
9557,2022110603,3689,46958,1,0,1,0,2022110603_3689,3.0,None,None,None,None

In [386]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317876 entries, 0 to 1317875
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317876 non-null  int64
 1   playId            1317876 non-null  int64
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object
 4   frameId           1317876 non-null  int64
 5   time              1317876 non-null  object
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object
 8   playDirection     1317876 non-null  object
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  event             113127 non-null   object
 17  game_play_Id      1317876 non-null  object
 18  defensiveTeam     1317876 non-null  object
 19  ballCarrierId     1317876 non-null  int64
 20  bcx               1317876 non-null  float64
 21  bcy               1317876 non-null  float64
 22  bc_s              1317876 non-null  float64
 23  bc_a              1317876 non-null  float64
 24  bc_dis            1317876 non-null  float64
 25  bc_o              1317876 non-null  float64
 26  bc_dir            1317876 non-null  float64
 27  distance_from_bc  1317876 non-null  float64
 28  tackler_one       966361 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239506 non-null  float64
 40  do_align          1317876 non-null  float64
 41  bc_do_align       1317876 non-null  float64
 42  weight            1317876 non-null  int64
 43  bc_weight         1317876 non-null  int64
 44  force             1317876 non-null  float64
 45  bc_force          1317876 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 462.5+ MB

In [388]:
###Dropping Fumble Rows without at least a second of data before the fumble from the tracking data
tracking_clean_1 = drop_dataless_rows(tracking_clean_1, missing_indices_fumble_1)

Total matching rows: 53

In [389]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1317823 entries, 0 to 1317875
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317823 non-null  int64
 1   playId            1317823 non-null  int64
 2   nflId             1317823 non-null  float64
 3   displayName       1317823 non-null  object
 4   frameId           1317823 non-null  int64
 5   time              1317823 non-null  object
 6   jerseyNumber      1317823 non-null  float64
 7   club              1317823 non-null  object
 8   playDirection     1317823 non-null  object
 9   x                 1317823 non-null  float64
 10  y                 1317823 non-null  float64
 11  s                 1317823 non-null  float64
 12  a                 1317823 non-null  float64
 13  dis               1317823 non-null  float64
 14  o                 1317823 non-null  float64
 15  dir               1317823 non-null  float64
 16  event             113113 non-null   object
 17  game_play_Id      1317823 non-null  object
 18  defensiveTeam     1317823 non-null  object
 19  ballCarrierId     1317823 non-null  int64
 20  bcx               1317823 non-null  float64
 21  bcy               1317823 non-null  float64
 22  bc_s              1317823 non-null  float64
 23  bc_a              1317823 non-null  float64
 24  bc_dis            1317823 non-null  float64
 25  bc_o              1317823 non-null  float64
 26  bc_dir            1317823 non-null  float64
 27  distance_from_bc  1317823 non-null  float64
 28  tackler_one       966308 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239453 non-null  float64
 40  do_align          1317823 non-null  float64
 41  bc_do_align       1317823 non-null  float64
 42  weight            1317823 non-null  int64
 43  bc_weight         1317823 non-null  int64
 44  force             1317823 non-null  float64
 45  bc_force          1317823 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 472.5+ MB

In [390]:
tracking_clean_1 = tracking_clean_1.reset_index(drop=True)

In [391]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317823 entries, 0 to 1317822
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317823 non-null  int64
 1   playId            1317823 non-null  int64
 2   nflId             1317823 non-null  float64
 3   displayName       1317823 non-null  object
 4   frameId           1317823 non-null  int64
 5   time              1317823 non-null  object
 6   jerseyNumber      1317823 non-null  float64
 7   club              1317823 non-null  object
 8   playDirection     1317823 non-null  object
 9   x                 1317823 non-null  float64
 10  y                 1317823 non-null  float64
 11  s                 1317823 non-null  float64
 12  a                 1317823 non-null  float64
 13  dis               1317823 non-null  float64
 14  o                 1317823 non-null  float64
 15  dir               1317823 non-null  float64
 16  event             113113 non-null   object
 17  game_play_Id      1317823 non-null  object
 18  defensiveTeam     1317823 non-null  object
 19  ballCarrierId     1317823 non-null  int64
 20  bcx               1317823 non-null  float64
 21  bcy               1317823 non-null  float64
 22  bc_s              1317823 non-null  float64
 23  bc_a              1317823 non-null  float64
 24  bc_dis            1317823 non-null  float64
 25  bc_o              1317823 non-null  float64
 26  bc_dir            1317823 non-null  float64
 27  distance_from_bc  1317823 non-null  float64
 28  tackler_one       966308 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239453 non-null  float64
 40  do_align          1317823 non-null  float64
 41  bc_do_align       1317823 non-null  float64
 42  weight            1317823 non-null  int64
 43  bc_weight         1317823 non-null  int64
 44  force             1317823 non-null  float64
 45  bc_force          1317823 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 462.5+ MB

In [392]:
tracking_clean_1.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv', index=False)

In [393]:
tracking_clean_1_old = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv')

In [394]:
tracking_clean_1_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317876 entries, 0 to 1317875
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317876 non-null  int64
 1   playId            1317876 non-null  int64
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object
 4   frameId           1317876 non-null  int64
 5   time              1317876 non-null  object
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object
 8   playDirection     1317876 non-null  object
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  event             113127 non-null   object
 17  game_play_Id      1317876 non-null  object
 18  defensiveTeam     1317876 non-null  object
 19  ballCarrierId     1317876 non-null  int64
 20  bcx               1317876 non-null  float64
 21  bcy               1317876 non-null  float64
 22  bc_s              1317876 non-null  float64
 23  bc_a              1317876 non-null  float64
 24  bc_dis            1317876 non-null  float64
 25  bc_o              1317876 non-null  float64
 26  bc_dir            1317876 non-null  float64
 27  distance_from_bc  1317876 non-null  float64
 28  tackler_one       966361 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239506 non-null  float64
 40  do_align          1317876 non-null  float64
 41  bc_do_align       1317876 non-null  float64
 42  weight            1317876 non-null  int64
 43  bc_weight         1317876 non-null  int64
 44  force             1317876 non-null  float64
 45  bc_force          1317876 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 462.5+ MB

In [395]:
tackles_1v1_1_fumbles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9739 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9739 non-null   int64
 1   playId            9739 non-null   int64
 2   nflId             9739 non-null   int64
 3   tackle            9739 non-null   int64
 4   assist            9739 non-null   int64
 5   forcedFumble      9739 non-null   int64
 6   pff_missedTackle  9739 non-null   int64
 7   game_play_Id      9739 non-null   object
 8   event_type        9739 non-null   float64
 9   s_avg_05          9676 non-null   object
 10  s_avg_1           9676 non-null   object
 11  bc_s_avg_05       9676 non-null   object
 12  bc_s_avg_1        9676 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB

In [396]:
###Dropping tackling events with fumble and not at least 4 seconds of data before the fumble from the tracking data
tackles_1v1_1_master = drop_matching_rows(tackles_1v1_1_fumbles, tracking_clean_1_old, missing_indices_fumble_1)

In [397]:
tackles_1v1_1_master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9735 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9735 non-null   int64
 1   playId            9735 non-null   int64
 2   nflId             9735 non-null   int64
 3   tackle            9735 non-null   int64
 4   assist            9735 non-null   int64
 5   forcedFumble      9735 non-null   int64
 6   pff_missedTackle  9735 non-null   int64
 7   game_play_Id      9735 non-null   object
 8   event_type        9735 non-null   float64
 9   s_avg_05          9676 non-null   object
 10  s_avg_1           9676 non-null   object
 11  bc_s_avg_05       9676 non-null   object
 12  bc_s_avg_1        9676 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB

In [401]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317823 entries, 0 to 1317822
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317823 non-null  int64
 1   playId            1317823 non-null  int64
 2   nflId             1317823 non-null  float64
 3   displayName       1317823 non-null  object
 4   frameId           1317823 non-null  int64
 5   time              1317823 non-null  object
 6   jerseyNumber      1317823 non-null  float64
 7   club              1317823 non-null  object
 8   playDirection     1317823 non-null  object
 9   x                 1317823 non-null  float64
 10  y                 1317823 non-null  float64
 11  s                 1317823 non-null  float64
 12  a                 1317823 non-null  float64
 13  dis               1317823 non-null  float64
 14  o                 1317823 non-null  float64
 15  dir               1317823 non-null  float64
 16  event             113113 non-null   object
 17  game_play_Id      1317823 non-null  object
 18  defensiveTeam     1317823 non-null  object
 19  ballCarrierId     1317823 non-null  int64
 20  bcx               1317823 non-null  float64
 21  bcy               1317823 non-null  float64
 22  bc_s              1317823 non-null  float64
 23  bc_a              1317823 non-null  float64
 24  bc_dis            1317823 non-null  float64
 25  bc_o              1317823 non-null  float64
 26  bc_dir            1317823 non-null  float64
 27  distance_from_bc  1317823 non-null  float64
 28  tackler_one       966308 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239453 non-null  float64
 40  do_align          1317823 non-null  float64
 41  bc_do_align       1317823 non-null  float64
 42  weight            1317823 non-null  int64
 43  bc_weight         1317823 non-null  int64
 44  force             1317823 non-null  float64
 45  bc_force          1317823 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 462.5+ MB

---

**Updated Compute Speed**

In [699]:
def compute_speed_features(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['s_avg_05'] = None
    df1['s_avg_1'] = None
    df1['bc_s_avg_05'] = None
    df1['bc_s_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Print the index if it is a multiple of 1000
        if index % 1000 == 0:
            print(f"Processing index: {index}")
            
        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 3:
            condition = (df2['event'] == 'fumble') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 4:
            condition = (df2['event'] == 'first_contact') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1,2,3, nor 4

        matching_indexes = df2.index[condition]

        #Checking if there are no matching indexes
        if len(matching_indexes) == 0:
            print(f"Index {index} has no matching index")
            continue
        #Checking if there is one matching index (What we want)
        elif len(matching_indexes) == 1:
            i = matching_indexes[0]
        #Checking to make sure there is only one macthing index
        elif len(matching_indexes) > 1:
            print(f"Index {index} has more than one matching index")
    
        # Calculate averages and assign to df1
        df1.at[index, 's_avg_05'] = df2.loc[i-5:i-1, 's'].mean()
        df1.at[index, 's_avg_1'] = df2.loc[i-10:i-6, 's'].mean()
        df1.at[index, 'bc_s_avg_05'] = df2.loc[i-5:i-1, 'bc_s'].mean()
        df1.at[index, 'bc_s_avg_1'] = df2.loc[i-10:i-6, 'bc_s'].mean()

    return df1

# Example usage:
# updated_df1 = compute_averages_modified(df1, df2)

In [411]:
tackles_1v1_1_master.drop(columns=['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1'], inplace=True)

In [436]:
tackles_1v1_1_master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9735 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9735 non-null   int64
 1   playId            9735 non-null   int64
 2   nflId             9735 non-null   int64
 3   tackle            9735 non-null   int64
 4   assist            9735 non-null   int64
 5   forcedFumble      9735 non-null   int64
 6   pff_missedTackle  9735 non-null   int64
 7   game_play_Id      9735 non-null   object
 8   event_type        9735 non-null   float64
 9   s_avg_05          9734 non-null   object
 10  s_avg_1           9734 non-null   object
 11  bc_s_avg_05       9734 non-null   object
 12  bc_s_avg_1        9734 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.3+ MB

Index 8689 has no matching index: DELETE gpId: 	2022103009_2259, nflId: 53592
Index 219 has no matching index: CORRECT gpId: 2022091805_2361, nflId: 52444
Index 455 has no matching index: CORRECT gpId:2022091102_189, nflId:52571
Index 696 has no matching index: CORRECT gpId: 2022091105_2742, nflId: 53450
Index 2449 has no matching index: CORRECT gpId: 2022092507_3091, nflId: 47899
Index 4667 has no matching index: CORRECT gpId: 2022100906_3322, nflId: 54574
Index 5135 has no matching index: CORRECT gpId: 2022101600_636, nflId: 54503
Index 6144 has no matching index: CORRECT gpId: 2022102300_2890, nflId: 52627
Index 7169 has no matching index: CORRECT gpId: 2022103009_2993, nflID: 43358
Index 7262 has no matching index: CORRECT gpId: 2022110600_2782,nflId:52594

In [416]:
tackles_1v1_1_speedtest = compute_speed_features_edited(tackles_1v1_1_master, tracking_clean_1)

Index 8689 has no matching index
Index 219 has no matching index
Index 455 has no matching index
Index 696 has no matching index
Index 2449 has no matching index
Index 4667 has no matching index
Index 5135 has no matching index
Index 6144 has no matching index
Index 7169 has no matching index
Index 7262 has no matching index

In [417]:
tackles_1v1_1_speedtest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9735 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9735 non-null   int64
 1   playId            9735 non-null   int64
 2   nflId             9735 non-null   int64
 3   tackle            9735 non-null   int64
 4   assist            9735 non-null   int64
 5   forcedFumble      9735 non-null   int64
 6   pff_missedTackle  9735 non-null   int64
 7   game_play_Id      9735 non-null   object
 8   event_type        9735 non-null   float64
 9   s_avg_05          9734 non-null   object
 10  s_avg_1           9734 non-null   object
 11  bc_s_avg_05       9734 non-null   object
 12  bc_s_avg_1        9734 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.3+ MB

**Dropping Strange Observation**

In [502]:
strange_obs = tackles_1v1_1_speedtest[tackles_1v1_1_speedtest[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

In [530]:
tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest.drop(strange_obs.index)

In [531]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9734 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9734 non-null   int64
 1   playId            9734 non-null   int64
 2   nflId             9734 non-null   int64
 3   tackle            9734 non-null   int64
 4   assist            9734 non-null   int64
 5   forcedFumble      9734 non-null   int64
 6   pff_missedTackle  9734 non-null   int64
 7   game_play_Id      9734 non-null   object
 8   event_type        9734 non-null   float64
 9   s_avg_05          9734 non-null   object
 10  s_avg_1           9734 non-null   object
 11  bc_s_avg_05       9734 non-null   object
 12  bc_s_avg_1        9734 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB

In [506]:
tackles_1v1_1_speedtest_nso[tackles_1v1_1_speedtest_nso[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

Empty DataFrame
Columns: [gameId, playId, nflId, tackle, assist, forcedFumble, pff_missedTackle, game_play_Id, event_type, s_avg_05, s_avg_1, bc_s_avg_05, bc_s_avg_1]
Index: []

**Dropping the out of bounds with missed tackle observations**

In [532]:
###Resetting Index of tackles_1v1_1_speedtest_nso so only tackle index and not missed tackle index gets dropped
tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest_nso.reset_index(drop=True)

In [534]:
filtered_row_1 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091805_2361') & 
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52444) & 
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_2 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091102_189') & 
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52571) & 
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_3 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091105_2742') & 
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 53450) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_4 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022092507_3091') &  
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 47899) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_5 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022100906_3322') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 54574) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_6 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022101600_636') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 54503) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_7 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022102300_2890') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52627) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_8 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022103009_2993') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 43358) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_9 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022110600_2782') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52594) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

In [535]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9734 entries, 0 to 9733
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9734 non-null   int64
 1   playId            9734 non-null   int64
 2   nflId             9734 non-null   int64
 3   tackle            9734 non-null   int64
 4   assist            9734 non-null   int64
 5   forcedFumble      9734 non-null   int64
 6   pff_missedTackle  9734 non-null   int64
 7   game_play_Id      9734 non-null   object
 8   event_type        9734 non-null   float64
 9   s_avg_05          9734 non-null   object
 10  s_avg_1           9734 non-null   object
 11  bc_s_avg_05       9734 non-null   object
 12  bc_s_avg_1        9734 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 988.7+ KB

In [536]:
for i in range(1, 10):
    # Get the DataFrame filtered_row_{i}
    filtered_rows = globals()[f'filtered_row_{i}']
    
    # Drop the rows from tackles_1v1_1_speedtest_nso
    tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest_nso.drop(filtered_rows.index)

In [537]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9725 entries, 0 to 9733
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object
 10  s_avg_1           9725 non-null   object
 11  bc_s_avg_05       9725 non-null   object
 12  bc_s_avg_1        9725 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB

In [538]:
tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest_nso.reset_index(drop=True)

In [539]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object
 10  s_avg_1           9725 non-null   object
 11  bc_s_avg_05       9725 non-null   object
 12  bc_s_avg_1        9725 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 987.8+ KB

In [545]:
tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091110_750') & (tackles_1v1_1_speedtest_nso['nflId'] == 52546)]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
734,2022091110,750,52546,0,0,0,1,2022091110_750,2.0,1.456,2.868,0.386,2.1
9701,2022091110,750,52546,1,0,0,0,2022091110_750,1.0,1.456,2.868,0.386,2.1

In [546]:
tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091200_3723') & (tackles_1v1_1_speedtest_nso['nflId'] == 52435)]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
958,2022091200,3723,52435,0,0,0,1,2022091200_3723,2.0,2.02,2.704,2.212,1.586
9702,2022091200,3723,52435,1,0,0,0,2022091200_3723,1.0,2.02,2.704,2.212,1.586

In [541]:
tackles_original = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/tackles.csv')

---

**Looking into observations regarding using 'first_contact' event for missed tackles**

In [577]:
double_tackles_original = tackles_original[(tackles_original['tackle'] == 1) & (tackles_original['pff_missedTackle'] == 1)]

In [579]:
double_tackles_original

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle
219,2022091805,2361,52444,1,0,0,1
455,2022091102,189,52571,1,0,0,1
696,2022091105,2742,53450,1,0,0,1
935,2022091110,750,52546,1,0,0,1
1213,2022091200,3723,52435,1,0,0,1
1239,2022091801,3061,41270,1,0,0,1
1445,2022091801,2090,41270,1,0,0,1
2449,2022092507,3091,47899,1,0,0,1
2610,2022091900,736,53451,1,0,0,1
2817,2022091812,2620,47804,1,0,0,1
2893,2022092503,4086,38548,1,0,0,1
3055,2022100206,2702,47913,1,0,0,1
3072,2022100209,2038,44926,1,0,0,1
3865,2022100205,3163,47871,1,0,0,1
3957,2022100902,1025,54543,1,0,0,1
4289,2022100204,426,53592,1,0,0,1
4647,2022100904,3777,52497,1,0,1,1
4667,2022100906,3322,54574,1,0,0,1
4862,2022101700,2126,46264,1,0,0,1
4881,2022100911,2608,39984,1,0,0,1
5135,2022101600,636,54503,1,0,0,1
5144,2022101600,3211,46841,1,0,0,1
6144,2022102300,2890,52627,1,0,0,1
6390,2022102311,1564,38548,1,0,0,1
7169,2022103009,2993,43358,1,0,0,1
7262,2022110600,2782,52594,1,0,0,1
8229,2022110601,3266,43503,1,0,0,1
8241,2022110603,441,54653,1,0,0,1
8555,2022102308,881,53509,1,0,0,1
8683,2022103004,726,46669,1,0,0,1
8936,2022100211,1393,54586,1,0,0,1
9048,2022100906,2763,52435,1,0,0,1
9170,2022101604,699,38559,1,0,0,1
9575,2022110605,1030,53450,1,0,0,1
9620,2022110610,2875,47971,1,0,0,1

In [580]:
#Function to create 'game_play_Id' column in DF
def game_play_Id(df):
    df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')

    return df

In [581]:
double_tackles_original = game_play_Id(double_tackles_original)

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/2643504950.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')

In [618]:
# Create an empty list to store the indices
indices = []

# Iterate over the rows in double_tackles_original
for index, row in double_tackles_original.iterrows():
    # Find the indices in tracking_clean_1 where 'game_play_Id' and 'nflId' are equal to the current row's values and 'event' is 'first_contact'
    matching_indices = tracking_clean_1[(tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                                        (tracking_clean_1['nflId'] == row['nflId']) & 
                                        (tracking_clean_1['event'] == 'first_contact')].index
    
    if len(matching_indices) == 0:
        print(f"Index {index} has no matching index")
        continue
    elif len(matching_indices) == 1:
        i = matching_indices[0]
    elif len(matching_indices) > 1:
        print(f"Index {index} has more than one matching index")
        continue

    # Check if i - 10 has the same 'game_play_Id' and 'nflId' as i
    if (tracking_clean_1.loc[i - 10, 'game_play_Id'] != tracking_clean_1.loc[i, 'game_play_Id']) or (tracking_clean_1.loc[i - 10, 'nflId'] != tracking_clean_1.loc[i, 'nflId']):
            # If not, add i to the list of indices
            indices.append(i)

# Print the indices
print(indices)

Index 219 has no matching index
Index 8936 has no matching index
[285344, 553684, 778691, 785306, 816954]

In [617]:
double_tackles_original

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id
219,2022091805,2361,52444,1,0,0,1,2022091805_2361
455,2022091102,189,52571,1,0,0,1,2022091102_189
696,2022091105,2742,53450,1,0,0,1,2022091105_2742
935,2022091110,750,52546,1,0,0,1,2022091110_750
1213,2022091200,3723,52435,1,0,0,1,2022091200_3723
1239,2022091801,3061,41270,1,0,0,1,2022091801_3061
1445,2022091801,2090,41270,1,0,0,1,2022091801_2090
2449,2022092507,3091,47899,1,0,0,1,2022092507_3091
2610,2022091900,736,53451,1,0,0,1,2022091900_736
2817,2022091812,2620,47804,1,0,0,1,2022091812_2620
2893,2022092503,4086,38548,1,0,0,1,2022092503_4086
3055,2022100206,2702,47913,1,0,0,1,2022100206_2702
3072,2022100209,2038,44926,1,0,0,1,2022100209_2038
3865,2022100205,3163,47871,1,0,0,1,2022100205_3163
3957,2022100902,1025,54543,1,0,0,1,2022100902_1025
4289,2022100204,426,53592,1,0,0,1,2022100204_426
4647,2022100904,3777,52497,1,0,1,1,2022100904_3777
4667,2022100906,3322,54574,1,0,0,1,2022100906_3322
4862,2022101700,2126,46264,1,0,0,1,2022101700_2126
4881,2022100911,2608,39984,1,0,0,1,2022100911_2608
5135,2022101600,636,54503,1,0,0,1,2022101600_636
5144,2022101600,3211,46841,1,0,0,1,2022101600_3211
6144,2022102300,2890,52627,1,0,0,1,2022102300_2890
6390,2022102311,1564,38548,1,0,0,1,2022102311_1564
7169,2022103009,2993,43358,1,0,0,1,2022103009_2993
7262,2022110600,2782,52594,1,0,0,1,2022110600_2782
8229,2022110601,3266,43503,1,0,0,1,2022110601_3266
8241,2022110603,441,54653,1,0,0,1,2022110603_441
8555,2022102308,881,53509,1,0,0,1,2022102308_881
8683,2022103004,726,46669,1,0,0,1,2022103004_726
8936,2022100211,1393,54586,1,0,0,1,2022100211_1393
9048,2022100906,2763,52435,1,0,0,1,2022100906_2763
9170,2022101604,699,38559,1,0,0,1,2022101604_699
9575,2022110605,1030,53450,1,0,0,1,2022110605_1030
9620,2022110610,2875,47971,1,0,0,1,2022110610_2875

**Changing observation at Index 164 back (219 in original) back to event_type 2.0 due to lack of first_contact event**

In [657]:
tackles_1v1_1_all_features.event_type.value_counts()

event_type
1.0    7775
2.0    1858
3.0      59
4.0      33
Name: count, dtype: int64

In [658]:
tackles_1v1_1_all_features.at[164, 'event_type'] = 2.0

In [660]:
tackles_1v1_1_all_features.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      32
Name: count, dtype: int64

In [661]:
tackles_1v1_1_all_features[tackles_1v1_1_all_features['event_type']== 4]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1
357,2022091102,189,52571,0,0,0,1,2022091102_189,4.0,6.090,6.108,8.892,9.012,0.949142,0.973595,-0.684533,-0.4808,0.752511,0.788778
542,2022091105,2742,53450,0,0,0,1,2022091105_2742,4.0,8.682,8.116,8.738,8.478,0.867132,0.884459,0.630511,0.577178,0.675511,0.560733
734,2022091110,750,52546,0,0,0,1,2022091110_750,4.0,2.614,4.244,1.754,3.382,0.991219,0.979105,0.922267,0.957733,0.858378,0.759067
958,2022091200,3723,52435,0,0,0,1,2022091200_3723,4.0,2.492,2.772,1.804,1.294,0.718267,0.534332,0.945289,0.951356,-0.841156,-0.541289
981,2022091801,3061,41270,0,0,0,1,2022091801_3061,4.0,2.622,2.930,7.144,8.094,-0.556878,-0.822733,0.044422,0.408067,0.725578,0.808978
1129,2022091801,2090,41270,0,0,0,1,2022091801_2090,4.0,4.390,5.196,5.170,5.598,0.786652,0.959055,0.443556,0.288133,0.934689,0.8616
1937,2022092507,3091,47899,0,0,0,1,2022092507_3091,4.0,4.286,5.076,4.566,5.004,0.980674,0.95232,0.273489,0.0534,0.927778,0.896044
2066,2022091900,736,53451,0,0,0,1,2022091900_736,4.0,2.986,2.266,1.498,0.874,0.922129,0.886142,0.845711,0.9148,0.830444,0.877333
2232,2022091812,2620,47804,0,0,0,1,2022091812_2620,4.0,2.482,5.536,4.108,4.940,0.34789,0.382951,0.402822,0.5578,0.816622,0.762489
2294,2022092503,4086,38548,0,0,0,1,2022092503_4086,4.0,7.696,7.508,5.326,4.914,0.912203,0.956775,0.924867,0.817822,0.757422,0.848022
2422,2022100206,2702,47913,0,0,0,1,2022100206_2702,4.0,5.540,6.210,5.278,6.284,-0.450668,0.391746,0.843644,0.801089,0.945089,0.881844
2438,2022100209,2038,44926,0,0,0,1,2022100209_2038,4.0,5.938,6.312,5.166,5.480,0.852892,0.412437,0.706911,0.459156,0.582689,0.376756
3068,2022100205,3163,47871,0,0,0,1,2022100205_3163,4.0,5.042,4.342,7.160,7.044,0.940989,0.962482,0.167489,-0.158822,0.368822,0.664333
3145,2022100902,1025,54543,0,0,0,1,2022100902_1025,4.0,2.456,2.350,4.796,4.542,0.341205,-0.247444,0.589156,0.895778,0.846,0.932689
3413,2022100204,426,53592,0,0,0,1,2022100204_426,4.0,2.958,3.436,3.852,4.484,0.338237,0.238849,0.886422,0.862333,0.832622,0.810244
3701,2022100906,3322,54574,0,0,0,1,2022100906_3322,4.0,9.672,9.726,8.684,8.852,0.92378,0.951628,0.892311,0.935178,0.9088,0.926444
3862,2022101700,2126,46264,0,0,0,1,2022101700_2126,4.0,1.284,1.492,3.292,5.474,0.925665,0.719982,-0.824356,-0.339978,-0.703844,-0.915244
3879,2022100911,2608,39984,0,0,0,1,2022100911_2608,4.0,3.884,2.932,3.300,2.630,0.98776,0.719586,0.521778,0.623956,0.435244,0.311556
4082,2022101600,636,54503,0,0,0,1,2022101600_636,4.0,4.864,3.126,5.450,4.134,0.863155,0.956389,0.814,0.696311,0.626533,0.437067
4089,2022101600,3211,46841,0,0,0,1,2022101600_3211,4.0,4.848,5.444,3.366,1.972,-0.57449,-0.495644,0.822822,0.840978,0.6288,0.601133
4876,2022102300,2890,52627,0,0,0,1,2022102300_2890,4.0,4.412,3.960,6.878,7.594,0.905289,0.704543,-0.057844,-0.045556,0.659133,0.781689
5078,2022102311,1564,38548,0,0,0,1,2022102311_1564,4.0,5.942,5.708,5.910,7.826,0.85217,0.61876,0.551511,0.572356,0.7652,0.786511
5677,2022103009,2993,43358,0,0,0,1,2022103009_2993,4.0,7.554,7.272,7.740,6.684,0.911204,0.936374,0.775622,0.893422,0.4974,0.584111
5749,2022110600,2782,52594,0,0,0,1,2022110600_2782,4.0,7.884,6.952,8.348,8.148,0.899167,0.812733,0.728733,0.657044,0.7278,0.830422
6518,2022110601,3266,43503,0,0,0,1,2022110601_3266,4.0,2.060,4.360,5.416,5.980,-0.787105,-0.11907,0.771089,0.620622,0.796978,0.637067
6527,2022110603,441,54653,0,0,0,1,2022110603_441,4.0,4.906,5.116,5.184,4.334,0.656328,0.48689,0.7518,0.495756,0.580244,0.729867
6783,2022102308,881,53509,0,0,0,1,2022102308_881,4.0,3.172,4.492,3.680,4.560,0.103628,0.43658,0.258644,0.565244,0.871822,0.581022
6882,2022103004,726,46669,0,0,0,1,2022103004_726,4.0,7.262,8.430,6.432,7.658,0.836698,0.974694,0.786644,0.972778,0.705556,0.618178
7168,2022100906,2763,52435,0,0,0,1,2022100906_2763,4.0,6.980,6.498,7.306,6.954,0.83329,0.640687,0.392511,0.457067,0.630644,0.789244
7266,2022101604,699,38559,0,0,0,1,2022101604_699,4.0,4.402,3.902,3.812,4.904,0.717871,0.776895,0.700533,0.320911,0.812444,0.708956
7584,2022110605,1030,53450,0,0,0,1,2022110605_1030,4.0,2.916,2.560,3.796,3.256,-0.553153,-0.668217,0.113333,0.320311,0.630467,0.911711
7623,2022110610,2875,47971,0,0,0,1,2022110610_2875,4.0,3.882,5.820,2.108,2.026,-0.924228,0.161653,0.574289,0.754022,0.611289,0.464244

**Finding observations that match indices without a full second of data before them from tracking_clean_1**

In [662]:
# Get the 'game_play_Id' and 'nflId' values from tracking_clean_1 at the specified indices
game_play_ids = tracking_clean_1.loc[[285344, 553684, 778691, 785306, 816954], 'game_play_Id']
nfl_ids = tracking_clean_1.loc[[285344, 553684, 778691, 785306, 816954], 'nflId']

# Find the rows in tackles_1v1_1_newest where 'game_play_Id' and 'nflId' are in the lists
matching_rows = tackles_1v1_1_all_features[(tackles_1v1_1_all_features['game_play_Id'].isin(game_play_ids)) & 
                                     (tackles_1v1_1_all_features['nflId'].isin(nfl_ids))]

# Get the indices of the matching rows
matching_indices = matching_rows.index

# Print the indices
print(matching_indices)

Index([2066, 2438, 4082, 4089, 7266, 9705, 9709, 9715, 9722], dtype='int64')

In [663]:
tackles_1v1_1_all_features.iloc[matching_indices]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1
2066,2022091900,736,53451,0,0,0,1,2022091900_736,4.0,2.986,2.266,1.498,0.874,0.922129,0.886142,0.845711,0.9148,0.830444,0.877333
2438,2022100209,2038,44926,0,0,0,1,2022100209_2038,4.0,5.938,6.312,5.166,5.480,0.852892,0.412437,0.706911,0.459156,0.582689,0.376756
4082,2022101600,636,54503,0,0,0,1,2022101600_636,4.0,4.864,3.126,5.450,4.134,0.863155,0.956389,0.814,0.696311,0.626533,0.437067
4089,2022101600,3211,46841,0,0,0,1,2022101600_3211,4.0,4.848,5.444,3.366,1.972,-0.57449,-0.495644,0.822822,0.840978,0.6288,0.601133
7266,2022101604,699,38559,0,0,0,1,2022101604_699,4.0,4.402,3.902,3.812,4.904,0.717871,0.776895,0.700533,0.320911,0.812444,0.708956
9705,2022091900,736,53451,1,0,0,0,2022091900_736,1.0,2.654,0.846,0.986,1.014,0.946746,0.687905,0.950711,0.435178,0.881356,0.347311
9709,2022100209,2038,44926,1,0,0,0,2022100209_2038,1.0,2.170,3.888,1.316,3.746,0.851791,0.989272,0.354111,0.8498,0.345333,0.622511
9715,2022101600,3211,46841,1,0,0,0,2022101600_3211,1.0,3.430,3.336,4.948,5.330,0.864697,0.573301,0.901689,0.647911,0.256711,0.670222
9722,2022101604,699,38559,1,0,0,0,2022101604_699,1.0,0.846,1.470,4.854,3.626,-0.870827,-0.519733,0.156311,0.794,0.5676,0.438711

In [664]:
tracking_clean_1.iloc[indices]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
285344,2022091900,736,53451.0,Caleb Farley,7,2022-09-19 19:48:09.799999,3.0,TEN,left,68.79,6.05,4.78,2.79,0.46,80.36,127.99,first_contact,2022091900_736,TEN,42489,69.23,6.52,0.61,3.55,0.05,33.87,60.41,0.643817,53451.0,NaN,NaN,NaN,53451.0,NaN,NaN,NaN,NaN,NaN,NaN,0.381393,0.470778,0.705111,207,191,577.53,678.05
553684,2022100209,2038,44926.0,Rayshawn Jenkins,7,2022-10-02 14:40:20.500000,2.0,JAX,right,51.86,25.80,5.97,4.55,0.59,165.18,119.29,first_contact,2022100209_2038,JAX,47834,53.38,21.74,5.77,2.31,0.59,66.03,43.17,4.335205,44926.0,NaN,NaN,NaN,44926.0,NaN,NaN,NaN,NaN,NaN,NaN,0.239889,0.490111,0.746000,220,226,1001.00,522.06
778691,2022101600,636,54503.0,Arnold Ebiketie,7,2022-10-16 13:29:16.500000,47.0,ATL,right,24.95,10.66,4.88,2.47,0.50,191.84,151.66,first_contact,2022101600_636,ATL,47819,25.12,9.09,1.14,1.52,0.11,42.63,265.12,1.579177,54503.0,NaN,NaN,NaN,54503.0,52424.0,NaN,NaN,NaN,NaN,NaN,-0.398109,0.553556,-0.527889,256,214,632.32,325.28
785306,2022101600,3211,46841.0,Matt Dickerson,8,2022-10-16 15:35:47.500000,91.0,ATL,right,56.96,21.39,3.95,3.23,0.41,157.86,172.42,first_contact,2022101600_3211,ATL,47819,60.05,12.64,1.14,4.66,0.13,102.01,318.22,9.279580,46841.0,NaN,NaN,NaN,46841.0,46135.0,38592.0,NaN,NaN,NaN,NaN,-0.827081,0.838222,-0.597667,290,214,936.70,997.24
816954,2022101604,699,38559.0,Harrison Smith,10,2022-10-16 13:27:08.400000,22.0,MIN,right,80.84,32.40,4.44,0.81,0.45,229.53,223.88,first_contact,2022101604_699,MIN,53435,80.52,32.22,3.23,2.89,0.33,181.92,182.96,0.367151,38559.0,NaN,NaN,NaN,38559.0,NaN,NaN,NaN,NaN,NaN,NaN,0.755625,0.937222,0.988444,214,182,173.34,525.98

In [665]:
matching_indices_drop = matching_indices[0:5]

In [666]:
tackles_1v1_1_all_features.iloc[matching_indices_drop]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1
2066,2022091900,736,53451,0,0,0,1,2022091900_736,4.0,2.986,2.266,1.498,0.874,0.922129,0.886142,0.845711,0.9148,0.830444,0.877333
2438,2022100209,2038,44926,0,0,0,1,2022100209_2038,4.0,5.938,6.312,5.166,5.480,0.852892,0.412437,0.706911,0.459156,0.582689,0.376756
4082,2022101600,636,54503,0,0,0,1,2022101600_636,4.0,4.864,3.126,5.450,4.134,0.863155,0.956389,0.814,0.696311,0.626533,0.437067
4089,2022101600,3211,46841,0,0,0,1,2022101600_3211,4.0,4.848,5.444,3.366,1.972,-0.57449,-0.495644,0.822822,0.840978,0.6288,0.601133
7266,2022101604,699,38559,0,0,0,1,2022101604_699,4.0,4.402,3.902,3.812,4.904,0.717871,0.776895,0.700533,0.320911,0.812444,0.708956

In [669]:
tackles_1v1_1_all_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   float64
 10  s_avg_1           9725 non-null   float64
 11  bc_s_avg_05       9725 non-null   float64
 12  bc_s_avg_1        9725 non-null   float64
 13  cos_avg_05        9717 non-null   object
 14  cos_avg_1         9721 non-null   object
 15  do_avg_05         9725 non-null   object
 16  do_avg_1          9725 non-null   object
 17  bc_do_avg_05      9725 non-null   object
 18  bc_do_avg_1       9725 non-null   object
dtypes: float64(5), int64(7), object(7)
memory usage: 1.4+ MB

In [670]:
###Dropping the 5 observations where there is no data at least 1 second before 'first_contact' event
tackles_1v1_1_af_drop5 = tackles_1v1_1_all_features.drop(matching_indices_drop)

In [671]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9712 non-null   object
 14  cos_avg_1         9716 non-null   object
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
dtypes: float64(5), int64(7), object(7)
memory usage: 1.5+ MB

In [672]:
tackles_1v1_1_af_drop5[(tackles_1v1_1_af_drop5['game_play_Id'] == '2022100211_1393') & (tackles_1v1_1_af_drop5['nflId'] == 54586)]

Empty DataFrame
Columns: [gameId, playId, nflId, tackle, assist, forcedFumble, pff_missedTackle, game_play_Id, event_type, s_avg_05, s_avg_1, bc_s_avg_05, bc_s_avg_1, cos_avg_05, cos_avg_1, do_avg_05, do_avg_1, bc_do_avg_05, bc_do_avg_1]
Index: []

In [582]:
double_tackles_original.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 219 to 9620
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            35 non-null     int64
 1   playId            35 non-null     int64
 2   nflId             35 non-null     int64
 3   tackle            35 non-null     int64
 4   assist            35 non-null     int64
 5   forcedFumble      35 non-null     int64
 6   pff_missedTackle  35 non-null     int64
 7   game_play_Id      35 non-null     object
dtypes: int64(7), object(1)
memory usage: 2.5+ KB

---

**Re-running speed features**

In [547]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object
 10  s_avg_1           9725 non-null   object
 11  bc_s_avg_05       9725 non-null   object
 12  bc_s_avg_1        9725 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 987.8+ KB

In [548]:
tackles_1v1_1_updated = tackles_1v1_1_speedtest_nso.drop(columns=['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1'])

In [549]:
tackles_1v1_1_updated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
dtypes: float64(1), int64(7), object(1)
memory usage: 683.9+ KB

In [552]:
###Re-running speed computation to see if the events with both a missed tackle an dtackle originally get properly calculated
tackles_1v1_1_newest = compute_speed_features_edited(tackles_1v1_1_updated, tracking_clean_1)

In [553]:
tackles_1v1_1_newest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object
 10  s_avg_1           9725 non-null   object
 11  bc_s_avg_05       9725 non-null   object
 12  bc_s_avg_1        9725 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 987.8+ KB

In [555]:
tackles_1v1_1_newest.head()

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0,3.52,4.332,5.694,6.83
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0,2.164,1.706,0.298,0.336
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0,2.332,2.274,3.0,2.376
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0,4.274,5.334,4.364,5.72
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0,0.854,1.828,1.448,2.134

In [556]:
tackles_1v1_1_newest['s_avg_05'] = tackles_1v1_1_newest['s_avg_05'].astype(float)
tackles_1v1_1_newest['s_avg_1'] = tackles_1v1_1_newest['s_avg_1'].astype(float)
tackles_1v1_1_newest['bc_s_avg_05'] = tackles_1v1_1_newest['bc_s_avg_05'].astype(float)
tackles_1v1_1_newest['bc_s_avg_1'] = tackles_1v1_1_newest['bc_s_avg_1'].astype(float)

In [557]:
tackles_1v1_1_newest.head()

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0,3.520,4.332,5.694,6.830
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0,2.164,1.706,0.298,0.336
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0,2.332,2.274,3.000,2.376
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0,4.274,5.334,4.364,5.720
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0,0.854,1.828,1.448,2.134

In [558]:
tackles_1v1_1_newest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   float64
 10  s_avg_1           9725 non-null   float64
 11  bc_s_avg_05       9725 non-null   float64
 12  bc_s_avg_1        9725 non-null   float64
dtypes: float64(5), int64(7), object(1)
memory usage: 987.8+ KB

In [559]:
tackles_1v1_1_newest[(tackles_1v1_1_newest['game_play_Id'] == '2022091110_750') & (tackles_1v1_1_newest['nflId'] == 52546)]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
734,2022091110,750,52546,0,0,0,1,2022091110_750,2.0,2.614,4.244,1.754,3.382
9701,2022091110,750,52546,1,0,0,0,2022091110_750,1.0,1.456,2.868,0.386,2.100

In [560]:
tackles_1v1_1_newest[(tackles_1v1_1_newest['game_play_Id'] == '2022091200_3723') & (tackles_1v1_1_newest['nflId'] == 52435)]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
958,2022091200,3723,52435,0,0,0,1,2022091200_3723,2.0,2.492,2.772,1.804,1.294
9702,2022091200,3723,52435,1,0,0,0,2022091200_3723,1.0,2.020,2.704,2.212,1.586

In [568]:
tracking_clean_1[(tracking_clean_1['game_play_Id'] == '2022091801_2090') & (tracking_clean_1['nflId'] == 41270)]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
175881,2022091801,2090,41270.0,Lamarcus Joyner,1,2022-09-18 14:39:11.900000,29.0,NYJ,right,65.10,36.65,7.06,2.28,0.71,325.72,0.18,NaN,2022091801_2090,NYJ,52523,60.11,44.50,3.85,4.67,0.40,254.42,42.00,9.301753,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.745243,0.617111,-0.639778,185,240,421.80,1120.8
175882,2022091801,2090,41270.0,Lamarcus Joyner,2,2022-09-18 14:39:12.000000,29.0,NYJ,right,65.11,37.35,6.89,2.45,0.70,321.91,1.01,NaN,2022091801_2090,NYJ,52523,60.36,44.75,3.38,4.75,0.35,247.53,47.46,8.793321,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.688987,0.565556,-0.777000,185,240,453.25,1140.0
175883,2022091801,2090,41270.0,Lamarcus Joyner,3,2022-09-18 14:39:12.099999,29.0,NYJ,right,65.12,38.03,6.65,2.61,0.68,316.73,1.74,NaN,2022091801_2090,NYJ,52523,60.62,44.92,2.93,6.23,0.31,232.26,59.89,8.229344,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.527697,0.499889,-0.915222,185,240,482.85,1495.2
175884,2022091801,2090,41270.0,Lamarcus Joyner,4,2022-09-18 14:39:12.200000,29.0,NYJ,right,65.14,38.67,6.29,2.98,0.64,304.90,2.20,NaN,2022091801_2090,NYJ,52523,60.88,45.03,2.66,6.69,0.28,219.62,75.30,7.654881,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.290702,0.363333,-0.603556,185,240,551.30,1605.6
175885,2022091801,2090,41270.0,Lamarcus Joyner,5,2022-09-18 14:39:12.299999,29.0,NYJ,right,65.16,39.27,5.85,3.44,0.60,297.44,2.10,NaN,2022091801_2090,NYJ,52523,61.13,45.08,2.61,7.09,0.26,207.74,90.65,7.070856,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.025305,0.281556,-0.301000,185,240,636.40,1701.6
175886,2022091801,2090,41270.0,Lamarcus Joyner,6,2022-09-18 14:39:12.400000,29.0,NYJ,right,65.19,39.83,5.36,4.02,0.56,288.06,2.51,pass_outcome_caught,2022091801_2090,NYJ,52523,61.39,45.04,2.75,6.19,0.26,204.95,105.40,6.448573,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.223080,0.172778,-0.106111,185,240,743.70,1485.6
175887,2022091801,2090,41270.0,Lamarcus Joyner,7,2022-09-18 14:39:12.500000,29.0,NYJ,right,65.21,40.31,4.70,4.65,0.48,279.54,2.78,NaN,2022091801_2090,NYJ,52523,61.66,44.92,3.04,6.14,0.29,186.06,122.08,5.818471,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.489382,0.075111,0.289111,185,240,860.25,1473.6
175888,2022091801,2090,41270.0,Lamarcus Joyner,8,2022-09-18 14:39:12.599999,29.0,NYJ,right,65.23,40.72,3.96,5.26,0.41,273.76,2.67,NaN,2022091801_2090,NYJ,52523,61.91,44.72,3.38,5.54,0.32,174.32,132.07,5.198307,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.634731,0.012111,0.530556,185,240,973.10,1329.6
175889,2022091801,2090,41270.0,Lamarcus Joyner,9,2022-09-18 14:39:12.700000,29.0,NYJ,right,65.24,41.06,3.17,5.69,0.34,266.13,1.55,NaN,2022091801_2090,NYJ,52523,62.16,44.47,3.75,4.74,0.36,168.75,139.36,4.595052,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.740922,-0.060222,0.673444,185,240,1052.65,1137.6
175890,2022091801,2090,41270.0,Lamarcus Joyner,10,2022-09-18 14:39:12.799999,29.0,NYJ,right,65.24,41.30,2.26,6.12,0.24,252.92,0.77,NaN,2022091801_2090,NYJ,52523,62.39,44.15,4.09,4.05,0.39,164.94,145.23,4.030509,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.813710,-0.198333,0.781000,185,240,1132.20,972.0
175891,2022091801,2090,41270.0,Lamarcus Joyner,11,2022-09-18 14:39:12.900000,29.0,NYJ,right,65.24,41.46,1.37,6.31,0.16,247.80,0.37,NaN,2022091801_2090,NYJ,52523,62.62,43.78,4.41,3.57,0.43,168.94,150.35,3.499543,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.865851,-0.250778,0.793444,185,240,1167.35,856.8
175892,2022091801,2090,41270.0,Lamarcus Joyner,12,2022-09-18 14:39:13.000000,29.0,NYJ,right,65.23,41.53,0.44,6.96,0.07,249.75,347.31,NaN,2022091801_2090,NYJ,52523,62.83,43.37,4.72,3.13,0.46,160.11,153.54,3.024169,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.971259,-0.084000,0.927000,185,240,1287.60,751.2
175893,2022091801,2090,41270.0,Lamarcus Joyner,13,2022-09-18 14:39:13.099999,29.0,NYJ,right,65.22,41.53,0.39,6.75,0.02,246.14,206.28,NaN,2022091801_2090,NYJ,52523,63.04,42.93,5.00,2.66,0.49,154.16,155.99,2.590830,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.638902,0.557111,0.979667,185,240,1248.75,638.4
175894,2022091801,2090,41270.0,Lamarcus Joyner,14,2022-09-18 14:39:13.200000,29.0,NYJ,right,65.20,41.44,1.19,6.53,0.08,238.02,191.85,NaN,2022091801_2090,NYJ,52523,63.24,42.46,5.21,2.05,0.51,147.97,157.72,2.209525,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.827767,0.487000,0.891667,185,240,1208.05,492.0
175895,2022091801,2090,41270.0,Lamarcus Joyner,15,2022-09-18 14:39:13.299999,29.0,NYJ,right,65.17,41.30,1.83,5.83,0.15,234.92,188.99,NaN,2022091801_2090,NYJ,52523,63.44,41.96,5.36,1.48,0.53,140.18,158.98,1.851621,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.865938,0.489667,0.791111,185,240,1078.55,355.2
175896,2022091801,2090,41270.0,Lamarcus Joyner,16,2022-09-18 14:39:13.400000,29.0,NYJ,right,65.15,41.08,2.43,5.05,0.22,233.50,185.50,NaN,2022091801_2090,NYJ,52523,63.62,41.45,5.51,1.19,0.55,131.95,160.36,1.574103,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.905272,0.466667,0.684333,185,240,934.25,285.6
175897,2022091801,2090,41270.0,Lamarcus Joyner,17,2022-09-18 14:39:13.500000,29.0,NYJ,right,65.14,40.80,3.01,4.36,0.28,230.87,182.68,NaN,2022091801_2090,NYJ,52523,63.81,40.93,5.59,0.75,0.56,127.91,160.95,1.336338,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.928939,0.464556,0.632889,185,240,806.60,180.0
175898,2022091801,2090,41270.0,Lamarcus Joyner,18,2022-09-18 14:39:13.599999,29.0,NYJ,right,65.16,40.46,3.51,3.78,0.34,232.38,177.93,first_contact,2022091801_2090,NYJ,52523,63.99,40.39,5.64,0.55,0.56,125.81,161.58,1.172092,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.959560,0.395000,0.602556,185,240,699.30,132.0
175899,2022091801,2090,41270.0,Lamarcus Joyner,19,2022-09-18 14:39:13.700000,29.0,NYJ,right,65.19,40.09,3.93,3.24,0.38,231.22,174.74,NaN,2022091801_2090,NYJ,52523,64.16,39.84,5.72,0.58,0.57,127.10,162.55,1.059906,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.977453,0.372444,0.606111,185,240,599.40,139.2
175900,2022091801,2090,41270.0,Lamarcus Joyner,20,2022-09-18 14:39:13.799999,29.0,NYJ,right,65.26,39.67,4.37,3.29,0.42,230.15,171.30,NaN,2022091801_2090,NYJ,52523,64.33,39.29,5.82,0.75,0.58,129.83,163.95,1.004639,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.991783,0.346111,0.620889,185,240,608.65,180.0
175901,2022091801,2090,41270.0,Lamarcus Joyner,21,2022-09-18 14:39:13.900000,29.0,NYJ,right,65.34,39.22,4.70,3.20,0.46,232.18,168.22,NaN,2022091801_2090,NYJ,52523,64.48,38.72,5.83,0.88,0.59,129.83,165.11,0.994786,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.998527,0.289333,0.608000,185,240,592.00,211.2
175902,2022091801,2090,41270.0,Lamarcus Joyner,22,2022-09-18 14:39:14.000000,29.0,NYJ,right,65.45,38.75,4.94,2.74,0.48,226.75,166.06,NaN,2022091801_2090,NYJ,52523,64.63,38.15,5.83,0.97,0.59,129.17,166.19,1.016071,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.999997,0.325667,0.588667,185,240,506.90,232.8
175903,2022091801,2090,41270.0,Lamarcus Joyner,23,2022-09-18 14:39:14.099999,29.0,NYJ,right,65.58,38.27,5.10,2.26,0.50,217.33,163.23,NaN,2022091801_2090,NYJ,52523,64.76,37.58,5.81,1.02,0.59,126.35,166.98,1.071681,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.997859,0.398889,0.548556,185,240,418.10,244.8
175904,2022091801,2090,41270.0,Lamarcus Joyner,24,2022-09-18 14:39:14.200000,29.0,NYJ,right,65.74,37.77,5.27,1.83,0.52,203.50,161.21,NaN,2022091801_2090,NYJ,52523,64.89,37.02,5.76,1.08,0.58,126.35,167.59,1.133578,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.993807,0.530111,0.541778,185,240,338.55,259.2
175905,2022091801,2090,41270.0,Lamarcus Joyner,25,2022-09-18 14:39:14.299999,29.0,NYJ,right,65.93,37.26,5.46,1.76,0.54,203.50,158.65,NaN,2022091801_2090,NYJ,52523,65.00,36.46,5.63,1.45,0.57,134.59,169.03,1.226744,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.983634,0.501667,0.617333,185,240,325.60,348.0
175906,2022091801,2090,41270.0,Lamarcus Joyner,26,2022-09-18 14:39:14.400000,29.0,NYJ,right,66.14,36.75,5.60,1.52,0.56,210.17,156.93,NaN,2022091801_2090,NYJ,52523,65.09,35.91,5.56,1.61,0.56,140.09,170.85,1.344656,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.970633,0.408444,0.658222,185,240,281.20,386.4
175907,2022091801,2090,41270.0,Lamarcus Joyner,27,2022-09-18 14:39:14.500000,29.0,NYJ,right,66.37,36.23,5.69,1.27,0.57,217.52,155.52,NaN,2022091801_2090,NYJ,52523,65.18,35.35,5.51,1.45,0.56,146.49,171.19,1.480034,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.962833,0.311111,0.725556,185,240,234.95,348.0
175908,2022091801,2090,41270.0,Lamarcus Joyner,28,2022-09-18 14:39:14.599999,29.0,NYJ,right,66.62,35.71,5.77,1.10,0.58,224.87,154.21,NaN,2022091801_2090,NYJ,52523,65.26,34.81,5.45,1.25,0.55,151.44,171.57,1.630828,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.954449,0.214889,0.776333,185,240,203.50,300.0
175909,2022091801,2090,41270.0,Lamarcus Joyner,29,2022-09-18 14:39:14.700000,29.0,NYJ,right,66.88,35.18,5.83,0.95,0.58,232.11,153.15,NaN,2022091801_2090,NYJ,52523,65.35,34.26,5.47,0.93,0.55,149.62,171.59,1.785301,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.948655,0.122667,0.755889,185,240,175.75,223.2
175910,2022091801,2090,41270.0,Lamarcus Joyner,30,2022-09-18 14:39:14.799999,29.0,NYJ,right,67.14,34.67,5.80,0.87,0.58,239.92,152.38,NaN,2022091801_2090,NYJ,52523,65.42,33.72,5.42,0.91,0.55,148.18,171.98,1.964917,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.942057,0.027333,0.735556,185,240,160.95,218.4
175911,2022091801,2090,41270.0,Lamarcus Joyner,31,2022-09-18 14:39:14.900000,29.0,NYJ,right,67.42,34.16,5.74,1.04,0.58,243.15,151.45,NaN,2022091801_2090,NYJ,52523,65.51,33.17,5.43,0.84,0.55,153.05,170.86,2.151325,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.943165,-0.018889,0.802111,185,240,192.40,201.6
175912,2022091801,2090,41270.0,Lamarcus Joyner,32,2022-09-18 14:39:15.000000,29.0,NYJ,right,67.69,33.66,5.63,1.23,0.57,243.15,151.15,NaN,2022091801_2090,NYJ,52523,65.63,32.63,5.50,0.89,0.56,163.02,168.83,2.303150,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.952768,-0.022222,0.935444,185,240,227.55,213.6
175913,2022091801,2090,41270.0,Lamarcus Joyner,33,2022-09-18 14:39:15.099999,29.0,NYJ,right,67.96,33.17,5.52,1.39,0.56,240.26,151.08,NaN,2022091801_2090,NYJ,52523,65.76,32.08,5.57,1.30,0.56,161.15,166.24,2.455219,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.965199,0.009111,0.943444,185,240,257.15,312.0
175914,2022091801,2090,41270.0,Lamarcus Joyner,34,2022-09-18 14:39:15.200000,29.0,NYJ,right,68.21,32.69,5.40,1.51,0.55,236.87,151.81,NaN,2022091801_2090,NYJ,52523,65.92,31.54,5.59,1.68,0.56,164.53,163.42,2.562538,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.979540,0.054889,0.987667,185,240,279.35,403.2
175915,2022091801,2090,41270.0,Lamarcus Joyner,35,2022-09-18 14:39:15.299999,29.0,NYJ,right,68.46,32.20,5.37,1.34,0.54,234.02,152.64,NaN,2022091801_2090,NYJ,52523,66.09,31.01,5.56,1.85,0.56,168.06,160.96,2.651980,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.989475,0.095778,0.921111,185,240,247.90,444.0
175916,2022091801,2090,41270.0,Lamarcus Joyner,36,2022-09-18 14:39:15.400000,29.0,NYJ,right,68.70,31.72,5.32,1.51,0.54,224.88,154.96,NaN,2022091801_2090,NYJ,52523,66.33,30.49,5.63,2.81,0.57,168.06,155.64,2.670169,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.999930,0.223111,0.862000,185,240,279.35,674.4
175917,2022091801,2090,41270.0,Lamarcus Joyner,37,2022-09-18 14:39:15.500000,29.0,NYJ,right,68.91,31.24,5.21,1.92,0.52,219.37,157.25,NaN,2022091801_2090,NYJ,52523,66.59,29.99,5.61,2.97,0.56,166.22,151.75,2.635318,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.995396,0.309778,0.839222,185,240,355.20,712.8
175918,2022091801,2090,41270.0,Lamarcus Joyner,38,2022-09-18 14:39:15.599999,29.0,NYJ,right,69.10,30.76,5.11,1.95,0.52,218.23,159.08,NaN,2022091801_2090,NYJ,52523,66.89,29.51,5.67,3.07,0.57,161.73,147.34,2.539016,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.979081,0.342778,0.840111,185,240,360.75,736.8
175919,2022091801,2090,41270.0,Lamarcus Joyner,39,2022-09-18 14:39:15.700000,29.0,NYJ,right,69.25,30.25,5.21,2.36,0.53,233.03,163.77,NaN,2022091801_2090,NYJ,52523,67.22,29.06,5.59,3.12,0.56,154.01,142.97,2.353083,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.934826,0.230444,0.877333,185,240,436.60,748.8
175920,2022091801,2090,41270.0,Lamarcus Joyner,40,2022-09-18 14:39:15.799999,29.0,NYJ,right,69.37,29.75,5.13,2.61,0.52,227.40,167.51,NaN,2022091801_2090,NYJ,52523,67.56,28.63,5.49,2.88,0.55,149.85,139.89,2.128497,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.886042,0.334556,0.889333,185,240,482.85,691.2
175921,2022091801,2090,41270.0,Lamarcus Joyner,41,2022-09-18 14:39:15.900000,29.0,NYJ,right,69.47,29.26,4.99,2.52,0.50,227.40,170.13,NaN,2022091801_2090,NYJ,52523,67.92,28.22,5.41,2.71,0.55,147.19,137.14,1.866574,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.838766,0.363667,0.888333,185,240,466.20,650.4
175922,2022091801,2090,41270.0,Lamarcus Joyner,42,2022-09-18 14:39:16.000000,29.0,NYJ,right,69.54,28.82,4.62,2.73,0.45,222.36,172.80,NaN,2022091801_2090,NYJ,52523,68.29,27.82,5.33,2.16,0.54,144.19,135.89,1.600781,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.799580,0.449333,0.907778,185,240,505.05,518.4
175923,2022091801,2090,41270.0,Lamarcus Joyner,43,2022-09-18 14:39:16.099999,29.0,NYJ,right,69.59,28.38,4.35,3.02,0.44,223.95,175.16,NaN,2022091801_2090,NYJ,52523,68.65,27.44,5.18,1.84,0.53,141.93,135.53,1.329361,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.770179,0.457889,0.928889,185,240,558.70,441.6
175924,2022091801,2090,41270.0,Lamarcus Joyner,44,2022-09-18 14:39:16.200000,29.0,NYJ,right,69.62,27.97,4.09,3.05,0.42,224.78,177.35,NaN,2022091801_2090,NYJ,52523,68.99,27.06,5.00,1.76,0.51,139.81,136.23,1.106797,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.753334,0.473000,0.960222,185,240,564.25,422.4
175925,2022091801,2090,41270.0,Lamarcus Joyner,45,2022-09-18 14:39:16.299999,29.0,NYJ,right,69.64,27.56,3.90,2.70,0.41,225.62,178.27,NaN,2022091801_2090,NYJ,52523,69.31,26.67,4.93,1.69,0.51,139.81,138.75,0.949210,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.771403,0.473889,0.988222,185,240,499.50,405.6
175926,2022091801,2090,41270.0,Lamarcus Joyner,46,2022-09-18 14:39:16.400000,29.0,NYJ,right,69.70,27.19,3.58,2.63,0.37,203.62,175.07,NaN,2022091801_2090,NYJ,52523,69.63,26.30,4.82,1.72,0.49,142.66,139.56,0.892749,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,missed tackle,0.814014,0.682778,0.965556,185,240,486.55,412.8
175927,2022091801,2090,41270.0,Lamarcus Joyner,47,2022-09-18 14:39:16.500000,29.0,NYJ,right,69.76,26.88,3.21,2.79,0.32,186.73,171.91,NaN,2022091801_2090,NYJ,52523,69.94,25.93,4.66,1.85,0.47,145.92,140.75,0.966902,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.855726,0.835333,0.942556,185,240,516.15,444.0
175928,2022091801,2090,41270.0,Lamarcus Joyner,48,2022-09-18 14:39:16.599999,29.0,NYJ,right,69.81,26.57,2.94,2.69,0.31,180.41,170.74,NaN,2022091801_2090,NYJ,52523,70.21,25.58,4.42,2.12,0.44,144.40,142.33,1.067755,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.879566,0.892556,0.977000,185,240,497.65,508.8
175929,2022091801,2090,41270.0,Lamarcus Joyner,49,2022-09-18 14:39:16.700000,29.0,NYJ,right,69.85,26.32,2.47,3.19,0.26,171.08,167.88,NaN,2022091801_2090,NYJ,52523,70.46,25.25,4.12,2.44,0.42,139.33,144.06,1.231666,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.914819,0.964444,0.947444,185,240,590.15,585.6
175930,2022091801,2090,41270.0,Lamarcus Joyner,50,2022-09-18 14:39:16.799999,29.0,NYJ,right,69.90,26.11,1.96,3.58,0.21,163.67,164.53,NaN,2022091801_2090,NYJ,52523,70.68,24.93,3.79,2.79,0.39,149.90,146.43,1.414496,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.950516,0.990444,0.961444,185,240,662.30,669.6
175931,2022091801,2090,41270.0,Lamarcus Joyner,51,2022-09-18 14:39:16.900000,29.0,NYJ,right,69.96,25.94,1.59,3.53,0.18,148.05,160.18,NaN,2022091801_2090,NYJ,52523,70.87,24.61,3.51,2.86,0.38,158.92,148.16,1.611521,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.978075,0.865222,0.880444,185,240,653.05,686.4
175932,2022091801,2090,41270.0,Lamarcus Joyner,52,2022-09-18 14:39:17.000000,29.0,NYJ,right,70.01,25.81,1.22,3.44,0.14,140.99,154.25,NaN,2022091801_2090,NYJ,52523,71.07,24.31,3.35,2.49,0.36,168.53,148.67,1.836736,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.995261,0.852667,0.779333,185,240,636.40,597.6
175933,2022091801,2090,41270.0,Lamarcus Joyner,53,2022-09-18 14:39:17.099999,29.0,NYJ,right,70.06,25.72,0.90,3.14,0.11,128.80,147.35,NaN,2022091801_2090,NYJ,52523,71.24,24.03,3.12,2.35,0.32,175.50,149.94,2.061189,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.998978,0.793889,0.716000,185,240,580.90,564.0
175934,2022091801,2090,41270.0,Lamarcus Joyner,54,2022-09-18 14:39:17.200000,29.0,NYJ,right,70.11,25.66,0.65,2.65,0.07,109.02,139.37,tackle,2022091801_2090,NYJ,52523,71.32,23.81,2.69,2.79,0.24,175.50,156.25,2.210566,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.956915,0.662778,0.786111,185,240,490.25,669.6
175935,2022091801,2090,41270.0,Lamarcus Joyner,55,2022-09-18 14:39:17.299999,29.0,NYJ,right,70.15,25.62,0.53,2.00,0.06,99.65,128.45,NaN,2022091801_2090,NYJ,52523,71.35,23.63,2.13,3.62,0.19,174.74,164.31,2.323812,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.810451,0.680000,0.884111,185,240,370.00,868.8
175936,2022091801,2090,41270.0,Lamarcus Joyner,56,2022-09-18 14:39:17.400000,29.0,NYJ,right,70.19,25.60,0.42,1.44,0.05,99.65,118.17,NaN,2022091801_2090,NYJ,52523,71.32,23.54,1.38,4.56,0.10,159.96,181.64,2.349574,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.446666,0.794222,0.759111,185,240,266.40,1094.4
175937,2022091801,2090,41270.0,Lamarcus Joyner,57,2022-09-18 14:39:17.500000,29.0,NYJ,right,70.23,25.57,0.43,0.92,0.05,102.65,109.28,NaN,2022091801_2090,NYJ,52523,71.33,23.40,1.11,4.55,0.14,142.70,193.83,2.432879,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,0.094977,0.926333,0.431889,185,240,170.20,1092.0
175938,2022091801,2090,41270.0,Lamarcus Joyner,58,2022-09-18 14:39:17.599999,29.0,NYJ,right,70.26,25.57,0.24,0.89,0.03,118.61,98.74,NaN,2022091801_2090,NYJ,52523,71.28,23.32,0.85,4.02,0.09,200.18,219.97,2.470405,41270.0,NaN,NaN,NaN,41270.0,46255.0,42467.0,NaN,NaN,NaN,NaN,-0.518475,0.779222,0.780111,185,240,164.65,964.8

In [567]:
long_play_2[:60]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
178471,2022091801,3061,41270.0,Lamarcus Joyner,1,2022-09-18 15:20:16.299999,29.0,NYJ,left,59.73,36.88,0.17,0.28,0.02,94.96,295.38,NaN,2022091801_3061,NYJ,46104,77.33,31.56,0.00,0.00,0.00,271.41,253.58,18.386473,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.773111,0.801889,185,225,51.80,0.00
178472,2022091801,3061,41270.0,Lamarcus Joyner,2,2022-09-18 15:20:16.400000,29.0,NYJ,left,59.71,36.89,0.21,0.30,0.02,94.96,301.29,NaN,2022091801_3061,NYJ,46104,77.33,31.56,0.00,0.00,0.00,271.41,250.72,18.408512,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.707444,0.770111,185,225,55.50,0.00
178473,2022091801,3061,41270.0,Lamarcus Joyner,3,2022-09-18 15:20:16.500000,29.0,NYJ,left,59.69,36.90,0.27,0.38,0.02,90.41,295.40,NaN,2022091801_3061,NYJ,46104,77.33,31.56,0.00,0.00,0.00,271.41,248.68,18.430551,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.722333,0.747444,185,225,70.30,0.00
178474,2022091801,3061,41270.0,Lamarcus Joyner,4,2022-09-18 15:20:16.599999,29.0,NYJ,left,59.65,36.91,0.40,0.66,0.04,86.66,284.31,NaN,2022091801_3061,NYJ,46104,77.33,31.56,0.00,0.00,0.00,271.41,249.02,18.471732,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.803889,0.751222,185,225,122.10,0.00
178475,2022091801,3061,41270.0,Lamarcus Joyner,5,2022-09-18 15:20:16.700000,29.0,NYJ,left,59.60,36.93,0.62,1.10,0.05,74.90,285.85,NaN,2022091801_3061,NYJ,46104,77.33,31.56,0.00,0.00,0.00,270.07,246.40,18.525383,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.656111,0.737000,185,225,203.50,0.00
178476,2022091801,3061,41270.0,Lamarcus Joyner,6,2022-09-18 15:20:16.799999,29.0,NYJ,left,59.53,36.95,0.84,1.44,0.08,68.68,286.00,ball_snap,2022091801_3061,NYJ,46104,77.32,31.55,0.00,0.00,0.01,269.13,243.29,18.591506,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.585333,0.712889,185,225,266.40,0.00
178477,2022091801,3061,41270.0,Lamarcus Joyner,7,2022-09-18 15:20:16.900000,29.0,NYJ,left,59.43,36.98,1.12,1.73,0.10,64.70,287.33,NaN,2022091801_3061,NYJ,46104,77.31,31.54,0.03,0.63,0.01,267.67,235.22,18.689248,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.614147,-0.526333,0.639444,185,225,320.05,141.75
178478,2022091801,3061,41270.0,Lamarcus Joyner,8,2022-09-18 15:20:17.000000,29.0,NYJ,left,59.30,37.02,1.47,2.14,0.14,64.11,285.72,NaN,2022091801_3061,NYJ,46104,77.31,31.53,0.16,1.43,0.01,266.08,222.19,18.828176,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.445729,-0.537667,0.512333,185,225,395.90,321.75
178479,2022091801,3061,41270.0,Lamarcus Joyner,9,2022-09-18 15:20:17.099999,29.0,NYJ,left,59.14,37.06,1.80,2.45,0.17,57.29,284.73,NaN,2022091801_3061,NYJ,46104,77.28,31.50,0.44,2.35,0.04,265.27,217.59,18.972960,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.388481,-0.472889,0.470222,185,225,453.25,528.75
178480,2022091801,3061,41270.0,Lamarcus Joyner,10,2022-09-18 15:20:17.200000,29.0,NYJ,left,58.95,37.11,2.10,2.42,0.20,57.29,284.22,NaN,2022091801_3061,NYJ,46104,77.24,31.43,0.93,3.51,0.09,265.27,215.07,19.151671,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.355923,-0.478556,0.442222,185,225,447.70,789.75
178481,2022091801,3061,41270.0,Lamarcus Joyner,11,2022-09-18 15:20:17.299999,29.0,NYJ,left,58.73,37.17,2.38,2.17,0.23,56.53,283.78,NaN,2022091801_3061,NYJ,46104,77.17,31.33,1.35,3.79,0.12,265.27,212.67,19.342678,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.323752,-0.475000,0.415556,185,225,401.45,852.75
178482,2022091801,3061,41270.0,Lamarcus Joyner,12,2022-09-18 15:20:17.400000,29.0,NYJ,left,58.48,37.23,2.71,2.09,0.26,57.85,284.13,NaN,2022091801_3061,NYJ,46104,77.08,31.19,1.80,3.66,0.17,263.06,212.90,19.556114,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.321770,-0.485778,0.442667,185,225,386.65,823.50
178483,2022091801,3061,41270.0,Lamarcus Joyner,13,2022-09-18 15:20:17.500000,29.0,NYJ,left,58.20,37.30,3.00,1.97,0.29,56.89,283.31,NaN,2022091801_3061,NYJ,46104,76.94,31.02,2.31,3.68,0.23,260.78,215.90,19.764261,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.384134,-0.484222,0.501333,185,225,364.45,828.00
178484,2022091801,3061,41270.0,Lamarcus Joyner,14,2022-09-18 15:20:17.599999,29.0,NYJ,left,57.89,37.37,3.22,1.66,0.31,58.40,283.40,NaN,2022091801_3061,NYJ,46104,76.74,30.78,2.95,4.06,0.30,260.78,218.34,19.968741,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.421669,-0.500000,0.528444,185,225,307.10,913.50
178485,2022091801,3061,41270.0,Lamarcus Joyner,15,2022-09-18 15:20:17.700000,29.0,NYJ,left,57.57,37.45,3.37,1.23,0.33,57.53,282.96,handoff,2022091801_3061,NYJ,46104,76.54,30.53,3.40,3.90,0.32,260.78,220.06,20.192754,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.455545,-0.495222,0.547556,185,225,227.55,877.50
178486,2022091801,3061,41270.0,Lamarcus Joyner,16,2022-09-18 15:20:17.799999,29.0,NYJ,left,57.24,37.52,3.46,0.76,0.34,55.22,282.41,NaN,2022091801_3061,NYJ,46104,76.30,30.26,3.79,3.48,0.36,258.02,221.88,20.395862,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.491968,-0.475667,0.598444,185,225,140.60,783.00
178487,2022091801,3061,41270.0,Lamarcus Joyner,17,2022-09-18 15:20:17.900000,29.0,NYJ,left,56.90,37.59,3.44,0.42,0.34,52.23,280.75,NaN,2022091801_3061,NYJ,46104,76.02,29.97,4.14,3.12,0.40,254.67,224.39,20.582488,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.553973,-0.460889,0.663556,185,225,77.70,702.00
178488,2022091801,3061,41270.0,Lamarcus Joyner,18,2022-09-18 15:20:18.000000,29.0,NYJ,left,56.58,37.63,3.30,0.96,0.33,52.88,277.70,NaN,2022091801_3061,NYJ,46104,75.71,29.67,4.48,3.22,0.43,256.76,228.68,20.720002,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.655796,-0.502000,0.688000,185,225,177.60,724.50
178489,2022091801,3061,41270.0,Lamarcus Joyner,19,2022-09-18 15:20:18.099999,29.0,NYJ,left,56.27,37.64,3.07,1.86,0.31,56.06,272.56,NaN,2022091801_3061,NYJ,46104,75.35,29.38,4.70,3.17,0.46,258.15,232.66,20.791200,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.767165,-0.594444,0.716778,185,225,344.10,713.25
178490,2022091801,3061,41270.0,Lamarcus Joyner,20,2022-09-18 15:20:18.200000,29.0,NYJ,left,55.99,37.64,2.76,2.48,0.28,60.17,268.13,NaN,2022091801_3061,NYJ,46104,74.96,29.10,4.94,3.35,0.48,258.95,237.36,20.803666,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.859228,-0.689333,0.760111,185,225,458.80,753.75
178491,2022091801,3061,41270.0,Lamarcus Joyner,21,2022-09-18 15:20:18.299999,29.0,NYJ,left,55.74,37.61,2.49,2.99,0.25,63.23,261.47,NaN,2022091801_3061,NYJ,46104,74.52,28.85,5.15,3.37,0.51,262.72,241.85,20.722596,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.941940,-0.797333,0.768111,185,225,553.15,758.25
178492,2022091801,3061,41270.0,Lamarcus Joyner,22,2022-09-18 15:20:18.400000,29.0,NYJ,left,55.51,37.56,2.29,2.89,0.24,64.23,256.03,NaN,2022091801_3061,NYJ,46104,74.03,28.63,5.51,4.10,0.54,260.29,247.95,20.560528,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.990073,-0.868889,0.862889,185,225,534.65,922.50
178493,2022091801,3061,41270.0,Lamarcus Joyner,23,2022-09-18 15:20:18.500000,29.0,NYJ,left,55.39,37.37,2.05,4.70,0.22,68.80,226.04,NaN,2022091801_3061,NYJ,46104,73.50,28.44,5.77,4.03,0.56,262.04,251.98,20.192003,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.899253,-0.747111,0.888222,185,225,869.50,906.75
178494,2022091801,3061,41270.0,Lamarcus Joyner,24,2022-09-18 15:20:18.599999,29.0,NYJ,left,55.28,37.18,2.16,5.15,0.22,74.74,207.78,NaN,2022091801_3061,NYJ,46104,72.93,28.27,6.07,3.76,0.59,265.79,255.18,19.771459,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.676876,-0.478222,0.882111,185,225,952.75,846.00
178495,2022091801,3061,41270.0,Lamarcus Joyner,25,2022-09-18 15:20:18.700000,29.0,NYJ,left,55.23,36.96,2.36,5.49,0.23,80.48,190.91,NaN,2022091801_3061,NYJ,46104,72.32,28.13,6.37,3.43,0.62,268.63,258.40,19.236346,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.382845,-0.227000,0.886333,185,225,1015.65,771.75
178496,2022091801,3061,41270.0,Lamarcus Joyner,26,2022-09-18 15:20:18.799999,29.0,NYJ,left,55.24,36.70,2.72,5.53,0.26,80.48,175.06,NaN,2022091801_3061,NYJ,46104,71.68,28.03,6.64,3.25,0.65,267.21,261.69,18.586084,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.058784,-0.050889,0.938667,185,225,1023.05,731.25
178497,2022091801,3061,41270.0,Lamarcus Joyner,27,2022-09-18 15:20:18.900000,29.0,NYJ,left,55.29,36.42,3.14,6.10,0.29,85.09,165.88,NaN,2022091801_3061,NYJ,46104,71.00,27.96,7.00,3.64,0.68,262.86,265.58,17.843085,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.168489,0.102333,0.969778,185,225,1128.50,819.00
178498,2022091801,3061,41270.0,Lamarcus Joyner,28,2022-09-18 15:20:19.000000,29.0,NYJ,left,55.39,36.09,3.67,5.85,0.34,87.61,158.86,NaN,2022091801_3061,NYJ,46104,70.29,27.92,7.21,3.31,0.71,261.19,268.32,16.992907,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.333149,0.208333,0.920778,185,225,1082.25,744.75
178499,2022091801,3061,41270.0,Lamarcus Joyner,29,2022-09-18 15:20:19.099999,29.0,NYJ,left,55.55,35.73,4.19,4.89,0.40,88.64,154.94,NaN,2022091801_3061,NYJ,46104,69.56,27.92,7.37,3.12,0.73,264.79,271.46,16.039832,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.446510,0.263333,0.925889,185,225,904.65,702.00
178500,2022091801,3061,41270.0,Lamarcus Joyner,30,2022-09-18 15:20:19.200000,29.0,NYJ,left,55.74,35.34,4.50,3.61,0.44,93.68,152.48,NaN,2022091801_3061,NYJ,46104,68.81,27.97,7.54,3.20,0.75,267.21,274.89,15.004726,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.535974,0.346667,0.914667,185,225,667.85,720.00
178501,2022091801,3061,41270.0,Lamarcus Joyner,31,2022-09-18 15:20:19.299999,29.0,NYJ,left,55.96,34.94,4.61,2.36,0.45,96.23,150.28,NaN,2022091801_3061,NYJ,46104,68.05,28.09,7.74,3.71,0.77,270.03,279.30,13.895704,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.629592,0.399444,0.897000,185,225,436.60,834.75
178502,2022091801,3061,41270.0,Lamarcus Joyner,32,2022-09-18 15:20:19.400000,29.0,NYJ,left,56.19,34.54,4.65,1.44,0.46,96.23,148.49,NaN,2022091801_3061,NYJ,46104,67.28,28.24,7.86,3.78,0.78,271.88,282.65,12.754533,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.696664,0.419333,0.880333,185,225,266.40,850.50
178503,2022091801,3061,41270.0,Lamarcus Joyner,33,2022-09-18 15:20:19.500000,29.0,NYJ,left,56.42,34.19,4.33,1.25,0.42,95.30,146.44,NaN,2022091801_3061,NYJ,46104,66.51,28.44,7.96,3.62,0.79,274.76,285.85,11.613380,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.759385,0.431778,0.876778,185,225,231.25,814.50
178504,2022091801,3061,41270.0,Lamarcus Joyner,34,2022-09-18 15:20:19.599999,29.0,NYJ,left,56.64,33.88,3.88,2.27,0.38,94.50,144.53,NaN,2022091801_3061,NYJ,46104,65.75,28.68,8.00,3.35,0.80,275.63,288.57,10.489619,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.809427,0.444111,0.856222,185,225,419.95,753.75
178505,2022091801,3061,41270.0,Lamarcus Joyner,35,2022-09-18 15:20:19.700000,29.0,NYJ,left,56.86,33.57,3.66,2.70,0.38,96.33,143.86,NaN,2022091801_3061,NYJ,46104,64.99,28.95,8.12,2.73,0.81,273.15,290.38,9.351005,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.834078,0.471889,0.808556,185,225,499.50,614.25
178506,2022091801,3061,41270.0,Lamarcus Joyner,36,2022-09-18 15:20:19.799999,29.0,NYJ,left,57.05,33.30,3.21,3.24,0.33,93.34,143.45,NaN,2022091801_3061,NYJ,46104,64.23,29.24,8.15,1.89,0.81,273.15,291.31,8.248394,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.846751,0.443222,0.798222,185,225,599.40,425.25
178507,2022091801,3061,41270.0,Lamarcus Joyner,37,2022-09-18 15:20:19.900000,29.0,NYJ,left,57.22,33.05,2.87,3.24,0.30,91.09,144.83,NaN,2022091801_3061,NYJ,46104,63.46,29.53,8.16,1.17,0.82,275.34,291.47,7.164356,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.835232,0.402889,0.820778,185,225,599.40,263.25
178508,2022091801,3061,41270.0,Lamarcus Joyner,38,2022-09-18 15:20:20.000000,29.0,NYJ,left,57.37,32.82,2.60,3.04,0.28,89.75,146.35,NaN,2022091801_3061,NYJ,46104,62.70,29.82,8.09,1.05,0.81,275.34,290.83,6.116282,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.813913,0.371111,0.827889,185,225,562.40,236.25
178509,2022091801,3061,41270.0,Lamarcus Joyner,39,2022-09-18 15:20:20.099999,29.0,NYJ,left,57.51,32.61,2.31,2.80,0.25,89.07,147.46,NaN,2022091801_3061,NYJ,46104,61.95,30.09,7.95,1.78,0.80,270.11,289.06,5.105291,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.783693,0.351222,0.789444,185,225,518.00,400.50
178510,2022091801,3061,41270.0,Lamarcus Joyner,40,2022-09-18 15:20:20.200000,29.0,NYJ,left,57.62,32.39,2.27,2.12,0.25,87.21,151.90,NaN,2022091801_3061,NYJ,46104,61.20,30.32,7.65,3.25,0.78,261.37,285.96,4.135372,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.695411,0.281222,0.726778,185,225,392.20,731.25
178511,2022091801,3061,41270.0,Lamarcus Joyner,41,2022-09-18 15:20:20.299999,29.0,NYJ,left,57.73,32.11,2.49,1.44,0.29,82.17,157.49,NaN,2022091801_3061,NYJ,46104,60.47,30.52,7.43,3.57,0.76,259.29,283.85,3.167917,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.592857,0.163111,0.727111,185,225,266.40,803.25
178512,2022091801,3061,41270.0,Lamarcus Joyner,42,2022-09-18 15:20:20.400000,29.0,NYJ,left,57.84,31.85,2.65,1.16,0.29,76.33,160.01,NaN,2022091801_3061,NYJ,46104,59.76,30.68,7.15,3.75,0.73,258.62,281.70,2.248399,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.525323,0.070222,0.743556,185,225,214.60,843.75
178513,2022091801,3061,41270.0,Lamarcus Joyner,43,2022-09-18 15:20:20.500000,29.0,NYJ,left,57.95,31.58,2.81,0.89,0.29,64.21,160.01,NaN,2022091801_3061,NYJ,46104,59.07,30.81,6.92,3.69,0.71,258.62,279.58,1.359154,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.493487,-0.064444,0.767111,185,225,164.65,830.25
178514,2022091801,3061,41270.0,Lamarcus Joyner,44,2022-09-18 15:20:20.599999,29.0,NYJ,left,58.05,31.31,2.89,0.83,0.29,49.78,160.30,NaN,2022091801_3061,NYJ,46104,58.40,30.92,6.57,3.54,0.67,248.51,278.81,0.524023,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.477312,-0.228000,0.663333,185,225,153.55,796.50
178515,2022091801,3061,41270.0,Lamarcus Joyner,45,2022-09-18 15:20:20.700000,29.0,NYJ,left,58.14,31.03,2.94,0.89,0.29,42.23,163.48,first_contact,2022091801_3061,NYJ,46104,57.75,31.03,6.40,2.96,0.66,239.17,278.51,0.390000,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,missed tackle,-0.423093,-0.347222,0.562889,185,225,164.65,666.00
178516,2022091801,3061,41270.0,Lamarcus Joyner,46,2022-09-18 15:20:20.799999,29.0,NYJ,left,58.22,30.75,2.96,0.78,0.29,36.49,165.15,NaN,2022091801_3061,NYJ,46104,57.12,31.14,6.24,2.53,0.64,234.90,278.61,1.167090,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.398109,-0.429556,0.514333,185,225,144.30,569.25
178517,2022091801,3061,41270.0,Lamarcus Joyner,47,2022-09-18 15:20:20.900000,29.0,NYJ,left,58.29,30.47,2.83,1.41,0.29,33.60,169.62,NaN,2022091801_3061,NYJ,46104,56.50,31.24,6.13,2.13,0.63,231.00,279.02,1.948589,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.332161,-0.511333,0.466444,185,225,260.85,479.25
178518,2022091801,3061,41270.0,Lamarcus Joyner,48,2022-09-18 15:20:21.000000,29.0,NYJ,left,58.33,30.19,2.67,2.29,0.28,32.84,175.02,NaN,2022091801_3061,NYJ,46104,55.90,31.33,5.94,1.95,0.60,228.07,278.90,2.684120,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.239889,-0.579778,0.435222,185,225,423.65,438.75
178519,2022091801,3061,41270.0,Lamarcus Joyner,49,2022-09-18 15:20:21.099999,29.0,NYJ,left,58.35,29.93,2.47,2.62,0.26,29.05,180.69,NaN,2022091801_3061,NYJ,46104,55.33,31.42,5.75,1.95,0.58,224.71,279.13,3.367566,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.146774,-0.684889,0.395333,185,225,484.70,438.75
178520,2022091801,3061,41270.0,Lamarcus Joyner,50,2022-09-18 15:20:21.200000,29.0,NYJ,left,58.33,29.69,2.19,3.01,0.23,22.22,187.91,NaN,2022091801_3061,NYJ,46104,54.73,31.54,5.85,1.42,0.61,222.35,280.84,4.047530,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.051116,-0.841000,0.350111,185,225,556.85,319.50
178521,2022091801,3061,41270.0,Lamarcus Joyner,51,2022-09-18 15:20:21.299999,29.0,NYJ,left,58.30,29.50,1.95,2.76,0.20,21.56,192.53,NaN,2022091801_3061,NYJ,46104,54.13,31.70,5.92,1.49,0.61,213.29,283.69,4.714753,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.020244,-0.899667,0.217778,185,225,510.60,335.25
178522,2022091801,3061,41270.0,Lamarcus Joyner,52,2022-09-18 15:20:21.400000,29.0,NYJ,left,58.25,29.32,1.68,2.76,0.18,8.49,198.84,NaN,2022091801_3061,NYJ,46104,53.57,31.87,5.86,1.80,0.59,213.29,286.63,5.329625,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.038562,-0.885000,0.185111,185,225,510.60,405.00
178523,2022091801,3061,41270.0,Lamarcus Joyner,53,2022-09-18 15:20:21.500000,29.0,NYJ,left,58.19,29.17,1.51,2.54,0.16,238.89,205.99,NaN,2022091801_3061,NYJ,46104,53.02,32.05,5.74,2.01,0.57,238.38,288.81,5.918049,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.124987,0.634444,0.439667,185,225,469.90,452.25
178524,2022091801,3061,41270.0,Lamarcus Joyner,54,2022-09-18 15:20:21.599999,29.0,NYJ,left,58.13,29.06,1.29,2.50,0.13,221.94,215.73,NaN,2022091801_3061,NYJ,46104,52.50,32.27,5.61,3.02,0.56,295.49,293.33,6.480818,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.214735,0.931000,0.976000,185,225,462.50,679.50
178525,2022091801,3061,41270.0,Lamarcus Joyner,55,2022-09-18 15:20:21.700000,29.0,NYJ,left,58.04,29.01,1.05,2.82,0.10,210.62,237.41,NaN,2022091801_3061,NYJ,46104,52.00,32.50,5.45,3.19,0.55,63.97,296.33,6.975794,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.516234,0.702333,-0.418222,185,225,521.70,717.75
178526,2022091801,3061,41270.0,Lamarcus Joyner,56,2022-09-18 15:20:21.799999,29.0,NYJ,left,57.95,28.97,1.01,2.65,0.10,218.01,253.42,NaN,2022091801_3061,NYJ,46104,51.55,32.74,5.03,3.54,0.52,37.05,298.95,7.427846,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.700536,0.606556,-0.090000,185,225,490.25,796.50
178527,2022091801,3061,41270.0,Lamarcus Joyner,57,2022-09-18 15:20:21.900000,29.0,NYJ,left,57.85,28.96,1.01,2.53,0.10,220.50,270.25,NaN,2022091801_3061,NYJ,46104,51.12,32.99,4.74,3.65,0.49,28.38,302.24,7.844348,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.848141,0.447222,0.042889,185,225,468.05,821.25
178528,2022091801,3061,41270.0,Lamarcus Joyner,58,2022-09-18 15:20:22.000000,29.0,NYJ,left,57.74,28.96,1.07,2.45,0.10,220.50,283.69,NaN,2022091801_3061,NYJ,46104,50.75,33.24,4.32,3.84,0.45,27.15,305.81,8.196249,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.926397,0.297889,0.096222,185,225,453.25,864.00
178529,2022091801,3061,41270.0,Lamarcus Joyner,59,2022-09-18 15:20:22.099999,29.0,NYJ,left,57.64,29.00,1.14,1.96,0.11,216.72,293.21,tackle,2022091801_3061,NYJ,46104,50.44,33.50,3.86,4.12,0.40,27.15,311.24,8.490583,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.950895,0.150111,0.156556,185,225,362.60,927.00
178530,2022091801,3061,41270.0,Lamarcus Joyner,60,2022-09-18 15:20:22.200000,29.0,NYJ,left,57.53,29.06,1.17,1.39,0.12,212.89,299.45,NaN,2022091801_3061,NYJ,46104,50.20,33.75,3.38,4.29,0.35,24.83,317.19,8.702011,41270.0,NaN,46186.0,NaN,41270.0,NaN,NaN,NaN,NaN,NaN,NaN,0.952449,0.038222,0.248444,185,225,257.15,965.25

In [562]:
long_play = tracking_clean_1[(tracking_clean_1['game_play_Id'] == '2022091200_3723') & (tracking_clean_1['nflId'] == 52435)]

In [563]:
long_play[0:60]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
151595,2022091200,3723,52435.0,Jordyn Brooks,1,2022-09-12 23:02:26.200000,56.0,SEA,left,65.56,30.46,7.12,2.25,0.70,24.59,4.55,NaN,2022091200_3723,SEA,53464,68.73,35.48,6.22,2.81,0.63,60.88,342.87,5.937112,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.929262,0.777333,0.133222,245,220,551.25,618.2
151596,2022091200,3723,52435.0,Jordyn Brooks,2,2022-09-12 23:02:26.299999,56.0,SEA,left,65.62,31.18,7.34,1.57,0.72,25.99,4.83,NaN,2022091200_3723,SEA,53464,68.55,36.08,6.17,2.51,0.62,55.36,344.84,5.709194,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.939752,0.764889,0.216444,245,220,384.65,552.2
151597,2022091200,3723,52435.0,Jordyn Brooks,3,2022-09-12 23:02:26.400000,56.0,SEA,left,65.68,31.92,7.50,0.92,0.74,27.26,4.69,NaN,2022091200_3723,SEA,53464,68.40,36.67,6.12,2.24,0.62,50.50,346.72,5.473655,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.951218,0.749222,0.291333,245,220,225.40,492.8
151598,2022091200,3723,52435.0,Jordyn Brooks,4,2022-09-12 23:02:26.500000,56.0,SEA,left,65.74,32.68,7.64,0.54,0.76,28.30,4.79,pass_arrived,2022091200_3723,SEA,53464,68.26,37.27,6.02,1.97,0.61,47.27,347.99,5.236268,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.957319,0.738778,0.341333,245,220,132.30,433.4
151599,2022091200,3723,52435.0,Jordyn Brooks,5,2022-09-12 23:02:26.599999,56.0,SEA,left,65.80,33.45,7.72,0.42,0.77,28.30,4.25,NaN,2022091200_3723,SEA,53464,68.14,37.86,6.02,1.48,0.61,37.18,348.55,4.992364,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.962692,0.732778,0.459667,245,220,102.90,325.6
151600,2022091200,3723,52435.0,Jordyn Brooks,6,2022-09-12 23:02:26.700000,56.0,SEA,left,65.85,34.22,7.74,0.89,0.77,28.30,3.05,pass_outcome_caught,2022091200_3723,SEA,53464,68.01,38.45,5.95,1.20,0.60,24.30,348.39,4.749579,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.967445,0.719444,0.601000,245,220,218.05,264.0
151601,2022091200,3723,52435.0,Jordyn Brooks,7,2022-09-12 23:02:26.799999,56.0,SEA,left,65.87,34.99,7.75,1.27,0.78,25.05,1.71,NaN,2022091200_3723,SEA,53464,67.89,39.03,5.91,1.04,0.60,5.45,347.52,4.516857,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.969488,0.740667,0.800778,245,220,311.15,228.8
151602,2022091200,3723,52435.0,Jordyn Brooks,8,2022-09-12 23:02:26.900000,56.0,SEA,left,65.87,35.79,7.91,1.79,0.79,25.05,359.41,NaN,2022091200_3723,SEA,53464,67.75,39.60,5.82,1.22,0.59,348.97,346.83,4.248588,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.975993,0.715111,0.976222,245,220,438.55,268.4
151603,2022091200,3723,52435.0,Jordyn Brooks,9,2022-09-12 23:02:27.000000,56.0,SEA,left,65.85,36.58,7.96,1.98,0.79,24.46,357.72,NaN,2022091200_3723,SEA,53464,67.59,40.17,5.85,1.42,0.59,329.73,344.36,3.989449,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.972937,0.702889,0.837444,245,220,485.10,312.4
151604,2022091200,3723,52435.0,Jordyn Brooks,10,2022-09-12 23:02:27.099999,56.0,SEA,left,65.81,37.38,8.00,1.96,0.80,22.08,356.20,NaN,2022091200_3723,SEA,53464,67.42,40.73,5.82,1.89,0.59,317.51,341.73,3.716800,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.968279,0.712444,0.730889,245,220,480.20,415.8
151605,2022091200,3723,52435.0,Jordyn Brooks,11,2022-09-12 23:02:27.200000,56.0,SEA,left,65.75,38.18,8.04,1.79,0.80,19.64,354.84,NaN,2022091200_3723,SEA,53464,67.22,41.28,5.84,2.03,0.59,305.27,339.41,3.430875,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.963956,0.724444,0.620667,245,220,438.55,446.6
151606,2022091200,3723,52435.0,Jordyn Brooks,12,2022-09-12 23:02:27.299999,56.0,SEA,left,65.67,38.99,8.10,1.36,0.81,15.88,354.12,NaN,2022091200_3723,SEA,53464,66.99,41.83,5.93,2.08,0.60,294.25,336.67,3.131773,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.953979,0.758222,0.528667,245,220,333.20,457.6
151607,2022091200,3723,52435.0,Jordyn Brooks,13,2022-09-12 23:02:27.400000,56.0,SEA,left,65.58,39.80,8.17,0.75,0.81,21.46,353.97,NaN,2022091200_3723,SEA,53464,66.75,42.37,5.86,1.80,0.59,298.17,335.21,2.823792,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.946874,0.694556,0.588444,245,220,183.75,396.0
151608,2022091200,3723,52435.0,Jordyn Brooks,14,2022-09-12 23:02:27.500000,56.0,SEA,left,65.49,40.61,8.12,1.01,0.81,24.68,353.07,NaN,2022091200_3723,SEA,53464,66.52,42.90,5.74,1.06,0.58,304.61,336.72,2.510976,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.959560,0.648778,0.643222,245,220,247.45,233.2
151609,2022091200,3723,52435.0,Jordyn Brooks,15,2022-09-12 23:02:27.599999,56.0,SEA,left,65.40,41.42,8.18,0.72,0.82,24.68,353.97,NaN,2022091200_3723,SEA,53464,66.32,43.43,5.58,1.64,0.57,311.52,339.24,2.210543,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.967135,0.658778,0.692000,245,220,176.40,360.8
151610,2022091200,3723,52435.0,Jordyn Brooks,16,2022-09-12 23:02:27.700000,56.0,SEA,left,65.33,42.24,8.19,1.25,0.82,26.89,355.70,NaN,2022091200_3723,SEA,53464,66.14,43.94,5.38,2.43,0.55,318.28,342.08,1.883109,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.971879,0.653444,0.735556,245,220,306.25,534.6
151611,2022091200,3723,52435.0,Jordyn Brooks,17,2022-09-12 23:02:27.799999,56.0,SEA,left,65.29,43.06,8.20,1.88,0.82,40.51,357.74,NaN,2022091200_3723,SEA,53464,65.99,44.45,5.20,2.68,0.53,320.19,344.09,1.556310,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.971755,0.524778,0.734444,245,220,460.60,589.6
151612,2022091200,3723,52435.0,Jordyn Brooks,18,2022-09-12 23:02:27.900000,56.0,SEA,left,65.27,43.87,8.07,2.41,0.81,49.73,359.72,first_contact,2022091200_3723,SEA,53464,65.91,44.96,5.03,3.46,0.51,328.58,350.59,1.264002,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.987331,0.444333,0.755444,245,220,590.45,761.2
151613,2022091200,3723,52435.0,Jordyn Brooks,19,2022-09-12 23:02:28.000000,56.0,SEA,left,65.29,44.67,7.90,2.79,0.80,52.95,1.81,NaN,2022091200_3723,SEA,53464,65.89,45.46,4.90,3.90,0.50,334.87,357.64,0.992018,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.997353,0.431778,0.747000,245,220,683.55,858.0
151614,2022091200,3723,52435.0,Jordyn Brooks,20,2022-09-12 23:02:28.099999,56.0,SEA,left,65.32,45.45,7.74,2.81,0.78,55.82,3.22,NaN,2022091200_3723,SEA,53464,65.90,45.95,4.85,3.62,0.50,350.34,2.15,0.765768,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.999826,0.415556,0.868778,245,220,688.45,796.4
151615,2022091200,3723,52435.0,Jordyn Brooks,21,2022-09-12 23:02:28.200000,56.0,SEA,left,65.41,46.19,7.37,3.71,0.74,110.78,6.87,NaN,2022091200_3723,SEA,53464,65.94,46.43,4.75,3.27,0.48,357.64,6.24,0.581808,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.999940,-0.154556,0.904444,245,220,908.95,719.4
151616,2022091200,3723,52435.0,Jordyn Brooks,22,2022-09-12 23:02:28.299999,56.0,SEA,left,65.51,46.90,7.04,3.92,0.71,140.51,9.41,NaN,2022091200_3723,SEA,53464,65.99,46.90,4.64,2.82,0.47,0.35,9.12,0.480000,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.999987,-0.456667,0.902556,245,220,960.40,620.4
151617,2022091200,3723,52435.0,Jordyn Brooks,23,2022-09-12 23:02:28.400000,56.0,SEA,left,65.62,47.56,6.63,3.94,0.68,161.91,10.61,NaN,2022091200_3723,SEA,53464,66.07,47.35,4.49,1.96,0.46,359.27,10.27,0.496588,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.999982,-0.681111,0.877778,245,220,965.30,431.2
151618,2022091200,3723,52435.0,Jordyn Brooks,24,2022-09-12 23:02:28.500000,56.0,SEA,left,65.74,48.19,6.25,3.86,0.64,169.01,11.36,NaN,2022091200_3723,SEA,53464,66.15,47.78,4.35,1.56,0.44,356.22,10.24,0.579828,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.999809,-0.751667,0.844222,245,220,945.70,343.2
151619,2022091200,3723,52435.0,Jordyn Brooks,25,2022-09-12 23:02:28.599999,56.0,SEA,left,65.85,48.77,5.67,4.48,0.58,195.77,11.68,NaN,2022091200_3723,SEA,53464,66.23,48.20,4.13,2.13,0.43,350.98,7.67,0.685055,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.997552,-0.954556,0.814556,245,220,1097.60,468.6
151620,2022091200,3723,52435.0,Jordyn Brooks,26,2022-09-12 23:02:28.700000,56.0,SEA,left,65.95,49.29,5.12,4.83,0.53,204.56,11.66,NaN,2022091200_3723,SEA,53464,66.27,48.60,3.92,2.41,0.40,347.62,4.83,0.760592,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.992903,-0.856667,0.808778,245,220,1183.35,530.2
151621,2022091200,3723,52435.0,Jordyn Brooks,27,2022-09-12 23:02:28.799999,56.0,SEA,left,66.04,49.76,4.51,5.01,0.47,207.76,10.39,NaN,2022091200_3723,SEA,53464,66.28,48.98,3.70,3.18,0.38,340.83,357.11,0.816088,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.973259,-0.807000,0.819111,245,220,1227.45,699.6
151622,2022091200,3723,52435.0,Jordyn Brooks,28,2022-09-12 23:02:28.900000,56.0,SEA,left,66.11,50.17,3.97,4.90,0.42,212.54,8.43,NaN,2022091200_3723,SEA,53464,66.23,49.34,3.49,3.56,0.36,337.81,349.48,0.838630,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.945802,-0.732111,0.870333,245,220,1200.50,783.2
151623,2022091200,3723,52435.0,Jordyn Brooks,29,2022-09-12 23:02:29.000000,56.0,SEA,left,66.14,50.54,3.44,4.84,0.37,218.77,4.45,NaN,2022091200_3723,SEA,53464,66.12,49.66,3.32,3.89,0.34,336.70,339.66,0.880227,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.907851,-0.618667,0.967111,245,220,1185.80,855.8
151624,2022091200,3723,52435.0,Jordyn Brooks,30,2022-09-12 23:02:29.099999,56.0,SEA,left,66.15,50.85,2.94,4.81,0.31,220.23,0.28,NaN,2022091200_3723,SEA,53464,65.95,49.95,3.32,4.25,0.34,332.52,328.03,0.921954,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.845728,-0.556111,0.950111,245,220,1178.45,935.0
151625,2022091200,3723,52435.0,Jordyn Brooks,31,2022-09-12 23:02:29.200000,56.0,SEA,left,66.14,51.12,2.52,4.34,0.27,221.86,355.81,NaN,2022091200_3723,SEA,53464,65.75,50.21,3.27,3.98,0.33,327.92,320.10,0.990051,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.811982,-0.488333,0.913111,245,220,1063.30,875.6
151626,2022091200,3723,52435.0,Jordyn Brooks,32,2022-09-12 23:02:29.299999,56.0,SEA,left,66.12,51.35,2.15,3.92,0.23,219.27,350.36,NaN,2022091200_3723,SEA,53464,65.53,50.43,3.19,3.82,0.31,320.85,312.48,1.092932,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.789298,-0.456556,0.907000,245,220,960.40,840.4
151627,2022091200,3723,52435.0,Jordyn Brooks,33,2022-09-12 23:02:29.400000,56.0,SEA,left,66.07,51.55,1.88,3.38,0.20,215.90,343.86,NaN,2022091200_3723,SEA,53464,65.30,50.61,3.03,3.58,0.30,307.18,304.34,1.215113,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.771403,-0.421778,0.968444,245,220,828.10,787.6
151628,2022091200,3723,52435.0,Jordyn Brooks,34,2022-09-12 23:02:29.500000,56.0,SEA,left,66.02,51.72,1.63,2.86,0.17,216.49,338.41,NaN,2022091200_3723,SEA,53464,65.05,50.76,2.85,3.71,0.29,297.41,296.03,1.364734,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.738691,-0.354667,0.984667,245,220,700.70,816.2
151629,2022091200,3723,52435.0,Jordyn Brooks,35,2022-09-12 23:02:29.599999,56.0,SEA,left,65.96,51.85,1.38,2.48,0.15,215.77,333.81,NaN,2022091200_3723,SEA,53464,64.79,50.87,2.68,4.29,0.28,286.01,287.43,1.526204,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.689872,-0.311556,0.984222,245,220,607.60,943.8
151630,2022091200,3723,52435.0,Jordyn Brooks,36,2022-09-12 23:02:29.700000,56.0,SEA,left,65.90,51.96,1.18,2.17,0.13,214.67,327.29,NaN,2022091200_3723,SEA,53464,64.53,50.92,2.44,4.43,0.26,270.13,275.94,1.720029,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.624561,-0.251333,0.935444,245,220,531.65,974.6
151631,2022091200,3723,52435.0,Jordyn Brooks,37,2022-09-12 23:02:29.799999,56.0,SEA,left,65.84,52.04,0.97,2.09,0.10,215.40,318.74,NaN,2022091200_3723,SEA,53464,64.30,50.92,2.30,4.32,0.24,257.04,263.23,1.904206,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.566262,-0.148222,0.931222,245,220,512.05,950.4
151632,2022091200,3723,52435.0,Jordyn Brooks,38,2022-09-12 23:02:29.900000,56.0,SEA,left,65.76,52.10,0.87,1.95,0.09,215.40,305.42,NaN,2022091200_3723,SEA,53464,64.07,50.88,2.29,3.64,0.23,251.82,255.04,2.084346,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.637693,-0.000222,0.964222,245,220,477.75,800.8
151633,2022091200,3723,52435.0,Jordyn Brooks,39,2022-09-12 23:02:30.000000,56.0,SEA,left,65.68,52.15,0.89,1.61,0.09,215.40,294.46,NaN,2022091200_3723,SEA,53464,63.86,50.81,2.23,3.07,0.22,246.16,247.04,2.260088,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.676619,0.121556,0.990222,245,220,394.45,675.4
151634,2022091200,3723,52435.0,Jordyn Brooks,40,2022-09-12 23:02:30.099999,56.0,SEA,left,65.59,52.18,0.99,1.51,0.10,218.94,283.26,NaN,2022091200_3723,SEA,53464,63.66,50.72,2.17,2.39,0.22,246.16,241.82,2.420021,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.749649,0.285333,0.951778,245,220,369.95,525.8
151635,2022091200,3723,52435.0,Jordyn Brooks,41,2022-09-12 23:02:30.200000,56.0,SEA,left,65.48,52.20,1.20,1.72,0.11,224.43,277.04,NaN,2022091200_3723,SEA,53464,63.47,50.66,2.00,1.15,0.20,246.85,247.95,2.532133,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.873857,0.415444,0.987778,245,220,421.40,253.0
151636,2022091200,3723,52435.0,Jordyn Brooks,42,2022-09-12 23:02:30.299999,56.0,SEA,left,65.35,52.21,1.44,1.75,0.13,226.81,273.96,NaN,2022091200_3723,SEA,53464,63.29,50.62,1.84,1.29,0.19,251.12,254.11,2.602249,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.940585,0.476111,0.966778,245,220,428.75,283.8
151637,2022091200,3723,52435.0,Jordyn Brooks,43,2022-09-12 23:02:30.400000,56.0,SEA,left,65.19,52.22,1.65,1.81,0.15,230.36,270.98,NaN,2022091200_3723,SEA,53464,63.13,50.61,1.61,2.07,0.16,255.89,263.99,2.614517,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.992567,0.548667,0.910000,245,220,443.45,455.4
151638,2022091200,3723,52435.0,Jordyn Brooks,44,2022-09-12 23:02:30.500000,56.0,SEA,left,65.02,52.22,1.89,1.74,0.18,236.02,268.21,NaN,2022091200_3723,SEA,53464,62.99,50.62,1.36,2.89,0.14,94.31,276.54,2.584744,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.989450,0.642333,-0.975222,245,220,426.30,635.8
151639,2022091200,3723,52435.0,Jordyn Brooks,45,2022-09-12 23:02:30.599999,56.0,SEA,left,64.81,52.21,2.14,1.73,0.20,248.13,265.88,NaN,2022091200_3723,SEA,53464,62.87,50.64,1.18,3.05,0.12,89.96,289.31,2.495696,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.917547,0.802778,-0.785000,245,220,423.85,671.0
151640,2022091200,3723,52435.0,Jordyn Brooks,46,2022-09-12 23:02:30.700000,56.0,SEA,left,64.59,52.18,2.36,1.75,0.23,252.34,263.03,NaN,2022091200_3723,SEA,53464,62.76,50.69,1.15,2.94,0.12,77.30,303.25,2.359873,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.763571,0.881222,-0.489444,245,220,428.75,646.8
151641,2022091200,3723,52435.0,Jordyn Brooks,47,2022-09-12 23:02:30.799999,56.0,SEA,left,64.34,52.15,2.56,1.66,0.25,253.19,260.31,NaN,2022091200_3723,SEA,53464,62.67,50.76,1.13,2.41,0.11,77.30,314.68,2.172786,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.582549,0.920889,-0.362444,245,220,406.70,530.2
151642,2022091200,3723,52435.0,Jordyn Brooks,48,2022-09-12 23:02:30.900000,56.0,SEA,left,64.08,52.10,2.75,1.43,0.27,253.19,259.15,NaN,2022091200_3723,SEA,53464,62.59,50.84,1.17,1.56,0.12,88.17,317.78,1.951333,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.520563,0.933778,-0.448778,245,220,350.35,343.2
151643,2022091200,3723,52435.0,Jordyn Brooks,49,2022-09-12 23:02:31.000000,56.0,SEA,left,63.80,52.04,2.86,1.20,0.28,253.19,257.50,NaN,2022091200_3723,SEA,53464,62.50,50.92,1.26,0.77,0.13,94.70,317.52,1.715925,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.499698,0.952111,-0.524222,245,220,294.00,169.4
151644,2022091200,3723,52435.0,Jordyn Brooks,50,2022-09-12 23:02:31.099999,56.0,SEA,left,63.52,51.98,2.89,0.79,0.29,254.77,256.00,NaN,2022091200_3723,SEA,53464,62.39,51.02,1.39,0.48,0.14,103.72,313.68,1.482734,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.534647,0.986333,-0.667111,245,220,193.55,105.6
151645,2022091200,3723,52435.0,Jordyn Brooks,51,2022-09-12 23:02:31.200000,56.0,SEA,left,63.25,51.91,2.80,0.54,0.28,258.75,255.48,NaN,2022091200_3723,SEA,53464,62.28,51.12,1.52,0.73,0.15,106.54,313.19,1.251000,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.534205,0.963667,-0.703889,245,220,132.30,160.6
151646,2022091200,3723,52435.0,Jordyn Brooks,52,2022-09-12 23:02:31.299999,56.0,SEA,left,62.98,51.85,2.75,0.61,0.28,262.88,256.70,NaN,2022091200_3723,SEA,53464,62.17,51.23,1.59,0.73,0.15,106.54,312.03,1.020049,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.568849,0.931333,-0.716778,245,220,149.45,160.6
151647,2022091200,3723,52435.0,Jordyn Brooks,53,2022-09-12 23:02:31.400000,56.0,SEA,left,62.72,51.80,2.60,1.12,0.26,266.46,259.26,NaN,2022091200_3723,SEA,53464,62.04,51.33,1.69,0.81,0.17,114.34,308.77,0.826620,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.649315,0.920000,-0.839667,245,220,274.40,178.2
151648,2022091200,3723,52435.0,Jordyn Brooks,54,2022-09-12 23:02:31.500000,56.0,SEA,left,62.47,51.78,2.48,1.72,0.25,271.90,265.67,NaN,2022091200_3723,SEA,53464,61.91,51.44,1.74,0.59,0.17,125.94,308.60,0.655134,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.732186,0.930778,-0.970444,245,220,421.40,129.8
151649,2022091200,3723,52435.0,Jordyn Brooks,55,2022-09-12 23:02:31.599999,56.0,SEA,left,62.23,51.77,2.37,1.86,0.24,273.17,268.82,NaN,2022091200_3723,SEA,53464,61.75,51.56,1.91,0.69,0.20,137.64,306.84,0.523927,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.787796,0.951667,-0.880000,245,220,455.70,151.8
151650,2022091200,3723,52435.0,Jordyn Brooks,56,2022-09-12 23:02:31.700000,56.0,SEA,left,62.00,51.78,2.26,2.03,0.23,274.99,274.33,NaN,2022091200_3723,SEA,53464,61.57,51.69,2.09,0.82,0.22,143.87,305.77,0.439318,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.853187,0.992667,-0.798889,245,220,497.35,180.4
151651,2022091200,3723,52435.0,Jordyn Brooks,57,2022-09-12 23:02:31.799999,56.0,SEA,left,61.78,51.82,2.15,2.14,0.22,274.99,281.44,NaN,2022091200_3723,SEA,53464,61.39,51.83,2.27,0.88,0.23,155.23,305.21,0.390128,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,missed tackle,0.915171,0.928333,-0.666444,245,220,524.30,193.6
151652,2022091200,3723,52435.0,Jordyn Brooks,58,2022-09-12 23:02:31.900000,56.0,SEA,left,61.62,51.88,1.82,2.64,0.17,278.10,291.00,NaN,2022091200_3723,SEA,53464,61.20,51.96,2.36,0.80,0.23,160.19,304.69,0.427551,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.971590,0.856667,-0.605556,245,220,646.80,176.0
151653,2022091200,3723,52435.0,Jordyn Brooks,59,2022-09-12 23:02:32.000000,56.0,SEA,left,61.48,51.93,1.50,2.74,0.15,286.21,295.93,NaN,2022091200_3723,SEA,53464,61.00,52.09,2.43,0.63,0.24,164.15,304.14,0.505964,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.989751,0.892000,-0.555444,245,220,671.30,138.6
151654,2022091200,3723,52435.0,Jordyn Brooks,60,2022-09-12 23:02:32.099999,56.0,SEA,left,61.37,51.98,1.18,2.86,0.12,289.28,302.69,tackle,2022091200_3723,SEA,53464,60.79,52.23,2.48,0.36,0.25,171.05,303.81,0.631585,52435.0,NaN,46117.0,NaN,52435.0,47941.0,NaN,NaN,NaN,NaN,NaN,0.999809,0.851000,-0.475111,245,220,700.70,79.2

---

### **2.7: Generating Cosine and Alignment Features**

In [698]:
def compute_positional_features(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['cos_avg_05'] = None
    df1['cos_avg_1'] = None
    df1['do_avg_05'] = None
    df1['do_avg_1'] = None
    df1['bc_do_avg_05'] = None
    df1['bc_do_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Print the index if it is a multiple of 1000
        if index % 1000 == 0:
            print(f"Processing index: {index}")

        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 3:
            condition = (df2['event'] == 'fumble') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 4:
            condition = (df2['event'] == 'first_contact') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1,2, nor 3

        matching_indexes = df2.index[condition]

        # Checking if there are no matching indexes
        if len(matching_indexes) == 0:
            print(f"Index {index} has no matching index")
            continue
        # Checking if there is one matching index (What we want)
        elif len(matching_indexes) == 1:
            i = matching_indexes[0]
        # Checking to make sure there is only one matching index
        elif len(matching_indexes) > 1:
            print(f"Index {index} has more than one matching index")

        # Calculate averages and assign to df1
        df1.at[index, 'cos_avg_05'] = df2.loc[i-5:i-1, 'cosine'].mean()
        df1.at[index, 'cos_avg_1'] = df2.loc[i-10:i-6, 'cosine'].mean()
        df1.at[index, 'do_avg_05'] = df2.loc[i-5:i-1, 'do_align'].mean()
        df1.at[index, 'do_avg_1'] = df2.loc[i-10:i-6, 'do_align'].mean()
        df1.at[index, 'bc_do_avg_05'] = df2.loc[i-5:i-1, 'bc_do_align'].mean()
        df1.at[index, 'bc_do_avg_1'] = df2.loc[i-10:i-6, 'bc_do_align'].mean()

    return df1

In [572]:
tackles_1v1_1_all_features = compute_positional_features(tackles_1v1_1_newest, tracking_clean_1)

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000

In [573]:
tackles_1v1_1_all_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9725 non-null   int64
 1   playId            9725 non-null   int64
 2   nflId             9725 non-null   int64
 3   tackle            9725 non-null   int64
 4   assist            9725 non-null   int64
 5   forcedFumble      9725 non-null   int64
 6   pff_missedTackle  9725 non-null   int64
 7   game_play_Id      9725 non-null   object
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   float64
 10  s_avg_1           9725 non-null   float64
 11  bc_s_avg_05       9725 non-null   float64
 12  bc_s_avg_1        9725 non-null   float64
 13  cos_avg_05        9717 non-null   object
 14  cos_avg_1         9721 non-null   object
 15  do_avg_05         9725 non-null   object
 16  do_avg_1          9725 non-null   object
 17  bc_do_avg_05      9725 non-null   object
 18  bc_do_avg_1       9725 non-null   object
dtypes: float64(5), int64(7), object(7)
memory usage: 1.4+ MB

In [576]:
tackles_1v1_1_all_features.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tackles_1v1_1_all_features_rough.csv', index=False)

---

**Editing observations where player has missed tackle and tackle on same play**

In [652]:
# Get the unique 'game_play_Id' and 'nflId' values from double_tackles_original
game_play_ids = double_tackles_original['game_play_Id'].unique()
nfl_ids = double_tackles_original['nflId'].unique()

# Find the rows in tackles_1v1_1_all_features where 'event_type' is 2 and 'game_play_Id' and 'nflId' are in the lists
filtered_rows = tackles_1v1_1_all_features[(tackles_1v1_1_all_features['event_type'] == 2) & 
                                           (tackles_1v1_1_all_features['game_play_Id'].isin(game_play_ids)) & 
                                           (tackles_1v1_1_all_features['nflId'].isin(nfl_ids))]

In [653]:
# Change the 'event_type' values of the rows in filtered_rows to 4.0
filtered_rows['event_type'] = 4.0

# Reflect this change in the tackles_1v1_1_all_features DataFrame
tackles_1v1_1_all_features.loc[filtered_rows.index, 'event_type'] = 4.0

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/281464958.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rows['event_type'] = 4.0

In [680]:
tackles_1v1_1_all_features.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      32
Name: count, dtype: int64

In [679]:
tackles_1v1_1_af_drop5.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      27
Name: count, dtype: int64

In [678]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9712 non-null   object
 14  cos_avg_1         9716 non-null   object
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
dtypes: float64(5), int64(7), object(7)
memory usage: 1.5+ MB

---

**Looking into observations in which cosine features were not developed**

In [688]:
tackles_1v1_1_af_drop5[tackles_1v1_1_af_drop5['cos_avg_05'].isnull()]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1
360,2022091102,1588,52563,1,0,0,0,2022091102_1588,1.0,0.246,0.624,0.000,0.004,NaN,-0.583413,0.428622,0.372556,0.267333,0.295644
2978,2022100902,3966,44813,1,0,0,0,2022100902_3966,1.0,0.000,0.008,0.646,0.398,NaN,-0.672744,-0.225956,-0.054556,0.270889,0.192356
3049,2022100202,1345,43780,1,0,0,0,2022100202_1345,1.0,0.520,1.052,0.000,0.000,NaN,NaN,0.812267,0.9498,-0.634222,-0.592578
3927,2022101602,3745,47795,1,0,0,0,2022101602_3745,1.0,0.294,0.184,0.000,0.000,NaN,NaN,-0.244133,0.363511,-0.268511,-0.015578
4456,2022101300,3894,46077,1,0,0,0,2022101300_3894,1.0,0.312,0.390,0.000,0.000,NaN,NaN,0.110111,0.075333,-0.284733,-0.242511
5374,2022102307,1266,46141,1,0,0,0,2022102307_1266,1.0,0.238,0.548,0.000,0.018,NaN,0.799925,-0.377244,0.056178,-0.059756,0.201178
6390,2022103012,525,43338,1,0,0,0,2022103012_525,1.0,0.194,0.594,0.000,0.000,NaN,NaN,0.302444,0.441378,-0.187622,-0.189867
7765,2022101611,3490,53504,1,0,0,0,2022101611_3490,1.0,0.000,0.008,0.382,1.156,NaN,0.975531,-0.752067,-0.510711,0.387,0.729422

In [689]:
tackles_1v1_1_af_drop5['cos_05_null'] = 0
tackles_1v1_1_af_drop5.loc[tackles_1v1_1_af_drop5['cos_avg_05'].isnull(), 'cos_05_null'] = 1
tackles_1v1_1_af_drop5['cos_avg_05'].fillna(1, inplace=True)

In [690]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9716 non-null   object
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
 19  cos_05_null       9720 non-null   int64
dtypes: float64(6), int64(8), object(6)
memory usage: 1.6+ MB

In [691]:
tackles_1v1_1_af_drop5[tackles_1v1_1_af_drop5['cos_avg_1'].isnull()]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1,cos_05_null
3049,2022100202,1345,43780,1,0,0,0,2022100202_1345,1.0,0.520,1.052,0.0,0.0,1.0,NaN,0.812267,0.9498,-0.634222,-0.592578,1
3927,2022101602,3745,47795,1,0,0,0,2022101602_3745,1.0,0.294,0.184,0.0,0.0,1.0,NaN,-0.244133,0.363511,-0.268511,-0.015578,1
4456,2022101300,3894,46077,1,0,0,0,2022101300_3894,1.0,0.312,0.390,0.0,0.0,1.0,NaN,0.110111,0.075333,-0.284733,-0.242511,1
6390,2022103012,525,43338,1,0,0,0,2022103012_525,1.0,0.194,0.594,0.0,0.0,1.0,NaN,0.302444,0.441378,-0.187622,-0.189867,1

In [692]:
tackles_1v1_1_af_drop5['cos_1_null'] = 0
tackles_1v1_1_af_drop5.loc[tackles_1v1_1_af_drop5['cos_avg_1'].isnull(), 'cos_1_null'] = 1
tackles_1v1_1_af_drop5['cos_avg_1'].fillna(1, inplace=True)

In [693]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
 19  cos_05_null       9720 non-null   int64
 20  cos_1_null        9720 non-null   int64
dtypes: float64(7), int64(9), object(5)
memory usage: 1.6+ MB

In [694]:
tackles_1v1_1_af_drop5.head(50)

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1,cos_05_null,cos_1_null
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0,3.520,4.332,5.694,6.830,0.428826,-0.385109,0.832711,0.645022,0.6916,0.929311,0,0
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0,2.164,1.706,0.298,0.336,0.985862,0.787554,0.287244,0.604378,-0.093511,-0.3034,0,0
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0,2.332,2.274,3.000,2.376,0.995057,0.993806,-0.236111,0.522356,-0.263867,0.533244,0,0
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0,4.274,5.334,4.364,5.720,0.975704,0.987113,0.287667,0.059622,-0.590022,0.458689,0,0
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0,0.854,1.828,1.448,2.134,0.191356,0.563645,0.215956,0.442644,-0.301644,-0.653667,0,0
5,2022090800,1736,44976,1,0,0,0,2022090800_1736,1.0,4.794,4.612,4.398,4.650,0.124383,-0.728045,0.702711,0.598533,0.302244,0.916533,0,0
6,2022090800,2860,46085,1,0,0,0,2022090800_2860,1.0,2.492,3.170,3.390,2.560,0.760174,-0.071476,0.523244,0.854733,0.8828,0.675067,0,0
7,2022090800,3145,52647,1,0,0,0,2022090800_3145,1.0,2.526,1.584,2.538,1.270,0.758493,0.166756,0.320667,0.658911,-0.696578,-0.2928,0,0
8,2022090800,3362,46190,1,0,0,0,2022090800_3362,1.0,4.638,4.050,3.230,4.426,-0.812444,-0.984762,0.184089,0.618489,0.726556,0.890378,0,0
9,2022090800,3383,54488,1,0,0,0,2022090800_3383,1.0,2.106,1.668,2.210,1.382,0.992764,0.930209,0.496,0.318089,-0.221467,-0.341511,0,0
10,2022091100,1260,44851,1,0,0,0,2022091100_1260,1.0,2.902,1.642,2.310,2.932,0.790750,0.484533,0.729844,0.146711,-0.715,-0.167156,0,0
11,2022091100,1672,40017,1,0,0,0,2022091100_1672,1.0,0.960,1.038,2.860,3.044,0.915242,-0.096464,0.6084,0.309867,-0.007578,0.594756,0,0
12,2022091100,2114,53469,1,0,0,0,2022091100_2114,1.0,1.316,2.822,5.148,5.182,-0.407532,-0.678775,-0.418956,0.450756,0.754578,0.831822,0,0
13,2022091100,2353,38607,1,0,0,0,2022091100_2353,1.0,2.890,4.766,3.414,5.610,0.978972,0.853606,-0.870222,-0.3026,0.879044,0.899533,0,0
14,2022091100,2512,53611,1,0,0,0,2022091100_2512,1.0,3.668,5.268,4.740,5.790,0.974194,0.954641,0.480378,0.846778,0.623756,0.738578,0,0
15,2022091100,2640,44862,1,0,0,0,2022091100_2640,1.0,5.946,6.110,6.082,6.304,0.800958,0.564771,0.906733,0.643556,0.976089,0.777178,0,0
16,2022091100,2878,53489,1,0,0,0,2022091100_2878,1.0,0.502,1.124,3.116,4.014,0.693378,0.037677,-0.219422,0.507222,0.453711,0.772089,0,0
17,2022091100,2899,37097,1,0,0,0,2022091100_2899,1.0,1.500,2.290,0.862,2.028,0.929083,0.920706,0.230644,0.333867,0.402289,0.715533,0,0
18,2022091100,3578,52542,1,0,0,0,2022091100_3578,1.0,2.658,4.704,3.582,4.726,-0.977228,-0.849411,0.444867,0.676778,-0.260978,0.279378,0,0
19,2022091100,3647,53469,1,0,0,0,2022091100_3647,1.0,4.054,6.274,4.998,5.004,0.985257,0.905291,0.806444,0.717578,0.221978,0.148511,0,0
20,2022091100,3778,53489,1,0,0,0,2022091100_3778,1.0,3.454,2.788,5.276,6.660,0.810879,0.451718,0.802089,0.677244,0.577,0.711689,0,0
21,2022091101,1744,44903,1,0,0,0,2022091101_1744,1.0,7.414,8.906,7.630,8.338,0.962508,0.961765,0.625822,0.1778,0.309333,0.350378,0,0
22,2022091101,1785,52452,1,0,0,0,2022091101_1785,1.0,3.094,5.422,3.904,4.632,0.510761,0.455433,0.839822,0.926867,0.037067,-0.790178,0,0
23,2022091101,2051,46527,1,0,0,0,2022091101_2051,1.0,0.292,0.648,0.032,0.108,0.941067,0.958682,0.546933,0.461311,-0.555533,-0.3108,0,0
24,2022091101,3221,47799,1,0,0,0,2022091101_3221,1.0,4.474,5.642,3.724,4.846,0.991906,0.923827,-0.300133,0.384267,0.532467,0.746378,0,0
25,2022091102,86,44938,1,0,0,0,2022091102_86,1.0,2.062,3.594,1.536,3.046,0.915136,0.942995,0.443511,-0.024822,0.749467,0.561556,0,0
26,2022091102,531,52571,1,0,0,0,2022091102_531,1.0,3.084,3.980,3.708,3.788,0.993932,0.985377,0.073933,0.329978,-0.858622,-0.669778,0,0
27,2022091102,756,53609,1,0,0,0,2022091102_756,1.0,4.496,6.692,4.660,5.526,0.444850,0.218954,0.838311,0.881578,0.7914,0.754711,0,0
28,2022091102,1493,54504,1,0,0,0,2022091102_1493,1.0,2.088,1.648,1.148,3.446,0.801562,0.356093,0.247644,0.770689,0.666889,0.934822,0,0
29,2022091102,2065,54504,1,0,0,0,2022091102_2065,1.0,2.056,4.714,2.218,4.728,0.957730,0.998227,-0.244222,0.079178,-0.778244,-0.810444,0,0
30,2022091102,2352,46290,1,0,0,0,2022091102_2352,1.0,0.124,0.860,0.352,0.396,-0.733261,0.117233,0.487667,0.899444,0.493644,0.127578,0,0
31,2022091102,2759,54504,1,0,0,0,2022091102_2759,1.0,3.940,5.270,3.716,4.262,0.985712,0.896576,0.387311,0.348133,0.310533,0.553222,0,0
32,2022091102,3783,52571,1,0,0,0,2022091102_3783,1.0,0.250,0.772,1.494,2.672,-0.165863,-0.920424,0.344622,0.718778,0.224733,-0.192333,0,0
33,2022091103,520,46146,1,0,0,0,2022091103_520,1.0,1.510,0.998,1.662,1.076,0.927395,0.842191,0.065378,0.5592,-0.569867,0.693489,0,0
34,2022091103,1037,44842,1,0,0,0,2022091103_1037,1.0,3.026,4.382,1.056,2.782,0.470649,-0.927726,-0.258067,0.799089,-0.444111,0.626778,0,0
35,2022091103,1315,46080,1,0,0,0,2022091103_1315,1.0,2.020,1.500,2.050,3.484,0.844278,-0.569803,-0.729156,-0.550333,-0.3898,0.533333,0,0
36,2022091103,2058,43641,1,0,0,0,2022091103_2058,1.0,1.122,2.826,1.264,0.930,0.954887,0.886119,-0.534778,0.222756,0.601578,0.630333,0,0
37,2022091103,2222,44842,1,0,0,0,2022091103_2222,1.0,3.046,4.372,3.586,5.572,0.965273,0.764376,0.953622,0.7338,0.357933,0.735467,0,0
38,2022091103,2291,46698,1,0,0,0,2022091103_2291,1.0,1.376,1.352,2.654,2.768,0.983289,0.987004,0.571822,0.009222,-0.503156,-0.702978,0,0
39,2022091103,3147,44872,1,0,0,0,2022091103_3147,1.0,4.480,4.094,2.990,3.016,0.946720,0.973165,0.383756,0.716,0.894489,0.475333,0,0
40,2022091103,3251,43325,1,0,0,0,2022091103_3251,1.0,6.884,8.052,5.982,7.932,0.975881,0.961501,0.8828,0.703356,0.260511,0.760222,0,0
41,2022091103,4175,43641,1,0,0,0,2022091103_4175,1.0,3.558,5.690,2.948,3.982,0.986116,0.988007,0.379822,0.484689,0.116889,0.564978,0,0
42,2022091103,4686,43641,1,0,0,0,2022091103_4686,1.0,2.050,3.198,2.664,1.996,0.531635,-0.744747,0.093822,0.852733,-0.365311,-0.039644,0,0
43,2022091103,5096,43350,1,0,0,0,2022091103_5096,1.0,4.590,6.072,4.024,5.432,0.983611,0.913662,0.4574,0.889267,0.753467,0.874533,0,0
44,2022091104,803,52411,1,0,0,0,2022091104_803,1.0,2.802,2.338,4.440,5.360,0.970540,0.752486,0.956267,-0.002467,-0.388533,0.664578,0,0
45,2022091104,910,54653,1,0,0,0,2022091104_910,1.0,0.628,0.256,1.742,0.746,0.961427,0.989477,0.028822,-0.313933,0.8838,0.115067,0,0
46,2022091104,999,47900,1,0,0,0,2022091104_999,1.0,5.044,4.202,5.562,6.430,0.901794,0.890944,0.9594,0.861844,0.825133,0.793,0,0
47,2022091104,2269,44888,1,0,0,0,2022091104_2269,1.0,6.482,8.430,5.112,8.216,0.985115,0.991495,-0.4892,0.858711,-0.123378,0.152822,0,0
48,2022091104,2974,47888,1,0,0,0,2022091104_2974,1.0,3.124,3.642,3.986,5.592,0.969970,0.744959,0.876333,0.710578,0.784622,0.794178,0,0
49,2022091104,3172,46151,1,0,0,0,2022091104_3172,1.0,2.446,1.894,7.652,7.812,-0.954416,-0.117976,0.617889,-0.3648,0.864111,0.791911,0,0

---

### **2.8: Running Feature Generation for Final Time**

**Dropping old generated features**

In [695]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
 19  cos_05_null       9720 non-null   int64
 20  cos_1_null        9720 non-null   int64
dtypes: float64(7), int64(9), object(5)
memory usage: 1.6+ MB

In [696]:
tackles_1v1_1_ffg = tackles_1v1_1_af_drop5.drop(columns=['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1', 'cos_avg_05', 'cos_avg_1', 'do_avg_05', 'do_avg_1', 'bc_do_avg_05', 'bc_do_avg_1', 'cos_05_null', 'cos_1_null'])

In [697]:
tackles_1v1_1_ffg.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
dtypes: float64(1), int64(7), object(1)
memory usage: 759.4+ KB

**Computing Speed Features**

In [700]:
tackles_1v1_1_speed = compute_speed_features(tackles_1v1_1_ffg, tracking_clean_1)

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000

In [701]:
tackles_1v1_1_speed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   object
 10  s_avg_1           9720 non-null   object
 11  bc_s_avg_05       9720 non-null   object
 12  bc_s_avg_1        9720 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.3+ MB

In [702]:
tackles_1v1_1_speed['s_avg_05'] = tackles_1v1_1_speed['s_avg_05'].astype(float)
tackles_1v1_1_speed['s_avg_1'] = tackles_1v1_1_speed['s_avg_1'].astype(float)
tackles_1v1_1_speed['bc_s_avg_05'] = tackles_1v1_1_speed['bc_s_avg_05'].astype(float)
tackles_1v1_1_speed['bc_s_avg_1'] = tackles_1v1_1_speed['bc_s_avg_1'].astype(float)

In [703]:
tackles_1v1_1_speed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
dtypes: float64(5), int64(7), object(1)
memory usage: 1.3+ MB

**Computing Positional Features**

In [704]:
tackles_1v1_1_af = compute_positional_features(tackles_1v1_1_speed, tracking_clean_1)

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000

In [705]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9712 non-null   object
 14  cos_avg_1         9716 non-null   object
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
dtypes: float64(5), int64(7), object(7)
memory usage: 1.7+ MB

In [706]:
tackles_1v1_1_af[tackles_1v1_1_af['cos_avg_05'].isnull()]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1
360,2022091102,1588,52563,1,0,0,0,2022091102_1588,1.0,0.246,0.624,0.000,0.004,NaN,-0.583413,0.428622,0.372556,0.267333,0.295644
2978,2022100902,3966,44813,1,0,0,0,2022100902_3966,1.0,0.000,0.008,0.646,0.398,NaN,-0.672744,-0.225956,-0.054556,0.270889,0.192356
3049,2022100202,1345,43780,1,0,0,0,2022100202_1345,1.0,0.520,1.052,0.000,0.000,NaN,NaN,0.812267,0.9498,-0.634222,-0.592578
3927,2022101602,3745,47795,1,0,0,0,2022101602_3745,1.0,0.294,0.184,0.000,0.000,NaN,NaN,-0.244133,0.363511,-0.268511,-0.015578
4456,2022101300,3894,46077,1,0,0,0,2022101300_3894,1.0,0.312,0.390,0.000,0.000,NaN,NaN,0.110111,0.075333,-0.284733,-0.242511
5374,2022102307,1266,46141,1,0,0,0,2022102307_1266,1.0,0.238,0.548,0.000,0.018,NaN,0.799925,-0.377244,0.056178,-0.059756,0.201178
6390,2022103012,525,43338,1,0,0,0,2022103012_525,1.0,0.194,0.594,0.000,0.000,NaN,NaN,0.302444,0.441378,-0.187622,-0.189867
7765,2022101611,3490,53504,1,0,0,0,2022101611_3490,1.0,0.000,0.008,0.382,1.156,NaN,0.975531,-0.752067,-0.510711,0.387,0.729422

In [707]:
tackles_1v1_1_af['cos_05_null'] = 0
tackles_1v1_1_af.loc[tackles_1v1_1_af['cos_avg_05'].isnull(), 'cos_05_null'] = 1
tackles_1v1_1_af['cos_avg_05'].fillna(0, inplace=True)

In [708]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9716 non-null   object
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
 19  cos_05_null       9720 non-null   int64
dtypes: float64(6), int64(8), object(6)
memory usage: 1.8+ MB

In [709]:
tackles_1v1_1_af[tackles_1v1_1_af['cos_avg_1'].isnull()]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1,cos_05_null
3049,2022100202,1345,43780,1,0,0,0,2022100202_1345,1.0,0.520,1.052,0.0,0.0,0.0,NaN,0.812267,0.9498,-0.634222,-0.592578,1
3927,2022101602,3745,47795,1,0,0,0,2022101602_3745,1.0,0.294,0.184,0.0,0.0,0.0,NaN,-0.244133,0.363511,-0.268511,-0.015578,1
4456,2022101300,3894,46077,1,0,0,0,2022101300_3894,1.0,0.312,0.390,0.0,0.0,0.0,NaN,0.110111,0.075333,-0.284733,-0.242511,1
6390,2022103012,525,43338,1,0,0,0,2022103012_525,1.0,0.194,0.594,0.0,0.0,0.0,NaN,0.302444,0.441378,-0.187622,-0.189867,1

In [710]:
tackles_1v1_1_af['cos_1_null'] = 0
tackles_1v1_1_af.loc[tackles_1v1_1_af['cos_avg_1'].isnull(), 'cos_1_null'] = 1
tackles_1v1_1_af['cos_avg_1'].fillna(0, inplace=True)

In [711]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   object
 16  do_avg_1          9720 non-null   object
 17  bc_do_avg_05      9720 non-null   object
 18  bc_do_avg_1       9720 non-null   object
 19  cos_05_null       9720 non-null   int64
 20  cos_1_null        9720 non-null   int64
dtypes: float64(7), int64(9), object(5)
memory usage: 1.9+ MB

In [712]:
tackles_1v1_1_af['do_avg_05'] = tackles_1v1_1_af['do_avg_05'].astype(float)
tackles_1v1_1_af['do_avg_1'] = tackles_1v1_1_af['do_avg_1'].astype(float)
tackles_1v1_1_af['bc_do_avg_05'] = tackles_1v1_1_af['bc_do_avg_05'].astype(float)
tackles_1v1_1_af['bc_do_avg_1'] = tackles_1v1_1_af['bc_do_avg_1'].astype(float)

In [713]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   float64
 16  do_avg_1          9720 non-null   float64
 17  bc_do_avg_05      9720 non-null   float64
 18  bc_do_avg_1       9720 non-null   float64
 19  cos_05_null       9720 non-null   int64
 20  cos_1_null        9720 non-null   int64
dtypes: float64(11), int64(9), object(1)
memory usage: 1.9+ MB

---
**Finding what plays had tackle and assist**

In [714]:
tackles_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            17426 non-null  int64
 1   playId            17426 non-null  int64
 2   nflId             17426 non-null  int64
 3   tackle            17426 non-null  int64
 4   assist            17426 non-null  int64
 5   forcedFumble      17426 non-null  int64
 6   pff_missedTackle  17426 non-null  int64
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB

In [675]:
###Adding 'game_play_Id' column to tackles_original
tackles_original = game_play_Id(tackles_original)

In [676]:
tackles_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            17426 non-null  int64
 1   playId            17426 non-null  int64
 2   nflId             17426 non-null  int64
 3   tackle            17426 non-null  int64
 4   assist            17426 non-null  int64
 5   forcedFumble      17426 non-null  int64
 6   pff_missedTackle  17426 non-null  int64
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB

In [716]:
tackles_1v1_1_af.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      27
Name: count, dtype: int64

In [715]:
tackles_1v1_1_af.tackle.value_counts()

tackle
1    7834
0    1886
Name: count, dtype: int64

In [717]:
# Create an empty list to store the indices
assist_indices = []

# Iterate over the rows in tackles_1v1_1_af_drop5 where 'tackle' is 1
for index, row in tackles_1v1_1_af[tackles_1v1_1_af['tackle'] == 1].iterrows():
    # Find the rows in tackles_original where 'assist' is 1 and 'game_play_Id' is equal to the current row's value
    matching_rows = tackles_original[(tackles_original['assist'] == 1) & 
                                     (tackles_original['game_play_Id'] == row['game_play_Id'])]
    
    if len(matching_rows) > 1:
        print(f"Index {index} has more than one matching index")
    # If there are any matching rows, add the index to the list
    if not matching_rows.empty:
        assist_indices.append(index)

# Print the indices and the count
print(assist_indices)
print(len(assist_indices))

[4, 10, 17, 45, 47, 56, 61, 70, 71, 80, 88, 89, 91, 92, 96, 97, 104, 116, 119, 131, 140, 141, 156, 162, 170, 173, 174, 179, 180, 181, 183, 189, 202, 206, 212, 213, 220, 230, 234, 236, 247, 248, 265, 268, 269, 273, 276, 278, 289, 294, 301, 314, 317, 332, 342, 346, 359, 360, 363, 370, 374, 380, 390, 399, 402, 403, 409, 411, 428, 429, 431, 434, 438, 443, 460, 462, 476, 483, 488, 490, 492, 498, 511, 527, 533, 541, 548, 551, 554, 580, 581, 582, 584, 585, 586, 589, 592, 593, 596, 597, 607, 609, 610, 633, 636, 637, 639, 651, 655, 658, 659, 660, 665, 673, 680, 686, 688, 690, 691, 698, 703, 705, 707, 710, 721, 742, 747, 757, 761, 764, 772, 773, 782, 801, 808, 811, 817, 829, 830, 832, 833, 847, 876, 877, 880, 886, 889, 890, 892, 895, 898, 903, 923, 925, 935, 956, 957, 961, 965, 970, 971, 975, 978, 985, 1006, 1013, 1015, 1017, 1020, 1024, 1034, 1046, 1048, 1050, 1056, 1064, 1067, 1076, 1078, 1084, 1086, 1089, 1090, 1097, 1098, 1104, 1111, 1116, 1118, 1128, 1130, 1136, 1161, 1170, 1178, 1188, 1192, 1203, 1204, 1211, 1212, 1213, 1223, 1224, 1225, 1228, 1232, 1237, 1240, 1243, 1244, 1249, 1253, 1255, 1270, 1271, 1273, 1276, 1278, 1279, 1280, 1287, 1296, 1298, 1304, 1305, 1306, 1308, 1315, 1317, 1320, 1325, 1329, 1331, 1335, 1342, 1351, 1353, 1374, 1380, 1381, 1383, 1386, 1390, 1393, 1407, 1415, 1431, 1438, 1440, 1442, 1451, 1454, 1462, 1464, 1465, 1469, 1477, 1481, 1490, 1495, 1498, 1499, 1500, 1506, 1511, 1513, 1525, 1530, 1532, 1543, 1546, 1549, 1561, 1563, 1571, 1572, 1576, 1582, 1583, 1585, 1587, 1599, 1602, 1604, 1605, 1607, 1614, 1616, 1618, 1619, 1622, 1623, 1625, 1629, 1635, 1638, 1645, 1647, 1652, 1654, 1655, 1667, 1675, 1676, 1677, 1698, 1704, 1709, 1715, 1718, 1725, 1729, 1730, 1731, 1732, 1736, 1741, 1750, 1751, 1752, 1754, 1762, 1768, 1771, 1775, 1776, 1779, 1782, 1789, 1798, 1802, 1807, 1816, 1817, 1818, 1820, 1821, 1834, 1849, 1852, 1859, 1861, 1864, 1865, 1869, 1878, 1884, 1895, 1896, 1904, 1909, 1917, 1918, 1920, 1923, 1928, 1930, 1934, 1935, 1947, 1951, 1954, 1967, 1968, 1973, 1985, 1991, 1993, 1994, 2000, 2001, 2003, 2004, 2008, 2014, 2016, 2017, 2018, 2023, 2025, 2026, 2030, 2034, 2041, 2051, 2058, 2061, 2080, 2087, 2098, 2110, 2112, 2124, 2127, 2133, 2135, 2136, 2138, 2143, 2153, 2158, 2160, 2168, 2172, 2178, 2181, 2182, 2189, 2204, 2208, 2219, 2221, 2222, 2237, 2242, 2249, 2251, 2252, 2256, 2269, 2270, 2275, 2276, 2279, 2280, 2291, 2292, 2293, 2295, 2296, 2297, 2301, 2302, 2304, 2306, 2313, 2318, 2323, 2324, 2339, 2344, 2368, 2371, 2380, 2381, 2382, 2387, 2403, 2411, 2413, 2414, 2425, 2429, 2433, 2439, 2441, 2442, 2449, 2465, 2470, 2474, 2493, 2496, 2497, 2500, 2502, 2508, 2511, 2515, 2527, 2543, 2550, 2554, 2556, 2560, 2567, 2572, 2576, 2595, 2596, 2597, 2618, 2629, 2634, 2635, 2638, 2640, 2652, 2664, 2667, 2671, 2674, 2679, 2689, 2701, 2733, 2736, 2742, 2750, 2758, 2759, 2765, 2766, 2768, 2770, 2771, 2775, 2776, 2778, 2779, 2780, 2783, 2786, 2787, 2789, 2791, 2793, 2794, 2796, 2800, 2805, 2832, 2843, 2844, 2864, 2882, 2890, 2896, 2897, 2902, 2905, 2908, 2916, 2920, 2924, 2928, 2932, 2933, 2934, 2939, 2952, 2964, 2965, 2967, 2973, 2975, 2976, 2977, 2984, 2985, 2989, 2990, 2994, 2995, 2997, 3001, 3002, 3009, 3015, 3018, 3022, 3024, 3027, 3030, 3037, 3045, 3053, 3067, 3070, 3071, 3080, 3083, 3086, 3088, 3098, 3108, 3112, 3129, 3140, 3156, 3167, 3168, 3169, 3181, 3192, 3194, 3203, 3210, 3211, 3214, 3223, 3227, 3247, 3256, 3260, 3265, 3267, 3274, 3278, 3296, 3298, 3300, 3305, 3308, 3310, 3335, 3355, 3362, 3365, 3370, 3376, 3378, 3379, 3383, 3390, 3399, 3403, 3420, 3422, 3423, 3426, 3428, 3429, 3431, 3432, 3434, 3439, 3440, 3442, 3443, 3447, 3451, 3453, 3457, 3466, 3470, 3475, 3495, 3498, 3501, 3512, 3513, 3514, 3516, 3519, 3521, 3530, 3535, 3537, 3539, 3540, 3541, 3545, 3546, 3563, 3564, 3575, 3581, 3582, 3584, 3588, 3589, 3599, 3604, 3605, 3612, 3618, 3619, 3621, 3631, 3642, 3643, 3647, 3655, 3663, 3683, 3684, 3685, 3692, 3694, 3695, 3705, 3709, 3712, 3713, 3722, 3734, 3736, 3748, 3759, 3762, 3764, 3779, 3783, 3786, 3788, 3797, 3799, 3815, 3817, 3818, 3822, 3828, 3829, 3832, 3835, 3839, 3842, 3844, 3863, 3865, 3866, 3871, 3875, 3877, 3883, 3888, 3889, 3903, 3906, 3908, 3917, 3922, 3923, 3927, 3930, 3931, 3932, 3934, 3935, 3942, 3962, 3964, 3969, 3982, 3995, 3996, 3999, 4000, 4003, 4004, 4010, 4014, 4033, 4036, 4056, 4067, 4078, 4083, 4084, 4085, 4090, 4091, 4096, 4097, 4106, 4110, 4124, 4139, 4143, 4151, 4153, 4160, 4172, 4173, 4177, 4178, 4181, 4184, 4187, 4200, 4210, 4212, 4213, 4216, 4219, 4227, 4229, 4238, 4252, 4255, 4256, 4257, 4258, 4261, 4262, 4269, 4278, 4283, 4284, 4285, 4300, 4302, 4310, 4311, 4313, 4316, 4320, 4324, 4330, 4334, 4339, 4343, 4344, 4351, 4357, 4358, 4360, 4373, 4376, 4377, 4381, 4385, 4388, 4390, 4392, 4401, 4408, 4424, 4438, 4441, 4462, 4464, 4466, 4476, 4480, 4487, 4492, 4499, 4507, 4508, 4511, 4517, 4518, 4530, 4534, 4536, 4543, 4551, 4556, 4566, 4569, 4571, 4577, 4592, 4599, 4604, 4607, 4621, 4622, 4624, 4627, 4632, 4633, 4638, 4640, 4648, 4653, 4656, 4657, 4671, 4672, 4675, 4676, 4682, 4683, 4684, 4691, 4699, 4721, 4727, 4728, 4733, 4755, 4758, 4759, 4760, 4762, 4781, 4782, 4786, 4787, 4789, 4796, 4800, 4801, 4819, 4821, 4822, 4829, 4833, 4845, 4847, 4848, 4853, 4859, 4864, 4866, 4871, 4881, 4884, 4900, 4902, 4905, 4908, 4909, 4910, 4911, 4913, 4939, 4947, 4952, 4954, 4958, 4959, 4981, 4987, 5005, 5006, 5024, 5027, 5029, 5030, 5036, 5039, 5058, 5064, 5075, 5077, 5083, 5085, 5094, 5109, 5111, 5124, 5136, 5137, 5138, 5140, 5142, 5151, 5162, 5164, 5166, 5167, 5171, 5172, 5173, 5176, 5180, 5183, 5186, 5190, 5191, 5193, 5195, 5200, 5201, 5204, 5208, 5210, 5214, 5218, 5221, 5224, 5231, 5238, 5255, 5274, 5275, 5278, 5287, 5289, 5290, 5291, 5295, 5302, 5306, 5308, 5311, 5312, 5313, 5314, 5319, 5324, 5325, 5327, 5336, 5339, 5343, 5344, 5350, 5353, 5359, 5361, 5368, 5396, 5404, 5406, 5415, 5430, 5435, 5449, 5468, 5469, 5470, 5472, 5490, 5492, 5493, 5495, 5500, 5502, 5513, 5520, 5521, 5524, 5525, 5534, 5540, 5552, 5559, 5572, 5580, 5583, 5594, 5602, 5603, 5605, 5620, 5628, 5629, 5639, 5663, 5664, 5675, 5680, 5681, 5686, 5691, 5696, 5702, 5703, 5707, 5711, 5718, 5719, 5722, 5732, 5746, 5748, 5765, 5767, 5768, 5769, 5775, 5776, 5783, 5786, 5788, 5791, 5794, 5802, 5804, 5806, 5811, 5842, 5844, 5850, 5859, 5860, 5867, 5876, 5884, 5885, 5887, 5889, 5915, 5922, 5923, 5931, 5933, 5936, 5939, 5943, 5961, 5964, 5968, 5982, 5985, 5989, 5992, 5997, 6001, 6003, 6005, 6020, 6022, 6024, 6028, 6029, 6035, 6041, 6056, 6061, 6064, 6071, 6081, 6084, 6086, 6089, 6093, 6095, 6101, 6108, 6110, 6113, 6115, 6118, 6121, 6124, 6125, 6130, 6137, 6144, 6153, 6155, 6159, 6176, 6178, 6185, 6187, 6189, 6191, 6192, 6203, 6206, 6207, 6208, 6209, 6216, 6218, 6219, 6222, 6223, 6240, 6243, 6247, 6251, 6252, 6269, 6270, 6276, 6287, 6291, 6293, 6300, 6311, 6312, 6313, 6326, 6328, 6333, 6349, 6355, 6361, 6366, 6372, 6379, 6390, 6394, 6397, 6400, 6401, 6403, 6408, 6409, 6410, 6413, 6415, 6416, 6417, 6430, 6433, 6434, 6445, 6449, 6451, 6452, 6468, 6474, 6486, 6490, 6494, 6501, 6505, 6516, 6525, 6528, 6530, 6532, 6534, 6545, 6552, 6557, 6558, 6561, 6568, 6573, 6574, 6588, 6589, 6593, 6594, 6596, 6604, 6612, 6617, 6618, 6619, 6624, 6630, 6633, 6636, 6652, 6655, 6656, 6658, 6662, 6663, 6670, 6675, 6694, 6697, 6700, 6711, 6725, 6732, 6734, 6738, 6747, 6752, 6756, 6765, 6769, 6774, 6777, 6780, 6781, 6790, 6792, 6793, 6796, 6798, 6799, 6800, 6803, 6810, 6811, 6816, 6817, 6823, 6825, 6827, 6829, 6830, 6843, 6863, 6868, 6869, 6874, 6879, 6896, 6899, 6901, 6903, 6907, 6908, 6917, 6919, 6920, 6922, 6925, 6932, 6933, 6936, 6943, 6945, 6948, 6954, 6955, 6956, 6968, 6971, 6972, 6973, 6981, 6988, 6992, 6997, 7041, 7042, 7047, 7056, 7058, 7060, 7063, 7071, 7074, 7080, 7091, 7098, 7108, 7110, 7122, 7124, 7125, 7131, 7132, 7134, 7141, 7147, 7148, 7150, 7152, 7154, 7158, 7161, 7166, 7169, 7180, 7181, 7182, 7185, 7190, 7220, 7234, 7236, 7244, 7247, 7259, 7261, 7292, 7293, 7294, 7295, 7298, 7303, 7304, 7308, 7311, 7318, 7320, 7321, 7322, 7323, 7324, 7354, 7362, 7379, 7382, 7388, 7396, 7405, 7413, 7418, 7423, 7425, 7430, 7431, 7432, 7435, 7438, 7446, 7447, 7457, 7458, 7464, 7467, 7474, 7477, 7479, 7489, 7491, 7498, 7500, 7515, 7521, 7525, 7526, 7530, 7532, 7535, 7549, 7550, 7552, 7569, 7571, 7575, 7583, 7585, 7591, 7595, 7604, 7608, 7609, 7622, 7624, 7636, 7638, 7640, 7641, 7643, 7646, 7655, 7662, 7676, 7688, 7690, 7732, 7744, 7757, 7771, 7772, 7778, 7780, 7799, 7802, 7820, 7821, 9702, 9703, 9708, 9710, 9713, 9716, 9717, 9718, 9724]
1440

In [718]:
import pickle

# Specify the file path to save the .pkl file
file_path = 'assist_indices.pkl'

# Save assist_indices as a .pkl file
with open(folder_path + file_path, 'wb') as f:
    pickle.dump(assist_indices, f)

---

### **2.9: Confirming Event Type 4 Worked Correctly**

In [719]:
tackles_1v1_1_af[tackles_1v1_1_af['event_type'] == 4]

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1,cos_05_null,cos_1_null
357,2022091102,189,52571,0,0,0,1,2022091102_189,4.0,6.090,6.072,8.956,8.974,0.960431,0.981887,-0.527756,-0.429356,0.754867,0.798378,0,0
542,2022091105,2742,53450,0,0,0,1,2022091105_2742,4.0,8.740,7.632,8.682,8.312,0.874701,0.892540,0.624800,0.599978,0.636400,0.462533,0,0
734,2022091110,750,52546,0,0,0,1,2022091110_750,4.0,6.672,6.850,7.176,6.640,0.685470,0.705134,0.728000,0.662978,0.541644,0.802333,0,0
958,2022091200,3723,52435,0,0,0,1,2022091200_3723,4.0,8.172,8.002,5.552,5.852,0.963441,0.967029,0.636067,0.722622,0.678733,0.738778,0,0
981,2022091801,3061,41270,0,0,0,1,2022091801_3061,4.0,2.622,2.930,7.144,8.094,-0.556878,-0.822733,0.044422,0.408067,0.725578,0.808978,0,0
1129,2022091801,2090,41270,0,0,0,1,2022091801_2090,4.0,1.770,2.240,5.334,4.070,0.833364,-0.805294,0.493000,-0.116244,0.795933,0.741089,0,0
1937,2022092507,3091,47899,0,0,0,1,2022092507_3091,4.0,4.826,6.444,4.904,5.588,0.957852,0.940188,0.069867,0.165178,0.905933,0.848711,0,0
2232,2022091812,2620,47804,0,0,0,1,2022091812_2620,4.0,0.672,2.240,4.732,4.778,0.269382,0.577129,-0.266933,-0.386956,0.899378,0.834978,0,0
2294,2022092503,4086,38548,0,0,0,1,2022092503_4086,4.0,6.756,5.780,8.438,7.590,0.811958,0.643841,0.952933,0.927644,0.983867,0.911933,0,0
2422,2022100206,2702,47913,0,0,0,1,2022100206_2702,4.0,5.540,6.210,5.278,6.284,-0.450668,0.391746,0.843644,0.801089,0.945089,0.881844,0,0
3068,2022100205,3163,47871,0,0,0,1,2022100205_3163,4.0,5.062,5.662,7.332,7.572,0.718429,0.867566,0.374489,0.787311,0.671200,0.830600,0,0
3145,2022100902,1025,54543,0,0,0,1,2022100902_1025,4.0,2.456,2.350,4.796,4.542,0.341205,-0.247444,0.589156,0.895778,0.846000,0.932689,0,0
3413,2022100204,426,53592,0,0,0,1,2022100204_426,4.0,3.036,3.572,3.918,4.762,0.287107,0.267326,0.903800,0.859200,0.893756,0.759978,0,0
3701,2022100906,3322,54574,0,0,0,1,2022100906_3322,4.0,9.552,9.756,8.658,8.820,0.925733,0.943702,0.846400,0.954222,0.926778,0.927000,0,0
3862,2022101700,2126,46264,0,0,0,1,2022101700_2126,4.0,1.492,1.510,5.474,5.816,0.719982,0.935288,-0.339978,-0.753356,-0.915244,-0.983422,0,0
3879,2022100911,2608,39984,0,0,0,1,2022100911_2608,4.0,4.876,4.506,6.762,6.806,0.376254,0.011781,0.602844,0.416244,0.557289,-0.042289,0,0
4876,2022102300,2890,52627,0,0,0,1,2022102300_2890,4.0,3.292,3.406,7.352,6.790,0.457648,-0.170959,0.084822,0.532800,0.820556,0.811444,0,0
5078,2022102311,1564,38548,0,0,0,1,2022102311_1564,4.0,5.922,5.208,7.182,8.120,0.693030,0.617158,0.553333,0.644444,0.794800,0.797911,0,0
5677,2022103009,2993,43358,0,0,0,1,2022103009_2993,4.0,7.518,7.236,7.522,6.506,0.909450,0.947397,0.810222,0.913556,0.512333,0.647600,0,0
5749,2022110600,2782,52594,0,0,0,1,2022110600_2782,4.0,7.694,6.336,8.364,7.866,0.869883,0.763661,0.685044,0.655378,0.781044,0.856044,0,0
6518,2022110601,3266,43503,0,0,0,1,2022110601_3266,4.0,3.046,4.798,5.754,5.882,-0.649976,0.123228,0.698067,0.594200,0.696444,0.662089,0,0
6527,2022110603,441,54653,0,0,0,1,2022110603_441,4.0,4.976,5.182,4.816,4.278,0.536225,0.587742,0.584733,0.560044,0.657622,0.738533,0,0
6783,2022102308,881,53509,0,0,0,1,2022102308_881,4.0,3.580,4.580,3.880,4.588,0.195859,0.457263,0.369000,0.597578,0.819600,0.489844,0,0
6882,2022103004,726,46669,0,0,0,1,2022103004_726,4.0,5.656,5.014,7.730,7.344,0.806161,0.448422,0.738511,0.624333,0.654200,0.692711,0,0
7168,2022100906,2763,52435,0,0,0,1,2022100906_2763,4.0,6.980,6.498,7.306,6.954,0.833290,0.640687,0.392511,0.457067,0.630644,0.789244,0,0
7584,2022110605,1030,53450,0,0,0,1,2022110605_1030,4.0,2.898,1.808,3.788,1.948,-0.650773,-0.705403,0.266267,0.428600,0.921867,0.791178,0,0
7623,2022110610,2875,47971,0,0,0,1,2022110610_2875,4.0,4.908,5.890,1.822,2.704,-0.708980,0.596081,0.696511,0.734511,0.774533,0.044133,0,0

In [721]:
tracking_clean_1[(tracking_clean_1['game_play_Id'] == '2022091105_2742') & (tracking_clean_1['nflId'] == 53450)]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
67806,2022091105,2742,53450.0,Kwity Paye,1,2022-09-11 15:11:41.000000,51.0,IND,right,24.69,19.21,5.50,1.96,0.60,195.33,201.68,NaN,2022091105_2742,IND,43496,18.96,17.37,7.15,3.55,0.71,125.17,197.35,6.018181,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.997146,0.929444,0.198000,265,235,519.40,834.25
67807,2022091105,2742,53450.0,Kwity Paye,2,2022-09-11 15:11:41.099999,51.0,IND,right,24.49,18.66,5.71,1.61,0.59,182.84,199.69,NaN,2022091105_2742,IND,43496,18.80,16.66,7.25,4.07,0.73,131.65,192.23,6.031260,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.991536,0.812778,0.326889,265,235,426.65,956.45
67808,2022091105,2742,53450.0,Kwity Paye,3,2022-09-11 15:11:41.200000,51.0,IND,right,24.29,18.08,5.92,1.18,0.61,181.32,198.37,NaN,2022091105_2742,IND,43496,18.67,15.94,7.37,4.22,0.73,127.33,188.17,6.013651,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.984196,0.810556,0.324000,265,235,312.70,991.70
67809,2022091105,2742,53450.0,Kwity Paye,4,2022-09-11 15:11:41.299999,51.0,IND,right,24.09,17.43,6.32,0.98,0.68,184.01,196.90,NaN,2022091105_2742,IND,43496,18.60,15.20,7.47,4.32,0.74,121.92,184.08,5.925622,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.975072,0.856778,0.309333,265,235,259.70,1015.20
67810,2022091105,2742,53450.0,Kwity Paye,5,2022-09-11 15:11:41.400000,51.0,IND,right,23.90,16.79,6.48,0.78,0.66,183.14,196.25,NaN,2022091105_2742,IND,43496,18.58,14.44,7.58,4.18,0.75,119.81,180.23,5.815918,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.961165,0.854333,0.328667,265,235,206.70,982.30
67811,2022091105,2742,53450.0,Kwity Paye,6,2022-09-11 15:11:41.500000,51.0,IND,right,23.73,16.12,6.69,0.82,0.69,180.21,194.89,run,2022091105_2742,IND,43496,18.61,13.68,7.72,4.43,0.76,118.82,175.77,5.671684,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.944835,0.836889,0.367222,265,235,217.30,1041.05
67812,2022091105,2742,53450.0,Kwity Paye,7,2022-09-11 15:11:41.599999,51.0,IND,right,23.57,15.42,6.91,1.14,0.72,175.14,193.32,NaN,2022091105_2742,IND,43496,18.69,12.91,7.84,4.33,0.78,116.94,172.10,5.487668,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.932198,0.798000,0.387111,265,235,302.10,1017.55
67813,2022091105,2742,53450.0,Kwity Paye,8,2022-09-11 15:11:41.700000,51.0,IND,right,23.43,14.66,7.20,1.46,0.77,175.14,191.19,NaN,2022091105_2742,IND,43496,18.81,12.13,7.94,3.94,0.79,109.24,169.06,5.267381,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.926332,0.821667,0.335333,265,235,386.90,925.90
67814,2022091105,2742,53450.0,Kwity Paye,9,2022-09-11 15:11:41.799999,51.0,IND,right,23.31,13.91,7.31,1.58,0.75,164.21,189.56,NaN,2022091105_2742,IND,43496,18.99,11.35,8.09,3.86,0.81,107.09,165.49,5.021554,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.913048,0.718333,0.351111,265,235,418.70,907.10
67815,2022091105,2742,53450.0,Kwity Paye,10,2022-09-11 15:11:41.900000,51.0,IND,right,23.20,13.14,7.46,1.83,0.78,161.43,187.87,NaN,2022091105_2742,IND,43496,19.23,10.57,8.26,4.09,0.82,109.23,161.41,4.729249,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.895246,0.706222,0.420222,265,235,484.95,961.15
67816,2022091105,2742,53450.0,Kwity Paye,11,2022-09-11 15:11:42.000000,51.0,IND,right,23.13,12.37,7.59,1.97,0.78,151.49,185.72,NaN,2022091105_2742,IND,43496,19.51,9.79,8.30,3.61,0.83,109.23,158.81,4.445312,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.891719,0.619667,0.449111,265,235,522.05,848.35
67817,2022091105,2742,53450.0,Kwity Paye,12,2022-09-11 15:11:42.099999,51.0,IND,right,23.07,11.62,7.66,2.42,0.75,138.88,183.51,NaN,2022091105_2742,IND,43496,19.84,9.02,8.44,3.67,0.84,111.77,155.38,4.146432,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.881880,0.504111,0.515444,265,235,641.30,862.45
67818,2022091105,2742,53450.0,Kwity Paye,13,2022-09-11 15:11:42.200000,51.0,IND,right,23.06,10.80,8.14,2.75,0.82,130.76,180.12,NaN,2022091105_2742,IND,43496,20.23,8.26,8.47,3.67,0.85,113.77,151.86,3.802696,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.880808,0.451556,0.576778,265,235,728.75,862.45
67819,2022091105,2742,53450.0,Kwity Paye,14,2022-09-11 15:11:42.299999,51.0,IND,right,23.10,9.95,8.49,2.88,0.85,144.34,176.47,NaN,2022091105_2742,IND,43496,20.68,7.52,8.60,3.82,0.87,113.77,148.15,3.429475,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.880312,0.643000,0.618000,265,235,763.20,897.70
67820,2022091105,2742,53450.0,Kwity Paye,15,2022-09-11 15:11:42.400000,51.0,IND,right,23.20,9.07,8.70,3.03,0.88,143.29,173.21,NaN,2022091105_2742,IND,43496,21.15,6.80,8.58,3.44,0.86,113.77,145.78,3.058660,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.887574,0.667556,0.644333,265,235,802.95,808.40
67821,2022091105,2742,53450.0,Kwity Paye,16,2022-09-11 15:11:42.500000,51.0,IND,right,23.34,8.18,8.84,3.17,0.91,141.65,170.44,NaN,2022091105_2742,IND,43496,21.70,6.11,8.68,3.75,0.88,109.51,141.64,2.640928,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.876307,0.680111,0.643000,265,235,840.05,881.25
67822,2022091105,2742,53450.0,Kwity Paye,17,2022-09-11 15:11:42.599999,51.0,IND,right,23.53,7.28,8.86,3.45,0.91,132.26,167.96,NaN,2022091105_2742,IND,43496,22.28,5.45,8.77,4.01,0.88,102.19,138.12,2.216168,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.867418,0.603333,0.600778,265,235,914.25,942.35
67823,2022091105,2742,53450.0,Kwity Paye,18,2022-09-11 15:11:42.700000,51.0,IND,right,23.74,6.41,8.81,3.43,0.90,123.44,165.74,NaN,2022091105_2742,IND,43496,22.88,4.81,8.78,3.89,0.87,106.10,135.27,1.816480,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.861895,0.530000,0.675889,265,235,908.95,914.15
67824,2022091105,2742,53450.0,Kwity Paye,19,2022-09-11 15:11:42.799999,51.0,IND,right,24.00,5.57,8.59,4.09,0.88,135.14,162.92,first_contact,2022091105_2742,IND,43496,23.50,4.20,8.74,3.57,0.87,106.10,132.76,1.458390,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.864626,0.691333,0.703778,265,235,1083.85,838.95
67825,2022091105,2742,53450.0,Kwity Paye,20,2022-09-11 15:11:42.900000,51.0,IND,right,24.29,4.76,8.31,4.57,0.85,128.57,160.27,NaN,2022091105_2742,IND,43496,24.16,3.62,8.72,3.36,0.87,108.07,130.20,1.147388,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.865414,0.647778,0.754111,265,235,1211.05,789.60
67826,2022091105,2742,53450.0,Kwity Paye,21,2022-09-11 15:11:43.000000,51.0,IND,right,24.58,3.99,7.96,4.87,0.82,124.74,158.53,NaN,2022091105_2742,IND,43496,24.83,3.08,8.64,3.97,0.87,108.71,127.17,0.943716,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,missed tackle,0.853914,0.624556,0.794889,265,235,1290.55,932.95
67827,2022091105,2742,53450.0,Kwity Paye,22,2022-09-11 15:11:43.099999,51.0,IND,right,24.88,3.28,7.52,5.17,0.78,119.89,156.77,NaN,2022091105_2742,IND,43496,25.52,2.57,8.58,4.33,0.86,107.91,123.70,0.955877,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.838005,0.590222,0.824556,265,235,1370.05,1017.55
67828,2022091105,2742,53450.0,Kwity Paye,23,2022-09-11 15:11:43.200000,51.0,IND,right,25.18,2.62,7.00,5.44,0.72,119.89,154.85,NaN,2022091105_2742,IND,43496,26.24,2.11,8.39,4.13,0.85,106.14,120.78,1.176308,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.828354,0.611556,0.837333,265,235,1441.60,970.55
67829,2022091105,2742,53450.0,Kwity Paye,24,2022-09-11 15:11:43.299999,51.0,IND,right,25.47,2.01,6.46,5.53,0.67,109.37,153.76,NaN,2022091105_2742,IND,43496,26.96,1.71,8.18,4.05,0.83,100.12,117.80,1.519901,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.809427,0.506778,0.803556,265,235,1465.45,951.75
67830,2022091105,2742,53450.0,Kwity Paye,25,2022-09-11 15:11:43.400000,51.0,IND,right,25.74,1.47,5.87,5.62,0.61,99.88,152.84,NaN,2022091105_2742,IND,43496,27.70,1.35,8.10,4.09,0.82,88.86,114.17,1.963670,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.780758,0.411556,0.718778,265,235,1489.30,961.15
67831,2022091105,2742,53450.0,Kwity Paye,26,2022-09-11 15:11:43.500000,51.0,IND,right,25.99,0.97,5.29,5.54,0.56,95.71,152.07,NaN,2022091105_2742,IND,43496,28.45,1.04,8.02,3.82,0.81,86.24,111.26,2.460996,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.756881,0.373778,0.722000,265,235,1468.10,897.70
67832,2022091105,2742,53450.0,Kwity Paye,27,2022-09-11 15:11:43.599999,51.0,IND,right,26.22,0.54,4.66,5.43,0.49,86.32,151.89,NaN,2022091105_2742,IND,43496,29.20,0.77,7.91,3.81,0.80,86.24,108.08,2.988863,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.721639,0.271444,0.757333,265,235,1438.95,895.35
67833,2022091105,2742,53450.0,Kwity Paye,28,2022-09-11 15:11:43.700000,51.0,IND,right,26.41,0.17,4.03,5.31,0.42,74.12,151.85,NaN,2022091105_2742,IND,43496,29.95,0.56,7.77,3.71,0.78,83.88,104.91,3.561418,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.682764,0.136333,0.766333,265,235,1407.15,871.85
67834,2022091105,2742,53450.0,Kwity Paye,29,2022-09-11 15:11:43.799999,51.0,IND,right,26.57,-0.16,3.44,5.08,0.36,64.73,152.89,NaN,2022091105_2742,IND,43496,30.71,0.37,7.74,3.09,0.78,80.57,103.06,4.173787,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.645058,0.020444,0.750111,265,235,1346.20,726.15
67835,2022091105,2742,53450.0,Kwity Paye,30,2022-09-11 15:11:43.900000,51.0,IND,right,26.71,-0.43,2.87,4.72,0.30,59.48,153.34,NaN,2022091105_2742,IND,43496,31.47,0.20,7.68,2.46,0.78,78.91,101.91,4.801510,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.623470,-0.042889,0.744444,265,235,1250.80,578.10
67836,2022091105,2742,53450.0,Kwity Paye,31,2022-09-11 15:11:44.000000,51.0,IND,right,26.83,-0.66,2.40,4.23,0.26,54.86,153.21,NaN,2022091105_2742,IND,43496,32.21,0.17,7.57,2.01,0.75,77.60,101.55,5.443648,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.620327,-0.092778,0.733889,265,235,1120.95,472.35
67837,2022091105,2742,53450.0,Kwity Paye,32,2022-09-11 15:11:44.099999,51.0,IND,right,26.90,-0.82,1.82,4.05,0.18,48.18,154.57,NaN,2022091105_2742,IND,43496,32.96,0.17,7.56,1.46,0.75,75.61,102.13,6.140334,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.609592,-0.182111,0.705333,265,235,1073.25,343.10
67838,2022091105,2742,53450.0,Kwity Paye,33,2022-09-11 15:11:44.200000,51.0,IND,right,26.96,-0.95,1.38,3.61,0.15,45.57,156.15,out_of_bounds,2022091105_2742,IND,43496,33.70,0.17,7.50,1.46,0.74,77.86,102.77,6.832423,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.596505,-0.228667,0.723222,265,235,956.65,343.10
67839,2022091105,2742,53450.0,Kwity Paye,34,2022-09-11 15:11:44.299999,51.0,IND,right,26.98,-1.02,0.84,3.41,0.07,39.06,161.97,NaN,2022091105_2742,IND,43496,34.42,-0.47,7.37,1.70,0.97,78.86,103.65,7.460302,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.525175,-0.365667,0.724556,265,235,903.65,399.50
67840,2022091105,2742,53450.0,Kwity Paye,35,2022-09-11 15:11:44.400000,51.0,IND,right,26.98,-1.08,0.49,2.95,0.06,34.05,175.50,NaN,2022091105_2742,IND,43496,35.13,-0.66,7.21,2.02,0.73,81.03,104.90,8.160815,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,0.332161,-0.571667,0.734778,265,235,781.75,474.70
67841,2022091105,2742,53450.0,Kwity Paye,36,2022-09-11 15:11:44.500000,51.0,IND,right,26.98,-1.12,0.27,2.58,0.04,31.55,203.56,NaN,2022091105_2742,IND,43496,35.82,-0.85,7.03,2.22,0.71,81.03,105.77,8.844122,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,-0.135543,-0.911222,0.725111,265,235,683.70,521.70
67842,2022091105,2742,53450.0,Kwity Paye,37,2022-09-11 15:11:44.599999,51.0,IND,right,26.95,-1.13,0.27,2.06,0.03,27.73,259.73,NaN,2022091105_2742,IND,43496,36.47,-1.05,6.73,2.68,0.68,91.53,107.23,9.520336,53450.0,NaN,NaN,NaN,53450.0,54561.0,NaN,NaN,NaN,NaN,NaN,-0.887011,-0.422222,0.825556,265,235,545.90,629.80

---

### **2.10: Adding `ballCarrierId` to feature_set df**

In [724]:
plays = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/plays.csv')

In [725]:
plays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12486 entries, 0 to 12485
Data columns (total 35 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   gameId                            12486 non-null  int64
 1   playId                            12486 non-null  int64
 2   ballCarrierId                     12486 non-null  int64
 3   ballCarrierDisplayName            12486 non-null  object
 4   playDescription                   12486 non-null  object
 5   quarter                           12486 non-null  int64
 6   down                              12486 non-null  int64
 7   yardsToGo                         12486 non-null  int64
 8   possessionTeam                    12486 non-null  object
 9   defensiveTeam                     12486 non-null  object
 10  yardlineSide                      12319 non-null  object
 11  yardlineNumber                    12486 non-null  int64
 12  gameClock                         12486 non-null  object
 13  preSnapHomeScore                  12486 non-null  int64
 14  preSnapVisitorScore               12486 non-null  int64
 15  passResult                        6105 non-null   object
 16  passLength                        5634 non-null   float64
 17  penaltyYards                      615 non-null    float64
 18  prePenaltyPlayResult              12486 non-null  int64
 19  playResult                        12486 non-null  int64
 20  playNullifiedByPenalty            12486 non-null  object
 21  absoluteYardlineNumber            12486 non-null  int64
 22  offenseFormation                  12482 non-null  object
 23  defendersInTheBox                 12481 non-null  float64
 24  passProbability                   12149 non-null  float64
 25  preSnapHomeTeamWinProbability     12486 non-null  float64
 26  preSnapVisitorTeamWinProbability  12486 non-null  float64
 27  homeTeamWinProbabilityAdded       12486 non-null  float64
 28  visitorTeamWinProbilityAdded      12486 non-null  float64
 29  expectedPoints                    12486 non-null  float64
 30  expectedPointsAdded               12485 non-null  float64
 31  foulName1                         592 non-null    object
 32  foulName2                         25 non-null     object
 33  foulNFLId1                        592 non-null    float64
 34  foulNFLId2                        25 non-null     float64
dtypes: float64(12), int64(12), object(11)
memory usage: 3.3+ MB

In [726]:
plays = game_play_Id(plays)

In [731]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   float64
 16  do_avg_1          9720 non-null   float64
 17  bc_do_avg_05      9720 non-null   float64
 18  bc_do_avg_1       9720 non-null   float64
 19  cos_05_null       9720 non-null   int64
 20  cos_1_null        9720 non-null   int64
dtypes: float64(11), int64(9), object(1)
memory usage: 1.9+ MB

In [729]:
# Merge 'ballCarrierId' from plays to tackles_1v1_1_af based on 'game_play_Id'
tackles_1v1_1_af_wbc = tackles_1v1_1_af.merge(plays[['game_play_Id', 'ballCarrierId']], on='game_play_Id', how='left')

In [730]:
tackles_1v1_1_af_wbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9720 entries, 0 to 9719
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            9720 non-null   int64
 1   playId            9720 non-null   int64
 2   nflId             9720 non-null   int64
 3   tackle            9720 non-null   int64
 4   assist            9720 non-null   int64
 5   forcedFumble      9720 non-null   int64
 6   pff_missedTackle  9720 non-null   int64
 7   game_play_Id      9720 non-null   object
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   float64
 16  do_avg_1          9720 non-null   float64
 17  bc_do_avg_05      9720 non-null   float64
 18  bc_do_avg_1       9720 non-null   float64
 19  cos_05_null       9720 non-null   int64
 20  cos_1_null        9720 non-null   int64
 21  ballCarrierId     9720 non-null   int64
dtypes: float64(11), int64(10), object(1)
memory usage: 1.6+ MB

In [735]:
tackles_1v1_1_af_wbc.tail()

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1,cos_avg_05,cos_avg_1,do_avg_05,do_avg_1,bc_do_avg_05,bc_do_avg_1,cos_05_null,cos_1_null,ballCarrierId
9715,2022103004,726,46669,1,0,0,0,2022103004_726,1.0,3.294,7.262,4.748,6.432,0.838964,0.836698,0.263978,0.786644,-0.281689,0.705556,0,0,43334
9716,2022100906,2763,52435,1,0,0,0,2022100906_2763,1.0,2.736,2.810,2.584,1.656,0.917227,0.888187,0.970178,0.851956,0.786600,0.801933,0,0,45244
9717,2022101604,699,38559,1,0,0,0,2022101604_699,1.0,0.846,1.470,4.854,3.626,-0.870827,-0.519733,0.156311,0.794000,0.567600,0.438711,0,0,53435
9718,2022110605,1030,53450,1,0,0,0,2022110605_1030,1.0,0.640,0.266,0.490,0.828,0.280762,-0.134445,0.791756,-0.225911,-0.390822,-0.175578,0,0,53549
9719,2022110610,2875,47971,1,0,0,0,2022110610_2875,1.0,0.464,0.428,3.584,2.914,0.847142,-0.278401,0.600622,0.568111,0.612311,0.579533,0,0,40011

In [736]:
plays.loc[plays['game_play_Id'] == '2022110605_1030']

,gameId,playId,ballCarrierId,ballCarrierDisplayName,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,gameClock,preSnapHomeScore,preSnapVisitorScore,passResult,passLength,penaltyYards,prePenaltyPlayResult,playResult,playNullifiedByPenalty,absoluteYardlineNumber,offenseFormation,defendersInTheBox,passProbability,preSnapHomeTeamWinProbability,preSnapVisitorTeamWinProbability,homeTeamWinProbabilityAdded,visitorTeamWinProbilityAdded,expectedPoints,expectedPointsAdded,foulName1,foulName2,foulNFLId1,foulNFLId2,game_play_Id
1412,2022110605,1030,53549,Rhamondre Stevenson,(10:54) R.Stevenson up the middle to IND 32 fo...,2,3,1,NE,IND,IND,34,10:54,3,0,NaN,NaN,NaN,2,2,N,44,JUMBO,7.0,0.277017,0.72826,0.27174,0.012378,-0.012378,3.514937,0.400487,NaN,NaN,NaN,NaN,2022110605_1030

### **2.10: Saving Finished Feature Set**

In [737]:
tackles_1v1_1_af_wbc.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tackles_feature_set_1.csv', index=False)