# **Feature Generation Notebook**
The purpose of this notebook is to generate and save the features for modeling

## **1.0: Package and Data Load**

In [171]:
import pandas as pd
import numpy as np
import pickle

In [2]:
tw1 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw1_processed.csv')
tw2 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw2_processed.csv')
tw3 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw3_processed.csv')
tw4 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw4_processed.csv')
tw5 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw5_processed.csv')
tw6 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw6_processed.csv')
tw7 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw7_processed.csv')
tw8 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw8_processed.csv')
tw9 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw9_processed.csv')

In [6]:
games = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/games.csv')
plays = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/plays.csv')
players = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/players.csv')
tackles = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/tackles.csv')

In [8]:
#Function to create 'game_play_Id' column in DF
def game_play_Id(df):
    df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')

    return df

In [9]:
plays = game_play_Id(plays)
tackles = game_play_Id(tackles)

In [20]:
plays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12486 entries, 0 to 12485
Data columns (total 36 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   gameId                            12486 non-null  int64
 1   playId                            12486 non-null  int64
 2   ballCarrierId                     12486 non-null  int64
 3   ballCarrierDisplayName            12486 non-null  object
 4   playDescription                   12486 non-null  object
 5   quarter                           12486 non-null  int64
 6   down                              12486 non-null  int64
 7   yardsToGo                         12486 non-null  int64
 8   possessionTeam                    12486 non-null  object
 9   defensiveTeam                     12486 non-null  object
 10  yardlineSide                      12319 non-null  object
 11  yardlineNumber                    12486 non-null  int64
 12  gameClock                         12486 non-null  object
 13  preSnapHomeScore                  12486 non-null  int64
 14  preSnapVisitorScore               12486 non-null  int64
 15  passResult                        6105 non-null   object
 16  passLength                        5634 non-null   float64
 17  penaltyYards                      615 non-null    float64
 18  prePenaltyPlayResult              12486 non-null  int64
 19  playResult                        12486 non-null  int64
 20  playNullifiedByPenalty            12486 non-null  object
 21  absoluteYardlineNumber            12486 non-null  int64
 22  offenseFormation                  12482 non-null  object
 23  defendersInTheBox                 12481 non-null  float64
 24  passProbability                   12149 non-null  float64
 25  preSnapHomeTeamWinProbability     12486 non-null  float64
 26  preSnapVisitorTeamWinProbability  12486 non-null  float64
 27  homeTeamWinProbabilityAdded       12486 non-null  float64
 28  visitorTeamWinProbilityAdded      12486 non-null  float64
 29  expectedPoints                    12486 non-null  float64
 30  expectedPointsAdded               12485 non-null  float64
 31  foulName1                         592 non-null    object
 32  foulName2                         25 non-null     object
 33  foulNFLId1                        592 non-null    float64
 34  foulNFLId2                        25 non-null     float64
 35  game_play_Id                      12486 non-null  object
dtypes: float64(12), int64(12), object(12)
memory usage: 3.4+ MB

In [7]:
pd.set_option('display.max_columns', None)
tw1.head()

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
0,2022090800,56,42489.0,Stefon Diggs,1,2022-09-08 20:24:05.200000,14.0,BUF,left,80.60,38.29,6.23,0.90,0.62,140.05,189.38,NaN,2022090800_56,LA,42489,80.60,38.29,6.23,0.90,0.62,140.05,189.38,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.451889,0.451889,191,191,171.90,171.90
1,2022090800,56,42489.0,Stefon Diggs,2,2022-09-08 20:24:05.299999,14.0,BUF,left,80.48,37.68,6.24,1.27,0.62,134.22,191.08,pass_arrived,2022090800_56,LA,42489,80.48,37.68,6.24,1.27,0.62,134.22,191.08,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.368222,0.368222,191,191,242.57,242.57
2,2022090800,56,42489.0,Stefon Diggs,3,2022-09-08 20:24:05.400000,14.0,BUF,left,80.34,37.09,5.98,2.48,0.60,127.16,194.40,NaN,2022090800_56,LA,42489,80.34,37.09,5.98,2.48,0.60,127.16,194.40,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.252889,0.252889,191,191,473.68,473.68
3,2022090800,56,42489.0,Stefon Diggs,4,2022-09-08 20:24:05.500000,14.0,BUF,left,80.19,36.53,5.67,3.37,0.58,120.72,196.97,NaN,2022090800_56,LA,42489,80.19,36.53,5.67,3.37,0.58,120.72,196.97,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.152778,0.152778,191,191,643.67,643.67
4,2022090800,56,42489.0,Stefon Diggs,5,2022-09-08 20:24:05.599999,14.0,BUF,left,80.01,36.00,5.43,3.65,0.56,118.07,199.54,NaN,2022090800_56,LA,42489,80.01,36.00,5.43,3.65,0.56,118.07,199.54,0.0,43294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.094778,0.094778,191,191,697.15,697.15

## **2.0: Feature Generation**

### **2.1: Figuring out how many non-assist tackling events**

In [11]:
tackles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            17426 non-null  int64
 1   playId            17426 non-null  int64
 2   nflId             17426 non-null  int64
 3   tackle            17426 non-null  int64
 4   assist            17426 non-null  int64
 5   forcedFumble      17426 non-null  int64
 6   pff_missedTackle  17426 non-null  int64
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB

In [43]:
tackles_1v1 = tackles[(tackles['tackle'] == 1) | (tackles['pff_missedTackle'] == 1)]

In [44]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11974 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11974 non-null  int64
 1   playId            11974 non-null  int64
 2   nflId             11974 non-null  int64
 3   tackle            11974 non-null  int64
 4   assist            11974 non-null  int64
 5   forcedFumble      11974 non-null  int64
 6   pff_missedTackle  11974 non-null  int64
 7   game_play_Id      11974 non-null  object
dtypes: int64(7), object(1)
memory usage: 841.9+ KB

In [45]:
tackles_1v1.tackle.value_counts()

tackle
1    9919
0    2055
Name: count, dtype: int64

In [46]:
tackles_1v1.pff_missedTackle.value_counts()

pff_missedTackle
0    9884
1    2090
Name: count, dtype: int64

In [17]:
tackles_weird = tackles[(tackles['tackle'] == 1) & (tackles['pff_missedTackle'] == 1)]

In [28]:
tackles_weird.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 219 to 9620
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            35 non-null     int64
 1   playId            35 non-null     int64
 2   nflId             35 non-null     int64
 3   tackle            35 non-null     int64
 4   assist            35 non-null     int64
 5   forcedFumble      35 non-null     int64
 6   pff_missedTackle  35 non-null     int64
 7   game_play_Id      35 non-null     object
dtypes: int64(7), object(1)
memory usage: 2.5+ KB

### **2.2: Creating Event Type Label**

In [47]:
# Function to determine event_type
def determine_event_type(row):
    if row['tackle'] == 1 and row['pff_missedTackle'] == 0:
        return 1
    elif row['tackle'] == 0 and row['pff_missedTackle'] == 1:
        return 2
    else:
        return None

In [48]:
# Apply the function to each row
tackles_1v1['event_type'] = tackles_1v1.apply(determine_event_type, axis=1)

# Find indices where both 'tackle' and 'pff_missedTackle' are 1
both_one_indices = tackles_1v1[(tackles_1v1['tackle'] == 1) & (tackles_1v1['pff_missedTackle'] == 1)].index

# Create duplicates of these rows
duplicates = tackles_1v1.loc[both_one_indices].copy()

# Modify the original rows
tackles_1v1.loc[both_one_indices, 'tackle'] = 0
tackles_1v1.loc[both_one_indices, 'event_type'] = 2

# Modify the duplicates
duplicates['pff_missedTackle'] = 0
duplicates['event_type'] = 1

# Concatenate the original DataFrame with the duplicates
tackles_1v1 = pd.concat([tackles_1v1, duplicates])

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/2649901282.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tackles_1v1['event_type'] = tackles_1v1.apply(determine_event_type, axis=1)

In [49]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            12009 non-null  int64
 1   playId            12009 non-null  int64
 2   nflId             12009 non-null  int64
 3   tackle            12009 non-null  int64
 4   assist            12009 non-null  int64
 5   forcedFumble      12009 non-null  int64
 6   pff_missedTackle  12009 non-null  int64
 7   game_play_Id      12009 non-null  object
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB

In [130]:
tackles_1v1.event_type.value_counts()

event_type
1.0    9919
2.0    2090
Name: count, dtype: int64

In [129]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            12009 non-null  int64
 1   playId            12009 non-null  int64
 2   nflId             12009 non-null  int64
 3   tackle            12009 non-null  int64
 4   assist            12009 non-null  int64
 5   forcedFumble      12009 non-null  int64
 6   pff_missedTackle  12009 non-null  int64
 7   game_play_Id      12009 non-null  object
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB

### **2.3: Combining all tracking data into one df**

In [142]:
tw1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154194 entries, 0 to 154193
Data columns (total 46 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   gameId            154194 non-null  int64
 1   playId            154194 non-null  int64
 2   nflId             154194 non-null  float64
 3   displayName       154194 non-null  object
 4   frameId           154194 non-null  int64
 5   time              154194 non-null  object
 6   jerseyNumber      154194 non-null  float64
 7   club              154194 non-null  object
 8   playDirection     154194 non-null  object
 9   x                 154194 non-null  float64
 10  y                 154194 non-null  float64
 11  s                 154194 non-null  float64
 12  a                 154194 non-null  float64
 13  dis               154194 non-null  float64
 14  o                 154194 non-null  float64
 15  dir               154194 non-null  float64
 16  event             13684 non-null   object
 17  game_play_Id      154194 non-null  object
 18  defensiveTeam     154194 non-null  object
 19  ballCarrierId     154194 non-null  int64
 20  bcx               154194 non-null  float64
 21  bcy               154194 non-null  float64
 22  bc_s              154194 non-null  float64
 23  bc_a              154194 non-null  float64
 24  bc_dis            154194 non-null  float64
 25  bc_o              154194 non-null  float64
 26  bc_dir            154194 non-null  float64
 27  distance_from_bc  154194 non-null  float64
 28  tackler_one       120749 non-null  float64
 29  tackler_two       104 non-null     float64
 30  assister_one      60503 non-null   float64
 31  assister_two      31428 non-null   float64
 32  missed_tackler_1  41990 non-null   float64
 33  missed_tackler_2  10793 non-null   float64
 34  missed_tackler_3  490 non-null     float64
 35  missed_tackler_4  0 non-null       float64
 36  missed_tackler_5  0 non-null       float64
 37  missed_tackler_6  0 non-null       float64
 38  new_event         256 non-null     object
 39  cosine            145216 non-null  float64
 40  do_align          154194 non-null  float64
 41  bc_do_align       154194 non-null  float64
 42  weight            154194 non-null  int64
 43  bc_weight         154194 non-null  int64
 44  force             154194 non-null  float64
 45  bc_force          154194 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 54.1+ MB

In [132]:
tracking_clean = pd.concat([tw1, tw2, tw3, tw4, tw5, tw6, tw7, tw8, tw9], ignore_index=True)

In [154]:
tracking_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334038 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1334038 non-null  int64
 1   playId            1334038 non-null  int64
 2   nflId             1334038 non-null  float64
 3   displayName       1334038 non-null  object
 4   frameId           1334038 non-null  int64
 5   time              1334038 non-null  object
 6   jerseyNumber      1334038 non-null  float64
 7   club              1334038 non-null  object
 8   playDirection     1334038 non-null  object
 9   x                 1334038 non-null  float64
 10  y                 1334038 non-null  float64
 11  s                 1334038 non-null  float64
 12  a                 1334038 non-null  float64
 13  dis               1334038 non-null  float64
 14  o                 1334038 non-null  float64
 15  dir               1334038 non-null  float64
 16  event             115891 non-null   object
 17  game_play_Id      1334038 non-null  object
 18  defensiveTeam     1334038 non-null  object
 19  ballCarrierId     1334038 non-null  int64
 20  bcx               1334038 non-null  float64
 21  bcy               1334038 non-null  float64
 22  bc_s              1334038 non-null  float64
 23  bc_a              1334038 non-null  float64
 24  bc_dis            1334038 non-null  float64
 25  bc_o              1334038 non-null  float64
 26  bc_dir            1334038 non-null  float64
 27  distance_from_bc  1334038 non-null  float64
 28  tackler_one       981539 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565335 non-null   float64
 31  assister_two      323674 non-null   float64
 32  missed_tackler_1  342879 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2090 non-null     object
 39  cosine            1255662 non-null  float64
 40  do_align          1334038 non-null  float64
 41  bc_do_align       1334038 non-null  float64
 42  weight            1334038 non-null  int64
 43  bc_weight         1334038 non-null  int64
 44  force             1334038 non-null  float64
 45  bc_force          1334038 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 468.2+ MB

In [155]:
###Saving Tracking Clean (Still has all observations)
tracking_clean.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean.csv', index=False)

### **2.4: Deleting Observations without a second of data beforehand**

In [238]:
def check_indices(df):
    # Get the indices of the rows where 'event' is 'tackle' and 'nflId' is not equal to 'ballCarrierId'
    tackle_indices = df[(df['event'] == 'tackle') & (df['nflId'] != df['ballCarrierId'])].index

    # Number of frames before 'tackle' event
    X = 10

    # Initialize count
    count = 0

    # List to store the indices where 'game_play_Id' and 'nflId' are different
    different_indices = []

    for idx in tackle_indices:
        # Check if the index X indices before exists in the DataFrame
        if idx - X in df.index:
            # Check if 'game_play_Id' and 'nflId' are the same
            if df.loc[idx, 'game_play_Id'] != df.loc[idx - X, 'game_play_Id'] or df.loc[idx, 'nflId'] != df.loc[idx - X, 'nflId']:
                count += 1
                different_indices.append(idx)

    # Print the indices where 'game_play_Id' and 'nflId' are different
    print('Indices where game_play_Id and nflId are different:', different_indices)

    # Print the count
    print('Count:', count)

    return different_indices

In [161]:
missing_indices_07 = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [14063, 14074, 17612, 17623, 20579, 20590, 51887, 51898, 91263, 91274, 91562, 91573, 106329, 106340, 119489, 119500, 136398, 136409, 144658, 144669, 144878, 144889, 154658, 154669, 191539, 191550, 230405, 230416, 243028, 243039, 255160, 255171, 276491, 276502, 290376, 290387, 348106, 348117, 385470, 385481, 401427, 401438, 424743, 424754, 432652, 432663, 450031, 450042, 459968, 459979, 479700, 479711, 486440, 486451, 521657, 521668, 524722, 524733, 564815, 564826, 581886, 581897, 599640, 599651, 604195, 604206, 604781, 604792, 644283, 644294, 654830, 654841, 657479, 657490, 666904, 666915, 695217, 695228, 718709, 718720, 723525, 723536, 737745, 737756, 767105, 767116, 786301, 786312, 820288, 820299, 867588, 867599, 924264, 924275, 946608, 946619, 953235, 953246, 1002689, 1002700, 1002711, 1002722, 1036794, 1036805, 1148633, 1148644, 1191458, 1191469, 1196551, 1196562, 1314707, 1314718, 1316210, 1316221, 1318480, 1318491, 1319282, 1319293]
Count: 118

In [177]:
missing_indices_1 = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [1315, 1327, 2656, 2670, 14063, 14074, 17612, 17623, 17635, 17647, 18586, 18600, 20579, 20590, 21210, 21223, 28372, 28385, 33582, 38659, 38673, 39329, 39343, 43404, 43416, 46962, 46975, 47234, 47246, 50191, 50205, 51887, 51898, 54749, 54761, 55128, 55141, 60335, 60347, 66088, 66101, 76756, 76769, 76851, 76863, 77770, 77782, 83988, 84001, 90209, 90222, 91263, 91274, 91562, 91573, 92539, 92553, 96571, 96583, 96964, 96977, 98068, 98082, 98508, 98522, 106329, 106340, 106353, 106366, 108474, 108487, 108500, 119489, 119500, 121755, 121769, 122518, 122532, 127548, 127562, 136398, 136409, 138069, 138083, 139897, 139911, 140810, 140822, 142333, 142347, 144658, 144669, 144878, 144889, 154658, 154669, 154779, 154791, 156073, 156087, 156694, 156707, 159833, 159845, 163121, 163133, 170023, 170036, 175554, 175568, 179355, 179369, 180149, 180161, 189038, 189052, 191539, 191550, 196635, 196648, 199053, 199067, 203011, 203023, 204547, 204559, 204704, 204717, 204877, 204889, 204902, 204915, 205420, 205432, 205911, 205923, 209055, 209068, 209080, 209092, 212911, 212925, 215112, 215126, 220822, 220834, 226877, 226890, 229712, 229725, 230405, 230416, 237220, 237233, 237767, 237779, 243028, 243039, 254044, 254056, 254070, 254084, 255160, 255171, 263701, 263715, 263729, 263743, 271012, 271026, 276491, 276502, 280246, 280260, 281089, 281101, 287764, 287776, 288875, 288889, 290376, 290387, 290461, 290473, 291306, 291319, 291593, 291607, 305947, 305959, 310754, 310768, 311916, 311928, 311940, 317394, 317407, 324536, 324550, 327023, 327035, 327048, 327061, 340560, 340574, 342933, 342947, 348106, 348117, 348708, 348722, 349342, 349355, 352754, 352768, 354068, 354080, 355570, 355583, 357785, 357799, 374187, 374201, 378109, 378121, 378133, 378145, 381446, 381460, 382244, 382258, 382270, 382282, 383183, 383197, 383780, 383794, 385470, 385481, 387254, 387268, 391622, 391634, 395088, 395101, 395965, 395979, 399315, 399327, 401427, 401438, 402235, 402249, 402439, 402451, 403054, 403068, 404249, 404261, 408577, 408591, 409885, 409897, 412653, 412666, 412679, 412692, 424743, 424754, 425800, 425814, 426776, 426789, 428927, 428939, 429972, 429986, 432652, 432663, 440877, 440889, 450031, 450042, 450638, 450652, 456166, 456179, 459968, 459979, 474134, 474146, 479700, 479711, 482306, 482318, 486440, 486451, 488044, 488058, 494012, 494024, 496772, 496786, 500726, 500740, 502265, 502279, 509367, 509379, 516618, 516632, 519537, 519549, 519677, 519691, 521657, 521668, 524722, 524733, 525815, 525827, 527291, 527304, 527317, 527330, 533067, 533080, 540127, 540139, 540715, 540729, 541290, 541304, 542057, 542070, 542897, 542911, 545637, 545651, 556720, 556733, 564815, 564826, 565278, 565292, 567187, 567201, 581886, 581897, 587095, 587108, 588325, 588339, 594344, 594356, 598286, 598298, 599640, 599651, 604195, 604206, 604781, 604792, 607063, 607075, 611526, 611540, 615426, 615440, 619779, 619793, 621746, 621760, 626487, 626499, 643272, 643284, 644283, 644294, 645840, 645854, 646660, 646673, 648980, 648992, 649005, 649018, 654830, 654841, 657479, 657490, 660189, 660201, 662618, 662631, 663887, 663901, 664357, 664369, 666904, 666915, 670730, 670744, 671189, 671201, 685048, 685061, 694630, 694644, 695217, 695228, 707378, 707391, 708946, 708960, 717155, 717167, 718709, 718720, 723525, 723536, 723826, 723840, 723854, 725369, 725381, 725437, 725451, 727010, 727024, 732433, 732446, 734040, 734054, 737745, 737756, 747761, 747774, 748036, 748050, 767105, 767116, 769495, 769508, 769592, 769604, 770979, 770991, 786301, 786312, 790736, 790748, 794283, 794296, 798682, 798694, 799979, 799991, 805190, 805204, 808469, 808482, 811436, 811449, 818076, 818090, 820288, 820299, 837817, 837829, 839641, 839654, 843371, 843384, 845241, 845254, 845884, 845896, 850028, 850040, 853166, 853179, 855591, 855604, 857218, 857232, 859855, 859869, 867588, 867599, 876526, 876538, 881585, 881598, 887831, 887844, 896642, 896654, 896668, 896682, 898650, 898662, 898981, 898993, 902010, 902022, 902730, 902743, 908078, 908091, 911349, 911363, 911659, 911673, 916714, 916727, 919052, 919065, 923262, 923276, 924264, 924275, 926837, 926850, 927966, 927979, 934678, 934691, 941413, 941427, 941441, 941455, 944680, 944692, 946608, 946619, 953235, 953246, 953258, 953270, 967010, 967023, 979579, 979592, 1000963, 1000977, 1001942, 1001955, 1002689, 1002700, 1002711, 1002722, 1019697, 1019710, 1028282, 1028294, 1028542, 1028554, 1032356, 1032370, 1033242, 1033256, 1036794, 1036805, 1038001, 1038013, 1041485, 1041498, 1042466, 1042478, 1048860, 1048873, 1048886, 1062086, 1062099, 1063982, 1063995, 1069082, 1069096, 1070423, 1070435, 1091920, 1091934, 1092408, 1092422, 1101704, 1101716, 1116754, 1116768, 1118312, 1118325, 1121181, 1121195, 1123553, 1123566, 1130379, 1130393, 1131365, 1131379, 1134004, 1134016, 1136232, 1136245, 1136481, 1136495, 1141945, 1141957, 1144710, 1144722, 1148633, 1148644, 1159488, 1159502, 1161622, 1161635, 1162973, 1162985, 1168027, 1168041, 1171774, 1171786, 1191458, 1191469, 1196231, 1196243, 1196551, 1196562, 1200460, 1200474, 1200654, 1200668, 1206773, 1206785, 1207218, 1207230, 1211346, 1211358, 1215615, 1215629, 1240393, 1240407, 1245245, 1245259, 1248510, 1248524, 1248538, 1255160, 1255172, 1256218, 1256231, 1264990, 1265002, 1265014, 1266259, 1266273, 1270652, 1270664, 1272695, 1272708, 1273518, 1273530, 1281301, 1281315, 1297666, 1297680, 1297694, 1301459, 1301471, 1308760, 1308774, 1308993, 1309006, 1314707, 1314718, 1316210, 1316221, 1318480, 1318491, 1319282, 1319293, 1322330, 1322344, 1323878, 1323891, 1324044, 1324057, 1328638, 1328650, 1329968, 1329982]
Count: 690

In [239]:
missing_indices_1_no_bc = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [1327, 2670, 14063, 17623, 17647, 18600, 20590, 21223, 28372, 38659, 39343, 43404, 46962, 47246, 50191, 51887, 54749, 55141, 60335, 66088, 76756, 76851, 77770, 84001, 90209, 91274, 91562, 92539, 96571, 96964, 98082, 98508, 106340, 106353, 108487, 108500, 119500, 121769, 122532, 127548, 136398, 138083, 139897, 140822, 142347, 144669, 144889, 154669, 154791, 156087, 156707, 159845, 163133, 170023, 175568, 179355, 180161, 189038, 191550, 196635, 199053, 203023, 204559, 204717, 204877, 204902, 205420, 205911, 209055, 209080, 212925, 215126, 220822, 226877, 229712, 230405, 237220, 237779, 243039, 254044, 254070, 255160, 263715, 263743, 271012, 276491, 280260, 281101, 287776, 288889, 290387, 290461, 291319, 291593, 305947, 310768, 311916, 311928, 317394, 324550, 327023, 327061, 340574, 342947, 348106, 348722, 349355, 352754, 354068, 355583, 357799, 374201, 378109, 378133, 381446, 382244, 382270, 383183, 383780, 385470, 387254, 391634, 395101, 395979, 399315, 401438, 402235, 402451, 403068, 404261, 408591, 409885, 412653, 412692, 424743, 425800, 426776, 428939, 429986, 432663, 440889, 450031, 450638, 456166, 459968, 474134, 479700, 482318, 486440, 488044, 494024, 496786, 500726, 502279, 509367, 516632, 519537, 519677, 521657, 524733, 525827, 527291, 527330, 533067, 540139, 540715, 541290, 542057, 542911, 545637, 556733, 564815, 565278, 567187, 581886, 587108, 588339, 594356, 598298, 599640, 604206, 604792, 607075, 611540, 615426, 619793, 621760, 626499, 643284, 644294, 645854, 646660, 648992, 649005, 654830, 657490, 660201, 662631, 663887, 664357, 666915, 670730, 671201, 685048, 694644, 695217, 707391, 708946, 717167, 718709, 723525, 723826, 723840, 725369, 725451, 727010, 732433, 734054, 737745, 747761, 748050, 767116, 769508, 769592, 770991, 786312, 790736, 794283, 798694, 799991, 805190, 808469, 811449, 818076, 820288, 837829, 839641, 843371, 845254, 845896, 850028, 853166, 855591, 857218, 859855, 867588, 876538, 881585, 887831, 896642, 896668, 898650, 898981, 902010, 902730, 908078, 911349, 911659, 916714, 919065, 923276, 924275, 926850, 927979, 934691, 941413, 941455, 944680, 946608, 953246, 953258, 967023, 979592, 1000963, 1001955, 1002700, 1002711, 1019710, 1028282, 1028554, 1032370, 1033256, 1036805, 1038013, 1041485, 1042466, 1048860, 1048873, 1062086, 1063995, 1069082, 1070423, 1091934, 1092422, 1101704, 1116754, 1118325, 1121195, 1123566, 1130393, 1131365, 1134016, 1136245, 1136495, 1141945, 1144710, 1148633, 1159502, 1161622, 1162973, 1168041, 1171786, 1191458, 1196243, 1196562, 1200474, 1200654, 1206785, 1207218, 1211346, 1215629, 1240407, 1245259, 1248510, 1248524, 1255172, 1256231, 1264990, 1265014, 1266273, 1270652, 1272695, 1273530, 1281301, 1297666, 1297694, 1301471, 1308774, 1309006, 1314707, 1316221, 1318491, 1319282, 1322330, 1323891, 1324057, 1328638, 1329968]
Count: 348

**Checking if any indices are in 'missing_indices_07' but are not in 'missing_indices_1'**

In [184]:
# Convert the lists to sets
set_07 = set(missing_indices_07)
set_1 = set(missing_indices_1)

# Find the elements that are in set_07 but not in set_1
difference = set_07.difference(set_1)

# Print the number of such elements
print(len(difference))

0

In [172]:
# Define the path to the folder where you want to save the file
folder_path = '/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/'

In [173]:
###Save list of Tackle Indices for 7 frames before
with open(folder_path + 'missed_indices_07.pkl', 'wb') as f:
    pickle.dump(missing_indices_07, f)

In [178]:
###Save list of Tackle Indices for 10 frames before
with open(folder_path + 'missing_indices_1.pkl', 'wb') as f:
    pickle.dump(missing_indices_1, f)

In [240]:
###Function to check number of indicies that they there is data for missed tackles
def check_indices_mt(df):
    # Get the indices of the rows where 'event' is 'tackle'
    missed_tackle_indices = df[(df['new_event'] == 'missed tackle') & (df['nflId'] != df['ballCarrierId'])].index

    # Number of frames before 'tackle' event
    X = 10

    # Initialize count
    count = 0

    # List to store the indices where 'game_play_Id' and 'nflId' are different
    different_indices = []

    for idx in missed_tackle_indices:
        # Check if the index X indices before exists in the DataFrame
        if idx - X in df.index:
            # Check if 'game_play_Id' and 'nflId' are the same
            if df.loc[idx, 'game_play_Id'] != df.loc[idx - X, 'game_play_Id'] or df.loc[idx, 'nflId'] != df.loc[idx - X, 'nflId']:
                count += 1
                different_indices.append(idx)

    # Print the indices where 'game_play_Id' and 'nflId' are different
    print('Indices where game_play_Id and nflId are different:', different_indices)

    # Print the count
    print('Count:', count)

    return different_indices

In [163]:
missing_indices_mt_07 = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 34725, 51731, 52779, 55640, 57411, 58035, 68848, 86381, 107019, 110595, 120597, 120631, 136338, 147996, 156674, 158520, 178125, 212823, 214636, 311921, 332121, 351489, 368915, 372788, 382782, 409111, 432892, 452750, 464894, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 574471, 581048, 610460, 630315, 654434, 670021, 673241, 676171, 692371, 699997, 771085, 780654, 788532, 794968, 795241, 796630, 807953, 815705, 819585, 840445, 841241, 842578, 845521, 854124, 877829, 884016, 886686, 899833, 901033, 907655, 921162, 924949, 933033, 959407, 987203, 994045, 1047478, 1053698, 1060203, 1091799, 1124084, 1128294, 1136398, 1140202, 1150719, 1165152, 1177443, 1181479, 1194337, 1214065, 1214145, 1215864, 1218259, 1236455, 1239235, 1266063, 1272172, 1296186, 1307083]
Count: 100

In [180]:
missing_indices_mt_1 = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 19937, 34725, 44263, 48795, 51731, 52145, 52779, 55640, 57411, 58035, 59739, 64431, 68848, 73619, 78497, 83491, 86381, 88656, 99800, 107019, 110595, 117045, 120597, 120631, 136338, 147996, 148433, 155369, 156674, 158520, 177788, 178125, 192331, 193642, 212823, 214636, 216202, 225155, 226134, 244252, 263660, 298871, 301237, 306877, 311921, 317547, 323191, 327498, 332121, 341552, 350970, 351489, 356544, 368915, 372788, 380308, 380580, 382385, 382782, 398124, 409111, 427521, 432892, 436573, 444996, 452750, 464894, 466031, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 557963, 574471, 581048, 592086, 596080, 610460, 623984, 630315, 636633, 654434, 668747, 670021, 673241, 676171, 692371, 699997, 706701, 712253, 713260, 723993, 729310, 730937, 731747, 752331, 764733, 771085, 771476, 780654, 788532, 794968, 795080, 795241, 796630, 796807, 807953, 809992, 812423, 815705, 819585, 819869, 823013, 825463, 840445, 841241, 842578, 843034, 845521, 847855, 854124, 877829, 884016, 886686, 887370, 899261, 899833, 901033, 906224, 907655, 910631, 911311, 921162, 924949, 926079, 933033, 944461, 959407, 987203, 994045, 994666, 1002894, 1020531, 1047478, 1053698, 1057306, 1060203, 1069427, 1077155, 1085274, 1091799, 1102411, 1107945, 1124084, 1124511, 1128294, 1132489, 1136398, 1140202, 1150719, 1152050, 1164741, 1165152, 1177443, 1181479, 1194337, 1195152, 1204679, 1209794, 1214065, 1214145, 1215864, 1216842, 1218259, 1229866, 1236455, 1239235, 1240551, 1266063, 1269088, 1272172, 1274447, 1277804, 1296186, 1302468, 1307083, 1313187]
Count: 195

In [241]:
missing_indices_mt_1_no_bc = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 19937, 34725, 44263, 48795, 51731, 52145, 52779, 55640, 57411, 58035, 59739, 64431, 68848, 73619, 78497, 83491, 86381, 88656, 99800, 107019, 110595, 117045, 120597, 120631, 136338, 147996, 148433, 155369, 156674, 158520, 177788, 178125, 192331, 193642, 212823, 214636, 216202, 225155, 226134, 244252, 263660, 298871, 301237, 306877, 311921, 317547, 323191, 327498, 332121, 341552, 350970, 351489, 356544, 368915, 372788, 380308, 380580, 382385, 382782, 398124, 409111, 427521, 432892, 436573, 444996, 452750, 464894, 466031, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 557963, 574471, 581048, 592086, 596080, 610460, 623984, 630315, 636633, 654434, 668747, 670021, 673241, 676171, 692371, 699997, 706701, 712253, 713260, 723993, 729310, 730937, 731747, 752331, 764733, 771085, 771476, 780654, 788532, 794968, 795080, 795241, 796630, 796807, 807953, 809992, 812423, 815705, 819585, 819869, 823013, 825463, 840445, 841241, 842578, 843034, 845521, 847855, 854124, 877829, 884016, 886686, 887370, 899261, 899833, 901033, 906224, 907655, 910631, 911311, 921162, 924949, 926079, 933033, 944461, 959407, 987203, 994045, 994666, 1002894, 1020531, 1047478, 1053698, 1057306, 1060203, 1069427, 1077155, 1085274, 1091799, 1102411, 1107945, 1124084, 1124511, 1128294, 1132489, 1136398, 1140202, 1150719, 1152050, 1164741, 1165152, 1177443, 1181479, 1194337, 1195152, 1204679, 1209794, 1214065, 1214145, 1215864, 1216842, 1218259, 1229866, 1236455, 1239235, 1240551, 1266063, 1269088, 1272172, 1274447, 1277804, 1296186, 1302468, 1307083, 1313187]
Count: 195

In [174]:
###Save list of Missed Tackle Indices for 7 frames before
with open(folder_path + 'missed_indices_mt_07.pkl', 'wb') as f:
    pickle.dump(missing_indices_mt_07, f)

In [181]:
###Save list of Missed Tackle Indices for 10 frames before
with open(folder_path + 'missed_indices_mt_1.pkl', 'wb') as f:
    pickle.dump(missing_indices_mt_1, f)

In [165]:
'''OLD VERSION
###Function to delete rows where there is no data at least 7 frames before the tackle
def drop_dataless_rows(df, indices):
    count = 0
    for index in indices:
        game_play_id = df.loc[index, 'game_play_Id']
        nfl_id = df.loc[index, 'nflId']
        matching_rows = df[(df['game_play_Id'] == game_play_id) & (df['nflId'] == nfl_id)]
        count += len(matching_rows)
        df = df.drop(matching_rows.index)
    print(f'Total matching rows: {count}')
    return df
'''

In [204]:
###Function to delete rows where there is no data at least 7 frames before the tackle
def drop_dataless_rows(df, indices):
    count = 0
    for index in indices:
        if index in df.index:
            game_play_id = df.loc[index, 'game_play_Id']
            nfl_id = df.loc[index, 'nflId']
            matching_rows = df[(df['game_play_Id'] == game_play_id) & (df['nflId'] == nfl_id)]
            count += len(matching_rows)
            df = df.drop(matching_rows.index)
        else:
            print(f'Index {index} not in DataFrame')
    print(f'Total matching rows: {count}')
    return df

In [203]:
missing_indices_1

[1315,
 1327,
 2656,
 2670,
 14063,
 14074,
 17612,
 17623,
 17635,
 17647,
 18586,
 18600,
 20579,
 20590,
 21210,
 21223,
 28372,
 28385,
 33582,
 38659,
 38673,
 39329,
 39343,
 43404,
 43416,
 46962,
 46975,
 47234,
 47246,
 50191,
 50205,
 51887,
 51898,
 54749,
 54761,
 55128,
 55141,
 60335,
 60347,
 66088,
 66101,
 76756,
 76769,
 76851,
 76863,
 77770,
 77782,
 83988,
 84001,
 90209,
 90222,
 91263,
 91274,
 91562,
 91573,
 92539,
 92553,
 96571,
 96583,
 96964,
 96977,
 98068,
 98082,
 98508,
 98522,
 106329,
 106340,
 106353,
 106366,
 108474,
 108487,
 108500,
 119489,
 119500,
 121755,
 121769,
 122518,
 122532,
 127548,
 127562,
 136398,
 136409,
 138069,
 138083,
 139897,
 139911,
 140810,
 140822,
 142333,
 142347,
 144658,
 144669,
 144878,
 144889,
 154658,
 154669,
 154779,
 154791,
 156073,
 156087,
 156694,
 156707,
 159833,
 159845,
 163121,
 163133,
 170023,
 170036,
 175554,
 175568,
 179355,
 179369,
 180149,
 180161,
 189038,
 189052,
 191539,
 191550,
 196635,
 196648,
 199053,
 199067,
 203011,
 203023,
 204547,
 204559,
 204704,
 204717,
 204877,
 204889,
 204902,
 204915,
 205420,
 205432,
 205911,
 205923,
 209055,
 209068,
 209080,
 209092,
 212911,
 212925,
 215112,
 215126,
 220822,
 220834,
 226877,
 226890,
 229712,
 229725,
 230405,
 230416,
 237220,
 237233,
 237767,
 237779,
 243028,
 243039,
 254044,
 254056,
 254070,
 254084,
 255160,
 255171,
 263701,
 263715,
 263729,
 263743,
 271012,
 271026,
 276491,
 276502,
 280246,
 280260,
 281089,
 281101,
 287764,
 287776,
 288875,
 288889,
 290376,
 290387,
 290461,
 290473,
 291306,
 291319,
 291593,
 291607,
 305947,
 305959,
 310754,
 310768,
 311916,
 311928,
 311940,
 317394,
 317407,
 324536,
 324550,
 327023,
 327035,
 327048,
 327061,
 340560,
 340574,
 342933,
 342947,
 348106,
 348117,
 348708,
 348722,
 349342,
 349355,
 352754,
 352768,
 354068,
 354080,
 355570,
 355583,
 357785,
 357799,
 374187,
 374201,
 378109,
 378121,
 378133,
 378145,
 381446,
 381460,
 382244,
 382258,
 382270,
 382282,
 383183,
 383197,
 383780,
 383794,
 385470,
 385481,
 387254,
 387268,
 391622,
 391634,
 395088,
 395101,
 395965,
 395979,
 399315,
 399327,
 401427,
 401438,
 402235,
 402249,
 402439,
 402451,
 403054,
 403068,
 404249,
 404261,
 408577,
 408591,
 409885,
 409897,
 412653,
 412666,
 412679,
 412692,
 424743,
 424754,
 425800,
 425814,
 426776,
 426789,
 428927,
 428939,
 429972,
 429986,
 432652,
 432663,
 440877,
 440889,
 450031,
 450042,
 450638,
 450652,
 456166,
 456179,
 459968,
 459979,
 474134,
 474146,
 479700,
 479711,
 482306,
 482318,
 486440,
 486451,
 488044,
 488058,
 494012,
 494024,
 496772,
 496786,
 500726,
 500740,
 502265,
 502279,
 509367,
 509379,
 516618,
 516632,
 519537,
 519549,
 519677,
 519691,
 521657,
 521668,
 524722,
 524733,
 525815,
 525827,
 527291,
 527304,
 527317,
 527330,
 533067,
 533080,
 540127,
 540139,
 540715,
 540729,
 541290,
 541304,
 542057,
 542070,
 542897,
 542911,
 545637,
 545651,
 556720,
 556733,
 564815,
 564826,
 565278,
 565292,
 567187,
 567201,
 581886,
 581897,
 587095,
 587108,
 588325,
 588339,
 594344,
 594356,
 598286,
 598298,
 599640,
 599651,
 604195,
 604206,
 604781,
 604792,
 607063,
 607075,
 611526,
 611540,
 615426,
 615440,
 619779,
 619793,
 621746,
 621760,
 626487,
 626499,
 643272,
 643284,
 644283,
 644294,
 645840,
 645854,
 646660,
 646673,
 648980,
 648992,
 649005,
 649018,
 654830,
 654841,
 657479,
 657490,
 660189,
 660201,
 662618,
 662631,
 663887,
 663901,
 664357,
 664369,
 666904,
 666915,
 670730,
 670744,
 671189,
 671201,
 685048,
 685061,
 694630,
 694644,
 695217,
 695228,
 707378,
 707391,
 708946,
 708960,
 717155,
 717167,
 718709,
 718720,
 723525,
 723536,
 723826,
 723840,
 723854,
 725369,
 725381,
 725437,
 725451,
 727010,
 727024,
 732433,
 732446,
 734040,
 734054,
 737745,
 737756,
 747761,
 747774,
 748036,
 748050,
 767105,
 767116,
 769495,
 769508,
 769592,
 769604,
 770979,
 770991,
 786301,
 786312,
 790736,
 790748,
 794283,
 794296,
 798682,
 798694,
 799979,
 799991,
 805190,
 805204,
 808469,
 808482,
 811436,
 811449,
 818076,
 818090,
 820288,
 820299,
 837817,
 837829,
 839641,
 839654,
 843371,
 843384,
 845241,
 845254,
 845884,
 845896,
 850028,
 850040,
 853166,
 853179,
 855591,
 855604,
 857218,
 857232,
 859855,
 859869,
 867588,
 867599,
 876526,
 876538,
 881585,
 881598,
 887831,
 887844,
 896642,
 896654,
 896668,
 896682,
 898650,
 898662,
 898981,
 898993,
 902010,
 902022,
 902730,
 902743,
 908078,
 908091,
 911349,
 911363,
 911659,
 911673,
 916714,
 916727,
 919052,
 919065,
 923262,
 923276,
 924264,
 924275,
 926837,
 926850,
 927966,
 927979,
 934678,
 934691,
 941413,
 941427,
 941441,
 941455,
 944680,
 944692,
 946608,
 946619,
 953235,
 953246,
 953258,
 953270,
 967010,
 967023,
 979579,
 979592,
 1000963,
 1000977,
 1001942,
 1001955,
 1002689,
 1002700,
 1002711,
 1002722,
 1019697,
 1019710,
 1028282,
 1028294,
 1028542,
 1028554,
 1032356,
 1032370,
 1033242,
 1033256,
 1036794,
 1036805,
 1038001,
 1038013,
 1041485,
 1041498,
 1042466,
 1042478,
 1048860,
 1048873,
 1048886,
 1062086,
 1062099,
 1063982,
 1063995,
 1069082,
 1069096,
 1070423,
 1070435,
 1091920,
 1091934,
 1092408,
 1092422,
 1101704,
 1101716,
 1116754,
 1116768,
 1118312,
 1118325,
 1121181,
 1121195,
 1123553,
 1123566,
 1130379,
 1130393,
 1131365,
 1131379,
 1134004,
 1134016,
 1136232,
 1136245,
 1136481,
 1136495,
 1141945,
 1141957,
 1144710,
 1144722,
 1148633,
 1148644,
 1159488,
 1159502,
 1161622,
 1161635,
 1162973,
 1162985,
 1168027,
 1168041,
 1171774,
 1171786,
 1191458,
 1191469,
 1196231,
 1196243,
 1196551,
 1196562,
 1200460,
 1200474,
 1200654,
 1200668,
 1206773,
 1206785,
 1207218,
 1207230,
 1211346,
 1211358,
 1215615,
 1215629,
 1240393,
 1240407,
 1245245,
 1245259,
 1248510,
 1248524,
 1248538,
 1255160,
 1255172,
 1256218,
 1256231,
 1264990,
 1265002,
 1265014,
 1266259,
 1266273,
 1270652,
 1270664,
 1272695,
 1272708,
 1273518,
 1273530,
 1281301,
 1281315,
 1297666,
 1297680,
 1297694,
 1301459,
 1301471,
 1308760,
 1308774,
 1308993,
 1309006,
 1314707,
 1314718,
 1316210,
 1316221,
 1318480,
 1318491,
 1319282,
 1319293,
 1322330,
 1322344,
 1323878,
 1323891,
 1324044,
 1324057,
 1328638,
 1328650,
 1329968,
 1329982]

In [166]:
tracking_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334038 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1334038 non-null  int64
 1   playId            1334038 non-null  int64
 2   nflId             1334038 non-null  float64
 3   displayName       1334038 non-null  object
 4   frameId           1334038 non-null  int64
 5   time              1334038 non-null  object
 6   jerseyNumber      1334038 non-null  float64
 7   club              1334038 non-null  object
 8   playDirection     1334038 non-null  object
 9   x                 1334038 non-null  float64
 10  y                 1334038 non-null  float64
 11  s                 1334038 non-null  float64
 12  a                 1334038 non-null  float64
 13  dis               1334038 non-null  float64
 14  o                 1334038 non-null  float64
 15  dir               1334038 non-null  float64
 16  event             115891 non-null   object
 17  game_play_Id      1334038 non-null  object
 18  defensiveTeam     1334038 non-null  object
 19  ballCarrierId     1334038 non-null  int64
 20  bcx               1334038 non-null  float64
 21  bcy               1334038 non-null  float64
 22  bc_s              1334038 non-null  float64
 23  bc_a              1334038 non-null  float64
 24  bc_dis            1334038 non-null  float64
 25  bc_o              1334038 non-null  float64
 26  bc_dir            1334038 non-null  float64
 27  distance_from_bc  1334038 non-null  float64
 28  tackler_one       981539 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565335 non-null   float64
 31  assister_two      323674 non-null   float64
 32  missed_tackler_1  342879 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2090 non-null     object
 39  cosine            1255662 non-null  float64
 40  do_align          1334038 non-null  float64
 41  bc_do_align       1334038 non-null  float64
 42  weight            1334038 non-null  int64
 43  bc_weight         1334038 non-null  int64
 44  force             1334038 non-null  float64
 45  bc_force          1334038 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 468.2+ MB

In [167]:
###Running for Tackles Indices
tracking_clean_07 = drop_dataless_rows(tracking_clean, missing_indices_07)

Total matching rows: 1298

In [168]:
tracking_clean_07.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1332740 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1332740 non-null  int64
 1   playId            1332740 non-null  int64
 2   nflId             1332740 non-null  float64
 3   displayName       1332740 non-null  object
 4   frameId           1332740 non-null  int64
 5   time              1332740 non-null  object
 6   jerseyNumber      1332740 non-null  float64
 7   club              1332740 non-null  object
 8   playDirection     1332740 non-null  object
 9   x                 1332740 non-null  float64
 10  y                 1332740 non-null  float64
 11  s                 1332740 non-null  float64
 12  a                 1332740 non-null  float64
 13  dis               1332740 non-null  float64
 14  o                 1332740 non-null  float64
 15  dir               1332740 non-null  float64
 16  event             115551 non-null   object
 17  game_play_Id      1332740 non-null  object
 18  defensiveTeam     1332740 non-null  object
 19  ballCarrierId     1332740 non-null  int64
 20  bcx               1332740 non-null  float64
 21  bcy               1332740 non-null  float64
 22  bc_s              1332740 non-null  float64
 23  bc_a              1332740 non-null  float64
 24  bc_dis            1332740 non-null  float64
 25  bc_o              1332740 non-null  float64
 26  bc_dir            1332740 non-null  float64
 27  distance_from_bc  1332740 non-null  float64
 28  tackler_one       980241 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565335 non-null   float64
 31  assister_two      323674 non-null   float64
 32  missed_tackler_1  342879 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2090 non-null     object
 39  cosine            1254364 non-null  float64
 40  do_align          1332740 non-null  float64
 41  bc_do_align       1332740 non-null  float64
 42  weight            1332740 non-null  int64
 43  bc_weight         1332740 non-null  int64
 44  force             1332740 non-null  float64
 45  bc_force          1332740 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 477.9+ MB

In [169]:
###Running for Missed Tackle Indices
tracking_clean_07 = drop_dataless_rows(tracking_clean_07, missing_indices_mt_07)

Total matching rows: 3609

In [170]:
tracking_clean_07.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1329131 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1329131 non-null  int64
 1   playId            1329131 non-null  int64
 2   nflId             1329131 non-null  float64
 3   displayName       1329131 non-null  object
 4   frameId           1329131 non-null  int64
 5   time              1329131 non-null  object
 6   jerseyNumber      1329131 non-null  float64
 7   club              1329131 non-null  object
 8   playDirection     1329131 non-null  object
 9   x                 1329131 non-null  float64
 10  y                 1329131 non-null  float64
 11  s                 1329131 non-null  float64
 12  a                 1329131 non-null  float64
 13  dis               1329131 non-null  float64
 14  o                 1329131 non-null  float64
 15  dir               1329131 non-null  float64
 16  event             115238 non-null   object
 17  game_play_Id      1329131 non-null  object
 18  defensiveTeam     1329131 non-null  object
 19  ballCarrierId     1329131 non-null  int64
 20  bcx               1329131 non-null  float64
 21  bcy               1329131 non-null  float64
 22  bc_s              1329131 non-null  float64
 23  bc_a              1329131 non-null  float64
 24  bc_dis            1329131 non-null  float64
 25  bc_o              1329131 non-null  float64
 26  bc_dir            1329131 non-null  float64
 27  distance_from_bc  1329131 non-null  float64
 28  tackler_one       976963 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564973 non-null   float64
 31  assister_two      323448 non-null   float64
 32  missed_tackler_1  339270 non-null   float64
 33  missed_tackler_2  76926 non-null    float64
 34  missed_tackler_3  14781 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1990 non-null     object
 39  cosine            1250757 non-null  float64
 40  do_align          1329131 non-null  float64
 41  bc_do_align       1329131 non-null  float64
 42  weight            1329131 non-null  int64
 43  bc_weight         1329131 non-null  int64
 44  force             1329131 non-null  float64
 45  bc_force          1329131 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 476.6+ MB

In [182]:
tracking_clean_07.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_07.csv', index=False)

**Generating tracking_clean for observations that have at least 10 frames of data available before them**

In [189]:
# Convert the lists to sets
set_1 = set(missing_indices_1)
set_mt_1 = set(missing_indices_mt_1)

# Find the common elements
common_indices = set_1.intersection(set_mt_1)

# Convert the set back to a list, if needed
common_indices_list = list(common_indices)

print(common_indices_list)

[]

In [205]:
###Applying for Tackle Indices
tracking_clean_1 = drop_dataless_rows(tracking_clean, missing_indices_1)

Total matching rows: 8768

In [206]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1325270 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1325270 non-null  int64
 1   playId            1325270 non-null  int64
 2   nflId             1325270 non-null  float64
 3   displayName       1325270 non-null  object
 4   frameId           1325270 non-null  int64
 5   time              1325270 non-null  object
 6   jerseyNumber      1325270 non-null  float64
 7   club              1325270 non-null  object
 8   playDirection     1325270 non-null  object
 9   x                 1325270 non-null  float64
 10  y                 1325270 non-null  float64
 11  s                 1325270 non-null  float64
 12  a                 1325270 non-null  float64
 13  dis               1325270 non-null  float64
 14  o                 1325270 non-null  float64
 15  dir               1325270 non-null  float64
 16  event             113796 non-null   object
 17  game_play_Id      1325270 non-null  object
 18  defensiveTeam     1325270 non-null  object
 19  ballCarrierId     1325270 non-null  int64
 20  bcx               1325270 non-null  float64
 21  bcy               1325270 non-null  float64
 22  bc_s              1325270 non-null  float64
 23  bc_a              1325270 non-null  float64
 24  bc_dis            1325270 non-null  float64
 25  bc_o              1325270 non-null  float64
 26  bc_dir            1325270 non-null  float64
 27  distance_from_bc  1325270 non-null  float64
 28  tackler_one       972908 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      565212 non-null   float64
 31  assister_two      323551 non-null   float64
 32  missed_tackler_1  342726 non-null   float64
 33  missed_tackler_2  77631 non-null    float64
 34  missed_tackler_3  14893 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         2086 non-null     object
 39  cosine            1246894 non-null  float64
 40  do_align          1325270 non-null  float64
 41  bc_do_align       1325270 non-null  float64
 42  weight            1325270 non-null  int64
 43  bc_weight         1325270 non-null  int64
 44  force             1325270 non-null  float64
 45  bc_force          1325270 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 475.2+ MB

In [202]:
index_to_check = 311916
if index_to_check in missing_indices_1:
    print(f"Index {index_to_check} is in 'missing_indices_1'")
else:
    print(f"Index {index_to_check} is not in 'missing_indices_1'")

Index 311916 is in 'missing_indices_1'

In [207]:
###Applying for Missed Tackle Indices
tracking_clean_1 = drop_dataless_rows(tracking_clean_1, missing_indices_mt_1)

Index 311921 not in DataFrame
Total matching rows: 7394

In [208]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1317876 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   gameId            1317876 non-null  int64
 1   playId            1317876 non-null  int64
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object
 4   frameId           1317876 non-null  int64
 5   time              1317876 non-null  object
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object
 8   playDirection     1317876 non-null  object
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  event             113127 non-null   object
 17  game_play_Id      1317876 non-null  object
 18  defensiveTeam     1317876 non-null  object
 19  ballCarrierId     1317876 non-null  int64
 20  bcx               1317876 non-null  float64
 21  bcy               1317876 non-null  float64
 22  bc_s              1317876 non-null  float64
 23  bc_a              1317876 non-null  float64
 24  bc_dis            1317876 non-null  float64
 25  bc_o              1317876 non-null  float64
 26  bc_dir            1317876 non-null  float64
 27  distance_from_bc  1317876 non-null  float64
 28  tackler_one       966361 non-null   float64
 29  tackler_two       104 non-null      float64
 30  assister_one      564105 non-null   float64
 31  assister_two      323066 non-null   float64
 32  missed_tackler_1  335332 non-null   float64
 33  missed_tackler_2  76200 non-null    float64
 34  missed_tackler_3  14614 non-null    float64
 35  missed_tackler_4  3961 non-null     float64
 36  missed_tackler_5  1525 non-null     float64
 37  missed_tackler_6  888 non-null      float64
 38  new_event         1892 non-null     object
 39  cosine            1239506 non-null  float64
 40  do_align          1317876 non-null  float64
 41  bc_do_align       1317876 non-null  float64
 42  weight            1317876 non-null  int64
 43  bc_weight         1317876 non-null  int64
 44  force             1317876 non-null  float64
 45  bc_force          1317876 non-null  float64
dtypes: float64(32), int64(6), object(8)
memory usage: 472.6+ MB

In [209]:
tracking_clean_1.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv', index=False)

In [215]:
tracking_clean_1 = tracking_clean_1.reset_index(drop=True)

### **2.5: Deleting Observations from Tackles_1v1 which did not have a full second of data before hand**

In [232]:
def drop_matching_rows(df1, df2, indices):
    for i in indices:
        if i in df2.index:
            game_play_Id = df2.loc[i, 'game_play_Id']
            nflId = df2.loc[i, 'nflId']
            df1 = df1.drop(df1[(df1['game_play_Id'] == game_play_Id) & (df1['nflId'] == nflId)].index)
    return df1

In [246]:
tackles_1v1_1 = drop_matching_rows(tackles_1v1, tracking_clean, missing_indices_1)

In [247]:
tackles_1v1_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11667 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11667 non-null  int64
 1   playId            11667 non-null  int64
 2   nflId             11667 non-null  int64
 3   tackle            11667 non-null  int64
 4   assist            11667 non-null  int64
 5   forcedFumble      11667 non-null  int64
 6   pff_missedTackle  11667 non-null  int64
 7   game_play_Id      11667 non-null  object
 8   event_type        11667 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 911.5+ KB

In [248]:
tackles_1v1_1 = drop_matching_rows(tackles_1v1_1, tracking_clean, missing_indices_mt_1)

In [249]:
tackles_1v1_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11472 non-null  int64
 1   playId            11472 non-null  int64
 2   nflId             11472 non-null  int64
 3   tackle            11472 non-null  int64
 4   assist            11472 non-null  int64
 5   forcedFumble      11472 non-null  int64
 6   pff_missedTackle  11472 non-null  int64
 7   game_play_Id      11472 non-null  object
 8   event_type        11472 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 896.2+ KB

In [250]:
tackles_1v1_1.head(10)

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0
5,2022090800,1286,44976,1,0,0,0,2022090800_1286,1.0
6,2022090800,1736,44976,1,0,0,0,2022090800_1736,1.0
7,2022090800,2860,46085,1,0,0,0,2022090800_2860,1.0
8,2022090800,3092,46190,1,0,0,0,2022090800_3092,1.0
9,2022090800,3145,52647,1,0,0,0,2022090800_3145,1.0

### **2.6: Generating Average Magnitude**

In [251]:
def compute_speed_features(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['s_avg_05'] = None
    df1['s_avg_1'] = None
    df1['bc_s_avg_05'] = None
    df1['bc_s_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1 nor 2

        matching_indexes = df2.index[condition]

        for i in matching_indexes:
            # Ensure index range does not go below 0
            start_index_05 = max(i - 5, 0)
            start_index_1 = max(i - 10, 0)

            # Calculate averages and assign to df1
            df1.at[index, 's_avg_05'] = df2.loc[start_index_05:i, 's'].mean()
            df1.at[index, 's_avg_1'] = df2.loc[start_index_1:start_index_05, 's'].mean()
            df1.at[index, 'bc_s_avg_05'] = df2.loc[start_index_05:i, 'bc_s'].mean()
            df1.at[index, 'bc_s_avg_1'] = df2.loc[start_index_1:start_index_05, 'bc_s'].mean()

    return df1

# Example usage:
# updated_df1 = compute_averages_modified(df1, df2)

In [252]:
tackles_1v1_1_test = compute_speed_features(tackles_1v1_1, tracking_clean_1)

In [261]:
tackles_1v1_1_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            11472 non-null  int64
 1   playId            11472 non-null  int64
 2   nflId             11472 non-null  int64
 3   tackle            11472 non-null  int64
 4   assist            11472 non-null  int64
 5   forcedFumble      11472 non-null  int64
 6   pff_missedTackle  11472 non-null  int64
 7   game_play_Id      11472 non-null  object
 8   event_type        11472 non-null  float64
 9   s_avg_05          9678 non-null   object
 10  s_avg_1           9678 non-null   object
 11  bc_s_avg_05       9678 non-null   object
 12  bc_s_avg_1        9678 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 1.5+ MB

In [262]:
tracking_clean.event.value_counts()

event
first_contact                26142
tackle                       24948
ball_snap                    16053
handoff                      15071
pass_outcome_caught          12708
pass_arrived                 11123
out_of_bounds                 3924
run                           2140
man_in_motion                 1054
play_action                    652
touchdown                      545
shift                          359
qb_slide                       291
fumble                         244
pass_forward                   206
snap_direct                    127
lateral                         63
line_set                        56
pass_shovel                     38
autoevent_passforward           36
autoevent_passinterrupted       29
qb_sack                         21
autoevent_ballsnap              15
fumble_defense_recovered        14
penalty_flag                    12
fumble_offense_recovered         8
safety                           7
run_pass_option                  2
penalty_accepted                 2
pass_outcome_touchdown           1
Name: count, dtype: int64

**Exploration to find out why averages are npot identified for all observations**

In [268]:
play_1 = tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022090800_101') & (tracking_clean_1['nflId'] == 42816)]

In [270]:
play_1

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
104,2022090800,101,42816.0,Troy Hill,1,2022-09-08 20:25:08.200000,2.0,LA,left,64.67,40.76,0.06,0.55,0.01,112.17,108.97,NaN,2022090800_101,LA,47857,79.61,29.56,0.00,0.00,0.00,265.65,255.74,18.672000,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.964444,0.889889,184,203,101.20,0.00
105,2022090800,101,42816.0,Troy Hill,2,2022-09-08 20:25:08.299999,2.0,LA,left,64.67,40.77,0.08,0.56,0.01,109.90,7.85,NaN,2022090800_101,LA,47857,79.60,29.56,0.00,0.00,0.00,265.65,258.97,18.670003,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.133889,0.925778,184,203,103.04,0.00
106,2022090800,101,42816.0,Troy Hill,3,2022-09-08 20:25:08.400000,2.0,LA,left,64.66,40.79,0.20,0.68,0.02,105.18,356.70,NaN,2022090800_101,LA,47857,79.60,29.56,0.00,0.00,0.00,265.65,259.87,18.690011,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.205333,0.935778,184,203,125.12,0.00
107,2022090800,101,42816.0,Troy Hill,4,2022-09-08 20:25:08.500000,2.0,LA,left,64.66,40.81,0.30,0.59,0.03,102.25,0.46,NaN,2022090800_101,LA,47857,79.60,29.56,0.00,0.00,0.00,265.65,259.74,18.702035,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.131000,0.934333,184,203,108.56,0.00
108,2022090800,101,42816.0,Troy Hill,5,2022-09-08 20:25:08.599999,2.0,LA,left,64.66,40.85,0.40,0.43,0.04,100.21,0.20,NaN,2022090800_101,LA,47857,79.60,29.56,0.00,0.00,0.00,265.65,263.81,18.726123,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.111222,0.979556,184,203,79.12,0.00
109,2022090800,101,42816.0,Troy Hill,6,2022-09-08 20:25:08.700000,2.0,LA,left,64.66,40.90,0.43,0.23,0.04,100.21,0.54,ball_snap,2022090800_101,LA,47857,79.60,29.56,0.00,0.00,0.00,265.65,271.36,18.756311,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.107444,0.936556,184,203,42.32,0.00
110,2022090800,101,42816.0,Troy Hill,7,2022-09-08 20:25:08.799999,2.0,LA,left,64.65,40.95,0.49,0.10,0.06,97.66,353.61,NaN,2022090800_101,LA,47857,79.60,29.56,0.00,0.00,0.00,265.65,284.69,18.794536,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.156111,0.788444,184,203,18.40,0.00
111,2022090800,101,42816.0,Troy Hill,8,2022-09-08 20:25:08.900000,2.0,LA,left,64.64,40.99,0.48,0.02,0.04,96.49,352.78,NaN,2022090800_101,LA,47857,79.60,29.57,0.00,0.00,0.00,265.65,297.55,18.820680,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.152333,0.645556,184,203,3.68,0.00
112,2022090800,101,42816.0,Troy Hill,9,2022-09-08 20:25:09.000000,2.0,LA,left,64.63,41.04,0.46,0.11,0.04,93.22,349.30,NaN,2022090800_101,LA,47857,79.60,29.57,0.04,0.71,0.00,266.56,349.76,18.858998,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999968,-0.154667,0.075556,184,203,20.24,144.13
113,2022090800,101,42816.0,Troy Hill,10,2022-09-08 20:25:09.099999,2.0,LA,left,64.62,41.11,0.50,0.18,0.07,94.28,350.28,NaN,2022090800_101,LA,47857,79.60,29.59,0.25,2.01,0.02,267.37,355.82,18.897375,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.995329,-0.155556,0.017222,184,203,33.12,408.03
114,2022090800,101,42816.0,Troy Hill,11,2022-09-08 20:25:09.200000,2.0,LA,left,64.60,41.18,0.53,0.25,0.08,91.10,348.69,NaN,2022090800_101,LA,47857,79.59,29.65,0.68,3.56,0.06,268.21,355.75,18.911399,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992418,-0.137889,0.027333,184,203,46.00,722.68
115,2022090800,101,42816.0,Troy Hill,12,2022-09-08 20:25:09.299999,2.0,LA,left,64.58,41.26,0.55,0.31,0.08,87.66,349.02,NaN,2022090800_101,LA,47857,79.59,29.75,1.18,4.47,0.10,268.21,356.52,18.915079,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.991445,-0.096000,0.018778,184,203,57.04,907.41
116,2022090800,101,42816.0,Troy Hill,13,2022-09-08 20:25:09.400000,2.0,LA,left,64.58,41.33,0.55,0.35,0.07,90.08,351.03,NaN,2022090800_101,LA,47857,79.58,29.91,1.81,5.00,0.17,269.62,355.72,18.852491,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.996652,-0.100556,0.043333,184,203,64.40,1015.00
117,2022090800,101,42816.0,Troy Hill,14,2022-09-08 20:25:09.500000,2.0,LA,left,64.60,41.44,0.59,0.18,0.11,84.04,355.69,NaN,2022090800_101,LA,47857,79.55,30.15,2.47,5.19,0.23,272.32,354.01,18.734103,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999570,0.018333,0.092333,184,203,33.12,1053.57
118,2022090800,101,42816.0,Troy Hill,15,2022-09-08 20:25:09.599999,2.0,LA,left,64.60,41.50,0.63,0.73,0.06,78.92,0.52,NaN,2022090800_101,LA,47857,79.51,30.43,3.10,5.20,0.29,273.92,352.35,18.570218,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.989851,0.128889,0.128556,184,203,134.32,1055.60
119,2022090800,101,42816.0,Troy Hill,16,2022-09-08 20:25:09.700000,2.0,LA,left,64.63,41.60,0.87,1.98,0.10,88.30,12.94,NaN,2022090800_101,LA,47857,79.45,30.77,3.61,4.68,0.34,276.86,350.84,18.355416,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.926529,0.162667,0.178000,184,203,364.32,950.04
120,2022090800,101,42816.0,Troy Hill,17,2022-09-08 20:25:09.799999,2.0,LA,left,64.68,41.70,1.19,2.67,0.11,89.49,22.62,NaN,2022090800_101,LA,47857,79.38,31.15,4.09,4.07,0.39,280.70,348.85,18.093991,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.831276,0.257000,0.242778,184,203,491.28,826.21
121,2022090800,101,42816.0,Troy Hill,18,2022-09-08 20:25:09.900000,2.0,LA,left,64.76,41.84,1.70,3.51,0.16,82.72,31.88,NaN,2022090800_101,LA,47857,79.28,31.57,4.54,3.70,0.44,291.36,346.06,17.784918,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.696915,0.435111,0.392222,184,203,645.84,751.10
122,2022090800,101,42816.0,Troy Hill,19,2022-09-08 20:25:10.000000,2.0,LA,left,64.88,42.01,2.20,3.90,0.20,82.72,36.34,handoff,2022090800_101,LA,47857,79.16,32.03,4.89,3.25,0.47,296.75,343.59,17.421791,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.605294,0.484667,0.479556,184,203,717.60,659.75
123,2022090800,101,42816.0,Troy Hill,20,2022-09-08 20:25:10.099999,2.0,LA,left,65.03,42.20,2.65,3.91,0.25,82.72,40.09,NaN,2022090800_101,LA,47857,79.01,32.51,5.16,2.80,0.50,299.33,341.30,17.009894,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.518176,0.526333,0.533667,184,203,719.44,568.40
124,2022090800,101,42816.0,Troy Hill,21,2022-09-08 20:25:10.200000,2.0,LA,left,65.22,42.41,3.02,3.62,0.28,82.72,42.02,NaN,2022090800_101,LA,47857,78.82,33.01,5.41,2.50,0.53,299.33,338.59,16.532392,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.447291,0.547778,0.563778,184,203,666.08,507.50
125,2022090800,101,42816.0,Troy Hill,22,2022-09-08 20:25:10.299999,2.0,LA,left,65.46,42.65,3.48,3.37,0.34,78.33,45.82,NaN,2022090800_101,LA,47857,78.60,33.53,5.73,2.65,0.56,303.67,335.43,15.994812,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.335616,0.638778,0.647111,184,203,620.08,537.95
126,2022090800,101,42816.0,Troy Hill,23,2022-09-08 20:25:10.400000,2.0,LA,left,65.74,42.89,3.81,2.92,0.37,79.44,48.83,NaN,2022090800_101,LA,47857,78.34,34.05,6.01,2.79,0.59,304.72,332.36,15.391738,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.233954,0.659889,0.692889,184,203,537.28,566.37
127,2022090800,101,42816.0,Troy Hill,24,2022-09-08 20:25:10.500000,2.0,LA,left,66.04,43.14,4.02,2.30,0.39,77.79,51.18,NaN,2022090800_101,LA,47857,78.04,34.59,6.24,2.64,0.61,306.81,329.78,14.734399,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.149535,0.704333,0.744778,184,203,423.20,535.92
128,2022090800,101,42816.0,Troy Hill,25,2022-09-08 20:25:10.599999,2.0,LA,left,66.36,43.39,4.15,1.77,0.41,77.79,53.64,NaN,2022090800_101,LA,47857,77.70,35.13,6.48,2.61,0.64,307.90,326.95,14.029369,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.057738,0.731667,0.788333,184,203,325.68,529.83
129,2022090800,101,42816.0,Troy Hill,26,2022-09-08 20:25:10.700000,2.0,LA,left,66.71,43.62,4.14,1.73,0.41,83.33,57.20,NaN,2022090800_101,LA,47857,77.33,35.68,6.69,2.43,0.66,308.51,324.69,13.260015,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.043794,0.709667,0.820222,184,203,318.32,493.29
130,2022090800,101,42816.0,Troy Hill,27,2022-09-08 20:25:10.799999,2.0,LA,left,67.06,43.83,3.99,3.40,0.41,90.63,62.82,NaN,2022090800_101,LA,47857,76.92,36.23,6.94,2.37,0.69,307.15,322.60,12.449080,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.177428,0.691000,0.828333,184,203,625.60,481.11
131,2022090800,101,42816.0,Troy Hill,28,2022-09-08 20:25:10.900000,2.0,LA,left,67.41,43.99,3.77,4.26,0.39,93.00,69.83,NaN,2022090800_101,LA,47857,76.48,36.78,7.08,2.13,0.70,307.15,320.51,11.586587,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.330844,0.742556,0.851556,184,203,783.84,432.39
132,2022090800,101,42816.0,Troy Hill,29,2022-09-08 20:25:11.000000,2.0,LA,left,67.76,44.10,3.56,4.43,0.36,96.18,77.54,NaN,2022090800_101,LA,47857,76.02,37.32,7.19,2.12,0.72,307.15,318.07,10.686253,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.491968,0.792889,0.878667,184,203,815.12,430.36
133,2022090800,101,42816.0,Troy Hill,30,2022-09-08 20:25:11.099999,2.0,LA,left,68.10,44.13,3.28,5.09,0.34,99.97,89.20,NaN,2022090800_101,LA,47857,75.52,37.85,7.25,2.18,0.72,307.15,315.64,9.720844,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.689114,0.880333,0.905667,184,203,936.56,442.54
134,2022090800,101,42816.0,Troy Hill,31,2022-09-08 20:25:11.200000,2.0,LA,left,68.42,44.08,3.16,5.57,0.32,104.92,103.02,NaN,2022090800_101,LA,47857,74.99,38.35,7.26,2.37,0.73,304.32,313.06,8.717672,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.865676,0.978889,0.902889,184,203,1024.88,481.11
135,2022090800,101,42816.0,Troy Hill,32,2022-09-08 20:25:11.299999,2.0,LA,left,68.70,43.96,3.14,6.00,0.31,108.49,118.61,NaN,2022090800_101,LA,47857,74.45,38.83,7.26,2.44,0.73,301.65,310.63,7.705803,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.978075,0.887556,0.900222,184,203,1104.00,495.32
136,2022090800,101,42816.0,Troy Hill,33,2022-09-08 20:25:11.400000,2.0,LA,left,68.95,43.75,3.32,6.02,0.32,112.09,132.52,NaN,2022090800_101,LA,47857,73.85,39.25,7.24,3.35,0.73,300.08,305.48,6.652819,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.992461,0.773000,0.940000,184,203,1107.68,680.05
137,2022090800,101,42816.0,Troy Hill,34,2022-09-08 20:25:11.500000,2.0,LA,left,69.17,43.46,3.65,6.37,0.36,118.12,146.87,NaN,2022090800_101,LA,47857,73.23,39.63,7.19,3.87,0.72,294.76,300.86,5.581442,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.898718,0.680556,0.932222,184,203,1172.08,785.61
138,2022090800,101,42816.0,Troy Hill,35,2022-09-08 20:25:11.599999,2.0,LA,left,69.35,43.13,3.95,6.26,0.38,124.07,156.64,NaN,2022090800_101,LA,47857,72.59,39.94,7.14,4.49,0.72,287.66,295.28,4.546834,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.750573,0.638111,0.915333,184,203,1151.84,911.47
139,2022090800,101,42816.0,Troy Hill,36,2022-09-08 20:25:11.700000,2.0,LA,left,69.48,42.75,4.25,5.81,0.41,130.82,164.41,NaN,2022090800_101,LA,47857,71.93,40.21,7.05,4.65,0.71,286.16,290.47,3.529037,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.588632,0.626778,0.952111,184,203,1069.04,943.95
140,2022090800,101,42816.0,Troy Hill,37,2022-09-08 20:25:11.799999,2.0,LA,left,69.56,42.32,4.39,5.19,0.43,139.13,172.70,NaN,2022090800_101,LA,47857,71.27,40.41,6.86,5.07,0.69,287.97,285.60,2.563630,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.389124,0.627000,0.973667,184,203,954.96,1029.21
141,2022090800,101,42816.0,Troy Hill,38,2022-09-08 20:25:11.900000,2.0,LA,left,69.59,41.88,4.52,4.80,0.45,152.78,180.00,first_contact,2022090800_101,LA,47857,70.62,40.56,6.63,5.37,0.67,287.22,280.60,1.674306,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.183951,0.697556,0.926444,184,203,883.20,1090.11
142,2022090800,101,42816.0,Troy Hill,39,2022-09-08 20:25:12.000000,2.0,LA,left,69.57,41.43,4.55,4.18,0.45,152.78,185.57,NaN,2022090800_101,LA,47857,69.97,40.65,6.47,4.86,0.66,287.22,276.33,0.876584,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.013264,0.635667,0.879000,184,203,769.12,986.58
143,2022090800,101,42816.0,Troy Hill,40,2022-09-08 20:25:12.099999,2.0,LA,left,69.51,40.99,4.43,3.74,0.44,165.31,190.65,NaN,2022090800_101,LA,47857,69.36,40.67,6.17,4.90,0.62,292.32,270.68,0.353412,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.173133,0.718444,0.759556,184,203,688.16,994.70
144,2022090800,101,42816.0,Troy Hill,41,2022-09-08 20:25:12.200000,2.0,LA,left,69.41,40.58,4.20,3.50,0.42,160.90,195.40,NaN,2022090800_101,LA,47857,68.76,40.63,5.97,4.68,0.60,293.95,265.31,0.651920,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.343496,0.616667,0.681778,184,203,644.00,950.04
145,2022090800,101,42816.0,Troy Hill,42,2022-09-08 20:25:12.299999,2.0,LA,left,69.31,40.24,3.55,4.01,0.36,189.49,198.63,NaN,2022090800_101,LA,47857,68.18,40.54,5.75,4.38,0.58,294.97,260.48,1.169145,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.471782,0.898444,0.616778,184,203,737.84,889.14
146,2022090800,101,42816.0,Troy Hill,43,2022-09-08 20:25:12.400000,2.0,LA,left,69.22,39.94,3.00,4.41,0.31,196.68,199.90,NaN,2022090800_101,LA,47857,67.65,40.43,5.47,4.04,0.54,296.60,256.58,1.644688,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.549315,0.964222,0.555333,184,203,811.44,820.12
147,2022090800,101,42816.0,Troy Hill,44,2022-09-08 20:25:12.500000,2.0,LA,left,69.14,39.69,2.42,4.77,0.26,203.84,200.76,NaN,2022090800_101,LA,47857,67.16,40.30,5.11,4.12,0.51,239.44,253.43,2.071835,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.606405,0.965778,0.844556,184,203,877.68,836.36
148,2022090800,101,42816.0,Troy Hill,45,2022-09-08 20:25:12.599999,2.0,LA,left,69.08,39.50,1.80,4.97,0.20,210.96,198.30,tackle,2022090800_101,LA,47857,66.69,40.15,4.74,3.88,0.49,218.73,251.22,2.476812,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.602930,0.859333,0.639000,184,203,914.48,787.64
149,2022090800,101,42816.0,Troy Hill,46,2022-09-08 20:25:12.700000,2.0,LA,left,69.04,39.36,1.21,5.03,0.15,235.04,193.80,NaN,2022090800_101,LA,47857,66.26,40.00,4.40,3.74,0.46,205.44,249.61,2.852718,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.561939,0.541778,0.509222,184,203,925.52,759.22
150,2022090800,101,42816.0,Troy Hill,47,2022-09-08 20:25:12.799999,2.0,LA,left,69.02,39.27,0.75,4.63,0.10,245.76,184.75,NaN,2022090800_101,LA,47857,65.86,39.85,3.99,3.71,0.42,203.49,249.31,3.212787,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.429566,0.322111,0.490889,184,203,851.92,753.13
151,2022090800,101,42816.0,Troy Hill,48,2022-09-08 20:25:12.900000,2.0,LA,left,69.03,39.21,0.46,3.95,0.06,254.21,157.70,NaN,2022090800_101,LA,47857,65.51,39.71,3.52,3.87,0.38,212.15,251.24,3.555334,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.061745,-0.072333,0.565667,184,203,726.80,785.61
152,2022090800,101,42816.0,Troy Hill,49,2022-09-08 20:25:13.000000,2.0,LA,left,69.06,39.18,0.44,3.12,0.04,256.96,118.14,NaN,2022090800_101,LA,47857,65.19,39.61,3.11,3.78,0.33,225.75,252.65,3.893816,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.701034,-0.542444,0.701111,184,203,574.08,767.34

In [275]:
play_1[39:44]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event,game_play_Id,defensiveTeam,ballCarrierId,bcx,bcy,bc_s,bc_a,bc_dis,bc_o,bc_dir,distance_from_bc,tackler_one,tackler_two,assister_one,assister_two,missed_tackler_1,missed_tackler_2,missed_tackler_3,missed_tackler_4,missed_tackler_5,missed_tackler_6,new_event,cosine,do_align,bc_do_align,weight,bc_weight,force,bc_force
143,2022090800,101,42816.0,Troy Hill,40,2022-09-08 20:25:12.099999,2.0,LA,left,69.51,40.99,4.43,3.74,0.44,165.31,190.65,NaN,2022090800_101,LA,47857,69.36,40.67,6.17,4.90,0.62,292.32,270.68,0.353412,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.173133,0.718444,0.759556,184,203,688.16,994.70
144,2022090800,101,42816.0,Troy Hill,41,2022-09-08 20:25:12.200000,2.0,LA,left,69.41,40.58,4.20,3.50,0.42,160.90,195.40,NaN,2022090800_101,LA,47857,68.76,40.63,5.97,4.68,0.60,293.95,265.31,0.651920,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.343496,0.616667,0.681778,184,203,644.00,950.04
145,2022090800,101,42816.0,Troy Hill,42,2022-09-08 20:25:12.299999,2.0,LA,left,69.31,40.24,3.55,4.01,0.36,189.49,198.63,NaN,2022090800_101,LA,47857,68.18,40.54,5.75,4.38,0.58,294.97,260.48,1.169145,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.471782,0.898444,0.616778,184,203,737.84,889.14
146,2022090800,101,42816.0,Troy Hill,43,2022-09-08 20:25:12.400000,2.0,LA,left,69.22,39.94,3.00,4.41,0.31,196.68,199.90,NaN,2022090800_101,LA,47857,67.65,40.43,5.47,4.04,0.54,296.60,256.58,1.644688,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.549315,0.964222,0.555333,184,203,811.44,820.12
147,2022090800,101,42816.0,Troy Hill,44,2022-09-08 20:25:12.500000,2.0,LA,left,69.14,39.69,2.42,4.77,0.26,203.84,200.76,NaN,2022090800_101,LA,47857,67.16,40.30,5.11,4.12,0.51,239.44,253.43,2.071835,42816.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.606405,0.965778,0.844556,184,203,877.68,836.36

In [276]:
play_1['s'][39:44].mean()

3.5200000000000005

In [254]:
tackles_1v1_1_test.head(50)

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle,game_play_Id,event_type,s_avg_05,s_avg_1,bc_s_avg_05,bc_s_avg_1
0,2022090800,101,42816,1,0,0,0,2022090800_101,1.0,3.233333,4.348333,5.535,6.72
1,2022090800,393,46232,1,0,0,0,2022090800_393,1.0,2.083333,1.8,0.276667,0.341667
2,2022090800,486,40166,1,0,0,0,2022090800_486,1.0,2.328333,2.258333,3.06,2.4
3,2022090800,646,47939,1,0,0,0,2022090800_646,1.0,4.12,5.241667,4.271667,5.561667
4,2022090800,818,40107,1,0,0,0,2022090800_818,1.0,0.745,1.78,1.446667,2.041667
5,2022090800,1286,44976,1,0,0,0,2022090800_1286,1.0,None,None,None,None
6,2022090800,1736,44976,1,0,0,0,2022090800_1736,1.0,4.665,4.676667,4.283333,4.656667
7,2022090800,2860,46085,1,0,0,0,2022090800_2860,1.0,2.381667,3.155,3.231667,2.735
8,2022090800,3092,46190,1,0,0,0,2022090800_3092,1.0,None,None,None,None
9,2022090800,3145,52647,1,0,0,0,2022090800_3145,1.0,2.445,1.703333,2.546667,1.438333
10,2022090800,3362,46190,1,0,0,0,2022090800_3362,1.0,4.471667,4.191667,2.981667,4.37
11,2022090800,3383,54488,1,0,0,0,2022090800_3383,1.0,2.126667,1.716667,2.195,1.501667
12,2022091100,1260,44851,1,0,0,0,2022091100_1260,1.0,2.95,1.766667,2.278333,2.855
13,2022091100,1672,40017,1,0,0,0,2022091100_1672,1.0,0.971667,0.991667,2.82,3.028333
14,2022091100,2114,53469,1,0,0,0,2022091100_2114,1.0,1.198333,2.685,5.098333,5.17
15,2022091100,2353,38607,1,0,0,0,2022091100_2353,1.0,2.716667,4.586667,3.188333,5.398333
16,2022091100,2512,53611,1,0,0,0,2022091100_2512,1.0,3.436667,5.131667,4.616667,5.678333
17,2022091100,2640,44862,1,0,0,0,2022091100_2640,1.0,5.78,6.151667,5.931667,6.325
18,2022091100,2878,53489,1,0,0,0,2022091100_2878,1.0,0.503333,0.998333,2.945,3.931667
19,2022091100,2899,37097,1,0,0,0,2022091100_2899,1.0,1.425,2.205,0.813333,1.881667
20,2022091100,3578,52542,1,0,0,0,2022091100_3578,1.0,2.39,4.555,3.393333,4.656667
21,2022091100,3647,53469,1,0,0,0,2022091100_3647,1.0,3.873333,6.043333,4.896667,5.036667
22,2022091100,3778,53489,1,0,0,0,2022091100_3778,1.0,3.341667,2.915,5.008333,6.561667
23,2022091101,1691,53481,1,0,0,0,2022091101_1691,1.0,None,None,None,None
24,2022091101,1744,44903,1,0,0,0,2022091101_1744,1.0,7.116667,8.798333,7.426667,8.34
25,2022091101,1785,52452,1,0,0,0,2022091101_1785,1.0,2.965,5.166667,3.836667,4.57
26,2022091101,2051,46527,1,0,0,0,2022091101_2051,1.0,0.276667,0.616667,0.028333,0.098333
27,2022091101,3221,47799,1,0,0,0,2022091101_3221,1.0,4.305,5.533333,3.486667,4.776667
28,2022091102,86,44938,1,0,0,0,2022091102_86,1.0,1.888333,3.456667,1.406667,2.903333
29,2022091102,531,52571,1,0,0,0,2022091102_531,1.0,2.951667,3.93,3.596667,3.798333
30,2022091102,756,53609,1,0,0,0,2022091102_756,1.0,4.213333,6.506667,4.518333,5.47
31,2022091102,1493,54504,1,0,0,0,2022091102_1493,1.0,2.043333,1.76,0.991667,3.22
32,2022091102,2065,54504,1,0,0,0,2022091102_2065,1.0,1.92,4.413333,1.988333,4.521667
33,2022091102,2352,46290,1,0,0,0,2022091102_2352,1.0,0.12,0.748333,0.323333,0.406667
34,2022091102,2759,54504,1,0,0,0,2022091102_2759,1.0,3.711667,5.151667,3.516667,4.25
35,2022091102,3783,52571,1,0,0,0,2022091102_3783,1.0,0.226667,0.708333,1.355,2.585
36,2022091102,4102,54639,1,0,0,0,2022091102_4102,1.0,None,None,None,None
37,2022091103,520,46146,1,0,0,0,2022091103_520,1.0,1.515,1.053333,1.703333,1.118333
38,2022091103,1037,44842,1,0,0,0,2022091103_1037,1.0,2.888333,4.241667,1.036667,2.526667
39,2022091103,1315,46080,1,0,0,0,2022091103_1315,1.0,2.01,1.515,1.975,3.288333
40,2022091103,1405,46080,1,0,0,0,2022091103_1405,1.0,None,None,None,None
41,2022091103,1672,46080,1,0,0,0,2022091103_1672,1.0,None,None,None,None
42,2022091103,2058,43641,1,0,0,0,2022091103_2058,1.0,1.033333,2.64,1.215,0.985
43,2022091103,2172,46097,1,0,0,0,2022091103_2172,1.0,None,None,None,None
44,2022091103,2222,44842,1,0,0,0,2022091103_2222,1.0,2.876667,4.256667,3.306667,5.405
45,2022091103,2291,46698,1,0,0,0,2022091103_2291,1.0,1.42,1.351667,2.566667,2.785
47,2022091103,3147,44872,1,0,0,0,2022091103_3147,1.0,4.353333,4.203333,2.95,3.05
48,2022091103,3251,43325,1,0,0,0,2022091103_3251,1.0,6.666667,7.965,5.623333,7.798333
49,2022091103,4175,43641,1,0,0,0,2022091103_4175,1.0,3.42,5.445,2.835,3.85
50,2022091103,4686,43641,1,0,0,0,2022091103_4686,1.0,2.055,2.986667,2.67,2.068333

In [259]:
###Checking to see if blank values are due to player being pushed out of bounds
def count_out_of_bounds(tackles_1v1_1_test, tracking_clean_1):
    # Filter rows where s_avg_05 is None
    filtered_tackles = tackles_1v1_1_test[tackles_1v1_1_test['s_avg_05'].isnull()]

    count = 0
    # Iterate over the filtered rows
    for _, row in filtered_tackles.iterrows():
        # Find matching rows in tracking_clean_1
        matching_rows = tracking_clean_1[(tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                                         (tracking_clean_1['nflId'] == row['nflId'])]
        # Count how many times 'event' is 'out_of_bounds'
        count += (matching_rows['event'] == 'out_of_bounds').sum()
    
    return count

In [260]:
count_out_of_bounds(tackles_1v1_1_test, tracking_clean_1)

1597

In [263]:
###Checking to see what final 197 blank valued rows could be due to
def get_unique_game_play_ids(tackles_1v1_1_test, tracking_clean_1):
    # Filter rows where s_avg_05 is None
    filtered_tackles = tackles_1v1_1_test[tackles_1v1_1_test['s_avg_05'].isnull()]

    unique_game_play_ids = set()
    # Iterate over the filtered rows
    for _, row in filtered_tackles.iterrows():
        # Find matching rows in tracking_clean_1
        matching_rows = tracking_clean_1[(tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                                         (tracking_clean_1['nflId'] == row['nflId'])]
        # Get unique game_play_Id's where 'event' is neither 'out_of_bounds' nor 'tackle'
        game_play_ids = set(matching_rows[~matching_rows['event'].isin(['out_of_bounds', 'tackle'])]['game_play_Id'].unique())
        unique_game_play_ids.update(game_play_ids)
    
    return unique_game_play_ids

In [264]:
missing_197 = get_unique_game_play_ids(tackles_1v1_1_test, tracking_clean_1)

In [266]:
len(missing_197)

1793

In [225]:
# Create an empty DataFrame to store the speed features
speed_features = pd.DataFrame(columns=['s_05', 's_1', 'bc_s_05', 'bc_s_1'])

# Iterate over each observation in tackles_1v1
for index, row in tackles_1v1.iterrows():
    if row['event_type'] == 1:
        # Find the index 'i' in tracking_clean_1
        filtered_df = tracking_clean_1[(tracking_clean_1['event'] == 'tackle') & 
                             (tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                             (tracking_clean_1['nflId'] == row['nflId'])]
        
        if not filtered_df.empty:
            i = filtered_df.index[0]
        else:
            continue
        
        # Calculate the average of tracking_clean_1[s] from i-5:i
        s_05_avg = tracking_clean_1.loc[i-5:i, 's'].mean()
        
        # Calculate the average of tracking_clean_1[s] from i-10:i-5
        s_1_avg = tracking_clean_1.loc[i-10:i-5, 's'].mean()
        
        # Calculate the average of tracking_clean_1[bc_s] from i-5:i
        bc_s_05_avg = tracking_clean_1.loc[i-5:i, 'bc_s'].mean()
        
        # Calculate the average of tracking_clean_1[bc_s] from i-10:i-5
        bc_s_1_avg = tracking_clean_1.loc[i-10:i-5, 'bc_s'].mean()
        
        # Append the speed features to the speed_features DataFrame
        #speed_features = speed_features.append({'s_05': s_05_avg, 's_1': s_1_avg, 'bc_s_05': bc_s_05_avg, 'bc_s_1': bc_s_1_avg}, ignore_index=True)
        speed_features = pd.concat([speed_features, pd.DataFrame([{'s_05': s_05_avg, 's_1': s_1_avg, 'bc_s_05': bc_s_05_avg, 'bc_s_1': bc_s_1_avg}])], ignore_index=True)

    elif row['event_type'] == 2:
        # Find the index 'i' in tracking_clean_1
        filtered_df = tracking_clean_1[(tracking_clean_1['new_event'] == 'missed tackle') & 
                             (tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                             (tracking_clean_1['nflId'] == row['nflId'])]
        
        if not filtered_df.empty:
            i = filtered_df.index[0]
        else:
            continue
        
        # Calculate the average of tracking_clean_1[s] from i-5:i
        s_05_avg = tracking_clean_1.loc[i-5:i, 's'].mean()
        
        # Calculate the average of tracking_clean_1[s] from i-10:i-5
        s_1_avg = tracking_clean_1.loc[i-10:i-5, 's'].mean()
        
        # Calculate the average of tracking_clean_1[bc_s] from i-5:i
        bc_s_05_avg = tracking_clean_1.loc[i-5:i, 'bc_s'].mean()
        
        # Calculate the average of tracking_clean_1[bc_s] from i-10:i-5
        bc_s_1_avg = tracking_clean_1.loc[i-10:i-5, 'bc_s'].mean()
        
        # Append the speed features to the speed_features DataFrame
        #speed_features = speed_features.append({'s_05': s_05_avg, 's_1': s_1_avg, 'bc_s_05': bc_s_05_avg, 'bc_s_1': bc_s_1_avg}, ignore_index=True)
        speed_features = pd.concat([speed_features, pd.DataFrame([{'s_05': s_05_avg, 's_1': s_1_avg, 'bc_s_05': bc_s_05_avg, 'bc_s_1': bc_s_1_avg}])], ignore_index=True)

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/1488225314.py:31: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  speed_features = pd.concat([speed_features, pd.DataFrame([{'s_05': s_05_avg, 's_1': s_1_avg, 'bc_s_05': bc_s_05_avg, 'bc_s_1': bc_s_1_avg}])], ignore_index=True)

In [227]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            12009 non-null  int64
 1   playId            12009 non-null  int64
 2   nflId             12009 non-null  int64
 3   tackle            12009 non-null  int64
 4   assist            12009 non-null  int64
 5   forcedFumble      12009 non-null  int64
 6   pff_missedTackle  12009 non-null  int64
 7   game_play_Id      12009 non-null  object
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB

In [231]:
speed_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   s_05     9668 non-null   float64
 1   s_1      9668 non-null   float64
 2   bc_s_05  9668 non-null   float64
 3   bc_s_1   9668 non-null   float64
dtypes: float64(4)
memory usage: 302.3 KB

In [229]:
speed_features.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/speed_features_test.csv', index=False)

In [210]:
def calculate_speed_features(df):
    # Create an empty DataFrame to store the speed features
    speed_features = pd.DataFrame()

    # Iterate over each observation in df
    for index, row in df.iterrows():
        if row['event_type'] == 1:
            # Find the index 'i' in df
            i = df[(df['event'] == 'tackle') & 
                   (df['game_play_Id'] == row['game_play_Id']) & 
                   (df['nflId'] == row['nflId'])].index[0]
            
            # Calculate the averages
            s_05_avg, s_1_avg, bc_s_05_avg, bc_s_1_avg = calculate_averages(df, i)
            
        elif row['event_type'] == 2:
            # Find the index 'i' in df
            i = df[(df['missed_event'] == 'missed tackle') & 
                   (df['game_play_Id'] == row['game_play_Id']) & 
                   (df['nflId'] == row['nflId'])].index[0]
            
            # Calculate the averages
            s_05_avg, s_1_avg, bc_s_05_avg, bc_s_1_avg = calculate_averages(df, i)
        
        # Append the speed features to the speed_features DataFrame
        speed_features = speed_features.append({'s_05': s_05_avg, 's_1': s_1_avg, 'bc_s_05': bc_s_05_avg, 'bc_s_1': bc_s_1_avg}, ignore_index=True)

    return speed_features

def calculate_averages(df, i):
    # Calculate the average of df[s] from i-5:i
    s_05_avg = df.loc[i-5:i, 's'].mean()
    
    # Calculate the average of df[s] from i-10:i-5
    s_1_avg = df.loc[i-10:i-5, 's'].mean()
    
    # Calculate the average of df[bc_s] from i-5:i
    bc_s_05_avg = df.loc[i-5:i, 'bc_s'].mean()
    
    # Calculate the average of df[bc_s] from i-10:i-5
    bc_s_1_avg = df.loc[i-10:i-5, 'bc_s'].mean()

    return s_05_avg, s_1_avg, bc_s_05_avg, bc_s_1_avg

In [211]:
speed_features_1 = calculate_speed_features(tracking_clean_1)

KeyError: 'event_type'